### ISSUE TITLE
Special constants/keywords `self`, `static`, `parent`, `null`, `false`, `true` handled as normal constants with names.

### ISSUE THREAD

**Issue by mricherzhagen** [nikic/PHP-Parser#1001]
Great library. Was very useful to me.

What I found weird is, that using literal values/keywords like `true`, `false` or `null` resulted in `Expr_ConstFetch(name: Name(name: null))`.

As these are not "really" constants:
```php
array_key_exists('null', get_defined_constants(false)) == false
array_key_exists('false', get_defined_constants(false)) == false
array_key_exists('true', get_defined_constants(false)) == false
```

Trying to `use` them shows that they are a "special class name":
```
php > use \true;
PHP Warning:  The use statement with non-compound name 'true' has no effect in php shell code on line 1
PHP Fatal error:  Cannot use true as true because 'true' is a special class name in php shell code on line 1
```

A similar "problem" exists for the "names" `self`, `static`, `parent` which result in `Expr_StaticCall(class: Name(name: parent), ...)` and `Expr_ClassConstFetch(class: Name(name: static))` despite the special meaning of the name.

```php
array_key_exists('self', get_defined_constants(false)) == false
define('self', 'something') == true
array_key_exists('parent', get_defined_constants(false)) == false
define('parent', 'something') == true
array_key_exists('static', get_defined_constants(false)) == false
define('static', 'something') == true
```

`echo static` even results in a syntax error if it is used like an rvalue and not followed by `::`, though.

I expected a subclass of `Name`, so they can easily be distinguished from "real" names that reference namespaced classes or constants without having that list in the code itself.

There might be more of these that I haven't found.

**Comment by nikic** [comment]
These are somewhat borderline, in that they behave like normal constants/classes in some cases and have special rules in others.

> As these are not "really" constants:
> 
> ```
> array_key_exists('null', get_defined_constants(false)) == false
> array_key_exists('false', get_defined_constants(false)) == false
> array_key_exists('true', get_defined_constants(false)) == false
> ```

This works if you replace `'null'` with `'NULL'`. They *are* constants, but they are case-insensitive. get_defined_constants() returns one arbitrary spelling of them.

PHP used to support case-insensitive constants in general, but now only these constants are case-insensitive for backwards-compatibility reasons.

> Trying to use them shows that they are a "special class name":
> ```
> php > use \true;
> PHP Warning:  The use statement with non-compound name 'true' has no effect in php shell code on line 1
> PHP Fatal error:  Cannot use true as true because 'true' is a special class name in php shell code on line 1
> ```

This is the wrong syntax to use -- you need `use const true`, which does work. And something like `use const true as X` also works. You can even do something silly like `use const A as true; define('A', 'A'); var_dump(true);`

-----

There is a `Name::isSpecialClassName()` method to detect self, parent and static. Maybe it would make sense to also have isSpecialConstName() to detect null, true and false.

**Comment by mricherzhagen** [comment]
> PHP used to support case-insensitive constants in general, but now only these constants are case-insensitive for backwards-compatibility reasons.

Ah. This makes sense! Thanks for explaining.

> This is the wrong syntax to use -- you need `use const true`, which does work. And something like `use const true as X` also works. You can even do something silly like `use const A as true; define('A', 'A'); var_dump(true);`

You are again correct and this is indeed cursed, but also a good explanation, why the parser has to handle those as names. Thank you.

> There is a `Name::isSpecialClassName()` method to detect self, parent and static. Maybe it would make sense to also have isSpecialConstName() to detect null, true and false.

Ah. I must have missed that. Sorry.

So I think this boils down to my code being wrong, then. I should have used `defined('null')` instead of `get_defined_constants` or properly thought about case insensitivity, so I guess I will close this.

Thank you for the library, your response and your time.
