### ISSUE TITLE
Spelling issue: dereferenceable vs dereferencable

### ISSUE THREAD

**Issue by rainx** [nikic/PHP-Parser#1005]
## What's happening

I have a question regarding another word: dereferenceable.

As a non-native English speaker, I'm not completely sure about the correct usage.

**dereferenceable** vs **dereferencable**:

When I searched for the word `dereferencable` on Wikipedia, it indicated that it is a misspelling of `dereferenceable` ([ref](https://en.wiktionary.org/wiki/dereferencable)).

However, the codebase contains both `dereferencable` and `dereferenceable`, with `dereferencable` being used more frequently.

## Actions

1. Standardize the codebase to use one term consistently.
2. Decide between using `dereferencable` or `dereferenceable` based on correctness and consistent usage.

### Recommendation

Considering the reference and the correct spelling, I recommend standardizing the term `dereferenceable` throughout the codebase.

## Related

https://github.com/nikic/PHP-Parser/pull/1004

**Comment by nikic** [comment]
Fixed by #1006, thanks!

ngrams result for reference: https://books.google.com/ngrams/graph?content=dereferencable%2Cdereferenceable&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3
