### ISSUE TITLE
How to create an array item with a boolean value?

### ISSUE THREAD

**Issue by fsuter** [nikic/PHP-Parser#1010]
I'm trying to create a new `ArrayItem` inside an existing array but the value should be a boolean. For a string, the code would be something like:

```php

$node->value->items[] = new ArrayItem(
    new String_('the value'),
    new String_('the key')
);
```

but I can't find any class corresponding to `String_` (or other similar) for boolean values.

Thanks in advance for the help.

**Comment by nikic** [comment]
Booleans are just constants, so something like `new Expr\ConstFetch(new Name('true'))`.

Alternatively you can use https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/BuilderFactory.php#L215 from the BuilderFactory, that is `$factory->val(true)` (also works for integers, strings, etc.)

**Comment by fsuter** [comment]
That worked beautifully. And the BuilderFactory is a wonderful catalog of examples that helped me with a couple of other things. Brilliant!
