### ISSUE TITLE
NameResolver will not work on Throws subnodes

### ISSUE THREAD

**Issue by maddy2101** [nikic/PHP-Parser#1011]
Hi,

i face the situation to want to analyse `throw new \Vendor\App\Foo\Exception('message', 123);` calls. When I filter for NEW_ nodes, the namespace of the exception class is resolved, all good.
But what I need is the Throw_ node, where $node->expr is the New_, but inside this class the namespace is not resolved.

Is there a way to go that route? 

Please feel free to ask for further information, I am not exactly sure how that might be resolved or maybe there is already some solution that I could use? Thank you very much for any help.

**Comment by maddy2101** [comment]
adding this to the NodeResolver::enterNode() function solves my issue:

`elseif ($node instanceof Expr\Throw_) {
            $name = $node->expr?->class ?? null;
            if ($name instanceof Name) {
                $node->expr->class = $this->resolveClassName($name);
            }
        }`

Do you want me to create a PR?

**Comment by nikic** [comment]
If you have one NodeTraverser with multiple visitors, they are interleaved, see https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown#multiple-visitors. If you need the child nodes to already be resolved, you can either:

 * Run your code inside leaveNode(), in which case children will have already been processed and resolved.
 * Use two separate NodeTraversers, where you first run NameResolver over everything, and then run your visitor over everything, completely independently. That way the order does not matter.

**Comment by maddy2101** [comment]
I feel slightly embarrassed to not have thought of it -.-. Running code in leaveNode proved to be working. Thank you so much for the work, the tool and the support.
