### ISSUE TITLE
Question: setting default value for properties or declaring them possibly null

### ISSUE THREAD

**Issue by fsuter** [nikic/PHP-Parser#1013]
Hi,

I'm building classes using `\PhpParser\BuilderFactory`. When adding properties, I couldn't find how to give them a default value or setting them as being possible `null`, i.e. something like that:

```php
protected string $name = '';
protected ?\Datetime $date;
```

Is that possible?

**Comment by nikic** [comment]
You can use https://github.com/nikic/PHP-Parser/blob/fadccead52e3c82fb0bb21c053fa81e72d94aa9a/lib/PhpParser/Builder/Property.php#L98 to set the default value and https://github.com/nikic/PHP-Parser/blob/fadccead52e3c82fb0bb21c053fa81e72d94aa9a/lib/PhpParser/Builder/Property.php#L126 to set the type (including a nullable type).

**Comment by fsuter** [comment]
Ah great! I had worked directly with `new \PhpParser\Node\Stmt\Property()` which is why I hadn't seen these possibilities.

Thanks.

**Comment by fsuter** [comment]
Sorry, I closed the issue too fast. I still can't create a nullable type property.

When I have something like:
```php
$property = new \PhpParser\Builder\Property('date');
$property->setType(new \PhpParser\Node\FullyQualified(\DateTime::class));
```

how do I make the property nullable?

**Comment by nikic** [comment]
You can wrap it into a `new \PhpParser\Node\NullableType(...)`.

**Comment by fsuter** [comment]
Ah indeed. Thanks again!
