### ISSUE TITLE
PHP 8.4 deprecation warning

### ISSUE THREAD

**Issue by alecpl** [nikic/PHP-Parser#1017]
```
PHP Deprecated:  PhpParser\Parser::parse(): Implicitly marking parameter $errorHandler as nullable is deprecated, the explicit nullable type must be used instead in /vendor/nikic/php-parser/lib/PhpParser/Parser.php on line 17
```

**Comment by nikic** [comment]
This was fixed in https://github.com/nikic/PHP-Parser/pull/984, you're probably using an old version? If you're on 4.x you basically need the very newest version 4.19.1.

**Comment by alecpl** [comment]
I'm running composer with `--prefer-lowest` (and `config.platform.php=8.1`) that gave me:
- phpunit/phpunit (9.6.20)
- phpunit/php-code-coverage (9.2.31)
- sebastian/complexity (2.0.0)
- nikic/php-parser (v4.18.0)

Both php-code-coverage and complexity have minimum set on 4.18. I guess I'll have to force 4.19.1 in my composer.json.

**Comment by sebastianbergmann** [comment]
> I guess I'll have to force 4.19.1 in my composer.json.

Or do not use `--prefer-lowest`. Anyway: https://github.com/sebastianbergmann/php-code-coverage/commit/2681df11ccc4d3553c973ecf348acbdd0e7b7415

**Comment by alecpl** [comment]
Thank you guys.
