### ISSUE TITLE
Suggestion: Add support for PHPUnit 11

### ISSUE THREAD

**Issue by ThomasLandauer** [nikic/PHP-Parser#1020]
Same suggestion for PHPUnit 10 https://github.com/nikic/PHP-Parser/issues/943 is closed as completed, but [`composer.json`](https://github.com/nikic/PHP-Parser/blob/master/composer.json) still only allows `"phpunit/phpunit": "^9.0"`.

**Comment by nikic** [comment]
We need PHPUnit 9 for PHP 7.4 support, and there is no benefit to supporting additional PHPUnit versions unless it becomes necessary to support new PHP versions. PHPUnit 10 needs some changes to the XML config file, so having both side by side is more hassle than it's worth.

**Comment by ThomasLandauer** [comment]
OK, but then please close the issues as "not planned", cause I was kinda puzzled to see the other issue being "completed".
