### ISSUE TITLE
LiteralArrayItem uses wrong PhpParser's ArrayItem

### ISSUE THREAD

**Issue by sharkodlak** [nikic/PHP-Parser#1021]
There is an issue in LiteralArrayItem which uses PhpParser\Node\Expr\ArrayItem. This namespace doesn't exist anymore and PhpParser\Node\ArrayItem shall be used instead.

phpstan/phpstan: 1.12.1
nikic/php-parser: v5.1.0

This issue is related to rector/rector. When I want to create my own PhpParser\Node\Arg with PhpParser\Node\ArrayItem it fails because PHPStan requires PhpParser\Node\Expr\ArrayItem instead.

[ERROR] Could not process "tests/Entities/TestEntity.php" file, due to:                                                
         "System error: "PHPStan\Node\LiteralArrayItem::__construct(): Argument #2 ($arrayItem) must be of type         
         ?PhpParser\Node\Expr\ArrayItem, PhpParser\Node\ArrayItem given, called in                                      
         phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php2326"

**Comment by staabm** [comment]
PHPStan is not yet compatible with php-parser version 5.

See https://github.com/phpstan/phpstan-src/blob/327789e17116cf88e9a1a98d60c5dd40b502ba2b/composer.json#L25

**Comment by sharkodlak** [comment]
Ok, than this issue isn't issue of PHPStan and may be closed.
