### ISSUE TITLE
`TraitUse` objects returned by `Class_::getTraitUses()` do not provide namespaced names when `NameResolver` is used

### ISSUE THREAD

**Issue by sebastianbergmann** [nikic/PHP-Parser#1027]
For each `Class_` that I process, I want to process the traits `use`d by the class. The `Class_` provides the `getTraitUses()` method to access this information. However, the `TraitUse` objects returned by `getTraitUses()` do not hold the namespaced name of the trait that is used, only the name without the namespace name:

```php
<?php declare(strict_types=1);
namespace example;

use PhpParser\Node;
use PhpParser\Node\Stmt\Class_;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitor\NameResolver;
use PhpParser\NodeVisitor\ParentConnectingVisitor;
use PhpParser\NodeVisitorAbstract;
use PhpParser\ParserFactory;

require __DIR__ . '/vendor/autoload.php';

trait T
{
}

class C
{
    use T;
}

$nodes = (new ParserFactory)->createForHostVersion()->parse(
    file_get_contents(__FILE__),
);

assert($nodes !== null);

$traverser = new NodeTraverser;

$traverser->addVisitor(new NameResolver);
$traverser->addVisitor(new ParentConnectingVisitor);

$traverser->addVisitor(
    new class extends NodeVisitorAbstract
    {
        public function enterNode(Node $node): void
        {
            if (!$node instanceof Class_) {
                return;
            }

            if ($node->isAnonymous()) {
                return;
            }

            var_dump($node->namespacedName->toString());

            foreach ($node->getTraitUses() as $traitUse) {
                foreach ($traitUse->traits as $trait) {
                    var_dump($trait->name);
                }
            }
        }
    }
);

$traverser->traverse($nodes);
```

Running the code shown above yields the output shown below:

```
string(9) "example\C"
string(1) "T"
```

Please advise how I can get the namespaced name (`example\T`) instead of non-namespaced name (`T`).

I use version 5.2.0 of PHP-Parser.

**Comment by nikic** [comment]
This should work if you either a) use a separate traverser for your visitor or b) use leaveNode. The problem is that the names only get resolved when the TraitUse node is visited, but you're trying to already use them when the Class node is visited.

**Comment by nikic** [comment]
See also https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown#multiple-visitors for what the general behavior here is. If the visitors are part of one traverser, they are interleaved.

**Comment by sebastianbergmann** [comment]
I can confirm that I get the desired information when I use separate `NodeTraverser`s: one to visit with `NameResolver` (and `ParentConnectingVisitor`) and another one to visit with my visitor:

```
string(9) "example\C"
string(9) "example\T"
```

I can also confirm that I get the same output as shown above when I implement `leaveNode()` in my visitor instead of `enterNode()`.

So as far as the (hopefully) minimal and self-contained example I extracted from my [`CodeUnitFindingVisitor`](https://github.com/sebastianbergmann/php-code-coverage/blob/11.0.6/src/StaticAnalysis/CodeUnitFindingVisitor.php) is concerned: I am happy. Thank you for your help!

I now have to think about how to adapt `CodeUnitFindingVisitor`. For performance reasons, I want to avoid traversing the AST twice. But when I simply rename that class' `enterNode()` method to `leaveNode()` then its existing tests start failing ... The fun never stops ;-)
