### ISSUE TITLE
Deep cloning of nodes?

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#103]
I would like to modify the node tree, but because it is referenced multiple times throughout my object hierarchy, I don't want to change existing instances.

NodeAbstract does not implement custom __clone() method so I suspect that cloning it will produce a shallow clone.

Is there any way to deep-clone nodes besides parsing the source code again or do I have to implement it myself?

**Comment by muglug** [comment]
For anyone tracking, the above is no longer true - `$stmts = $traverser->traverse($stmts);` returns the exact same collection of objects.
