### ISSUE TITLE
Not possible to parse stubs with function exit() and die() (PHP 8.4 change)

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#1036]
Hi,
both php-src stubs (https://github.com/php/php-src/blob/edc94a8d21021659853fca32f2c30f154318bb43/Zend/zend_builtin_functions.stub.php#L10-L13) and phpstorm-stubs (https://github.com/JetBrains/phpstorm-stubs/blob/a45eab9318f66864e9840379d3a1976ffe9b8d63/Core/Core.php#L1134-L1142) introduced `function exit()` and `die()`.

Because of this RFC: https://wiki.php.net/rfc/exit-as-function

With these functions PHP-Parser throws a parse error:

```
Uncaught PhpParser\Error: Syntax error, unexpected T_EXIT, expecting T_STRING or T_READONLY or '('
```

What could be done about this? Of course there's a hacky way around that:

```
		if (str_ends_with($path, '/vendor/jetbrains/phpstorm-stubs/Core/Core.php')) {
			$contents = str_replace([
				'function exit',
				'function die',
			], [
				'function _exit',
				'function _die',
			], $contents);
		}
```

But I don't think that's really feasible long-term. Should PHP or PHP-Parser change its grammar to accommodate for this? Or should these functions be removed from the stubs because it's no longer valid PHP?

**Comment by staabm** [comment]
Is this a duplicate of https://github.com/nikic/PHP-Parser/issues/1030 ?

**Comment by ondrejmirtes** [comment]
It is.
