### ISSUE TITLE
PHP-Parser cannot be installed in classmap-authoritative=true enabled projects that use deprecated class names

### ISSUE THREAD

**Issue by urbanecm** [nikic/PHP-Parser#1045]
`PHP-Parser` deprecates class names by creating a stub that `require`s the right file. For example, `lib/PhpParser/Node/Scalar/LNumber.php` currently contains:

```
<?php declare(strict_types=1);

require __DIR__ . '/Int_.php';
```

Unfortunately, this approach does not work when `classmap-authoritative` is set to `true`. In that case, Composer only consults its class map and it does not attempt to check the filesystem itself. This speeds up autoloading substantially.

See the following shell session that demonstrates the issue:

```
urbanecm@notebook classmap-authoritative-example % cat composer.json
{
    "name": "urbanecm/classmap-authoritative-example",
    "require": {
        "nikic/php-parser": "^5.3"
    },
    "authors": [
        {
            "name": "Martin Urbanec",
            "email": "murbanec@wikimedia.org"
        }
    ]
}
urbanecm@notebook classmap-authoritative-example % cat test.php
<?php

require_once __DIR__ . '/vendor/autoload.php';

echo \PhpParser\Node\Scalar\LNumber::KIND_BIN . PHP_EOL;
urbanecm@notebook classmap-authoritative-example % composer dump-autoload
Generating autoload files
Generated autoload files
urbanecm@notebook classmap-authoritative-example % php test.php
2
urbanecm@notebook classmap-authoritative-example % composer dump-autoload --classmap-authoritative
Generating optimized autoload files (authoritative)
Generated optimized autoload files (authoritative) containing 255 classes
urbanecm@notebook classmap-authoritative-example % php test.php
PHP Fatal error:  Uncaught Error: Class "PhpParser\Node\Scalar\LNumber" not found in /Users/urbanecm/tmp/classmap-authoritative-example/test.php:5
Stack trace:
#0 {main}
  thrown in /Users/urbanecm/tmp/classmap-authoritative-example/test.php on line 5

Fatal error: Uncaught Error: Class "PhpParser\Node\Scalar\LNumber" not found in /Users/urbanecm/tmp/classmap-authoritative-example/test.php:5
Stack trace:
#0 {main}
  thrown in /Users/urbanecm/tmp/classmap-authoritative-example/test.php on line 5
urbanecm@notebook classmap-authoritative-example %
```

We run into this issue while upgrading [MediaWiki](https://mediawiki.org)'s version of `nikic/php-parser` from `^4.10.2` to `^5.3.1`. For more details, see [downstream ticket](https://phabricator.wikimedia.org/T381291).

Would it be possible to alias class names in a way that allows `classmap-authoritative` to continue working?

**Comment by ghostwriter** [comment]
> Do you know what the right way to do this would be?

Here’s one solution:

The classes are defined only for composer, static analysis and internal tooling purposes.

They are not loaded or registered at runtime but are conditionally declared in their respective files.

eg.

```php
// lib/PhpParser/Node/Scalar/LNumber
<?php declare(strict_types=1);

namespace PhpParser\Node\Scalar;

require __DIR__ . '/Int_.php';

if (false) {
    class LNumber extends Int_ {}
}
```

```php
// lib/PhpParser/Node/Scalar/DNumber.php
<?php declare(strict_types=1);

namespace PhpParser\Node\Scalar;

require __DIR__ . '/Float_.php';

if (false) {
    class DNumber extends Float_ {}
}
```

**Comment by staabm** [comment]
> static analysis

AFAIR phpstan is smart enough to realize the IF case is never taken and it will not see this class therefore.
needs to be validated
