### ISSUE TITLE
Property with multiple props and property hooks should be a parse error

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#1050]
This piece of code:

```php
class Foo
{
    
    public $foo, $bar { get {} }
    
}
```

Is rejected by PHP with error message: `Parse error: syntax error, unexpected token “{”, expecting “,” or “;” in /in/RndUG on line 6`

But PHP-Parser does not report syntax error and represents this with an AST.

Multi-props with property hooks are not supported in PHP. I'm asking about this to find out if this should be a parse error in PHP-Parser, or if this is going to be represented with an AST and PHPStan should come with a custom rule to detect it.

Thanks.

**Comment by nikic** [comment]
I'm fine with having this as a parse error.

**Comment by ondrejmirtes** [comment]
Thanks. Unfortunately I don't know how to implement this one, grammar is still out of my expertise.

**Comment by nikic** [comment]
This one wouldn't be checked directly in the grammar, it needs a manual check like the one here: https://github.com/nikic/PHP-Parser/blob/4f9dc8b0f50d7bbc6b3197ec5cb2ad928fc10d40/lib/PhpParser/ParserAbstract.php#L1161-L1167

**Comment by ondrejmirtes** [comment]
Alright, tried it: https://github.com/nikic/PHP-Parser/pull/1052

Had to modify the grammar anyway 😅

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/PHP-Parser/commit/d20a197ca73fc07d1aa980509b49f4ce268a22a4.
