### ISSUE TITLE
PropertyHook::getStmts() is wrong for short body set hook

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#1053]
Given short body hooks:

```php
class Foo
{
    public $test {
        get => strtolower($this->test);
        set => strtoupper($value);
    }
}
```

The implementation of `PropertyHook::getStmts()`:

```php
    public function getStmts(): ?array {
        if ($this->body instanceof Expr) {
            return [new Return_($this->body)];
        }
        return $this->body;
    }
```

Is correct for the get hook, but not for set hook. I consulted this with Ilija (co-author of property hooks) and he showed me this piece of code: https://github.com/php/php-src/blob/6e759e079f882fe54afa6da31f9cc86e9f680bf6/Zend/zend_compile.c#L8492-L8506

Which shows that short body set hook is expanded to `$this->test = strtoupper($value);`, not `return strtoupper($value);`.

But the PropertyHook node does not have access to its property name so we can't construct the correct expression in `getStmts()`.

What would you recommend here? It's easy to work around this problem, but it's a bit misleading about how it works. For example, the `set` hook always has implicit `void` return type so it's always wrong to "return" something from it.

**Comment by nikic** [comment]
The best I can think of is to add an attribute with the property name that's set by the parser and make the method throw if it's not present.

**Comment by nikic** [comment]
> The best I can think of is to add an attribute with the property name that's set by the parser and make the method throw if it's not present.

I've implemented this variant now.

**Comment by ondrejmirtes** [comment]
Awesome, thank you! I've meant to look into it, but worked on property hooks support in PHPStan which made me busy for several weeks: https://github.com/phpstan/phpstan-src/pull/3746
