### ISSUE TITLE
How can I modify a specified Node in a traversal visitor 

### ISSUE THREAD

**Issue by yanhuichao** [nikic/PHP-Parser#1054]
`<?php
return [
    'account_conf' => [
        'cfg_a' => [
            'cashout_limit' => ['min' => 0, 'max' => 100],
        ],
       'cfg_b' => [
            'cashout_limit' => ['min' => 10, 'max' => 60],
        ],
    'cs' => [
        "test" => false
    ]
];
`

I want to add a new item(cfg_b) into the array 'account_conf', like the code shows. 
while the method NodeTraverser->traverse(array $nodes) don't accept extra params to pass the data that will be used in 'enterNode' function,  thanks

**Comment by nikic** [comment]
Maybe I'm misunderstanding the question here, but can't you pass the data to the Visitor? (Either via the constructor or a method call if you're reusing the visitor multiple times).

**Comment by yanhuichao** [comment]
`
private $class = null;
public function enterNode(Node $node) {
    if ($node instanceof Node\Stmt\Class_ &&
        $node->namespacedName->toString() === 'Foo\Bar\Baz'
    ) {
        $this->class = $node;
        return NodeTraverser::STOP_TRAVERSAL;
    }
}
`

Sorry, I didn't express myself clearly.  I meant to pass the class name like 'Foo\Bar\Baz' as a parameter to `enterNode` so that I can search any name I want, instead of
