### ISSUE TITLE
[Info] Working on parsers in PHP

### ISSUE THREAD

**Issue by nicolas-grekas** [nikic/PHP-Parser#142]
Hello,

This "issue" is just an informational notice to let you know about a side project I'm working on, related to parsing in PHP:

- https://github.com/nicolas-grekas/Parser is the most recent and in early WIP state. I took @nikic's idea of using kmyacc for generating parsers in PHP. But unlike PHP-Parser, I'm trying *not* to be bound to parsing only PHP. Instead, I take the symbols in the grammar files as nodes names in my AST, whatever the parsed syntax. [Here](https://github.com/nicolas-grekas/Parser/blob/master/test.php) is a self generating PHP file with its AST nodes next to each source code statement. [Here](https://github.com/nicolas-grekas/Parser/blob/master/test.xml) is the same AST but dumped in XML.

  I also managed to refactor the [abstract kmyacc parser algorithm](https://github.com/nicolas-grekas/Parser/blob/master/Parser/AbstractParser.php) to make it bijective. This means that non-semantic tokens are preserved (e.g. whitespaces and comments). This could be ported to PHP-Parser now (see #41).

- https://github.com/nicolas-grekas/Patchwork-PHP-Parser is an other *stable* PHP parser that has its first commit in 2005. The approache it uses is based on a collection of dedicated and contextual token analysers. So, no grammar behind, but only "expert" knowledge. I consider the kmyacc way a better one. My goal now is to port all the good things inside this old but stable parser to the above new one. What good things? Well, this parser is focused on applying *code transformations* to an existing PHP code. I have written a lot of local parsers for e.g. gathering contextual information (resolving namespaces), backward/forward porting new syntaxes, instrumentation, inlining, etc. [See the full list here](https://github.com/nicolas-grekas/Patchwork-PHP-Parser/tree/master/class/Patchwork/PHP/Parser) and [see them in action here](https://github.com/nicolas-grekas/Patchwork-PHP-Parser/tree/master/tests/Patchwork/Tests/PHP/Parser).

I'm not sure what's next to this notice. But at least that can give some ideas?

**Comment by nikic** [comment]
Closing as this isn't a real issue.

Btw there's also https://github.com/grom358/pharborist which tries to better support preserving whitespace and formatting in general. Didn't look closely at it yet.
