### ISSUE TITLE
Node->getPos

### ISSUE THREAD

**Issue by basz** [nikic/PHP-Parser#145]
I am collecting certain methods calls via a node visitor. Part of this process is to record where in the source the method call occurs. This can be easily accomplished with the getLine() method of a Node. However I would like to know the position within the line (or document) too. 

Is there a trick to this to accomplish this or simple not possible (at this moment). Are there plans to add such a feature?

**Comment by Ciantic** [comment]
@basz thanks for sharing. I think this will be valuable starting for writing proper IDE auto-completion for PHP (in vscode). Small nugget for sure, but determining the context where the cursor is located at is the first thing to look at when filtering for auto-completion choices.
