### ISSUE TITLE
Preserve information about used array syntax and number format.

### ISSUE THREAD

**Issue by suralc** [nikic/PHP-Parser#146]
Is it currently impossible to retrieve the syntax type used to define an array (`array()` vs `[]`) or did I overlook something? (The grammar file already makes a difference, but creates the same Array_ instance, maybe pass an optional parameter if the new syntax is used?)

Also binary and octal numbers (`0b1010` and `0777`) are represented as LNumber. It may  be useful to have the source format available there. (type attribute with a LNumber::TYPE_BINARY constant or similiar)

This may be used for some static analysis scenarios and detection of minimal php version requirements.

edit: I read about the second part in #26 It may still be nice to have atleast the used array notation as a flag on the node.

**Comment by gonzaloserrano** [comment]
Hi, this addition would be great! Since we have part of our codebase that supports PHP 5.3 and sometimes our devs use short array syntax by mistake, we could write a script to analyze the changed files and check for this behaviour.

**Comment by suralc** [comment]
@gonzaloserrano  Most of this should be managable to implement, I guess.
You could use http://php5.laurent-laville.org/compatinfo/blog/ for most circumstances (not short arrays, though). Some things are however not (yet) implemented there:
Take a look at the snippet above and the implementations(my project (some rewrites required), not related to the one linked above) here (Feel free to copy):
* [Lexer](https://github.com/suralc/pvra/blob/master/src/Lexer/ExtendedEmulativeLexer.php#L53)
* [PHP 5.4 Binary numbers](https://github.com/suralc/pvra/blob/master/src/Analysers/Php54Features.php#L190)
* [PHP 5.4 Short array](https://github.com/suralc/pvra/blob/master/src/Analysers/Php54Features.php#L207)
* [PHP 5.4 Always on - Short Echo](https://github.com/suralc/pvra/blob/master/src/Analysers/Php54Features.php#L221)

**Comment by gonzaloserrano** [comment]
Very cool projects @suralc, thanks!

**Comment by llaville** [comment]
@suralc Very interesting project (pvra). I've just take a look, and seems really promising.

As, I said, in an old version of my [roadmap](https://github.com/llaville/php-compat-info/issues/152), I'd like to implement such PHP features analyser.
But my priorities changed. So I'm happy to see that an alternative exist !

Perharps, before the stable release of new major version 4.0, a similar analyser will be born.
Until this day come true, I've a big challenge, almost reach, [detection of conditional code](https://github.com/llaville/php-compat-info/issues/160).

**Comment by nikic** [comment]
Added `kind` attribute for LNumber nodes in https://github.com/nikic/PHP-Parser/commit/ae30f97af6e006a26398d17de1b5c8ab933b822d.

**Comment by nikic** [comment]
And same is now also supported for array nodes: https://github.com/nikic/PHP-Parser/commit/aa199120c73d2d7a5fd1fb4d6a75025ccbaef886

As such closing this issue, finally :)
