### ISSUE TITLE
Differentiate die() and exit()

### ISSUE THREAD

**Issue by ockham** [nikic/PHP-Parser#150]
Both are represented by `Expr\Exit_`, which `PrettyPrinter` will print as `die`, which is an obstacle to bijectivity, among other things. Maybe we can have a `type` subnode to differentiate them as with `Expr\Include_`?

**Comment by edsonmedina** [comment]
+1

**Comment by nikic** [comment]
@ondrejmirtes `exit` and `die` are strictly identical, both accept either a status code or a string to print.

Generally the way something like this can be currently distinguished is by extending the lexer and adding an attribute, e.g. as done in the code sample on https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#attribute-handling.

So for this particular case you'd do something like this:

    if ($tokenId == PHPParser\Parser::T_EXIT) {
        $endAttributes['isDie'] = strtolower($value) === 'die';
    }

**Comment by ondrejmirtes** [comment]
@nikic Sorry, my bad. I used these functions in this way but didn't check the documentation before writing my remark.

**Comment by nikic** [comment]
Now adding a `kind` attribute to `Exit` nodes in the default lexer: https://github.com/nikic/PHP-Parser/commit/47c342a3e43b31c91fd757733a42072dab66fcd4
