### ISSUE TITLE
Feature request: allow NodeVisitor to indicate to NodeTraverser no further traversal down this branch

### ISSUE THREAD

**Issue by mappu** [nikic/PHP-Parser#161]
I need to avoid doing some processing on nodes if they have certain parents somewhere further up the AST.

One way would be to recursively look up parents of a node. But this isn't possible (even if it was, it duplicates NodeTraverser in reverse and would be less efficient than simply stopping the traversal at once when meeting my stop condition). So i think it would be useful if i could prevent further tree traversal from within a `NodeVisitor`.

I suggest this is implemented as
- an additional possible return value from `NodeVisitor`
- or alternatively, by throwing some certain `PleaseNoMoreTraversalDownThisBranch` exception from within `NodeVisitor::enterNode` caught by `NodeTraverser`.

**Comment by edsonmedina** [comment]
+1
The only workaround I could find is having a "mute" variable shared between `NodeVisitors` that I set on `enterNode` and later unset in `leaveNove` of the parent node. All visitors would have to respect this mute.

**Comment by nikic** [comment]
I've added a `NodeTraverser::DONT_TRAVERSE_CHILDREN` return value for `enterNode()` in https://github.com/nikic/PHP-Parser/commit/4071c4645d22881c05fa4bac03eb6da2158f5c69. The details of what will (not) be called are described in https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeTraverserInterface.php#L7.

Does this look okay to you?

**Comment by edsonmedina** [comment]
Brilliant. Thanks.
