### ISSUE TITLE
"new" with concatenated names parses incorrectly

### ISSUE THREAD

**Issue by stuartherbert** [nikic/PHP-Parser#162]
Given this code:

    $name1 = 'PHPReq\Scanner\\';
    $name2 = 'NodeInspector';
    $obj1 = new $name1 . $name2;

The parser produces this node:

    class PhpParser\Node\Expr\New_#1061 (2) {
      protected $subNodes =>
      array(2) {
        'class' =>
        class PhpParser\Node\Expr\Variable#1062 (2) {
          protected $subNodes =>
          array(1) {
            'name' =>
            string(5) "name1"
          }
          protected $attributes =>
          array(2) {
            'startLine' =>
            int(33)
            'endLine' =>
            int(33)
          }
        }
        'args' =>
        array(0) {
        }
      }
      protected $attributes =>
      array(2) {
        'startLine' =>
        int(33)
        'endLine' =>
        int(33)
      }
    }

$node->class contains a Variable. I was hoping that it would contain a BinaryOp\Concat instead :)

**Comment by nikic** [comment]
`new` has a higher precedence than concatenation, so PHP interprets your expression as `$obj = (new $name1) . $name2` (*). See http://codepad.viper-7.com/grv7BL.

(*) Actually this has less to do with precedence and more with the fact that `new` only accepts call-free base-variables. But it's easiest to think about it in terms of precedence.

**Comment by stuartherbert** [comment]
Ah, of course. Thank you for the quick reply!
