### ISSUE TITLE
Feature request: Tell other visitors to skip this node

### ISSUE THREAD

**Issue by edsonmedina** [nikic/PHP-Parser#164]
Hi,
Similarly to #161, could there be a way to tell NodeTraverser to not further traverse THIS node?

As an example, I have several NodeVisitors looking for specific patterns. After any of them finds what it's looking for, it makes no sense to have all other NodeVisitors look too.

Ticket #161 already tells the traverser to ignore the children, I want to ignore the CURRENT node.

**Comment by nikic** [comment]
If this is just a perf optimization, I'm not sure the added complexity is worth it. After all it's not just breaking out of a loop. We'd still have to do the `leaveNode` calls, but only for visitors that weren't skipped.

**Comment by edsonmedina** [comment]
You're right, it doesn't make sense.
