### ISSUE TITLE
Filtering parsed result

### ISSUE THREAD

**Issue by 19Gerhard85** [nikic/PHP-Parser#168]
Hey Nikita,

I'm trying to parse a php file determine which classes are called of this file.

The class isn't very large (100 lines) but the var_dump of the parsed result has 4000+ lines.

How can I filter the parsed result?

**Comment by nikic** [comment]
You can filter the tree by implementing a visitor, see https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#node-traversation. What exactly the visitor has to do depends on what you mean by "classes called of this file".

You can also get more compact output than `var_dump` using the `NodeDumper`, see https://github.com/nikic/PHP-Parser/blob/master/doc/3_Other_node_tree_representations.markdown#human-readable-dumping.
