### ISSUE TITLE
Make parser optionally tolerate syntax issues

### ISSUE THREAD

**Issue by cweagans** [nikic/PHP-Parser#170]
I'm working on an autocomplete library for PHP (similar to Jedi for Python), and I'm trying to figure out how to approach making the parser not die if it encounters a syntax error. It's going to be pretty common that as a user is typing out a line of code, the file is going to have some bad syntax, so the parser should be able to handle that.

PHPCodeIntel, a library that attempted to do what my library will do, used the 0.9.x version of PHP Parser, and handled it like this: https://github.com/deweller/PHPCodeIntel/blob/master/PHP/lib/local/PHPIntel/Context/Parser/TolerantParser.php

This, however, doesn't work with the 1.x version.

Any advice on how I should go about doing this?

**Comment by nikic** [comment]
There's already a ticket about this: #60. It has a link to a stub implementation that supports error recovery. I didn't pursue this further, because there didn't seem to be interest anymore.

It shouldn't be too hard to port this to the current code and add enough `error` recovery tokens to make it useful. But I don't think I'll have time to work on this soon.

**Comment by cweagans** [comment]
That's really helpful. Thanks! Perhaps I'll be able to submit a PR at some point. If not, do you take consulting work on this project? If so, can you send me a quote for finishing the error recovery via email? me@cweagans.net

**Comment by nikic** [comment]
Nope, I don't take consulting work on this project ^^ But I found some time to port the error recovery code to the 1.0 parser code, see https://github.com/nikic/PHP-Parser/tree/errorRecovery2. It's just a quick&dirty implementation, but it seems to already work for a number of cases, see https://github.com/nikic/PHP-Parser/commit/3c0c2380478596636f77bb5481e8322906554141#diff-6 for some examples.

The usage is still as described in ticket #60. What this primarily needs is a) better `error` annotations (this requires some feedback, we need to find cases where recovery does not yet work well) and b) handling for non-syntax errors, which currently just throw exceptions, so immediately abort everything.

**Comment by cweagans** [comment]
@nikic So I've been playing with that errorRecovery branch, and I think it's working pretty well. I'd like to suggest merging it to get more people using it. If there's any feedback, then I'd be happy to work on incorporating it. If not, then a new release could be tagged with this included. What do you think?

**Comment by nikic** [comment]
This is in master now: https://github.com/nikic/PHP-Parser/blob/master/doc/component/Error.markdown#error-recovery

Currently only a single `error` symbol is included (I noticed that the grammar in the `errorRecovery2` branch had reduce/reduce conflicts), so this is currently somewhat limited.
