### ISSUE TITLE
Parser does not support DocBlock Templates

### ISSUE THREAD

**Issue by vancoz** [nikic/PHP-Parser#171]
Hello @nikic,

the lib does not work properly with DocBlock Templates.

For example

```
class Test 
{
    /**#@+
     * @api
     * @test
     */
    const TEST13 = 'removed';
    const TEST14 = 'removed1';
    const TEST15 = 'removed2';

    /**#@-*/
}
```

DocBlock will be recognized only for first constant, but it should be available for all of them.

Thanks.

**Comment by nikic** [comment]
The parser doesn't analyze doc comments, it only returns them literally as they occur in the source code. Parsing doc comments is outside the scope of this project (especially such exotic things like templates - first time I heard about it).
