### ISSUE TITLE
Parse just an Expression

### ISSUE THREAD

**Issue by kparaju** [nikic/PHP-Parser#173]
I'm looking to parse a PHP Expression, not a whole file. Expressions like `$this->foo()` or `"Hello " . $name`.

I could not find documentation on how to do it and could not find any way to do with when snooping around the code either. Is it/Will it be supported?

**Comment by nikic** [comment]
It is not explicitly supported, but you should be able to do this simply by parsing `<?php expr;` instead. Example:

    $parser = new PhpParser\Parser(new PhpParser\Lexer);
    try {
        $stmts = $parser->parse('<?php ' . $expr . ';');
        $expr = $stmts[0];
        // Do something with $expr
    } catch (PhpParser\Error $e) {
        // ...
    }
