### ISSUE TITLE
Stop traversing when nesting limit reached

### ISSUE THREAD

**Issue by llaville** [nikic/PHP-Parser#174]
With my two projects that used your parser (v1.1.0), I've been recently confronted to a huge AST built.
And it's impossible to traverse fully, even if as recommanded, we set the `xdebug.max_nesting_level` directive to 2000.

Source code is Zend Framework 1.12.11 with file `library\Zend\Validate\Hostname\Biz.php` 

My question / request :  is it possible to stop traversing AST when we reach the nesting level and return a code to tell us that the traverse is incomplete ?

**Comment by nikic** [comment]
According to http://twtsurvey.com/xdebug-max-nesting you should be able to safely increase the nesting limit to something like `10000`. If that's enough I'd just do that instead of trying to track recursion level during traversation.

**Comment by llaville** [comment]
Ok it's a recommandation to added to your page `doc/2_Usage_of_basic_components.markdown`.

I run the test with 10000 and memory_limit = -1, and I got results.

**Comment by nikic** [comment]
I've adjusted the docs to use a `3000` nesting limit in https://github.com/nikic/PHP-Parser/commit/8f1eacdab702d94f569e1cfc00bb67543768e03a.

**Comment by llaville** [comment]
@nikic One more warning, and perharps tip, you should add is : 
If you've trouble with nesting level limit, just try without xdebug extension loaded.

This is what I've experimented and I gave good (better) results when I try to analyse the ZF1 source code with my project (php-compatinfo).
