### ISSUE TITLE
Please provides test

### ISSUE THREAD

**Issue by remicollet** [nikic/PHP-Parser#178]
Hi

Since 1.1.0 and 0dd2b9a74c46149847d79e72cf418a0f519e3ed9 tests are no more provided in the downloadable tarball.

Can you please consider removing  the export-ignore line for test in .gitattribute, and provide them again ?

     test export-ignore

**Comment by TomasVotruba** [comment]
@remicollet Hi, this dues to composer optimization, IIRC. You should be able to obtain test via cloning the repository.

**Comment by remicollet** [comment]
Yes, I'm able to get the test suite from a clone of the repo, but this is terribly ugly.

If composer don't want the test suite, this is a composer issue, which doesn't have to be fixed in each package, but in composer.

**Comment by TomasVotruba** [comment]
What exactly is ugly? Contributing to Github repository with help of git is natural. What is your goal actually? 

OT: Composer does not (and should not) restrict downloading of any file. It's up to repository maintainer, what to include.

**Comment by remicollet** [comment]
I'd just like https://github.com/nikic/PHP-Parser/archive/v1.1.0.tar.gz to be usable for downstream distribution.

But close this one if you don't care.

Composer just introduce very bad practices instead of very old good practices (having doc + test in distribution / official tarball).

**Comment by remicollet** [comment]
Notice if you don't distribute "test", no need to distribute phpunit.xml

**Comment by Ocramius** [comment]
Please see doctrine/doctrine2#543 as a reference: this is a useless repetition of the same question.

**Comment by remicollet** [comment]
Sorry, but I don't think this is useless. I still disagree and still think "test" and "doc" should be included.

Else remove everything not needed by composer. Why do you keep README, LICENSE, .*.md ?

**Comment by Ocramius** [comment]
LICENSE *MUST* be distributed, as for README, I actually agree that it's not necessary.

**Comment by nikic** [comment]
Personally I agree with @remicollet - it's not a biggie for this project due to low commit activity, but I find it rather annoying to have to clone huge git repos just to get to the test files.

Comparing the sizes of the 1.0.2 and 1.1.0 tar.gz archives, size went down from 110KB to 74KB. Is that really worth causing extra hassle?

**Comment by nikic** [comment]
I've reverted the `.gitattribute` changes in https://github.com/nikic/PHP-Parser/commit/c96636d19231fd0110021060fb258169b4eacdb3.

**Comment by remicollet** [comment]
Thanks.

**Comment by DavidPrevot** [comment]
:+1:

**Comment by kylekatarnls** [comment]
Guys. What can even justify to include tests in distributed packages. It's not a good habit.

Then you can still download the whole source if you like using `--prefer-source`

We should download only what you need when running `composer install` and if we want more, clone the repo. You want to see example usages? You can go to packgist.org > source. Please don't force everybody on the planet to download 200 times files only few people will use a couple of times in a lifetime.

When adding tests files in a project, it should not have impact on the size and download time of the package, mostly as it will be downloaded by machines in productions, CI tools.

And even in local development machines, you're waiting for downloading thousands of files (for instance, a whole symfony projects copy more than 3000 files, and it would be even worst if libraries would not use .gitattributes).

Doc and tests should be viewed online or downloaded on need. Composer purpose is downloading dependencies to run in an efficient way.

So the right option is making the package as light and fast to download use `export-ignore`, then for users who find easier to search documentation and tests in their vendor directory than on the web, they still can use `--prefer-source`.

**Comment by DavidPrevot** [comment]
The fact that composer doesn’t (yet?) offer a way to download a minimal package (without test or doc) is really not a good excuse to impose every single package to trim away their testsuite from their tarball.

**Comment by kylekatarnls** [comment]
Composer has no way to detect by itself what is needed and what is test/doc, so it's perfectly normal for the library owners to specify it. Remember it's a Git feature, not a composer's one. It's up to the user to choose: `--prefer-source` / `--prefer-dist`. So nothing is imposed. The library owner simply says "the library can work without this and that." As simple as this.

**Comment by nikic** [comment]
Probably fighting a loosing battle here ... I don't think it's good to strip tests from git tarballs, but I guess it's also kind of pointless to keep them in a single package when all the others are stripping them.

**Comment by kylekatarnls** [comment]
Hi @nikic, if you let them there's no way to not download them when you're deploying on production (a place you have absolutely no reason to download and keep tests files). However if you strip tests, users can choose to download all the packages with the whole source files or only with the useful files using the options `composer` provides.

As composer is the only documented way to install the package, it seems fair to be composer-friendly. Composer said in the doc for `--prefer-dist`:

> This can speed up installs substantially on build servers and other use cases where you typically do not run updates of the vendors.

It's designed to make builds faster. And it does if maintainers are OK to let their users decide what they need and it costs 1 line of code.
