### ISSUE TITLE
Also parse comments within statement

### ISSUE THREAD

**Issue by nickygerritsen** [nikic/PHP-Parser#181]
The subject might be a bit fuzzy, but what I would like to have is for the following example:

```php
$x
    /** @Desc("A B") */
    ->doSomething($t->trans('a.b'));
```

That the `@Desc` DocBlock gets added somewhere in the AST, I'd say to the `doSomething()` function. This currently does not seem to be the case. I checked the code and the DocBlock is parsed correctly and added to the `$attributeStack`, but it is never used as an argument to one of the `yyn*` functions.

Is this something that would be possible?

(I am trying to use this in a modification to a symfony2 plugin for extracting translation keys).

**Comment by nikic** [comment]
Sorry, I don't see any way to associate that comment with a node using the current system. The comments needs to be before the first token of a node to be recognized.
