### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#182]
BC compatible syntax changes:

* [x] [Return type declarations](https://wiki.php.net/rfc/return_types)
* [x] [Group use declarations](https://wiki.php.net/rfc/group_use_declarations)
* [x] [Null coalesce operator](https://wiki.php.net/rfc/isset_ternary)
* [x] [Spaceship operator](https://wiki.php.net/rfc/combined-comparison-operator)
* [x] [Coroutine delegation](https://wiki.php.net/rfc/generator-delegation)
* [x] [Anonymous classes](https://wiki.php.net/rfc/anonymous_classes)
* [x] [Context sensitive lexer](https://wiki.php.net/rfc/context_sensitive_lexer)

BC incompatible syntax changes:

* [x] [Uniform variable syntax](https://wiki.php.net/rfc/uniform_variable_syntax)
* [x] [Yield operator changes](https://wiki.php.net/rfc/abstract_syntax_tree)
* [x] [Unicode codepoint escape syntax](https://wiki.php.net/rfc/unicode_escape)
* [x] [Scalar type declarations](https://wiki.php.net/rfc/scalar_type_hints_v5)

API changes:

 * [x] Create separate PHP 5 and PHP 7 parsers
 * [x] Create wrapping parser that tries using both PHP 5 and PHP 7 in a specified order
 * [x] Create factory/builder that creates the proper lexer and parser instances in some simple way
 * [x] Document all the things

**Comment by avindra** [comment]
Linking related issue in other project:

https://github.com/bobthecow/psysh/issues/185

**Comment by nikic** [comment]
For the record, if you're hitting an error like `Cannot use 'String' as class name as it is reserved` running on PHP 7: All you need to do is update to version 1.3 and if that doesn't fix it replace your usages of `String` with `String_`.

This issue is only about support parsing of PHP 7, not running on PHP 7 (which should already fully work).
