### ISSUE TITLE
PHP7 compatibility and aliases issue with old code

### ISSUE THREAD

**Issue by llaville** [nikic/PHP-Parser#187]
Hello Nikita,

I've upgraded from version 1.1.0 to 1.2.0, and my old code did not worked as previously.
There is an issue with aliases introduced for PHP7 compatibility.

Have a look on this following script to demonstrate different results between two versions 
```php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

$lexer      = new PhpParser\Lexer\Emulative;
$parser     = new PhpParser\Parser($lexer);
$traverser  = new PhpParser\NodeTraverser;

use PhpParser\Node;

$code = "<?php

if (function_exists('foo')) {
    foo();
}
";

try {
    $stmts = $parser->parse($code);
    
    $stmts = $traverser->traverse($stmts); 
    
    $scalarString = $stmts[0]->cond->args[0]->value;
    print_r( $scalarString );
    
    if ($scalarString instanceof Node\Scalar\String_) {
        echo 'node type : Node\Scalar\String_';  
    
    } elseif ($scalarString instanceof Node\Scalar\String) {
        echo 'node type : Node\Scalar\String';  
    
    }
    
} catch (PhpParser\Error $e) {
    echo 'Parse Error: ', $e->getMessage();
}
```

With PHP-Parser 1.1.0 we got such output 

    PhpParser\Node\Scalar\String Object
    (
        [subNodes:protected] => Array
            (
                [value] => foo
            )

        [attributes:protected] => Array
            (
                [startLine] => 3
                [endLine] => 3
            )

    )
    node type : Node\Scalar\String

While PHP-Parser 1.2.0 give 

    PhpParser\Node\Scalar\String_ Object
    (
        [value] => foo
        [subNodeNames:PhpParser\NodeAbstract:private] =>
        [attributes:protected] => Array
            (
                [startLine] => 3
                [endLine] => 3
            )

    )
    node type : Node\Scalar\String_

So, if we used code such as `instanceof Node\Scalar\String`, upgrading to version 1.2.0, and it won't run as expected anymore 

Hope my explains are enough !

**Comment by nikic** [comment]
Thanks for the report - the issue is that `instanceof` does not invoke the autoloader, so the aliases are not registered.

**Comment by GrahamCampbell** [comment]
Is that a php bug, or a php behaviour?

**Comment by nikic** [comment]
@GrahamCampbell Not really a bug. If a class isn't loaded yet, then there's no way an object can be an instance of said class - that's the idea behind not making `instanceof` autoload. The premise is no longer true with the introduction of `class_alias`, but given that it is a rather second-class citizen I don't think it likely that this behavior will be changed.

**Comment by nikic** [comment]
Here we go: https://github.com/nikic/PHP-Parser/releases/tag/v1.2.1

**Comment by GrahamCampbell** [comment]
@nikic Right, I see. :)
