### ISSUE TITLE
NameResolver concept issue

### ISSUE THREAD

**Issue by llaville** [nikic/PHP-Parser#188]
Hello Nikita,

While, I worked on code restructuration of one my node visitor in my project (php-compatinfo), I found concept issue with `NameResolver` that I can't yet solved. 
Perharps can you give me a TIP ?

Well to understand the problem, I have a little script with a snippet code to analyse.

```
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

use PhpParser\Node;

class MyVisitor extends PhpParser\NodeVisitorAbstract
{
    public function enterNode(Node $node) 
    {
        if ($node instanceof Node\Stmt\ClassMethod) {
            print_r( $node );
            foreach ($node->params as $param) {
                // analyse parameter of class method
            }
        }
    }    
}

$lexer      = new PhpParser\Lexer\Emulative;
$parser     = new PhpParser\Parser($lexer);
$traverser  = new PhpParser\NodeTraverser;
$traverser->addVisitor(new PhpParser\NodeVisitor\NameResolver);
$traverser->addVisitor(new MyVisitor);


$code = '<?php

namespace Foo;

use Doctrine\Common\Cache\Cache;
use DateTime;

class Bar extends DateTime {
    function __construct (Cache $c) {
    }
}
';

try {
    $stmts = $parser->parse($code);
    
    $stmts = $traverser->traverse($stmts); 
    
    print_r( $stmts);
    
} catch (PhpParser\Error $e) {
    echo 'Parse Error: ', $e->getMessage();
}
```
When I want to explore parameters of class method (but it's also true with user function or closure), I can't do it just after entering the `Node\Stmt\ClassMethod` node.

Reason is, at this step, the `PhpParser\Node\Param` chlidren nodes are not yet proceeded.
So the `NameResolver` are not yet resolved class (in example its `Cache`) .

`print_r()` output in `MyVisitor` give 

    PhpParser\Node\Stmt\ClassMethod Object
    (
        [type] => 0
        [byRef] =>
        [name] => __construct
        [params] => Array
            (
                [0] => PhpParser\Node\Param Object
                    (
                        [type] => PhpParser\Node\Name Object
                            (
                                [parts] => Array
                                    (
                                        [0] => Cache
                                    )

                                [subNodeNames:PhpParser\NodeAbstract:private] =>
                                [attributes:protected] => Array
                                    (
                                        [startLine] => 9
                                        [endLine] => 9
                                    )

                            )

                        [byRef] =>
                        [variadic] =>
                        [name] => c
                        [default] =>
                        [subNodeNames:PhpParser\NodeAbstract:private] =>
                        [attributes:protected] => Array
                            (
                                [startLine] => 9
                                [endLine] => 9
                            )

                    )

            )

        [returnType] =>
        [stmts] => Array
            (
            )

        [subNodeNames:PhpParser\NodeAbstract:private] =>
        [attributes:protected] => Array
            (
                [startLine] => 9
                [endLine] => 10
            )

    )

And I'd like to have something like

    [name] => Bar
    [stmts] => Array
        (
            [0] => PhpParser\Node\Stmt\ClassMethod Object
                (
                    [type] => 0
                    [byRef] =>
                    [name] => __construct
                    [params] => Array
                        (
                            [0] => PhpParser\Node\Param Object
                                (
                                    [type] => PhpParser\Node\Name\FullyQualified Object
                                        (
                                            [parts] => Array
                                                (
                                                    [0] => Doctrine
                                                    [1] => Common
                                                    [2] => Cache
                                                    [3] => Cache
                                                )

                                            [subNodeNames:PhpParser\NodeAbstract:private] =>
                                            [attributes:protected] => Array
                                                (
                                                    [startLine] => 9
                                                    [endLine] => 9
                                                )

                                        )

With a `Node\Name\FullyQualified` for Cache $c parameter

Is it possible, and so how ?

**Comment by llaville** [comment]
FYI, I've almost solved my problem in php-compatinfo, even it's not yet perfect.

In my visitor, `enterNode()` I 've dupplicated at twice location the `Node\Param` procress  
```php
<?php

        } elseif ($node instanceof Node\Stmt\Function_
            || $node instanceof Node\Expr\Closure
            || $node instanceof Node\Stmt\ClassMethod
        ) {
              // analyse functions with their parameters  

        } elseif ($node instanceof Node\Param) {
             // parameters with type hint are here resolved

**Comment by nikic** [comment]
Why not just run the name resolver before anything else (i.e. separate pass)?

But I don't have a problem with adjusting the code to resolve param types earlier, if it makes things simpler.

**Comment by llaville** [comment]
With the same explain I gave you when I've proposed the `NodeProcessor` [concept](https://github.com/nikic/PHP-Parser/issues/165), my implementation add the name resolver as first visitor , then additional visitor (1 to n). And Run a pre-condtion parsing process to find conditional code.

So it's too complex for me. But I'm +1 if you can resolve name earlier

**Comment by llaville** [comment]
FYI, my "complex" implementation of PHP-Parser it resume on the parse() method at https://github.com/llaville/php-reflect/blob/3.0/src/Bartlett/Reflect.php#L113

**Comment by llaville** [comment]
@nikic Thanks for the fast solution implementation !  I'll check it tomorrow

**Comment by llaville** [comment]
I've just tested the new dev-master version, and it's works like a charm. Thanks a lot !

Before php-compatinfo 4.0.0-RC2, when you try to analyse such [snippet code](https://github.com/llaville/php-compat-info/blob/4.0/tests/fixtures/gh165.php) (remember the type hinting about Doctrine cache), we get this kind of output 

    Classes Analysis

        Class                       Matches REF  EXT min/Max PHP min/Max PHP all
      U Console_Table               1       user             4.0.0
        DateTime                    1       date 5.2.0       5.2.0
      U Doctrine\Common\Cache\Cache 1       user             5.3.0
        Foo\Bar                             user             5.3.0
        function __construct                user             4.0.0       5.3.0
        function foo                        user             5.3.0
      U Foo\Foo                     2       user             5.3.0
        PDO                         1       PDO  5.1.0       5.1.0
      U SebastianBergmann\Version   1       user             5.3.0
        Total [7]                                            5.3.0
        
This is a little wrong, because `Foo\Bar\__construct()` requires PHP min 5.3.0 due to type hinting.

And now with your fix, without changing a line of code on php-compatinfo, we can get 

    Classes Analysis

        Class                       Matches REF  EXT min/Max PHP min/Max PHP all
      U Console_Table               1       user             4.0.0
        DateTime                    1       date 5.2.0       5.2.0
      U Doctrine\Common\Cache\Cache 2       user             5.3.0
        Foo\Bar                             user             5.3.0
        function __construct                user             5.3.0
        function foo                        user             5.3.0
      U Foo\Foo                     2       user             5.3.0
        PDO                         1       PDO  5.1.0       5.1.0
      U SebastianBergmann\Version   1       user             5.3.0
        Total [7]                                            5.3.0

**Comment by llaville** [comment]
@nikic is it possible to have a new release 1.2.2 ?

**Comment by nikic** [comment]
Here goes the release: https://github.com/nikic/PHP-Parser/releases/tag/v1.2.2
