### ISSUE TITLE
Interface and multiple inheritance 

### ISSUE THREAD

**Issue by llaville** [nikic/PHP-Parser#189]
I don't think PHP is able (yet) to allow multiple inheritance on same object.

See https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Interface_.php#L31

I know that fixing that will introduce a BC break.
But user code need to know this difference with the class model https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Class_.php#L47 that allow (of course a single inheritance)

Catching either an array (empty or not) for `Node\Stmt\Interface_` and a Node\Name (or null) for `Node\Stmt\Class_`

**Comment by nikic** [comment]
Not sure I get what you mean - an interface can extend multiple other interfaces, while a class can extend only one other class, thus the different representation.

**Comment by llaville** [comment]
Sorry for disturbing. I'm pretty sure if was not possible.

**Comment by llaville** [comment]
My ambiguous position is because I don't see until now a code like that 

    interface PA
    interface PB
    interface M extends PA, PB
 
    class Foo implements M

But rather code like that 

    class Foo implements PA, PB

See full example and strange results not documented in PHP API Reflection 

```php
<?php

interface PA
{
    function fPA();
}

interface PB
{
    function fPB();
}

interface M extends PA, PB
{
    function fM();
}

class Foo implements M
{
    function fPA() { echo __FUNCTION__, PHP_EOL; }
    function fPB() { echo __FUNCTION__, PHP_EOL; }
    function fM()  { echo __FUNCTION__, PHP_EOL; }
}

class Bar extends Foo 
{
}

$foo = new Foo;
$foo->fPA();
$foo->fPB();
$foo->fM();

$rc  = new ReflectionClass('Bar');
$obj = $rc->getParentClass();
print_r ($obj);

$rc  = new ReflectionClass('PA');
$obj = $rc->getParentClass();
print_r ($obj);

$rc  = new ReflectionClass('M');
$obj = $rc->getParentClass();
print_r ($obj);
```

**Comment by sascha-tasche** [comment]
Yes, some thought that 'extends' means always 'parent class'.
But for interfaces, it means 'interface'.
