### ISSUE TITLE
Pretty print partial node

### ISSUE THREAD

**Issue by edsonmedina** [nikic/PHP-Parser#190]
Hi, 

Let's say I'm traversing the code looking for names of method calls. So from something like this:

    function whatever() 
    {
        $this->getFoo();
       
        // do some other stuff
       
        $x->doSomething();
    }

I expect to get a list with:

    $this->getFoo
    $x->doSomething

It's fairly simple to use the traverser, look for instances of PhpParser\Node\Expr\MethodCall, and then grab $node->var->name and $node-name. All good.

But, if we have instead something like:

    function whatever() 
    {
        $list[$y->item[5]]->getFoo();
       
        $x->$doSomething[1]();
    }

It becomes a nightmare to parse. A variety of different types can be set in $node->var, all with its own specific properties, and same for $name.

I know I could use the pretty printer to get the whole $node, but what if I want a list of arguments being passed into a method (and not the whole method pretty printed)?

Is there any way to pretty print just part of a $node's properties?

**Comment by nikic** [comment]
It's not possible to print only part of a node. To print just the method `$foo->bar` part of the method, I'd create a new temporary node `new Expr\PropertyFetch($methodCall->var, $methodCall->name)`. To print just the arguments, loop over the args array and print each `$arg->value` individually.

**Comment by edsonmedina** [comment]
That's actually a good idea. Thanks.
