### ISSUE TITLE
Scope chain

### ISSUE THREAD

**Issue by edsonmedina** [nikic/PHP-Parser#196]
Currently there's no way of knowing the scope of the current node (unless your Visitor is manually tracking it).

IMO it would be extremely handy to have a public property in NodeVisitorAbstract with a the scope chain.

So visitors could do something like:

    if ($node instanceof ClassMethod)
    {
        // we've got a method, now find its class name
        foreach ($this->scopeChain as $scope)
        {
            if ($scope instanceof Class_)
            {
                $className = $class->name;
            }
        }
        
        // ...
    }

This would be very easy to implement.

**Comment by nikic** [comment]
I don't think this belongs in `NodeVisitorAbstract` (which only job is to provide you empty method bodies). You can easily implement a separate visitor providing the context information that is necessary for your use case.

**Comment by edsonmedina** [comment]
I imagine you're describing something like this?

    $context = new ContextStack(); 
    
    // this visitor manages the stack
    $traverser->addVisitor (new ContextVisitor ($context)); 
    
    // this visitor consumes the stack
    $traverser->addVisitor (new SomeOtherVisitor ($context)); 

But nothing guarantees me the `ContextVisitor` will always be the first to run, right?

I usually make individual visitors keep track of all the relevant context they need, but this gets verbose quickly (lots of `instanceof` and state) and happens frequently.

It would be so much simpler if the context was provided by the parser (it already has the context in memory).

It could be an optional component if you think this would create unnecessary overhead.

**Comment by nikic** [comment]
Visitors are always run in the order they're registered. (I.e. they run concurrently, but for each node they are run in-order, which should be sufficient for managing context.)

**Comment by sekjun9878** [comment]
Please see https://github.com/nikic/PHP-Parser/pull/234

**Comment by edsonmedina** [comment]
Nikic's answer is satisfactory enough for me.

A visitor can track the scope and others can have a reference to it (or to a shared context object).

Closing this.
