### ISSUE TITLE
Make Method, Closure and Function FunctionLike

### ISSUE THREAD

**Issue by suralc** [nikic/PHP-Parser#198]
Method, closure and function definitions share certain aspects like parameters and return types. Would it make sense for them to have a common ancestor (`FunctionLike`) as it is done for `ClassLike` structures (Class, Interface, Trait)? 

A problem might arise from the fact that methods and functions inherit from Stmt and Closure from Expr. Maybe it's worth to consider an interface in V2.0 that guarantees the presence of methods to retrieve arguments and return type.

**Comment by nikic** [comment]
Agree that this would be nice, I've run into this myself a couple of times as well. As you already said, the reason why this wasn't done yet is the Stmt/Expr problem. Your suggestion of using an interface with getters sounds reasonable. The alternative would be making Stmt/Expr into interfaces, but that's probably not better.

**Comment by suralc** [comment]
@nikic I can open a pull request later today/tomorrow. Would the following interface suffice or did I miss anything obvious?

```php
interface FunctionLike {
    /**
     * @return bool
     */
    public function returnsByRef();
    /**
     * @return string
     */
    public function getName();
    /**
     * @return Node\Param[]
     */
    public function getParams();
    /**
     * @return null|string|Node\Name[]
     */
    public function getReturnType();
    /**
     * @return Node[]
     */
    public function getBody();
}
```

**Comment by nikic** [comment]
@suralc I'd drop the `getName()` method (as closures don't have one) and rename `getBody()` to `getStmts()` to mirror the property names 1-to-1. Might also want to extend from `Node` - so a typehint against `FunctionLike` also guarantees all the other usual node methods.

**Comment by suralc** [comment]
@nikic Please ping me if #203 requires further changes.
