### ISSUE TITLE
ClassName::class feature from PHP 5.5 throws error

### ISSUE THREAD

**Issue by Xlator** [nikic/PHP-Parser#200]
The [::class](http://us3.php.net/oop5.basic#language.oop5.basic.class.class) keyword that was implemented in PHP 5.5 appears to cause an `Unexpected token T_CLASS` error in PHP-Parser.

**Comment by ruudvanderweijde** [comment]
Are you running version 0.9.3 or lower?
PHP 5.5 is supported since 0.9.4

**Comment by Xlator** [comment]
Yeah, was my mistake. I was running 0.9.3 through vim-php/phpctags. Fixed it by deleting composer.lock. Sorry.
