### ISSUE TITLE
end of code comments are stripped out in the parser tree

### ISSUE THREAD

**Issue by pk-fr** [nikic/PHP-Parser#205]
code like this one:

    <?php
    /* comment is ok
    */
    // comment is ok
    
    $a = $b;
    
    /* what happens to this comment?
    */
    // to this one also?
    ?>

    $stmts  = $parser->parse(file_get_contents($filename));
    var_dump($stmts);

the last comments are not in the parsed tree structure.

btw, handling of end of lines is tricky ...
I use:  

     $parser->parse(trim(file_get_contents($filename)).PHP_EOL.PHP_EOL);
to have the best results when pretty printing.

**Comment by nikic** [comment]
This issue is basically the same as #205: Comments are always associated with the next node and if there is next node they are lost. I don't know how this can be solved at this point.
