### ISSUE TITLE
Multiple return types

### ISSUE THREAD

**Issue by natebrunette** [nikic/PHP-Parser#207]
ClassMethod::$returnType has `Node\Name[]` as a potential return.  Php 7 does not support multiple return types and should be changed to `Node\Name`.

**Comment by GrahamCampbell** [comment]
That's not a multiple return type. That's telling you it returns an array of name nodes...

**Comment by natebrunette** [comment]
Why would a method return type have multiple name nodes?

**Comment by GrahamCampbell** [comment]
Because it's an array...

**Comment by GrahamCampbell** [comment]
It returns an array.

**Comment by natebrunette** [comment]
My question is why is it an array?  An array on return type suggests multiple return types.  As it is, it's saying that this member variable can be multiple Name objects.  This doesn't make sense for return typing.

Look at the `Class_` member variables.  `Class_::$extends` is typed to `Node\Name` because a class can only extend one class.  `Class_::$implements` is typed to `Node\Name[]` because a class can implement many interfaces.

**Comment by GrahamCampbell** [comment]
> This doesn't make sense for return typing.

Yes it does. I can set a return type as `string|null` if I want. What's wrong with that?

**Comment by nikic** [comment]
Yeah, this is just a typo. Same issue exists in https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/Node/Stmt/Function_.php#L16, https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/Node/Expr/Closure.php#L19 and https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/Node/FunctionLike.php#L26.

**Comment by natebrunette** [comment]
@nikic Thank you.

**Comment by nikic** [comment]
@GrahamCampbell `string|null` is not a valid return type in PHP, at least not yet. Note that this is not referring to doc comments, but to actual return types.

**Comment by GrahamCampbell** [comment]
Oh, right. So you're meaning the actual thing returned at a given instant rather than all things that could be returned separately?

**Comment by MaxVandervelde** [comment]
@GrahamCampbell They're talking about the [declared return types] in PHP-7. Which don't allow multiple returns nor nulls. As opposed to the non-declared implicit ones in PHP-5.

[declared return types]: https://wiki.php.net/rfc/return_types

**Comment by nikic** [comment]
Fixed with https://github.com/nikic/PHP-Parser/commit/42e368e964e121d67d418708e2c12000a151aee6.
