### ISSUE TITLE
Using the generator with no namespace

### ISSUE THREAD

**Issue by mintbridge** [nikic/PHP-Parser#208]
Hi,

I'm using the generator to try and create a class that has no namespace but struggling, i would like:
```php
<?php

class MyClassName {
   //stuff
}
```
With the factory builder using 
```php
<?php
$factory = new PhpParser\BuilderFactory;
$node = $factory->namespace(null)
    ->addStmt($factory->use('Some\Other\Class'))
    ->addStmt($factory->class('MyClassName')
```
generates
```php
<?php
namespace {
    use Some\Other\Class;
    class MyClassName {
       //stuff
    }
}
```
I also tried ```''``` and ```' '``` instead of ```null```, the first threw an error, the second gave me
```php
<?php
namespace ;

use Some\Other\Class;
class MyClassName {
   //stuff
}
```

Any help would be appreciated

**Comment by nikic** [comment]
The namespace builder will always create a namespace. If you don't want to have a namespace you should simply not use the builder for it. For example:

```php
$stmts = [
    $factory->use('Some\Other\Class'),
    $factory->class('MyClassName'),
]
echo (new PhpParser\PrettyPrinter\Standard)->prettyPrintFile($stmts);
```

**Comment by mintbridge** [comment]
Thanks, i guess not many classes need no namespace anymore with PSR2 becoming popular

**Comment by tleb** [comment]
> Thanks, i guess not many classes need no namespace anymore with PSR2 becoming popular

It's rather because of [PSR-0](http://www.php-fig.org/psr/psr-0/) and [PSR-4](http://www.php-fig.org/psr/psr-4/). (Mainly PSR-4 though.)

@nikic This code didn't work for me. It was missing `->getNode()` for the `use()` and `class()` methods. Is it normal no exception are throwed when `getNode()` isn't called? I had a `CLI stopped working`, complete crash of the script.

BTW, amazing library!

**Comment by nikic** [comment]
@tleb Fixed the code in the comment and also fixed the infinite recursion issue when `getNode()` wasn't called there: https://github.com/nikic/PHP-Parser/commit/5ede167835fba5fe9624967654ad6eda48e3d14f
