### ISSUE TITLE
Trait properties

### ISSUE THREAD

**Issue by vandroids** [nikic/PHP-Parser#210]
I've tried to add property to a trait:
`$trait->addStmt( $factory->property( 'id' ) );`
which gave me an exception: Unexpected node of type "Stmt_Property"

After looking at Builder\Trait_.php I found that there is no support for properties in traits. 
Is this intended?

**Comment by nikic** [comment]
Thanks for the report, this is now fixed by https://github.com/nikic/PHP-Parser/commit/b862de1f5bdb1db0b9ce0aad97409ac5c78710c6. I forgot that traits can have properties as well.
