### ISSUE TITLE
Request: Start/end byte offset or line/col for AST nodes?

### ISSUE THREAD

**Issue by jesseschalken** [nikic/PHP-Parser#212]
As far as I can tell AST nodes only have a line number but no column number or byte offset. I would like to be able to find what range of bytes in the source file correspond to a node, either by start/end byte offset or start/end line/col pair.

Would this be possible?

Thanks

**Comment by nikic** [comment]
You can enable byte offsets in the lexer: https://github.com/nikic/PHP-Parser/blob/1.x/doc/component/Lexer.markdown#lexer-options

```php
// something like this
$lexer = new PhpParser\Lexer(array(
    'usedAttributes' => array(
        'comments', 'startLine', 'endLine', 'startFilePos', 'endFilePos'
    )
));
```

Here's some sample code for converting the file offset into a column number: https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/Error.php#L123

**Comment by jesseschalken** [comment]
Oh awesome, thank you @nikic!
