### ISSUE TITLE
How to print null?

### ISSUE THREAD

**Issue by Lewik** [nikic/PHP-Parser#213]
How to print

``` php
null
```

?

**Comment by Lewik** [comment]
```php
new ConstFetch(new Name('null'))
```

Is there simpler way?

**Comment by tleb** [comment]
I would recommend creating an Helper class to create all those basic things (`null`, `true`, `false`, etc).

**Comment by nikic** [comment]
Nope, there is currently no simpler way if you're constructing directly. If you're using builders things like default values and initializers will automatically convert null values etc to constant fetches, but that's limited in scope. The implementation might serve as inspiration though: https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/BuilderAbstract.php#L64

**Comment by nikic** [comment]
The BuilderFactory now has a val() method which creates the AST for literal values, including null/false/true. So a `null` can be created using `$f->val(null)`.
