### ISSUE TITLE
Tag 2.0.0 final?

### ISSUE THREAD

**Issue by nick-jones** [nikic/PHP-Parser#214]
Anything still pending for this?

**Comment by nikic** [comment]
Nothing particular (apart from one last-minute PHP 7 grammar change). I was hoping to get some more feedback, but there doesn't seem to be any...

**Comment by nikic** [comment]
Just tagged a beta: https://github.com/nikic/PHP-Parser/releases/tag/v2.0.0beta1

**Comment by GrahamCampbell** [comment]
Nice. Do you have a stable release date in mind? I was hoping we could get this into Laravel 5.2, scheduled for the start of December.

**Comment by GrahamCampbell** [comment]
This can be closed now. :)
