### ISSUE TITLE
Inline comments cause parsing problems.

### ISSUE THREAD

**Issue by litowitz-2** [nikic/PHP-Parser#215]
It appears that comments in the middle of method calls cause incomplete/incorrect parsing.
Consider the following php code.

```php
	$arr = array("a",
		/* no problem */
	"b");
```
results in `$arr = array('a', 'b');`

```php
	$arb = array("a",
		// Parse Error: Syntax error, unexpected ';', expecting ')' on line 1 
	"b");
```

```php
	$this->method()
		// comment
		->methodb();	
```
results in `$this->method();`

```php
	print TClass::StaticMethod(array("a",
		// Parse Error: Syntax error, unexpected ';', expecting ')' on line 1 
		"b", "c"));
```

```php
	print "this is a ".
		// Parse Error: Syntax error, unexpected ';', expecting ')' on line 1	
		"failcast\n";
```

```php
	print "but this is ".
		/* ok */
		"to do\n";
```

**Comment by nikic** [comment]
I wasn't able to reproduce this issue (put your second example in a file and ran `bin/php-parse.php` over it). Could you provide a sample code for how you're calling the parser?

My initial suspicion is that your single line comments are not followed by a correct (LF or CRLF) newline character.

**Comment by litowitz-2** [comment]
Here is the [file](https://gist.github.com/litowitz-2/13fa93ceaa4276f85d06).

**Comment by litowitz-2** [comment]
I figured it out, it was setup to strip line endings before parsing. This resulted in the problem you had suspected.
