### ISSUE TITLE
Why are visitors run concurrently?

### ISSUE THREAD

**Issue by Blackhol3** [nikic/PHP-Parser#217]
Currently, visitors are run in the order they are registered, but concurrently. Is there a reason for such a behaviour?

Basically, I want to be able to delete a node in my `NodeVisitor` even if it isn't the node currently visited in `leaveNode($currentNode)`, by calling something like `$this->delete($someOtherNode)` and taking the appropriate measures in this method. But if the visitors are run concurrently, the whole task is obviously impossible.

Can we contemplate to add an argument to the constructor of the `NodeTraverser`? Or maybe create two traversers, `NodeTraverserConcurrent` and `NodeTraverserSequential`, inheriting from another `NodeTraverserAbstract`?

**Comment by nikic** [comment]
There's no specific reason for the choice of concurrent over sequential. It's faster than the alternative and handy for certain usages (e.g. can have a state collecting visitor used by other visitors), but it could have gone either way.

However, in case you do need sequential runs, you can simply create another NodeTraverser and traverse again using it. Something like this might be useful to have multiple sequential passes each consisting of concurrent visitors:

```php
function runPasses($ast, array $passes) {
    foreach ($passes as $visitors) {
        $traverser = new NodeTraverser;
        foreach ($visitors as $visitor) {
            $traverser->addVisitor($visitor);
        }
        $ast = $traverser->traverse($ast);
    }
}

runPasses($ast, [
    [$visitor1, $visitor2],
    [$visitor3],
    [$visitor4, $visistor5],
]);
```

As such a function is easy to write and in my experience not commonly needed (what you usually need are sequential passes over *all* files, rather over a single AST), I don't think adding extra APIs for this is necessary.
