### ISSUE TITLE
Use PSR2 for code style

### ISSUE THREAD

**Issue by ovr** [nikic/PHP-Parser#224]
https://github.com/nikic/PHP-Parser/tree/master/lib/PhpParser/Node/Stmt

```php
Break_ -> BreakSt
```

I am going to setup travis ci to check it, okey?

**Comment by nikic** [comment]
This rename should not be necessary, as underscores have no meaning under PSR-4.

As to using PSR-2 -- depends on how big the diff to the current codebase would be. If it isn't too large, lets do it.

**Comment by felixfbecker** [comment]
I would love to see camel case used

**Comment by nikic** [comment]
I won't be changing class names to remove the underscore.
