### ISSUE TITLE
Use ScrutinizerCI

### ISSUE THREAD

**Issue by ovr** [nikic/PHP-Parser#225]
Can you setup https://scrutinizer-ci.com/?
After it I will send PR with configuration for check? okey?

**Comment by dupuchba** [comment]
:+1: for this one

**Comment by nikic** [comment]
The project is on scrutinizer under https://scrutinizer-ci.com/g/nikic/PHP-Parser but I couldn't figure out how to add a GH service hook.

**Comment by GrahamCampbell** [comment]
Scrutinizer should add it for you. Maybe disable and re-enable the project on scrutinizer, or contact support to get it added again.

**Comment by GrahamCampbell** [comment]
Shame they don't support repairing the webhook. The service I work on supports that.

**Comment by ovr** [comment]
@nikic 
Did you try to remove and add it again?

**Comment by GrahamCampbell** [comment]
> Did you try to remove and add it again?

I literally just said that:

> Maybe disable and re-enable the project on scrutinizer

**Comment by ovr** [comment]
@GrahamCampbell 
I didnt read you messages

> Shame they don't support repairing the webhook. The service I work on supports that.

How is it related to this issue?

**Comment by GrahamCampbell** [comment]
I was just saying that it's possible, and easy to implement, since I've implemented it before. ;)

**Comment by nikic** [comment]
I've removed/added the project and now the hook is there, so should be possible to test configs now.

**Comment by ovr** [comment]
@nikic Super, I will send PR in few hours

**Comment by nikic** [comment]
I've decided to not use Scrutinizer. It spews up a lot of notices but only very little is of interest to me (out of a couple dozen messages I looked at two were genuinely useful). I've set up coveralls for the test coverage, as that was the most interesting part of Scrutinizer.
