### ISSUE TITLE
PrettyPrinter messes with Newlines inside EOF strings

### ISSUE THREAD

**Issue by digitalkaoz** [nikic/PHP-Parser#227]
imagine this test class:

```php
<?php
class Test
{
    public function test()
    {
        $foo = <<<EOS
OK

EOS
;
    }
}
```

after parsing and pretty printing i get this result back:

```php
<?php

class Test
{
    public function test()
    {
        $foo = 'OK';
    }
}
```

so the necessary blank line inside the string is gone...(my contents are a bit more complex so i like to use the EOF feature). if i write it as normale strings it works btw. and if i add multiple blank lines at the end of the string there is always one missing, so i guess its an easy bugfix?

here the full test script:

```php
<?php
//... composer here

$code = '<?php
class Test
{
    public function test()
    {
        $foo = <<<EOS
OK

EOS
;
    }
}';

$parser = new \PhpParser\Parser(new \PhpParser\Lexer\Emulative());
$traverser     = new PhpParser\NodeTraverser();
$prettyPrinter = new PhpParser\PrettyPrinter\Standard();

$stms = $parser->parse($code);

$result = $prettyPrinter->prettyPrintFile($traverser->traverse($stms));

die($result);

```

**Comment by nikic** [comment]
Verified for Unix-style newlines. It looks like I fell for the PCRE `$` newline trap...

**Comment by nikic** [comment]
Fixed with https://github.com/nikic/PHP-Parser/commit/950ada4cbaed40cab7ff90a45aac5682298e22ea. Thanks for catching this!

**Comment by nikic** [comment]
Also tagged v1.4.1 for this change: https://github.com/nikic/PHP-Parser/releases/tag/v1.4.1

**Comment by digitalkaoz** [comment]
great thanks :)
