### ISSUE TITLE
Possiblity to use certain Language Level in Printing PHP-Code

### ISSUE THREAD

**Issue by digitalkaoz** [nikic/PHP-Parser#228]
is this possible?

so i can tell the PrettyPrinter please use `[]` instead of `array()` while dumping Nodes into a String?
or use `Foo::class` instead of `'\Namespace\Foo'` ?

**Comment by nikic** [comment]
We could add an option for short array syntax in particular, but something like `\Namespace\Foo` needs to be rewritten in the AST. It's not just a formatting change and the code is not semantically equivalent.

**Comment by nikic** [comment]
An option for the short array syntax is now available: https://github.com/nikic/PHP-Parser/commit/39a039fa4257d3b9209de36cc54f5d3f5d6253f5

```php
$pp = new PrettyPrinter\Standard(['shortArraySyntax' => true]);
```

**Comment by digitalkaoz** [comment]
thanks :) im thinking about that a bit further...
i think ill try to write a pretty printer which utilizes a `php-cs-fixer` config file then the formatting will depends on the users preference
