### ISSUE TITLE
[Question] Is it possible to parse invalid php code (partially written)?

### ISSUE THREAD

**Issue by docteurklein** [nikic/PHP-Parser#231]
I see that `token_get_all` tokenizes correctly an invalid content.
Can I configure the parser's `unexpectedTokenRule` so that it accepts anything?

My goal is to parse partial, potentially invalid content to provide autocompletion options for php code.

**Comment by nikic** [comment]
There is experimental support for error recovery: https://github.com/nikic/PHP-Parser/blob/master/doc/component/Error.markdown#error-recovery

It's pretty limited though, probably not suitable for autocomplete. It could be extended further though.
