### ISSUE TITLE
stmts property is not empty array but NULL for interface methods

### ISSUE THREAD

**Issue by HoffmannP** [nikic/PHP-Parser#235]
In interface methods the `stmts`-property is not `array()` as you would assume but `null`.
While this might sound the right thing to do it gives you problems when trying to traverse the ast.
My suggestion is to either return `array()` or - even better - to remove the stmts-property as there are not statements in an interface class method.
Either way works, just the current requires an extra check.

**Comment by nikic** [comment]
The idea here is to distinguish between `;` (null) and `{}` (empty array). It applies not only to interface methods but also to abstract methods. This e.g. allows the pretty printer to emit valid code without managing state about whether it's currently in an interface or not.

We could change this to use an empty array and have a flag to signify that it's a body-less method, maybe.

**Comment by lisachenko** [comment]
+1 for adding `emptyBody` attribute  (or something like this) to the `ClassMethod` and make `stmts` always an array.

**Comment by jesseschalken** [comment]
A method can have no body (abstract/interface method, `;`), an empty body (`{}`), or a non-empty body (`{...}`). `Stmt[]|null` fits this precisely.

If you introduce a distinct `noBody` property then what would it mean if `noBody` is `true` but `stmts` is not `[]`? Such a configuration would be invalid, but allowed according to the types of the properties.

**Comment by sascha-tasche** [comment]
Were is the difference between the checking if Stmt is null and checking if noBody is true/false?!

**Comment by nikic** [comment]
I'll be leaving this as-is -- I think it makes pretty little difference whether we use `null` to signal no body or have a separate property for it, and changing it at this point will necessarily break downstream code.
