### ISSUE TITLE
Get original string for variable interpolated strings

### ISSUE THREAD

**Issue by bpicolo** [nikic/PHP-Parser#237]
I've seen https://github.com/nikic/PHP-Parser/issues/26 , but it doesn't seem to apply for strings that had interpolated variables.

Say I have:
````
$foo = "$bar\n
";
````

This gets parsed and the string portion of it (literal newline + newline) get's shoved into an array for the full encapsed variable (It doesn't carry along any attributes). It doesn't actually become a String_ node. (In this case it counts as T_ENCAPSED_AND_WHITESPACE during lexing).
Here's vardumped:
```
  ["parts"]=>
  array(2) {
    [0]=>
    object(PhpParser\Node\Expr\Variable)#13 (2) {
      ["name"]=>
      string(3) "bar"
      ["attributes":protected]=>
      array(3) {
        ["startLine"]=>
        int(3)
        ["foo"]=>
        string(4) "$bar"
        ["endLine"]=>
        int(3)
      }
    }
    [1]=>
    string(2) "

"
```

Any idea how I can get the original string for this? I've been working through the source but haven't found a good strategy yet. Current attempted approach is figuring out how the parser is built and preventing that conversion in the grammar =(

**Comment by nikic** [comment]
Hm, this looks tricky. I can't think of any way to do this that will robustly work.

As 2.0 hasn't been released yet, it would be possible to introduce a proper node for string parts of encapsed strings. Could either reuse Scalar_String or have something separate (as it's not really a full string).

**Comment by bpicolo** [comment]
@nikic  So I'd have to change the parser yet, yeah? Currently stuck here:
```
encaps_list:
      encaps_list encaps_var                                { push($1, $2); }
    | encaps_list T_ENCAPSED_AND_WHITESPACE                 { $2 = Scalar\String_[$2]; push($1, $2); }
    | encaps_var                                            { init($1); }
    | T_ENCAPSED_AND_WHITESPACE encaps_var                  { init($1, $2); }
;
```

Got the encapsed after list to work properly, haven't gotten the final case to work yet.
```
T_ENCAPSED_AND_WHITESPACE encaps_var                  { init($1, $2); }
```


^^ Haven't successfully modified the grammar such that $1 becomes a scalar string node yet. I'm not suuuuper familiar with writing formal grammars and there's some trickery in the custom functions hah. Any idea there?

**Comment by nikic** [comment]
If you want to keep using simple strings, but don't perform parsing of strings you can simply drop all the `parseEncapsed` calls from the grammar.

If you want to convert to String nodes, I'd do something like this:

```
encaps_str:
      T_ENCAPSED_AND_WHITESPACE { $$ = Scalar\String_[$1]; }
;

encaps_list:
      encaps_list encaps_var                { push($1, $2); }
    | encaps_list encaps_str                { push($1, $2); }
    | encaps_var                            { init($1); }
    | encaps_str encaps_var                 { init($1, $2); }
;
```

Another way that might work is to enable file positions in the lexer and then determining the original string content based on the file offsets of the adjacent interpolated vars and the file offsets of the whole strings. That should work without changing the parser.

**Comment by bpicolo** [comment]
I thought about the file positions in the lexer part, but that doesn't work because the strings weren't becoming a node of any sort, and so didn't have attributes;

**Comment by nikic** [comment]
@bpicolo Yeah, I know. Which is why I'm suggesting to use the positions of the adjacent real nodes.  So something similar to this (not tested):

```php
// Get original string of $encapsed->parts[$index]
function getOriginalString($code, $encapsed, $index) {
    if ($index > 0) {
        $startOffset = $encapsed->parts[$index - 1]->getAttribute('endFileOffset');
    } else {
        // Here I'm assuming a "foo" style string. Heredoc and `` would need extra handling
        $startOffset = $encapsed->getAttribute('startOffset') + 1;
    }
    if ($index < count($encapsed)->parts) - 1) {
        $endOffset = $encapsed->parts[$index + 1]->getAttribute('startFileOffset');
    } else {
        // Again assuming "foo" string
        $endOffset = $encapsed->getAttribute('endOffset') - 1;
    }
    return substr($code, $startOffset, $endOffset - $startOffset);
}
```

**Comment by bpicolo** [comment]
@nikic  ahhh, gotcha.

**Comment by nikic** [comment]
I've introduced a `Scalar\EncapsedStringPart` node to represent string parts of encapsed strings and backtick expressions: https://github.com/nikic/PHP-Parser/commit/a9074c7444ebe4a907d331c5c0b7c2ba77a6fef2

Now it should be possible to handle this using the "usual" method :)
