### ISSUE TITLE
Get parent nodes

### ISSUE THREAD

**Issue by sourcerer-mike** [nikic/PHP-Parser#238]
For example ClassMethods should have at least "getParent()" which returns the class
or "getClass()".
For comparison and code analysis I like to walk around in the tree:
https://github.com/sourcerer-mike/phpsemver/tree/develop/lib/PHPSemVer/Assertions

**Comment by sekjun9878** [comment]
Wouldn't that cause a recursion? e.g. The class would also have to have the class methods, which in turn should have their parent class, and so on and so on.

**Comment by nikic** [comment]
@sekjun9878 It would create a cyclic graph, which by itself is not a problem (it will only degrade performance due to increased GC pressure).

If you need parent references, it should be relatively easy to construct them using a visitor. Something along these lines:

```php
class ParentConnector extends NodeVisitorAbstract {
    private $stack;
    public function beginTraverse(array $nodes) {
        $this->stack = [];
    }
    public function enterNode(Node $node) {
        if (!empty($this->stack)) {
            $node->setAttribute('parent', $this->stack[count($this->stack)-1]);
        }
        $this->stack[] = $node;
    }
    public function leaveNode(Node $node) {
        array_pop($this->stack);
    }
}
```

**Comment by sourcerer-mike** [comment]
Works like a charm! Thank you @nikic !
I tried it in my project and am now ready for a more generic approach.

This issues seems closed to me, as it can be solved by using the visitor.

**Comment by TomasVotruba** [comment]
These is also FAQ post, where this is explained:
https://github.com/nikic/PHP-Parser/blob/master/doc/5_FAQ.markdown#how-can-the-parent-of-a-node-be-obtained
