### ISSUE TITLE
Assign nodes should have Variable type hints

### ISSUE THREAD

**Issue by sekjun9878** [nikic/PHP-Parser#239]
Hello,

In https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Expr/Assign.php#L9 and https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Expr/AssignRef.php#L16, shouldn't they have Variable type hints instead of Expr? Is there any case where an assignment would happen on a non-variable?

**Comment by nikic** [comment]
I think these are the possibilities:

```
$a = $b; // Assignment to Variable
$a->b = $c; // Assignment to PropFetch
$a['b'] = $c; // Assignment to DimFetch
$a::$b = $c; // Assignment to StaticPropFetch
```

**Comment by sekjun9878** [comment]
Thanks!

**Comment by sekjun9878** [comment]
Just wondering, is it possible to have union type hints instead of the generic Expr type hint then?

**Comment by jesseschalken** [comment]
Don't forget `list(...) = ...;` :stuck_out_tongue:

**Comment by nikic** [comment]
@sekjun9878 I'll be leaving the type hint here as is, listing all the possibilities makes it overly specific. The parser can actually produce more than just these (and the one @jesseschalken mentioned), e.g. something like `func() = $x` is okay as far as the parser is concerned (even though it's not valid PHP). Doesn't make a lot of sense to me to specify a 10-adic union type here.
