### ISSUE TITLE
prettyPrinter does not play well with empty php files.

### ISSUE THREAD

**Issue by pk-fr** [nikic/PHP-Parser#240]
Hi Nikita,

someone using my php obfuscator reported an issue when obfuscating an empty php file
containing only 
<?php

I made a workaround within yakpro-po, but perhaps are you interested to correct it within prettyPrinter...

The parser itself does not have any problem parsing this kind of file, however, prettyPrinter generates errors.

(still using 1.x branch, not tested with 2.x)

Best Regards,
Pascal

PHP Fatal error:  Call to a member function getAttribute() on a non-object in .../yakpro-po/PHP-Parser-1.4/lib/PhpParser/PrettyPrinterAbstract.php on line 155

Fatal error: Call to a member function getAttribute() on a non-object in  .../yakpro-po/PHP-Parser-1.4/lib/PhpParser/PrettyPrinterAbstract.php on line 155

**Comment by nikic** [comment]
I can't reproduce this. Using the following code:

```php
$parser = new PhpParser\Parser(new PhpParser\Lexer);
$stmts = $parser->parse('<?php ');
$prettyPrinter = new PhpParser\PrettyPrinter\Standard();
var_dump($prettyPrinter->prettyPrint($stmts));
var_dump($prettyPrinter->prettyPrintFile($stmts));
```

I get:

```
string(0) ""
string(7) "<?php

"
```

If the string is just `'<?php'` I get a parse error -- but that's in accordance with how PHP behaves.

**Comment by pk-fr** [comment]
sorry ... it was a bug in the obfuscator .....
the faulty code was:
## 
     $last_inst  = array_pop($stmts); 
     $stmts      = shuffle_statements($stmts); 
     $stmts[]    = $last_inst; 

as stmts was array(0) {} ..... I added a null stmt :o(   ....  

Sorry to have disturbed you for nothing... 
I should have checked twice ....
