### ISSUE TITLE
Pass current indent through pretty printer methods instead of using noIndentToken

### ISSUE THREAD

**Issue by jesseschalken** [nikic/PHP-Parser#242]
I noticed the way the pretty printer deals with indenting is by searching and replacing `"\n"` with `"\n    "` using a special random marker `$this->noIndentToken` to avoid changing the contents of multi-line string literals.

In the past when I've needed to pretty print something I've passed an `$nl` variable containing the newline string to use through the pretty printer methods. `$nl` starts as `"\n"`, and when something needs to be indented, the pretty printer method for that is invoked with `"$nl    "` to add extra indentation. String literals use a raw `"\n"` and ignore the `$nl` variable. [Example](https://github.com/jesseschalken/fail-whale/blob/master/src/FailWhale/PrettyPrinter.php#L116)

This helps with performance as the pretty printer then only involves straight string concatenation without any searching/replacing or regular expressions. It also avoids the tiny chance that `$this->noIndentToken` occurs in the code.

Would @nikic favour such a change?

**Comment by nikic** [comment]
I'm not a big fan of passing `$nl` through 300 methods. The other way of getting rid of the noIndentToken is to assemble the code left-to-right rather than inside-out. I.e. have a property holding the current code to which is appended and another property holding the current indentation. I don't know if that's better than what is currently done or not.

**Comment by jesseschalken** [comment]
You can avoid adding the extra parameter to everything by having it as a property. Then you can either do:
```php
private function indented() {
    $self = clone $this;
    $self->nl .= '    ';
    return $self;
}

protected function pThing(Thing $node) {
    // ...
    $s = $this->indented()->p($node->foo);
    // ...
}
```

Or, if the overhead of the `clone` is high, set `$nl` temporarily and set it back again:

```php
private function indent() {
    $nl = $this->nl;
    $this->nl .= '    ';
    return $nl;
}

protected function pThing(Thing $node) {
    // ...
    
    $nl = $this->indent();
    $s  = $this->p($node->foo);
    $this->nl = $nl;
    // ...
}
```

I suspect either method would be more performant than the repeated searching and replacing.

**Comment by nikic** [comment]
The `$this->nl` variant is now implemented in master with https://github.com/nikic/PHP-Parser/commit/61e624bc9d5eee1ba7a5a8e027a3d952297b20fc.
