### ISSUE TITLE
Partial parsing as an alternative to error handling?

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#245]
Hello

This is more of a question, I'm not sure if this is possible with the current implementation of php-parser. Error handling is not an easy problem to solve when parsing, and even if it can ignore a line entirely, tools looking to parse PHP code to provide things such as autocompletion will run into problems:
```php
array_walk(
```

In this example, I would like information about the fact that the `array_walk` function is being invoked, but even if php-parser manages to correct itself and skip this line, no node will be generated for this statement and there is still no useful information for said tool. Would it instead be an option to somehow "stop the parser early"? This would mean that I would litterally just provide part of a PHP file and get all nodes up to there with as much information as is possible, for example:

```php
namespace Foo;

class Bar
{
   public function method()
   {
        array_walk(
```

In this example, I would somehow put php-parser in a "partial parsing mode", only providing this string of source code. The parser could then supply me with nodes up until that point in the file (information such as endLine information will, of course, not be retrievable). If it is important that the file contains correct syntax, the parser could even automatically insert the required code for example:

```php
namespace Foo;

class Bar
{
   public function method()
   {
        array_walk( // Detected that two scopes were opened and one parenthesis:
        );}} // Automatically close scopes and function call to get valid syntax.
```

Would such a thing be possible?

Thanks in advance

**Comment by nikic** [comment]
For reference, here's the docs for the existing error recovery support: https://github.com/nikic/PHP-Parser/blob/master/doc/component/Error.markdown#error-recovery

As you already said yourself, creating a parser with error recovery sufficiently good for use in IDEs is hard. I'm generally open to improving the error recovery support (either by placing more `error` tokens or by using a smarter recovery algorithm, e.g. something that tries to insert expected but missing tokens), but I won't be working on this myself. It's not a primary target for this library.

I don't think there's any easy way of creating a "partial parsing mode" -- the intermediary state of the parser is a stack of AST nodes without any clear relation to each other, there is no obvious way to assemble them into a coherent result.

**Comment by nikic** [comment]
Per the previous comment, I don't think anything is going to happen in this direction, so closing this issue.

**Comment by Gert-dev** [comment]
My apologies, I forgot to reply. Closing this ticket is fine, I understand your stance on the subject. Thanks for taking the time to review this.
