### ISSUE TITLE
Cannot use 'PhpParser\Node\Scalar\String' as class name

### ISSUE THREAD

**Issue by jedahan** [nikic/PHP-Parser#248]
When trying to run psysh in a test ( psysh.org ), I get this error: 

`Fatal error: Cannot use 'PhpParser\Node\Scalar\String' as class name as it is reserved in /usr/share/composer/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 86`
```console
❯ pake unit_nosetup SomeTest.php
>> exec         ENVIRONMENT=testing TMP_L…est.php || echo 'Test Failure'
#!/usr/bin/env php
PHPUnit 5.0.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.3 with Xdebug 2.4.0RC4
Configuration: /home/jdehan/dev/project/tests/phpunit/phpunit.xml


Starting test 'Test_HelperTest::testValid'.


Fatal error: Cannot use 'PhpParser\Node\Scalar\String' as class name as it is reserved in /usr/share/composer/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 86
Test Failure
```

Any suggestions on how to track this down better?

**Comment by nikic** [comment]
You're probably using a very old version of psysh. Can you try updating it?

**Comment by jedahan** [comment]
ok weird, installing it locally didn't work, but globally did. Looks like my dev environment is all sorts of funky. Thanks for the quick reply!
