### ISSUE TITLE
FQCN nodes are not returned as FQCN strings

### ISSUE THREAD

**Issue by jaytaph** [nikic/PHP-Parser#249]
Consider the following code:

    <?php

    include "./vendor/autoload.php";

    use PhpParser\Node\Name;
    use PhpParser\Node\Name\FullyQualified;

    $name = new Name("foo\\bar");
    var_dump($name->isUnqualified());
    var_dump($name->isQualified());
    var_dump($name->isFullyQualified());
    var_dump($name->isRelative());
    var_dump((string)$name);

    $name = new FullyQualified("foo\\bar");
    var_dump($name->isUnqualified());
    var_dump($name->isQualified());
    var_dump($name->isFullyQualified());
    var_dump($name->isRelative());
    var_dump((string)$name);

The output is:

    bool(true)
    bool(false)
    bool(false)
    bool(false)
    string(7) "foo\bar"
    bool(false)
    bool(false)
    bool(true)
    bool(false)
    string(7) "foo\bar"

Both nodes return the correct values `isUnqualified()` and `isFullyQualified()`, but the string version both result in a (un)qualified classname, and not a FQCN. Expected result would be '\foo\bar` on the second node.

I'm wondering if this is a bug or if this is by design. 

It's trivial to check for Name or FQCN class types on each node), but i'd reckon since we have a FQCN node, it should output FQCN. Adding a `toString()` to the FQCN node would be fairly trivial to fix this.

**Comment by nikic** [comment]
It's by design. The output of toString() is not intended to be used in generated code (the pretty printer will produce the correct results for that purpose), but rather for things like checking it against specific classes / maintaining symbol tables etc., in which case the canonical name (which does not have a \ prefix) is typically more useful.
