### ISSUE TITLE
Differentiate between bracketed and nonbracketed declare statements

### ISSUE THREAD

**Issue by jaytaph** [nikic/PHP-Parser#250]
Take the following code:

  declare (ticks = 2) { }
  declare (ticks = 1);
  register_tick_function(function(){ print "TICK";});
  print "hello";
  print "world";

Both declare statements will generate a `declare_` node with 0 statements. However, when pretty-printing, it will be outputted like this:

    declare (ticks=2) { };
    declare (ticks=1) { };

While the first is correct, the second is not. It seems that this does not matter in php5 (it seems that ticks are functional even for statements below the declare scope), but on php7 it (correctly) does not take the ticks into account.

The actual code outputted by the prettyprinter will be:

     declare (ticks = 2) {
     } 
    declare (ticks = 1) {
    }
    register_tick_function(function () {
      print 'TICK';
    }); 
    print 'hello';
    print 'world';

This affects php7, as the tick handler will not function (this is actually expected behaviour).

I would suggest to see if we can somehow store inside a declare node the difference between a `declare` with and without brackets. This way, any printers can setup their own brackets properly.

**Comment by jaytaph** [comment]
I see this is already fixed in 719ca71d4ac80e1985dcd91dd8ec5a47db58ad80

**Comment by nikic** [comment]
I should probably do a release for this.
