### ISSUE TITLE
Comments are assigned multiple times

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#253]
As reported in #36, a code snippet like

```
/* this is a common multiline comment */
$a * $b == 1 + 2;
```

will associate the comment with all of the `Equals` node, the `Mul` node and the `Variable` node for `$a`, basically all nodes that share the same starting token. The comment should only be associated with the outermost node.

**Comment by jhodgdon-drp** [comment]
Another related issue is #469 I think
