### ISSUE TITLE
Node class for finally keyword?

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#254]
Hello

I noticed that there seems to be no class for `finally` nodes, you can only fetch their statements using `finallyStmts` from the accompanying `TryCatch` node. This seems rather inconsistent as the `else` clause in an if-statement also has its own node. Is there perhaps a specific reason it was omitted?

Thanks in advance

**Comment by nikic** [comment]
I don't think there was a specific reason why it was omitted. Do you need a proper node for something in particular, or is this only a consistency concern?

**Comment by Gert-dev** [comment]
Thanks for your response. My reason is perhaps a bit of a strange one: I'm trying to differentiate between the ranges of the different parts of a try-catch-finally block.

For example, (If I recall correctly,) some nodes, such as case nodes, do not actually provide a contiguous region with their positions, for example:

```php
switch (true) {
    case a:
        some_statement();
        // A comment.

    case b:
        some_other_statement();
}
```

Here the `endFilePos` of the `case a` node will not run exactly up to the `startFilePos` of the `case b` node. This is not unexpected behavior, so I've found a workaround that involves using the `startFilePos` of the next case node instead. Sadly, it can't work in the same way for the try-catch-finally block as the finally statement isn't an actual node, so I have to resort to the first statement inside it (which isn't actually correct).

That and consistency is, of course, always nice ;-).

**Comment by nikic** [comment]
Thanks the explanation. I think adding an explicit `Finally_` node would be good, but this is running into the usual problem that changing the AST format will break backwards compatibility, so we can't really do it until the next major version (and it doesn't look like there will be need for one soon).

For your particular case, maybe just scanning backwards for the `finally` token from the startFilePos will be "good enough" for now?

**Comment by Gert-dev** [comment]
Thanks for the suggestion, it currently doesn't majorly impact anything so the first statement in the finally block is probably not that bad. I just thought I'd let you know so I can fix it at some point in the distant future. Feel free to close this or leave it open, whichever suits you best ;-).

**Comment by nikic** [comment]
Implemented via https://github.com/nikic/PHP-Parser/commit/5f97b125762c34ffd3478a6dbcf635cf347a3809 :)
