### ISSUE TITLE
Make all Nodes JsonSerializable

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#257]
It would be nice if a Node could be serialized to JSON. It should be enough to implement JsonSerializable in the base class like this:
```php
public function jsonSerialize()
{
  $properties = get_object_vars($this);
  $properties['nodeType'] = $this->getType();
  return $properties;
}
```
What do you think? PR welcome?

**Comment by nikic** [comment]
This definitely sounds like a good idea. Two things to consider:

 * There is some existing serialization infrastructure, which is currently only used for XML. JSON serialization could be implemented there, which would have the advantage of also supporting unserialization. However `JsonSerializable` is likely more convenient to use.
 * There are a number of things that JSON, unfortunately, does not support. In particular this includes non-UTF8 strings, as well as floating point Inf. Both of these can be part of the syntax tree during a normal parse. Should there be some attempt to support these (how?) or do we just say that this is "best effort"?

**Comment by nikic** [comment]
JsonSerializable on NodeAbstract and Comment implemented in https://github.com/nikic/PHP-Parser/commit/7dae6c7a6bde4a1447cffd7f3d0833e3a0c24ce8 (sample output in tests).

Other issues can be resolved separately should they prove to be a problem.
