### ISSUE TITLE
Support PHP 7.1

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#260]
Tracking bug for PHP 7.1 support.

* [x] Void return type: https://wiki.php.net/rfc/void_return_type (https://github.com/nikic/PHP-Parser/commit/5044fce1ff701ee078b8e82309e344a4581762a1)
* [x] Class constant visibility: https://wiki.php.net/rfc/class_const_visibility (https://github.com/nikic/PHP-Parser/commit/5ea2a76d8070db1ed33e88322608e51290601931)
* [x] Keys in list(): https://wiki.php.net/rfc/list_keys (https://github.com/nikic/PHP-Parser/commit/574665b45b646e3fab590507efd21335ea0817a6)
* [x] Multi catch: https://wiki.php.net/rfc/multiple-catch (https://github.com/nikic/PHP-Parser/commit/537b59d4d1e2d45fd844e0b11734168ed5363fb7)
* [x] Destructuring using `[]`: https://wiki.php.net/rfc/short_list_syntax (https://github.com/nikic/PHP-Parser/commit/437890d3862bca7162fe6152dd64030952245714)
* [x] Nullable types: https://wiki.php.net/rfc/nullable_types (https://github.com/nikic/PHP-Parser/commit/1edf72c0403c451ba9053d2b0ec7c624e16a7645)
* [x] Iterable type: https://wiki.php.net/rfc/iterable (https://github.com/nikic/PHP-Parser/commit/5044fce1ff701ee078b8e82309e344a4581762a1)
* [x] Octal string overflow: https://wiki.php.net/rfc/octal.overload-checking (no action: warning ignored)

Unclear yet whether this will require a new major version of PHP-Parser. The changes until now *could* be shoved into the existing structures, but it wouldn't necessarily be advisable.

**Comment by asgrim** [comment]
FWIW, at least using Better Reflection it seems `void` return type works without any changes - Roave/BetterReflection#209

**Comment by nikic** [comment]
@asgrim It's supported as a class `Name`, but it should now probably be represented as string `'void'` instead (like all the scalar types etc)

**Comment by asgrim** [comment]
Ah yes, makes sense - I think at Better Reflection's level, that subtlety is lost / ignored - we parse the string and phpDocumentor/TypeResolver turns it into a `phpDocumentor\Reflection\Types\Void` anyway.

**Comment by nikic** [comment]
Possible actions:

 * void: Only needs addition to https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/ParserAbstract.php#L484. Mild BC break.
 * iterable: Same.
 * Class constant visibility: Extra property on Stmt\ClassConst. No BC break.
 * [] destructuring: Allow null items in array item lists, like it is done for list(). No BC break.
 * list() keys: Introduce ListItem and either use it always (BC break) or only if a key is specified (inhomogeneous). Alternatively: Represent list() as array with extra attribute, as these are now interchangeable. Or at least reuse ArrayItem instead of having a separate ListItem.
 * Multi catch: Either replace type with types array (BC break) or make it inhomogenous using a single class or an array.
 * Nullable types: Add a Nullable node. No BC break.

**Comment by nikic** [comment]
I don't think it'll be possible to fully keep BC, so I'm targeting a new major version.
