### ISSUE TITLE
Way to find out String type (single quote, double quote, heredoc, nowdoc)

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#261]
I need to know wether a string Scalar\String node is a double- or single quoted string. PHP allows variable interpolation only inside double-quoted, so I need to provide code completion inside double quoted strings, but not in single-quoted. The end sequence for a heredoc/nowdoc would also be beneficial to know for auto completion.

**Comment by nikic** [comment]
Implemented: https://github.com/nikic/PHP-Parser/commit/588e6a4d4c69bf00d14ff42ddfd69507f73a4e10
