### ISSUE TITLE
Retrieve the startFilePos of a docblock?

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#263]
Hello

I see it is possible to retrieve the start line of a docblock via the `getLine` method. Is it also possible to retrieve the byte offset (cfr. `startFilePos` for nodes) for docblocks directly somewhere?

Thanks in advance

**Comment by nikic** [comment]
It is now: https://github.com/nikic/PHP-Parser/commit/15a2388d75ecf882ae6fb59f385e6e5bed9ae651

Not adding end line / end file pos (at least for now) as those are easily computable.
