### ISSUE TITLE
Remove some property from class.

### ISSUE THREAD

**Issue by Kvartir54** [nikic/PHP-Parser#267]
Hello!

I have class 'Foo', and property 'bar'

```
class Foo 
{
    public function $bar;
}

```
Can i remove this property from the class(file)? and how?

**Comment by nikic** [comment]
Assuming you want to remove a property with a certain name, you could use a node visitor looking something like this:

```php
use PhpParser;
use PhpParser\Node;
use PhpParser\Node\Stmt;

class Visitor extends PhpParser\NodeVisitor {
    public function leaveNode(Node $node) {
        if ($node instanceof Stmt\Property) {
            if (count($node->props) === 1) {
                if ($node->props[0]->name === 'bar') {
                    return PhpParser\NodeTraverser::REMOVE_NODE;
                }
            } else {
                foreach ($node->props as $i => $prop) {
                    if ($prop->name === 'bar') {
                        unset($node->props[$i]);
                        break;
                    }
                }
            }
        }
    }
}
```

The code is so complex because it tries to cover both the case of `public $bar` (in which case the whole property is dropped) and `public $foo, $bar` (in which case only one element of the property is dropped).

**Comment by Kvartir54** [comment]
Thanks, @nikic. But can you tell more in detail, what to do with it? and how to apply it to my classes and method?

**Comment by nikic** [comment]
The example from the node traverser docs should probably help: https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#node-traversation

It shows how to wire together the different components. You just need to use a different visitor there.

**Comment by Kvartir54** [comment]
I see, thanks @nikic
