### ISSUE TITLE
Explanation on test/code/parser/expr/new.test

### ISSUE THREAD

**Issue by remicollet** [nikic/PHP-Parser#271]
I notice in a0c216bf4b99a5e29f757a8d4b975111b74af689 you add "comments" in most test output, but not on new.test.

Running "php-parse" on this file output the comments...

What raised my attention on this, is while running the test suite from a git clone, it passes, but when I run it in a quite different way (system phpunit + PhpParser autoloader) I got a single failure on this file;

```
1) PhpParser\CodeParsingTest::testParse with data set "new" ('New (/dev/shm/BUILD/PHP-Parse....test)', '<?php\n\nnew A;\nnew A($b);\n\n// ...ew A);', 'array(\n    0: Expr_New(\n     ...   )\n)', null)
New (/dev/shm/BUILD/PHP-Parser-47b254ea51f1d6d5dc04b9b299e88346bf2369e3/test/code/parser/expr/new.test)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
         )
+        comments: array(
+            0: // class name variations
+        )

@@ @@
         args: array(
+        )
+        comments: array(
+            0: // DNCR object access
         )
     )
     6: Expr_New(
     ... <snip>...

```

So having the comment seems the right output ? but why not on your side... ?
Any idea ?

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/PHP-Parser/commit/e45e31c218dc224f20155b932e309438fe2eeeb2. Whether the test ran depended on filesystem iteration order, so you saw a failure, while I didn't. Now both the test and the test runner should be correct :)

**Comment by remicollet** [comment]
Yes, everything ok now, Thanks!!
