### ISSUE TITLE
How to Pretty Print arrays keeping all comments

### ISSUE THREAD

**Issue by vedmant** [nikic/PHP-Parser#273]
Basically I need to read array from file, alter array and add some comments, and then save array to file keeping formatting standard and comments. Right now it just saves whole array as single line and removes all comments.

**Comment by nikic** [comment]
If you need to preserve formatting this library is generally a bad pick. For your particular case you might be able to extend the pretty printer and override the formatting of arrays using something like this (untested):

```php
public function pExpr_Array(Expr\Array_ $node) {
    if (empty($node->items)) {
        return '[]';
    }    
    $result = "[";
    foreach ($node->items as $item) {
        $comments = $item->getAttribute('comments', []);
        if ($comments) {
            $result .= "\n" . $this->pComments($comments);
        } 
        $result .= "\n" . $this->p($item) . ",";
    }
    return $result . "\n]";
}
```

This will add comments and print array elements on separate lines.

**Comment by vedmant** [comment]
Thanks, this works! Few more questions if you don't mind, how can I maintain correct indentation and if it parses blank lines?

**Comment by nikic** [comment]
Keeping indentation and blank lines of the original file is, at least currently, not possible. At least there are no easy ways to do it. Formatting preserving transformations using this library are typically done by using the AST only for analysis and location information, and then doing the actual changes directly on the code :/

**Comment by vedmant** [comment]
I see, thanks, I thought I can use it to edit code.
