### ISSUE TITLE
Make \PhpParser\Node\Stmt\Trait_ constructor similar to Interface_ and Class_

### ISSUE THREAD

**Issue by tomzx** [nikic/PHP-Parser#274]
Hello,

I see the `Trait_` node being similar to the `Interface_` and the `Class_` nodes. This can be further demonstrated by the fact that all these classes extend the `ClassLike` abstract class. Thus, I think the next logical step would be for `Trait_` to have the same constructor format, namely

`public function __construct($name, array $subNodes = array(), array $attributes = array())`

instead of

`public function __construct($name, array $stmts = array(), array $attributes = array())`

In my project, if the `Trait_` could have the same format as `Interface_` and `Class_`, it would allow me to test them all together instead of requiring a special case for the `Trait_` instantiation.

```php
function getConstructorForContext($context)
{
	return [
		'class' => Class_::class,
		'interface' => Interface_::class,
		'trait' => Trait_::class,
	][$context];
}

[...]

// $context is either class, interface or trait
$constructor = getConstructorForContext($context);
$classBefore = new $constructor('tmp', [
	'stmts' => [
		new ClassMethod('tmpMethod', [
			'params' => [
				new Param('a', null, 'A'),
			],
		]),
	],
]);

$classAfter = new $constructor('tmp', [
	'stmts' => [
		new ClassMethod('tmpMethod', [
			'params' => [
				new Param('a', null, 'A'),
				new Param('b', null, 'B'),
			],
		]),
	],
]);
```

This change would however require a major bump (not backward compatible) since it completely changes the expected parameter format of the constructor.

Let me know what you think.

**Comment by nikic** [comment]
Scheduling this for 3.0. In the future traits might also support implements/extends, so this will have better forward-compat as well :)

**Comment by nikic** [comment]
Changed in 3.0: https://github.com/nikic/PHP-Parser/commit/867ae5148d975821a361d2ad5058bb8207b7c96a
