### ISSUE TITLE
What would be the most efficient way to compare two trees?

### ISSUE THREAD

**Issue by tomzx** [nikic/PHP-Parser#275]
I have two array of statements and I want to compare them to check if they are the same. For the moment I'm using the `NodeDumper` to dump the representation and test if they are both the same. However I am not sure if this is a reliable way to do it.

Normally I'd want to iterate through the node pairs and basically do a tree traversal, however considering the variety of existing nodes, I'm unsure about how to proceed.

Is my current method appropriate? If the tree traversal supporting all node types is not too complicated, would it be possible to produce an example as part of the documentation?

**Comment by nikic** [comment]
I use the node dumper method to check if ASTs are equal. Likely not the most efficient way, but at least the simplest :)

**Comment by tomzx** [comment]
I was hoping it would be possible to use PHP equal operator for it to automatically compare the structures recursively, however due to the fact that nodes have startLine/endLine, it is simply not possible. Thus I was thinking that by clearing the attributes array (or never filling it in) it would be possible simply do $stmts1 == $stmts2.

It appears that if I empty the `'usedAttributes' => array('comments', 'startLine', 'endLine'),` array, I can do exactly just that.

Is there any case where that would cause issues/not work?

**Comment by nikic** [comment]
The parser itself can set a couple of attributes related to formatting (primarily of literals). so this depends on whether you want to consider  `AST("foo")` and `AST('foo')` to be equal (this is what the comparison of the dumps would give you) or not (this is what your suggested approach would do).

Apart from that, it sounds like that approach should work.

**Comment by tomzx** [comment]
Thanks for the help!
