### ISSUE TITLE
Whitelisting Node Types

### ISSUE THREAD

**Issue by dhensby** [nikic/PHP-Parser#278]
At the moment I'm looking at using PHPParser to build a manifest file of that compiles a set of information about PHP files and what is contained within them, I'm looking to store any:

- Class/interface/trait definitions
  - Parent class (if there's an `extends`)
- Interfaces implemented

For this we only need to pull out "tokens" matching:

- `Class_`
- `Trait_`
- `Interface_`

Is there a way to only iterate over the tokens we need rather than iterating over all tokens in the file? At the moment we're experiencing a lot of overhead for this task and would like to optimise as best we reasonably can.

We are also using the namespace resolver too, so we'd need whatever that relied on too

**Comment by nikic** [comment]
Sorry, I don't think this is possible. We can't perform a partial parse of the file only -- the best that can be done here is avoid the AST instantiation, though I don't see how this could be done cheaply.
