### ISSUE TITLE
Parse, change and generate file

### ISSUE THREAD

**Issue by KKSzymanowski** [nikic/PHP-Parser#282]
Hi

Is it possible, using your library, to:
1. Parse a file
2. Add/change something
3. Generate the same file with updated content

What I'm trying to accomplish is add a `use` statement below the namespace and add a `trait` use statement at the top of class body.

Example(or really the only use case)
Original file:
```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```
Changed file:
```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Santigarcor\Laratrust\Traits\LaratrustUserTrait; // ---- add this ----

class User extends Authenticatable
{
    use LaratrustUserTrait; // ---- and this ----

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

I also want to leave unrelevant parts of the file alone, so that comments, formatting etc. stay unchanged.

I haven't found anything like this in your documentation.

Would I be better off doing this manually? By that I mean:
1. Parse the file using your tool(to catch any syntax errors etc.)
2. Fetch contents of the file to string
3. Find last use statement before `class` keyword
4. Add my new use statement
5. Add trait use statement after class definition header
6. Save new contents to the file

Thanks in advance.

**Comment by nikic** [comment]
It's a very common request, but this library currently does not support format-preserving code changes. I usually solve this with the approach described in https://github.com/nikic/PHP-Parser/issues/41#issuecomment-168498487, i.e. enable file offsets in the lexer, then use the AST to find the places I need to modify, but actually do the changes directly on the code, using the file offsets in the AST nodes. As you only need to do relatively high-level changes (rather than expression-level modifications), it may well be easier for you to skip the AST entirely and work on the tokens.

**Comment by KKSzymanowski** [comment]
Thanks for your responses.

What I did to achieve this was
1. Generate AST from file
2. Find last `use` before class definition and remember it's line number
3. Load file as an array of lines using `file($path)` method.
4, Add my line to this array using `array_splice`
5. Do the same for `trait` use statement inside class body
6. `Implode` the array and save to file.

It turned out to be quite complicated but apparently it works. What I mean by complicated, is it produced quite a spaghetti code and refactoring small pieces to separate methods rendered the class enormous.

Also, you may be right that working with just the tokens, omitting parsing stage can be easier. I will try it out some time soon.

**Comment by funivan** [comment]
Have same issue. One of the goal is to leave the same code formatting. For this task I create library https://github.com/funivan/PhpTokenizer This library is based on the core function tokens_get_all
