### ISSUE TITLE
Q: Zephir transpiler

### ISSUE THREAD

**Issue by andrejguran** [nikic/PHP-Parser#283]
Hi, I want to extend your parser a little to also include zephir lang, to make it possible to transpile source code from zephir to php 5/7 and vice versa. 
I need a little push, because I am not sure where to start.
Zephir has it's own grammar in lemon format: https://github.com/phalcon/zephir/blob/master/runtime/parser.lemon
so I was wondering if there is a possibility to create AST based on grammar definition in zephir repo and then use prettyPrinter to output PHP code?

**Comment by nikic** [comment]
There is no generic way to create an AST from the lemon grammar, you'll have to do some manual conversion for the AST construction at least. If you want to use kmyacc (as this project does) you will need to translate the grammar into yacc/bison format. It looks like there is also a [lemon parser generator](https://github.com/wez/lemon-php) for PHP, but I have no idea how usable it is.
