### ISSUE TITLE
PHP Fatal error:  Call to undefined method PhpParser\PrettyPrinter\Standard::pScalar_EncapsedStringPart()

### ISSUE THREAD

**Issue by javiern** [nikic/PHP-Parser#284]
im getting this error using the pretty printer

PHP Fatal error:  Call to undefined method PhpParser\PrettyPrinter\Standard::pScalar_EncapsedStringPart()

the method, effectively is not defined...

**Comment by nikic** [comment]
Do you have a reproduce code for this issue?

**Comment by nikic** [comment]
Ping?

**Comment by javiern** [comment]
sorry for not responding, i was out for a while,  the problem i think was my fault, because i manipulate de tree to extract parts of them, i supose iam was doing something wrong because i cannot find a simple case that reporduce the same failure... thanks any way....

**Comment by JanTvrdik** [comment]
@nikic This issue is still there, reproduction is trivial, just try to directly print `\PhpParser\Node\Scalar\EncapsedStringPart` – `\PhpParser\Node\Scalar\EncapsedStringPart` is instance of `Scalar` and therefore instance of `Expr`, so the printer should be able to handle this without fatal error OR `\PhpParser\Node\Scalar\EncapsedStringPart` should not be instance of `Expr`.

**Comment by nikic** [comment]
Yes, ideally it shouldn't be an Expr. Under what circumstances do you end up directly printing a EncapsedStringPart?

**Comment by JanTvrdik** [comment]
The circumstances are not interesting in this case. I basically iterate over `\PhpParser\Node\Scalar\Encapsed::$parts` and recursively process each part and as part of the processing the expression may be printed. I can easily work around this issue in my case, but I still think that the current behavior with fatal error is not correct.

**Comment by nikic** [comment]
The problem with printing an EncapsedStringPart is that it needs to know the quotation context to perform correct escaping. I could of course print something that is not strictly correct (say just return the string without escaping). Alternatively I could also explicitly throw an exception to indicate that it's not supported (like in https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php#L508).

**Comment by JanTvrdik** [comment]
Can the quotation context be added as EncapsedStringPart's attribute?

**Comment by nikic** [comment]
I've opened #500 to track the Expr classification issue.

The quotation type could theoretically be added to EncapsedStringPart's attributes, but I don't think it's a good solution. The quotation type is already fully determined by the parent structure, so this would just add a piece of duplicated state that can go out of sync with the parent (e.g. if an EncapsedStringPart is moved or duplicated).

**Comment by nikic** [comment]
Explicit exception added in https://github.com/nikic/PHP-Parser/commit/6526ea24974dfc83e620f8abdec22050736d7ebb.
