### ISSUE TITLE
How can I create a getter method?

### ISSUE THREAD

**Issue by ArminVieweg** [nikic/PHP-Parser#287]
Sorry for disturbing, but I would like to ask for help with creating a getter method, which returns the value of an attribute. Did not find a "Return_" expression, or am I totally wrong?

Wanted to write a script to extend existing classes with properties (and getter/setter methods).

Thanks in advance!
Armin

**Comment by nikic** [comment]
Return is a statement, not an expression: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Return_.php

**Comment by ArminVieweg** [comment]
Oh! Strange that I did not find it by myself. I'm sure I've searched for "Return_".
However... Thanks! :)
