### ISSUE TITLE
Ask: Is there any way to get the fully name of an class/trait that was use-imported?

### ISSUE THREAD

**Issue by LKDevelopment** [nikic/PHP-Parser#289]
Hello,

is there a way to get  the FQName of an trait, interface or class that was use-imported before?

Thanks for help!

**Comment by nikic** [comment]
This is what the name resolver is for, see https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#the-nameresolver-node-visitor.

The class/trait will have a `namespacedName` node after it has run, which contains the fully qualified name.
