### ISSUE TITLE
PHP code blocks parsed as Node\Stmt\InlineHTML

### ISSUE THREAD

**Issue by in-the-name-of-science** [nikic/PHP-Parser#290]
I'm not sure if this is due to the fact that the parsed application was written back in 2005 therefore a much older version of PHP was used but I am coming across an issue in which a PHP code blocks are processed as `Node\Stmt\InlineHTML` when I am visiting the AST.

For example the code:

`<? $a="a"; ?>`

will be represented as InlineHTML:

```
object(PhpParser\Node\Stmt\InlineHTML)#9 (2) {
  ["value"]=>
  string(13) "<? $a="a"; ?>"
  ["attributes":protected]=>
  array(2) {
    ["startLine"]=>
    int(1)
    ["endLine"]=>
    int(1)
  }
}
```

If I switch the opening tag from `<?` to `<?php` it is parsed as expected.

So I have some questions:

1. Is this a bug? Or does this just mean that the code is written in older-than-supported PHP?
2. If I were to write a  special Node visitor that were to change all opening tags to `<?php` so that PHP-Parser actually parses them as PHP what would be consequences be?

**Comment by nikic** [comment]
PHP-Parser uses PHP's own tokenizer for lexing, so if you want to support short tags, you should enable the short_open_tag ini option. Otherwise short tags will just be treated as normal text.

**Comment by in-the-name-of-science** [comment]
Ah yes. That did the trick. Thanks!
