### ISSUE TITLE
Class 'PhpParser\Node\Stmt\Nop' not found

### ISSUE THREAD

**Issue by luisfredgs** [nikic/PHP-Parser#291]
I'm getting this error:

`FatalErrorException in /home/toptarget/public_html/univtop/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php line 1285:
Class 'PhpParser\Node\Stmt\Nop' not found`

Please, help!

**Comment by nikic** [comment]
What version of php-parser do you use and what is the context?

**Comment by luisfredgs** [comment]
Hello, I'm using laravel 5.2 with nikic/php-parser included, i don't know yet what version. Please, see my composer.json


{
    "name": "nikic/php-parser",
    "description": "A PHP parser written in PHP",
    "keywords": ["php", "parser"],
    "type": "library",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Nikita Popov"
        }
    ],
    "require": {
        "php": ">=5.4",
        "ext-tokenizer": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0"
    },
    "autoload": {
        "psr-4": {
            "PhpParser\\": "lib/PhpParser"
        }
    },
    "bin": ["bin/php-parse"],
    "extra": {
        "branch-alias": {
            "dev-master": "2.1-dev"
        }
    }
}

**Comment by nikic** [comment]
You should be able to see the version in your composer.lock file. Not sure where this is coming from ... can you check if running `composer dump-autoload` fixes the issue?

**Comment by luisfredgs** [comment]
Yes, on composer.lick file founded:

```
"require": {
                "nikic/php-parser": "^1.2|^2.0",
                "php": ">=5.4",
                "symfony/polyfill-php56": "^1.0"
            },
```

i tried run `composer dump-autoload`, but not fixed. I could disable PHP7 support? My server is running php 5.6

**Comment by luisfredgs** [comment]
Is there a special requirements for php-parser?

**Comment by GrahamCampbell** [comment]
> Yes, on composer.lick file founded:

That's not the right part. The exact version number will be listed. Also you can run `composer show -i` to show the versions of all installed packages.

**Comment by luisfredgs** [comment]
v2.1.0 was listed. Thanks!

**Comment by nikic** [comment]
Issue #294 looks similar to this. If this problem isn't resolved yet, it looks like just dropping the nikic/php-parser directory in vendor/ and running composer again should fix it.

**Comment by EvoPulseGaming** [comment]
This is not okay. the issue referenced to close this, was also closed, and if you go down the rabbit hole, this ends as closed with "issue resolved itself".

The rabbit hole:
https://stackoverflow.com/questions/39247957/class-phpparser-parser-php7-not-found-laravel-when-using-mail
which leads to:
https://github.com/nikic/PHP-Parser/issues/291
which leads to:
https://github.com/nikic/PHP-Parser/issues/294

I'm a user of "fusio" and randomly get this message for no reason.
ref: https://github.com/apioo/fusio/issues/275 for cross reference

**Comment by EvoPulseGaming** [comment]
Just happened again. This is like the 2nd time this month...
