### ISSUE TITLE
prettyPrintFile comment bug

### ISSUE THREAD

**Issue by yejune** [nikic/PHP-Parser#293]
Code1 :

``` php
switch ($kind) {
    case 1:
        break;
        /* test */
    case 2:
        break;
    case 3:
        break;
    /* test */
    case 4:
        break;
}
```

prettyPrintFile Output:

``` php
switch ($kind) {
    case 1:
        break;
        /* test */
    /* test */
    case 2:
        break;
    case 3:
        break;
        /* test */
    /* test */
    case 4:
        break;
}
```

Code2 :

``` php
//test
{
    $a  = 0;
}

{
    //test
    $a  = 0;
}
```

prettyPrintFile Output:

``` php
$a  = 0;
//test
$a  = 0;
```

**Comment by nikic** [comment]
Second issue fixed in https://github.com/nikic/PHP-Parser/commit/83f34e7fa4975e9646e118b61226e17cebc5db14 -- the first comment should now be preserved on the assignment node.

**Comment by mithrabala** [comment]
I don't know how to run your document. please tell I'm new to this one

**Comment by jhodgdon-drp** [comment]
The first problem is actually in the parser. See #469

**Comment by nikic** [comment]
First issue fixed by https://github.com/nikic/PHP-Parser/commit/08215e764671a52e8d20fcfc122189648a76c5fa as part of #469.
