### ISSUE TITLE
Error on PhpParser\Parser\Multiple.php

### ISSUE THREAD

**Issue by plateena** [nikic/PHP-Parser#294]
PhpParser\Parser\Multipl cannot implement PhpParser\Parser - it is not an interface.

**Comment by plateena** [comment]
Ok it was an old file. Don't know why composer won't update it. Remove entire PhpParser folder and run composer again.

**Comment by nikic** [comment]
As the issue seems to have resolved itself, closing here.

**Comment by EvoPulseGaming** [comment]
It has not. This just happened again (2x this month) see #291
