### ISSUE TITLE
New objects assigned by reference($o =& new C) should raise a parse error

### ISSUE THREAD

**Issue by monque** [nikic/PHP-Parser#295]
Like it described at http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.new-by-ref.

This snippet

```
<?php
class C {}
$c =& new C;
```

it should raise a error `Parse error: syntax error, unexpected 'new' (T_NEW) in PHP-Parser/tmp.php on line 5`

But it parsed successful with `ParserFactory::ONLY_PHP7`.

**Comment by nikic** [comment]
`=& new` forbidden in PHP 7 mode via https://github.com/nikic/PHP-Parser/commit/13f7321defed66dbb3da9dba4aef6fed69e6d633.
