### ISSUE TITLE
Call to undefined function in Lexer.php

### ISSUE THREAD

**Issue by rcrum003** [nikic/PHP-Parser#296]
I'm getting this error with 
PHP 5.6.9, Apache 2.4.12, mysql 5.6.24 all running within AMMPS

Fatal error (1) in /nikic/php-parser/lib/PhpParser/Lexer.php on line 264: Call to undefined function PhpParser\\token_name(),

**Comment by GrahamCampbell** [comment]
Looks like you need to install ext-tokenization.

**Comment by GrahamCampbell** [comment]
edit: ext-tokenizer

**Comment by rcrum003** [comment]
That was it! thanks!
