### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by golaod** [nikic/PHP-Parser#298]
Package mkusher/padawa.php uses PHPParser and lately I have that issue:
File with line
`$countries = $this->country ?: ['US'] + array_keys(\CountryState::getCountries());`
throws an error:
`exception 'PhpParser\Error' with message 'Syntax error, unexpected T_STRING on line 52'`

**Comment by nikic** [comment]
`bin/php-parse "<?php \$countries = \$this->country ?: ['
US'] + array_keys(\CountryState::getCountries());"` works fine here. I also don't see anything special about that code that could be causing this issue.

**Comment by nikic** [comment]
Would it be possible to provide a complete file that exhibits this issue?
