### ISSUE TITLE
Builder does not support void return type

### ISSUE THREAD

**Issue by djmattyg007** [nikic/PHP-Parser#300]
`void` is missing from the list of scalar return types here: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Builder/FunctionLike.php#L70

This causes an instance of `PhpParser\Node\Name` to be created, rather than a string containing `void`.

**Comment by nikic** [comment]
Good point. Also missing `iterable`.

**Comment by nikic** [comment]
Support for void, iterable and nullables added in https://github.com/nikic/PHP-Parser/commit/1ab24d26eeb444303e99f772710e224f0b357ff7.

**Comment by djmattyg007** [comment]
Cheers!
