### ISSUE TITLE
Not clear how to set docblock comments on existing nodes

### ISSUE THREAD

**Issue by djmattyg007** [nikic/PHP-Parser#302]
The `PhpParser\Node` interface has a `getDocComment()` function, but no matching `setDocComment()` function. While it would certainly be possible to use `setAttribute()` to set the docblock comment on a node extending from `PhpParser\NodeAbstract` (due to reading the code to understand the underlying implementation), it would be nice if there was a concrete way of specifically setting a docblock comment that didn't rely on understanding the implementation.

This is useful when modifying existing code that has been scanned by the parser, rather than using the code generation builder classes to create code from scratch.

**Comment by nikic** [comment]
Sounds sensible.

 * If last comment is doc comment replace it
 * Otherwise append the new doc comment
 * Maybe: If argument is null and last comment is doc comment remove it

**Comment by nikic** [comment]
Peculiarly, there used to be a setDocComment method: https://github.com/nikic/PHP-Parser/commit/a824a2aba7c39254ad98f2960af6ca121349814c

**Comment by nikic** [comment]
setDocComment() added in https://github.com/nikic/PHP-Parser/commit/ea47b6e0d643b91d55167e7a212b22986406f217, for now without ability to pass null.

**Comment by djmattyg007** [comment]
Thanks!
