### ISSUE TITLE
Parser syntax error for methods named `list`

### ISSUE THREAD

**Issue by cmack** [nikic/PHP-Parser#307]
```
PHPParser: Syntax error, unexpected T_LIST, expecting T_STRING on line 87 - foo.php
```

Line 87 of foo.php is the definition of `list` method defined like this:

```php
protected function list()
{
    ...
}
```

**Comment by GrahamCampbell** [comment]
Are you parsing as PHP 5 code, or PHP 7 please? This is only permitted in PHP 7 since list became semi-reserved.

**Comment by cmack** [comment]
@GrahamCampbell yes, php7 with php parser v. 2.1.1 I have another similar error that I was going to file as a separate bug but it sounds like it might be similar root cause. Similar error for classes with `include()` methods: 
```
PHPParser: Syntax error, unexpected T_INCLUDE, expecting T_STRING on line 58
```

**Comment by cmack** [comment]
ah I think I misunderstood your comment, now checking to see if it's being parsed as php7 by parser.

**Comment by cmack** [comment]
mea culpa. It appears the tool I am using is not using the parser version I tell it to. I'll close this since I need to debug further. Sorry for the noise.
