### ISSUE TITLE
NameResolver throws error: need ErrorHandler for NodeVisitors

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#309]
I'm using the `NameResolver` in https://github.com/felixfbecker/php-language-server. I cannot assume that documents are always correct (also use throwOnError => false). The NameResolver however throws an error if a `use` statement is used twice, which aborts the whole AST traversal and atm even crashes the language server. What do you suggest to handle this? Maybe the NameResolver could also get a `throwOnError` option?

https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeVisitor/NameResolver.php#L135

**Comment by nikic** [comment]
I'd like to have a more general solution to this than adding a `throwOnError` option and a `getErrors()` method everywhere. I was considering the addition of an `ErrorHandler` interface with variants `ErrorHandler\Throwing` and `ErrorHandler\Collecting`, which can be passed to parser/lexer/name resolver/etc. The mainly problem I ran into is how this interacts with the `Parser\Multiple` -- in that case I wouldn't want the errors from multiple attempted parse runs to be collected. I'm not yet entirely sure how to best approach this.

**Comment by felixfbecker** [comment]
Interesting, could you explain a bit more what your interfaces would do?
And is there any short-term solution?

**Comment by nikic** [comment]
Here is what I had in mind: https://github.com/nikic/PHP-Parser/compare/errorHandler
I resolved the `Parser\Multiple` issue by defining a "successful" parse as anything that doesn't throw (i.e. effectively dropping any multiple parser tries in error recovery mode).

The usage would be something like this:

```php
// Setup
$errorHandler = new ErrorHandler\Collecting;
$parser = (new ParserFactory)->create(
    ParserFactory::ONLY_PHP7, $lexer, ['errorHandler' => $errorHandler]);
$traverser = new NodeTraverser;
$traverser->addVisitor(
    new NodeVisitor\NameResolver(['errorHandler' => $errorHandler]));

// Per-file
$errorHandler->clearErrors();
$stmts = $parser->parse($code);
$stmts = $traverser->traverse($stmts);

if ($errorHandler->hasErrors()) {
    registerErrors($errorHandler->getErrors());
}
```

Something I'm not quite sure about with this is that the user is responsible for clearing the errors if the `ErrorHandler` is reused (which it should be). The idea behind this is that this allows (as in the above example) to collect errors from a number of different operations, for example both parsing and name resolution. An alternative would be to add a `resetErrors()` method to the interface which is automatically called, e.g. when parsing starts / name resolution starts.  However that would prevent this kind of use.

**Comment by felixfbecker** [comment]
That is very nice, much better than `getErrors()` everywhere! `getErrors()` is also very problematic with async programming. In the language server we use an event loop and if two events parse a file, and later try to get their errors, they could be overridden. This is currently never the case but it could happen. So I think the user should definitely clear the errors himself.

Actually though, I think an even better pattern would be to pass an individual error handler to every call of `traverse()` or `parse()`. That is kind of in line how PSR-log interfaces work and allows you to share a parser object without sharing error state. You also don't need to "reset" the error handler then, you just create a new one for a new operation.

> I resolved the Parser\Multiple issue by defining a "successful" parse as anything that doesn't throw (i.e. effectively dropping any multiple parser tries in error recovery mode).

Does that mean you cannot fallback to PHP5 with error recovery mode?

**Comment by nikic** [comment]
> getErrors() is also very problematic with async programming. In the language server we use an event loop and if two events parse a file, and later try to get their errors, they could be overridden.

You're considering the case where you yield control between calling parse() and calling getErrors(), right?

> Actually though, I think an even better pattern would be to pass an individual error handler to every call of traverse() or parse(). That is kind of in line how PSR-log interfaces work and allows you to share a parser object without sharing error state. You also don't need to "reset" the error handler then, you just create a new one for a new operation.

Good point, I agree that this would be a better approach for the parser. However, I'm not sure how this would integrate in the NameResolver case, which is only invoked through the traverser. This would require making the traverser itself be aware of error handling and either pass the error handling along in individual calls or for example in beginTraverse. Not sure if the traverser should be coupled to error handling in this way.

> Does that mean you cannot fallback to PHP5 with error recovery mode?

Yes (though I'd prefer keeping this somehow). PHP7 is a syntactic superset of PHP5 with two exceptions: `$foo =& new Bar;` and `global $$foo->bar`, only the former of which may be encountered in the wild. Both of these would be (recoverable) errors in PHP7. Everything else are only differences in interpretation.

Error recovery and parser fallback sometimes interact weirdly. E.g. if you parse `$n = 08;` (invalid octal) in the PHP7 parser this would generate a (since recently recoverable) error. This would trigger a fallback to PHP5 which would generate the same parse tree, but drop this error.

**Comment by felixfbecker** [comment]
> You're considering the case where you yield control between calling parse() and calling getErrors(), right?

Exactly.

> Good point, I agree that this would be a better approach for the parser. However, I'm not sure how this would integrate in the NameResolver case, which is only invoked through the traverser. This would require making the traverser itself be aware of error handling and either pass the error handling along in individual calls or for example in beginTraverse. Not sure if the traverser should be coupled to error handling in this way.

PSR-log defines an interface with a `setLogger()` method if I remember correctly. PHPParser could define an interface with a `setErrorHandler` method that takes an error handler. The NodeTraverser then checks if a visitor implements this interface with `instanceof` and if yes, set the error handler. Only constructor errors could not be caught by this, but stuff like an `InvalidArgumentException` shouldnt be caught anyway.

> Yes (though I'd prefer keeping this somehow). PHP7 is a syntactic superset of PHP5 with two exceptions: $foo =& new Bar; and global $$foo->bar, only the former of which may be encountered in the wild. Both of these would be (recoverable) errors in PHP7. Everything else are only differences in interpretation.
> Error recovery and parser fallback sometimes interact weirdly. E.g. if you parse $n = 08; (invalid octal) in the PHP7 parser this would generate a (since recently recoverable) error. This would trigger a fallback to PHP5 which would generate the same parse tree, but drop this error.

We definitely need to support PHP 5, but I guess it's okay like you explained.

**Comment by nikic** [comment]
> We definitely need to support PHP 5, but I guess it's okay like you explained.

To be clear, it's still possible to replicate the exact previous behavior using code along these lines:

```php
$lexer = ...;
$parser7 = new Parser\Php7($lexer);
$parser5 = new Parser\Php5($lexer);

$errors7 = new ErrorHandler\Collecting();
$stmts7 = $parser7->parse($code, $errors7);
if ($errors7->hasErrors()) {
    $errors5 = new ErrorHandler\Collecting();
    $stmts5 = $parser5->parse($code, $errors5);
    if (!$errors5->hasErrors()) {
        // If PHP 7 parse has errors but PHP 5 parse has no errors, use PHP 5 result
        return [$stmts5, $errors5];
    }
}
// If PHP 7 succeeds or both fail use PHP 7 result
return [$stmts7, $errors7];
```

But it will not be possible to use the `Multiple` parser to do this, because it no longer has the context to distinguish a failed-but-recovered parse (let alone properly determine the errors).

**Comment by felixfbecker** [comment]
Here is how PSR/log does it: https://github.com/php-fig/log/blob/master/Psr/Log/LoggerAwareInterface.php

**Comment by nikic** [comment]
Forgot to link, this is mostly implemented by: https://github.com/nikic/PHP-Parser/commit/f99a96e0a2d48c903877fd9089fc0f222e0b2f65

This commit still uses the ctor to set the ErrorHandler in the NameResolver. I'd prefer leaving it at that for now -- I don't think that integrating error handling in the traverser is solving the right problem here. This is a special case of the more general problem of passing per-traversal data to a visitor. This comes up commonly, e.g. in your own project ReferencesAdder and ColumnCalculator would need this if they were reusable. I don't think it makes much sense to add a special mechanism for error handling only, especially if there's just the one visitor that needs it right now.

**Comment by felixfbecker** [comment]
And what about the NameResolver case? Can't have the language server crash when a document aliases the same namespace twice

**Comment by nikic** [comment]
@felixfbecker As said, the error handler is passed in the ctor for the NameResolver. As you're not reusing visitors anyway, you just need to pass `ErrorHandler\Collecting` as an extra arg in https://github.com/felixfbecker/php-language-server/blob/master/src/PhpDocument.php#L149.

**Comment by felixfbecker** [comment]
Ah, sorry. Thanks, I will try this!
