### ISSUE TITLE
Aborting Traversal (like a break statement in a loop)

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#310]
I'm traversing the AST to find a specific node. As soon as I have it, I would like to abort the traversal by returning something like `NodeTraverser::BREAK`, like a break statement in a loop. Need this for both `enterNode` and `leaveNode`

**Comment by nikic** [comment]
Sounds reasonable. It will probably be `STOP_ITERATION`, as `BREAK` can only be used as a constant name as of PHP 7.

**Comment by martinsik** [comment]
Isn't this already resolved by `NodeTraverser ::DONT_TRAVERSE_CHILDREN`?

https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeTraverser.php#L100

**Comment by felixfbecker** [comment]
No, that will continue to traverse siblings and their children.

**Comment by nikic** [comment]
For the record, the reason why I haven't implemented this yet is that it has a large testing surface area -- this can be returned by both enter and leave, has to early-abort the recursion, but still needs to preserve all modifications that may already have happened. That's 12 new branches in the traverser...

**Comment by nikic** [comment]
The last implementation I tried used a mutable internal flag in the traverser which was set when the break value is returned and checked after each recursion. It was pretty ugly. What I'd usually do for a multi-level break is throw an exception, but that does not play well with the mutability of the traversal.

**Comment by felixfbecker** [comment]
There are people who believe breaking out of a multi-level loop is a valid use-case for a `goto`

**Comment by nikic** [comment]
STOP_TRAVERSAL added in https://github.com/nikic/PHP-Parser/commit/58e7881e987c55c957104687ecccf963d1607753.
