### ISSUE TITLE
GroupUse::prefix endFilePos is wrong

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#311]
This code:
```php
use TestNamespace\{TestTrait, TestInterface};
```

The `GroupUse` Node will have a `prefix` property that is a `Name` node containing the name `TestNamespace`. It should range from column 5 to 18. Instead, it ranges the whole line (1 to 44), overlaying the other `UseUse` nodes.
This prevents me from implementing Goto Definition for `TestTrait` for example, because the node at the cursor position will always resolve to the `prefix` node.

**Comment by nikic** [comment]
Fixed with https://github.com/nikic/PHP-Parser/commit/f6eb341b1573a348b941b67ff0a8c7faa53ce9ac. It's a bit of a tricky case because I had to inline the namespace name productions to avoid shift/reduce conflicts.

**Comment by felixfbecker** [comment]
Wow, thanks for the quick fix!
