### ISSUE TITLE
Usefulness of attributes

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#312]
I was wondering what was the design decision behind adding an associative array of "attributes" to each node instead of simply patching attributes on the node directly. Calling `getAttribute('myAttribute')` everytime is a lot of boilerplate and has the performance overhead of a function call every time.
Just like JavaScript, PHP has excellent support for decorating objects with additional attributes without any warning or performance impact - it's even used by native `json_decode` or `PDO::FETCH_OBJECT`.
If I see remember correctly, `$namespacedNode` actually is also patched this way by the `NodeResolver` and not a defined property. I have to work with custom attributes a lot and always calling `getAttribute()` with the string name feels like working with just a raw array instead of an object.

Besides less code and better performance, it would have benefits for static tooling:

``` php
$node->getAttribute('startFilePos'); // was it startFilePos or fileStartPos? No help from IDE :(
```

With attributes, you could give static tooling a hint:

``` php
/** 
 * @property Node $parentNode
 */
interface LinkedNode extends Node {}

/**
 * @param LinkedNode $node
 */
public function enterNode($node) {
  $node->parentNode; // IDE knows $node has parentNode property
}
```

**Comment by nikic** [comment]
Attributes date back from sometime around the start of this project. At that time nodes extended `ArrayObject` in property mode and everything on that ArrayObject was considered a subnode. This changed at some point, switching to explicitly declared properties and a `getSubNodeNames()` method specifying the structure of the node. At this point, I don't think there is anything preventing us from using overloaded properties for attributes. I agree that this is both syntactically more convenient and would allow to at least declare all the standard attributes.

Do you know whether PhpStorm has some kind of mechanism to extend the properties of a class in a separate declaration? The `override` method seems to target factories exclusively.

**Comment by felixfbecker** [comment]
Awesome, this will make code so much less verbose. The best thing is that this can totally happen in a backwards-compatible manner, `getAttribute()` and `setAttribute()` can just get/set properties on the object.

> Do you know whether PhpStorm has some kind of mechanism to extend the properties of a class in a separate declaration? The override method seems to target factories exclusively.

Sorry, what do you mean by that? I'm not working with PhpStorm but I imagine something like the example I gave in the OP should work

**Comment by nikic** [comment]
Draft implementation: https://github.com/nikic/PHP-Parser/compare/attributes

Note that this keeps the backing `$attributes` property and uses `__get/__set` to handle access, for two reasons: Firstly, we operate on the full array in some places, in particular the initial construction is always from an array (we'd have to create a dynamic property table and copy otherwise). Secondly, this declares intent for IDEs, e.g. PhpStorm downgrades the warning level for access to undefined properties. Of course, it has the disadvantage that there's no performance benefit...

> Sorry, what do you mean by that? I'm not working with PhpStorm but I imagine something like the example I gave in the OP should work

Right, of course you aren't ^^ I was hoping for some magic to make this work without having to explicitly declare the node to be of a different type.

**Comment by felixfbecker** [comment]
`__get()`/`__set()` are about 3.4x slower than properties, about twice as slow as a normal function call.
Could you link where the implementation with native properties would be problematic ("initial construction")?

An IDE should be able to read `@property` with or without `__get()`. If not that is a problem of the IDE and we certainly should not base performance decisions on this.

**Comment by nikic** [comment]
> Could you link where the implementation with native properties would be problematic ("initial construction")?

The initial construction is https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeAbstract.php#L15. This would require copying all the attributes into the dynamic object properties. If you're considering this from a performance angle, this is expensive for the common case where attributes are not actually used much.

From an implementation perspective another problematic part is https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeAbstract.php#L105. This would need to gather the object properties, while excluding subnodes and declared properties that are not subnodes -- this comes down to using reflection, which I'm not keen on.

> An IDE should be able to read @property with or without __get(). If not that is a problem of the IDE and we certainly should not base performance decisions on this.

The IDE can read `@property`, but will (correctly) treat any custom attributes as undefined properties.

Of course you *are* right that magic get/set is slow. This certainly does not make sense if the goal is to improve performance -- is it? Is attribute fetching a bottleneck for you?

**Comment by felixfbecker** [comment]
Hm, valid points. Cannot confirm that it is a performance _bottleneck_ for me, but it is verbose for sure. I mostly see the benefit in cleaner code. But if the implementation is too hard of course we can leave it.
Is it needed to pass `$attributes` to the ctor? Can't the callee set them directly?

**Comment by felixfbecker** [comment]
@nikic I'm a bit lost in the source code, could you give me a link where the nodes are instantiated with `attributes`?

**Comment by felixfbecker** [comment]
@nikic I profiled my language server because I need to improve performance and it turns out `getAttribute()` actually is a performance bottleneck. As I iterate all ASTs and index FQNs, `getAttribute()` is called many many times for each Node for each AST for each file. For just parsing 100 files it was called 40,000 times and is actually the _most called function_ in the whole project. Just being able to access the attributes directly instead would save quite some CPU (PHP function invocations have more overhead than in any other language).

**Comment by nikic** [comment]
What percentage of the time is it though?

**Comment by felixfbecker** [comment]
Don't have the profile open atm but it was about 4%

**Comment by TomasVotruba** [comment]
What is this issue actually about?

I've noticed one note about autocomplete of `getAttribute(...)`. To fix that, you can use constants defined in single class: https://github.com/RectorPHP/Rector/blob/master/src/Node/Attribute.php

And use like this:

```php
$node->getAttribute(Attributes::TYPES);
```

Having constants makes it very hard to make a typo, compared to string naming.

Also I prefer current state using explicit methods than hiding it behind magic. I have very bad experience with that due to assumptions that other packages don't have to make. It was good and fast idea on first site though, so I understand your need.

I suggest either closing this or resolving it. Depending on your real current needs for this.

**Comment by TomasVotruba** [comment]
I think this one can be closed too, as:

* get line start/end, token start/end are part of `NodeAbstract` methods
* existing properties and attributes are now clearly separated

**Comment by nikic** [comment]
Given that dynamic properties are deprecated now, I think it's safe to close this.
