### ISSUE TITLE
Store string instead of Name::$parts

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#313]
In the end we pretty much always work on the string representation. Always indirecting through array operations is unnecessary and inefficient. However, the implementation of `::slice()` wrt empty slices might be problematic without a backing array.

**Comment by felixfbecker** [comment]
You could just split the string inside `slice()`. It's a question on what to optimize for

**Comment by nikic** [comment]
The issue is the case where slice() currently returns a name represented by an empty array (which would ordinarily be invalid. Representing this using an empty string is not quite the same, because it wouldn't concatenate correctly. I'm considering to either drop this part or represent it using a `null` value -- this would be consistent with the global namespace being `null` in namespace declarations. It would also allow writing code like [this](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeVisitor/NameResolver.php#L236) as just `Name::concat($this->namespace, $node->name)`, as the case where `$this->namespace` is null would be handled implicitly.

**Comment by muglug** [comment]
👍

**Comment by nikic** [comment]
Implementation: https://github.com/nikic/PHP-Parser/compare/nameString

In the end, not sure if this change is worthwhile, especially considering the BC this might cause.

**Comment by nikic** [comment]
E.g. psysh seems to be working directly on the parts array in a bunch of places: https://github.com/bobthecow/psysh/blob/master/src/Psy/CodeCleaner/NamespaceAwarePass.php#L48

**Comment by felixfbecker** [comment]
I would say just leave it then. Didn't know `parts` was public.

**Comment by nikic** [comment]
Could emulate with `__get`, but yeah, I'll just leave this for now.

**Comment by nikic** [comment]
To allow this in the future, I am however changing the slice API to use `null` instead of `new Name([])` (https://github.com/nikic/PHP-Parser/commit/fa7357b48398698a7463334488081318d108914a) and marking `$parts` as deprecated (https://github.com/nikic/PHP-Parser/commit/c0f0edf0441f0ddcff0604407b7600a40993faf2).

**Comment by felixfbecker** [comment]
What is the best way to iterate now over all parts of a name? There is only `getFirst`, `getLast` and `slice`...

**Comment by nikic** [comment]
Good question. I guess a `getParts()` method would ensure forward compatibility here. Out of interest, where do you iterate over the parts?

**Comment by felixfbecker** [comment]
When a class is instantiated like
```php
new NamespaceA\NamespaceB\ClassC();`
```
then that should register as a reference to
```
NamespaceA
NamespaceA\NamespaceB
NamespaceA\NamespaceB\ClassC
```
So the line is returned when you do a find-all-references for either one of them.

After discovering more use cases I'm more -1 on this change, but I outlined that in #322
