### ISSUE TITLE
PhpParser\Error thrown when using self-executing anonymous functions

### ISSUE THREAD

**Issue by mallardduck** [nikic/PHP-Parser#316]
I've recently started to use php-assumptions which uses this project as a parser. After doing some refactoring in my project I decided to use a self-executing anonymous function. Upon running the scan on my project again I found this error:

```
[dan@seymournx tools]$ phpa ./app
PHPAssumptions analyser v0.4.0 by @rskuipers

PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected '(' on line 119 in /home/mallard/.config/composer/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:275
Stack trace:
#0 /home/mallard/.config/composer/vendor/rskuipers/php-assumptions/src/PhpAssumptions/Analyser.php(59): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#1 /home/mallard/.config/composer/vendor/rskuipers/php-assumptions/src/PhpAssumptions/Cli.php(92): PhpAssumptions\Analyser->analyse(Array)
#2 /home/mallard/.config/composer/vendor/rskuipers/php-assumptions/bin/phpa(16): PhpAssumptions\Cli->handle(Array)
#3 {main}
  thrown in /home/mallard/.config/composer/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 275
```

The relevant lines of code triggering are as follows, the last line being line 119:

```
        $useCache = (function () use ($noCache) {
            $yes = ['1', 'y', 'yes']; // will be compared case-insensitive
            foreach ($yes as $value) {
                    if (strcasecmp($value, $noCache) === 0) {
                        return false;
                    }
            }
            return true;
        })();
```

### Update:
So I knew it was possible to use self-executing anonymous functions, but I honestly didn't know when it was added, or by what RFC. I wanted to know, so I looked it up. It was the [Generator Return Expressions](https://wiki.php.net/rfc/generator-return-expressions) RFC

**Comment by nikic** [comment]
To support PHP 7 you need to use the PHP 7 parser, see the first table in https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#parsing. Do you already do this?

**Comment by nikic** [comment]
Looks like this is being resolved in php-assumptions, so closing here.

Btw, the self-executing anonymous functions are part of the [uniform variable syntax](https://wiki.php.net/rfc/uniform_variable_syntax) RFC. Generator return expressions are something different :)
