### ISSUE TITLE
Error recovery from `new` statements

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#317]
Very important use case for completion is this:
```php
$obj = new 
```
where the cursor is after `new` and the user expects to get a list of classes. When parsing this document, the result is `null`. I would expect a `New` node with an `Error` node as `class` property

**Comment by felixfbecker** [comment]
Similarly, this should work too:
```php
$obj = new T
```
Where the `new` node is not yet terminated by a semicolon

**Comment by nikic** [comment]
Support for `new` without class name added in https://github.com/nikic/PHP-Parser/commit/c0630f81693a8fda40cfbd120b614ad1214287c8. `new T` without semicolon should already work. I've also added support for `$` (without following name) in https://github.com/nikic/PHP-Parser/commit/c5cdd5ad73ac20d855b84fa6d0f1f22ebff2e302 -- I'd assume you need this as well?.

**Comment by felixfbecker** [comment]
You guessed it :)

**Comment by felixfbecker** [comment]
It seems like the `Error` node has the wrong file offsets:

![image](https://cloud.githubusercontent.com/assets/10532611/20544460/80e0026c-b10a-11e6-853f-5b1521f5a9b3.png)

`startFilePos` and `endFilePos` are switched, which prevents me from resolving the node under the cursor correctly to the error node ;)

**Comment by nikic** [comment]
Should be fixed by https://github.com/nikic/PHP-Parser/commit/27281e913026eb039237baa6b37fafc9b6819b9b. The position of the `Error` node should now be the position of the token that caused the error.
