### ISSUE TITLE
Failed to detect "Fatal error: Call-time pass-by-reference has been removed"

### ISSUE THREAD

**Issue by SundialServices** [nikic/PHP-Parser#319]
The following line has a syntax error caused by the `&` symbol which is not detected by the parser:
`xml_set_object($this->parser, &$this);`
`------------------------------^`

*(an example of the correct use of simply `$this` can be seen in the current PHP manual-page.)*

PHP5 objects to this line with:
`Fatal error: Call-time pass-by-reference has been removed`

PHP7 complains:
`PHP Parse error:  syntax error, unexpected '&'`

... but the parser does not object at all.

The language apparently does not mind `&$this->foo`, that is to say, to a property of `$this`, but does not accept taking a reference to "`$this` itself."

**Comment by nikic** [comment]
The parser sets the `byRef` flag on the `Arg`, based on which you can throw an error.

Call-time pass-by-reference is supported in PHP 5.2 and 5.3, parsing of which is supported. It would be possible to remove support for this in the PHP 7 parser, but not sure if special-casing it is worthwhile.

**Comment by SundialServices** [comment]
I agree that it would not be worth changing and have closed the issue accordingly.  I'll modify my scanner.

However, may I ask that you please add a comment showing exactly what subtree I'd be looking at, and which node in that subtree would carry the `byRef` attribute that I'd be looking for?  I think that this would be useful and helpful documentation, for the next person who has this same issue.  Thanks.  *(And, "what a great tool!")*

**Comment by nikic** [comment]
The `args` subnode of the different call nodes are an array of [`Node\Arg`](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Arg.php), which as a `byRef` subnode. Checking for this error should be as simple as:

```php
class Visitor extends PhpParser\NodeVisitorAbstract {
    public function enterNode(PhpParser\Node $node) {
        if ($node instanceof PhpParser\Node\Arg && $node->byRef) {
            // throw error
        }
    }
}
```

**Comment by SundialServices** [comment]
Sorry to have been late to reply to this:  _"Perfect!  Thank you so much!"_
