### ISSUE TITLE
Breaks between 2.x and 3.x

### ISSUE THREAD

**Issue by GrahamCampbell** [nikic/PHP-Parser#326]
The names of functions defined in a file without a namespace now implement "FullyQualified", however they didn't before in 2.x.

When traversing the nodes of:

```php
<?php

return [env('123')];
```

in 2.x, no nodes are "fully qualified", but in 3.x, the name node for the function "env" is.

In:

```php
<?php namespace Foo;

return [env('123')];
```

this is not a problem.

**Comment by GrahamCampbell** [comment]
On further inspection, it seems the break lies in "PhpParser\NodeVisitor\NameResolver", where on 2.x, this doesn't resolve functions calls, but on 3.x, it does.

**Comment by nikic** [comment]
Yes, this is an intentional change, it needs to be added to UPGRADING. Previously, unqualified function calls in the global namespace were not resolved, now they are. This is consistent with the behavior for classes, and makes it easy to distinguish whether or not a name requires runtime resolution (without having to manually track the namespace).

**Comment by nikic** [comment]
Upgrading note added: https://github.com/nikic/PHP-Parser/commit/8a97065e300cd5d5fdc4c3c058ac9feec5c2f48b

If this change is causing issues for your use-case (outside of tests), please reopen.

**Comment by GrahamCampbell** [comment]
Ah right, I see the commit now: https://github.com/nikic/PHP-Parser/commit/90834bff8eaf7b7f893253f312e73d8f532341ca.

This change is breaking, though, I can work around it without a massive fuss. I'll just now need to check the type of the node with `getType` instead of just assuming it was what I wanted.

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Comment by GrahamCampbell** [comment]
Oh, dear, but `getType` just returns `Name_FullyQualified` of course. I guess I really need to look for the actual nodes instead of just their fully qualified child that gets appended.
