### ISSUE TITLE
NameResolver should save original name

### ISSUE THREAD

**Issue by felixfbecker** [nikic/PHP-Parser#330]
When doing a find-all-references for a namespace, I only want to return nodes that actually explicitly reference the namespace by its name - that is either a qualified class name or a `use` for the namespace.
Currently this is not possible when using the `NameResolver`, because it will rewrite all names to fully qualified ones and the original name is lost. It would be nice to have an `originalName` attribute added.

**Comment by nikic** [comment]
Resolved by #331.
