### ISSUE TITLE
Do we need the test_old folder anymore?

### ISSUE THREAD

**Issue by phpguru** [nikic/PHP-Parser#333]
The files in the test_old folder came up in a routine security scan; eg

`echo $file, ":\n    Parse of pretty print failed with message: {$e->getMessage()}\n";`

If you'd like a PR to remove this folder, I'd be happy to provide one.

**Comment by nikic** [comment]
Yeah, test_old is still in use. This test runner makes sure we can parse all files in the PHP testsuite. It might be good to rename it to something else, but it definitely shouldn't be dropped :)

**Comment by phpguru** [comment]
Gotcha, fair enough. We'll just add the folder to the list of directories we delete before pushing to production.
