### ISSUE TITLE
Attributes not dumped with JSON encoding

### ISSUE THREAD

**Issue by onet4** [nikic/PHP-Parser#334]
Hi there,

According to this [documentation](https://github.com/nikic/PHP-Parser/blob/master/doc/3_Other_node_tree_representations.markdown#json-encoding),
> This will result in the following output (which includes attributes):

It does not include attributes when I try it. I used the exact code written there. What I get is the following.

```json
[
    {
        "byRef": false,
        "name": "printLine",
        "params": [
            {
                "type": null,
                "byRef": false,
                "variadic": false,
                "name": "msg",
                "default": null
            }
        ],
        "returnType": null,
        "stmts": [
            {
                "exprs": [
                    {
                        "name": "msg"
                    },
                    {
                        "value": "\n"
                    }
                ]
            }
        ]
    },
    {
        "name": {
            "parts": [
                "printLine"
            ]
        },
        "args": [
            {
                "value": {
                    "value": "Hello World!!!"
                },
                "byRef": false,
                "unpack": false
            }
        ]
    }
]
```

**Comment by nikic** [comment]
Which version of PHP-Parser are you using? JSON serialization is supported as of version 3.0. As your output is missing not only attributes but also nodeType, I'd guess that you're using an older version.

**Comment by onet4** [comment]
You are right. Not sure why but I was using v2.1.1. Installed v3.0.2 and now attributes are included.

Thank you.
