### ISSUE TITLE
Possible to convert PHP code into Javascript?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [nikic/PHP-Parser#337]
Hello @nikic 

I like this library! Thanks for building it. 

I am trying to write a system which could transform PHP code into JS code. Given the similarities in language syntax, I believe this should be possible (though not completely). 

For starting off, I am trying to create a `Js` PrettyPrinter which prints different syntax (like replace `echo` with `console.log`, using `+` instead of `.` for concatenation). But I am sure that this is not the level I can be working on. There are other problems which cannot be solved at this level (the outputting level). Like, the way PHP treats classes and the way JS does that are different. The way Closures carry their environment in JS vs how we have to import the variables in PHP for the same. But there are of course a lot of similarities and I believe this is achievable to some extent. 

What do you suggest I need to look into? (Theoretically and Within the code). I have not gone through a compiler design course yet. Should I look into that first?

**Comment by Potherca** [comment]
You might want to take a look at a similar project: https://github.com/tito10047/PHP-to-Javascript (also uses`nikic/PHP-Parser`).

**Comment by vaibhav-kaushal** [comment]
@Potherca Lovely! I think I would give it a good read :)
