### ISSUE TITLE
 Add a "vendor" top level namespace

### ISSUE THREAD

**Issue by remicollet** [nikic/PHP-Parser#341]
From http://www.php-fig.org/psr/psr-4/

> The fully qualified class name MUST have a top-level namespace name, also known as a “vendor namespace”.

Ok, you can say "PhpParser" is the vendor... a way to circumvent PSR-4 (as the project SubNamespaceName is not mandatory.. one reason why I dislike this PSR). And PhpParser could be a bit too generic and may create conflict.

Al least, it conflicts with https://github.com/Microsoft/tolerant-php-parser

Proposal: use Nikic\PhpParser

I understand this is only doable as part of a new major version, because of BC break.

**Comment by remicollet** [comment]
See https://github.com/Microsoft/tolerant-php-parser/issues/35

**Comment by nikic** [comment]
It should have used a vendor namespace from the start, but I'm not going to change it at this point.
