### ISSUE TITLE
Is PhpParser\NodeTraverser::DONT_TRAVERSE_CHILDREN ever returned?

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#343]
I think this is dead code: https://github.com/nikic/PHP-Parser/blob/a46b3099758ac75fbbaa9e33a3716267ffb0d48d/lib/PhpParser/NodeTraverser.php#L93

As `enterNode` can only return a `null` or `Node`. Happy to be wrong!

**Comment by muglug** [comment]
Looks like you added this possibility in https://github.com/nikic/PHP-Parser/issues/161#issue-53023834 – but it would be great if you could update the interface's return type (maybe with a note?).

**Comment by nikic** [comment]
Right, "int" should be a valid return type here as well.

**Comment by nikic** [comment]
Doc comments updated in https://github.com/nikic/PHP-Parser/commit/70f86cb6cb59a3d63c41bd5785797ebc6f3790aa.
