### ISSUE TITLE
Pretty printing of hierarchies with error nodes

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#345]
Hello

I recently encountered the situation where I'm pretty printing a node that happened to have one of the new `Error` nodes in its structure. The code then halted with the error message `Call to undefined method PhpParser\PrettyPrinter\Standard::pExpr_Error()`.

I'm posting this here because this is an actual undefined function error (I'd have expected an exception or something at the least, rather than an error).

Apart from this, I wanted to hear your thoughts on this situation; is the pretty printer supposed to or will it support skipping error nodes or is the caller expected to just not try to print node hierarchies with errors in them (i.e. trying to will throw an exception)?

Thanks in advance

**Comment by nikic** [comment]
Good question, not sure whether this should just throw or print something. I guess if we print it would just be an empty string. What is the use-case for pretty printing a syntactically invalid file?

**Comment by Gert-dev** [comment]
I'm quite honestly not sure. I'm (ab)using the pretty printer as a sneaky way to check if two node hierarchies represent the same code by converting them to a string, so I don't really have a need for pretty printing a syntactically invalid file. Because of this, I'm happy with whichever approach you decide to take, as for my use case, it won't cause anything to break nor gain any functionality :-).

**Comment by nikic** [comment]
Exception added in https://github.com/nikic/PHP-Parser/commit/fd7ac251084746a24cbcbb66bd5d9d49c9e7cee2. I went with the exception as the conservative option, but if a use-case comes up we can change this to print something.
