### ISSUE TITLE
elseif/else if not working properly

### ISSUE THREAD

**Issue by Kilgaloon** [nikic/PHP-Parser#347]
Parser does not recognize `else if` as `elseif` statement, instead it recognize it as `else` statement. Both statements `elseif` and `else if` are valid by php syntax but parser doesn't recognize it.

**Comment by nikic** [comment]
`else if` is an `else` followed by an `if`:

```php
if ($x) { $y; }
else if ($z) { $u; }

// Equivalent to
if ($x) { $y; }
else { if ($z) { $u; } }
```

The parser recognizes it as such.
