### ISSUE TITLE
Comments inside arrays are dropped by Standard pretty printer

### ISSUE THREAD

**Issue by jhodgdon-drp** [nikic/PHP-Parser#351]
If you have some code like
```
array(
  'foo' => 'bar',
  // Comment here.
  'baz' => 7,
);
```
(or similar with [] array shorthand), and you pretty print it, it comes out as one line:
`array('foo' => 'bar', 'baz' => 7);`

So, the comment gets dropped.

I'm making a Pretty Printer class for a project, and the solution I came up with was to output all arrays multi-line instead of in one line, and then each Expr_ArrayItem can print out its comment (which is there in the parser output statements, but dropped currently by the Standard pretty printer).

**Comment by jhodgdon-drp** [comment]
By the way THANK YOU for this project! We had our own parser and pretty printer in our project, and using this library has made our code much cleaner, more understandable, and more maintainable. I'm just going to file a few issues about the Pretty Printer class that I came across... they aren't holding me up though since we needed our own pretty printer class anyway. Thanks!

**Comment by jhodgdon-drp** [comment]
I'll make a pull request with the code I used to accomplish this. Fairly straightforward...

**Comment by nikic** [comment]
This issue and #366 are now resolved by https://github.com/nikic/PHP-Parser/commit/c3cbf079466fad893e576d072c1f9daebfe04f95, which is a conservative version of #355, printing on multiple lines only if it is necessary to preserve comments.

Printing all arrays as multiline is something we could have behind an option (or maybe a callback so one can for example decide based on number of elements?)
