### ISSUE TITLE
PrettyPrinterAbstract::pPrec() should call p() instead of replicating behavior

### ISSUE THREAD

**Issue by jhodgdon-drp** [nikic/PHP-Parser#354]
In extending the PrettyPrinter class, I had a need to override the basic p() function from the PrettyPrinterAbstract class.

I found that I also needed to override the pPrec() function, because (perhaps for efficiency?) it does its own version of the code in p() rather than directly calling p(). This was a bit annoying... It would make it easier for people to make their own PrettyPrinter classes if everything went through p() itself.

I'll make a pull request for this one...

**Comment by jhodgdon-drp** [comment]
Oh, never mind! It looks like this has already been fixed in the latest development code:
```
{
                return '(' . $this->p($node) . ')';
            }
        }
        return $this->p($node);
```

Sorry about the duplicate issue! I used composer to download and probably got the latest release instead of the development version.

**Comment by jhodgdon-drp** [comment]
Well. It is fixed in the "master" branch but not in the 3.x branch. Perhaps I will reopen it?

**Comment by muglug** [comment]
If it's fixed in master, isn't it just fixed, period? Even though there isn't a release that includes that fix.

**Comment by nikic** [comment]
The master branch is still a couple of months away from a stable release, so backporting minor changes like this to 3.x makes sense.

**Comment by jhodgdon-drp** [comment]
I'm not familiar with your branch strategy in this project, so I'll leave it to you to decide to leave this open or not, and whether or not to port this change to the 3.x branch. Anyway, it isn't standing in my way (I just overrode the pPrec() method in my pretty printer class).

Which is all working very well, thanks to your clear code! It was really easy to figure out what to override, and the structure of the Pretty Print classes is quite clear.

**Comment by nikic** [comment]
Change ported to 3.x via https://github.com/nikic/PHP-Parser/commit/d18ccfeec7bcfaa832debb6b133d673b8c6dcd7f.
