### ISSUE TITLE
Support request: how do I get a DocBlock when there are no nodes

### ISSUE THREAD

**Issue by mvriel** [nikic/PHP-Parser#36]
Hey @nikic,

I received the following bug report in phpDocumentor/phpDocumentor2: https://github.com/phpDocumentor/phpDocumentor2/issues/604

The reporter indicates that the first DocBlock could not be found when there are no nodes. This is verified behaviour since I try to claim the file-level DocBlock in a NodeVisitor using the beforeTraverse method.

Can you provide me with a clue what the best way would be to still obtain the first DocComment in a file using PHP-Parser? (if PHP-Parser supports that)

**Comment by mfn** [comment]
Ran into this today too.

All docblocks/comments get accumulated to the next node found or dropped if none.

This makes it really inconvenient to use the same visitor/parser concept for a mixed tree where some files have docblocks without comments, etc.

I wish there was a mode where docblock/comments where just emmited as individual nodes like anything else.

**Comment by nikic** [comment]
Commit https://github.com/nikic/PHP-Parser/commit/7eac2cfd8bf9b06387a824ebcae9133364f37896 adds a Nop statement if there any trailing comments in a statement list. This should also include the case of the original report.

I've create a separate issue for the duplicate comment assignment (https://github.com/nikic/PHP-Parser/issues/253), so we can close this issue at last :)

**Comment by mvriel** [comment]
Thanks @nikic! I had missed the addition of the NOP statement so that should enable me to introduce file-level docblocks. Thanks!

**Comment by nikic** [comment]
@mvriel You didn't miss anything, I've only added them yesterday ;) The date info on that commit is off, because I rebased it off an older branch.
