### ISSUE TITLE
Autoload Failure

### ISSUE THREAD

**Issue by Silic0nS0ldier** [nikic/PHP-Parser#365]
Had a random failure of entire site for 10 min. This was in the error log.

```
[07-Mar-2017 04:15:14 UTC] PHP Fatal error:  require(): Failed opening required 'C:\iis_sites\digitool.com.au\app\vendor\nikic/PhpParser/Autoloader.php' (include_path='.;C:\php\pear') in C:\iis_sites\digitool.com.au\app\vendor\nikic\php-parser on line 4
```

Upon investigation, it appears as though on [this line](https://github.com/nikic/PHP-Parser/blob/a7120116b0931e72004b77bca962f4824f548dd0/lib/bootstrap.php#L4) the wrong directory was retrieved via `__DIR__`.

Alex over at UF recommended I let everyone here know, just in case you know anything about it. I'm thinking it was just luck of the draw in terms of this library being subject to the error. Either way, no harm is asking right?

Environment
----
Windows Server 2016
PHP 7.1.2
PHP-Parser version 1.4.2-dev (installed via composer)

**Comment by nikic** [comment]
As you already noted, I don't think this is related to this library. Though I'm also not aware of any specific PHP bugs that would cause `__DIR__` to return an incorrect value (apart from one that is just outdated due to the realpath cache).
