### ISSUE TITLE
Inline comments in between function call arguments are stripped by the printer

### ISSUE THREAD

**Issue by vovafeldman** [nikic/PHP-Parser#366]
We are using the parser for parsing WordPress plugins & themes. WordPress comes with a localization system that can get comment-like hints for translators. When the comments are added within the call arguments, the printer strip out those comments:
```php
return sprintf(
	/* translators: %s: Post type singular name */
	__( '%s Author', 'elementor-post-pack' ),
	$post_type_object->labels->singular_name
);
```

Any help would be appreciated. Thanks!

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/PHP-Parser/commit/c3cbf079466fad893e576d072c1f9daebfe04f95.
