### ISSUE TITLE
Get previous nodes

### ISSUE THREAD

**Issue by borNfreee** [nikic/PHP-Parser#369]
Hi,

what is the recommended and possible way to get the previous X Node?

Example:

```php
function someFunc($delta): bool
{
    if ($delta === 0) {
        return true;
    }

    // other logic

    return $delta < 0;
}
```
Why I need this:

I'm trying to mutate the code and change `<` (`Node\Expr\BinaryOp\Smaller`) on the last line of the function with `<=`. But if the function has early return with `==` or `===` condition before - I don't need to mutate it.

So here I want to walk to the begining of the function and check all the conditions with `$delta` variable. Is it feasible?

The only one way I found is to use something like this (https://github.com/nikic/PHP-Parser/pull/17 5 years old).

Thank you.

UPD: also found another related solutions: https://github.com/nikic/PHP-Parser/issues/238

Anyway, I'm looking forward to your comments and I think it worth to add the info about getting relations of nodes to the documentation because there were many issues/questions about it.

**Comment by borNfreee** [comment]
Solution is to use (with modifications) code from #238 that adds parent relations for each node:

```php
class ParentConnectorVisitor extends NodeVisitorAbstract
{
    const PARENT_KEY = 'parent';

    private $stack;

    public function beforeTraverse(array $nodes)
    {
        $this->stack = [];
    }

    public function enterNode(Node $node)
    {
        if (! empty($this->stack)) {
            $node->setAttribute(self::PARENT_KEY, $this->stack[count($this->stack) - 1]);
        }

        $this->stack[] = $node;
    }

    public function leaveNode(Node $node)
    {
        array_pop($this->stack);
    }
}
```

**Comment by nikic** [comment]
Just created a FAQ section in the docs and added this: https://github.com/nikic/PHP-Parser/blob/master/doc/5_FAQ.markdown#how-can-the-parent-of-a-node-be-obtained

**Comment by TomasVotruba** [comment]
@nikic Thank you!
