### ISSUE TITLE
What are these in call parser? 

### ISSUE THREAD

**Issue by Rivendall** [nikic/PHP-Parser#370]
Hello. 
After use php parser in any application, some one write these code: 
```
	$visitor = new MyVisitor() ;
	$parser = new PhpParser\Parser(new PhpParser\Lexer\Emulative) ;
	$traverser = new PhpParser\NodeTraverser ;
```
What are the meaning of them?  (any line)
Thank you.

**Comment by nikic** [comment]
Sorry, I don't understand the question.

**Comment by Rivendall** [comment]
For example this line 
$parser = new PhpParser\Parser(new PhpParser\Lexer\Emulative) ;
means create new instance of parser. is it? 
what about other line in this code.
