### ISSUE TITLE
Parse issue with function call inside curly brace under PHP 5.4

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#371]
Using v2.1.1, this is valid syntax (I think):

```php
var_dump("${date('Y')}");
```

But parsing [fails under PHP 5.4](https://travis-ci.org/vimeo/psalm/jobs/215598524) with
```
Syntax error, unexpected '(', expecting '[' or '}' on line 2
```

Works as expected on PHP 5.6 and PHP 7.

**Comment by nikic** [comment]
PHP <= 5.5 had a lexer bug, which prevents this from working: https://3v4l.org/X9G17 Of course, this is something that can be emulated in `Lexer\Emulative`. However, PHP-Parser 2.x (which is the last version that has PHP 5.4 support) is no longer maintained.

**Comment by muglug** [comment]
Thanks!
