### ISSUE TITLE
Class constant misspelled

### ISSUE THREAD

**Issue by g0morra** [nikic/PHP-Parser#374]
I think there is a typo in the name of this class constant:

`PhpParser\Node\Stmt\Class_::VISIBILITY_MODIFER_MASK`

should be

`::VISIBILITY_MODIFIER_MASK`

i.e. with an extra `I` in `MODIFIER`.

This constant is useful for bitwise operations against the other `Class_::MODIFIER_*` values if you want to check or alter the visibility of several node types, so it would be nice to avoid the misspelling propagating.

**Comment by nikic** [comment]
Fixed in https://github.com/nikic/PHP-Parser/commit/901b895c023769ab6d8a25bf35c61c1aa2e52aa7.
