### ISSUE TITLE
Php tag node?

### ISSUE THREAD

**Issue by DragorWW** [nikic/PHP-Parser#377]
how to get Node of type `PhpTag`

example:
```php
$code = '<?= "df"; ?>'
```
I expect to see
```json
[
   {
      "nodeType":"PhpTag",
      "props": {
           "shorTag": false
      },
      "exprs":[
         {
            "nodeType":"Stmt_Echo",
            "exprs":[
               {
                  "nodeType":"Scalar_String",
                  "value":"df",
                  "attributes":{
                     "startLine":1,
                     "endLine":1,
                     "kind":2
                  }
               }
            ]
         }
      ]
   }
]
```

after parse code i see
```php
$code = '<?= "df"; ?>';
$code2 = ''<?php echo "df"; ?>';
```
```json
[
    {
        "nodeType": "Stmt_Echo",
        "exprs": [
            {
                "nodeType": "Scalar_String",
                "value": "df",
                "attributes": {
                    "startLine": 1,
                    "endLine": 1,
                    "kind": 2
                }
            }
        ]
    }
]
```

**Comment by nikic** [comment]
PHP-Parser uses an abstract syntax tree, which hides details of representation. `<?php echo` and `<?=` are the same to PHP, so they are represented the same.

It is possible to distinguish them in two ways: Either enabling the token positions in the [lexer options](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#lexer-options) and then checking whether the token at tokenStartPos is a T_OPEN_TAG_WITH_ECHO, or by adding a [custom attribute](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#attribute-handling) in the lexer.
