### ISSUE TITLE
Proposal: add to ClassMethod checking on magic method

### ISSUE THREAD

**Issue by DragorWW** [nikic/PHP-Parser#378]
Proposal: 
- add a method for checking if this method - [magic method](http://php.net/manual/en/language.oop5.magic.php)

**Node\Stmt\ClassMethod**
- isMagic(): bool

_Thanks for this project, @nikic. Do you mind, if I will suggesting improvements to the api?_

**Comment by nikic** [comment]
I'm fine with adding a toMagic() method. Do you plan to PR this?

**Comment by DragorWW** [comment]
@nikic yes, i will can create PR for this functional.
