### ISSUE TITLE
PHP error in ClassMethod node due to return type hint (latest master)

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#386]
Hello

When using `getStmts()` on a `ClassMethod` node, a PHP error occurs in the latest master because the return type hint requires an `array` to be returned and the method may also return `null`. This only seems to happen when the method does not have a body (such as for interface methods or abstarct methods), for example:

```php
<?php

interface I
{
    public function foo();
}
```

I realize that the latest master is still mostly in development, but I figured I'd report this corner case since it doesn't show up when simply parsing and might otherwise go unnoticed.

Thanks in advance

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/PHP-Parser/commit/73dc35cbbd8dd464cedbe83b9cd9c6e1d1ebf144. Thanks for catching this!
