### ISSUE TITLE
Fatal error: Maximum function nesting level of '250' reached

### ISSUE THREAD

**Issue by ktdocker90** [nikic/PHP-Parser#388]
when load complex php file, i got error for print output:
Fatal error: Maximum function nesting level of '250' reached, aborting! in nikic\php-parser\lib\PhpParser\NodeAbstract.php on line 24

![error](https://cloud.githubusercontent.com/assets/17218942/25939028/a08875dc-365b-11e7-8a54-6202167a10af.jpg)

**Comment by nikic** [comment]
Please either increase your maximum nesting level or, preferably, disable XDebug entirely. See: https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#bootstrapping.

**Comment by ktdocker90** [comment]
thanks
