### ISSUE TITLE
Replace Array variable with string

### ISSUE THREAD

**Issue by ewezali** [nikic/PHP-Parser#389]
hello,
i have an issue for replacing node expression with another.
here the PHP code:

`$result = $this->db->query($stm, $table['room']);`

i want to change variable `$table['room']` to string literal like '1'.
i tried use visitor to change that variable, but didn't work.
```
use PhpParser\Node;
use PhpParser\Node\Stmt;
use PhpParser\NodeTraverser;

class VisitorUndefinedVariable extends \PhpParser\NodeVisitorAbstract
{
    public function leaveNode(Node $node) {
    	if ($node instanceof Node\Expr\ArrayDimFetch) {
            if ($node->var->name == $_SESSION['undefine_variable']) {
            	  return new Node\Scalar\String_("1");
            }
        }
    }
}
```

and i tried to remove `$table['room']` variable from code with this following Visitor, but it did not work. raise error "Uncaught LogicException: leaveNode() returned invalid value of type integer"

```
use PhpParser\Node;
use PhpParser\Node\Stmt;
use PhpParser\NodeTraverser;

class VisitorUndefinedVariable extends \PhpParser\NodeVisitorAbstract
{
    public function leaveNode(Node $node) {
    	if ($node instanceof Node\Expr\ArrayDimFetch) {
            if ($node->var->name == $_SESSION['undefine_variable']) {
            	  return NodeTraverser::REMOVE_NODE;
            }
        }
    }
}
```

am i miss something?
thanks.

**Comment by nikic** [comment]
Your first code looks right to me. I would assume that the issue is somewhere else, e.g. that you're not passing the modified AST to the pretty printer, or similar. The second code does not work because you can only remove nodes from arrays. In this case you're trying to remove a part of an Arg node. Instead you have to remove the surrounding Arg node.
