### ISSUE TITLE
Assignment by reference with null coalesce seems incorrect

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#392]
With PhpParser 3.0.4, a user reported an issue here: https://github.com/vimeo/psalm/issues/172

I assume
```php
$ref =& $_GET["name"] ?? null;
```
would by grouped as

```php
AssignRef($ref, NullCoalesce($_GET["name"], null));
```
but instead it's getting grouped as
```php
NullCoalesce($ref, AssignRef($_GET["name"], null));
```
which to me suggests the code
```php
($ref =& $_GET["name"]) ?? null;
```
which would result in very different evaluation.

**Comment by muglug** [comment]
I think the functionally-equivalent code to the above line is:

```php
if (isset($_GET["name"])) {
    $ref =& $_GET["name"];
} else {
    $ref = null;
}
```

**Comment by nikic** [comment]
The result is correct: The RHS of `=&` must be a variable, and null-coalesce is not a variable. Same as `!$foo = $bar` being `!($foo = $bar)` instead of `(!$foo) = $bar`, even though it goes against precedence.

**Comment by muglug** [comment]
Ah thanks!
