### ISSUE TITLE
Question: get class name from PhpParser\Node\Expr\Variable

### ISSUE THREAD

**Issue by spidgorny** [nikic/PHP-Parser#393]
Hi,

I'm using MyNodeVisitor to track **function** calls. When trying to track **method** calls I'm not able to get the class name for the variable, it seems.

```php
if ($node instanceof Node\Expr\MethodCall) {
	echo TAB, $node->var->name, '->', $node->name, '()', PHP_EOL;
	// $node->var->className ?
}
```
Is there any workaround?

In case of ```$this->method()``` I could catch and store the current class name in the Visitor and refer to it. But if variable is not ```$this``` like ```$doc->createElement()``` then what is the class for ```$doc```?

**Comment by nikic** [comment]
It's not possible to get this kind of information using this library alone. Determining the type of a variable requires some form of type inference, which is something that has been implemented by a number of static analyzers on top of PHP-Parser in various ways. Two that come to mind are [psalm](https://github.com/vimeo/psalm) and [phpstan](https://github.com/phpstan/phpstan), though there are more than that. Unfortunately I'm not aware of a library that *only* provides type inference.

**Comment by muglug** [comment]
@spidgorny you can use a plugin with Psalm after it does type inference to extract the information you need, but you may also want to check out Psalm's source code and adapt it to your own ends.
