### ISSUE TITLE
Deprecated Name->parts

### ISSUE THREAD

**Issue by theofidry** [nikic/PHP-Parser#397]
```php
namespace PhpParser\Node;

use PhpParser\NodeAbstract;

class Name extends NodeAbstract
{
   /**
     * @var string[] Parts of the name
     * @deprecated Avoid directly accessing $parts, use methods instead.
     */
    public $parts;

    //...
}
```

However if you want to calculate the number of parts the name has you have no choice but to do:

```php
count($node->parts)
```

Which requires access to the deprecated  `parts` property. Should we make `Name` implement `Countable`?

**Comment by nikic** [comment]
What do you use the number of parts for?

**Comment by theofidry** [comment]
To prefix it: https://github.com/humbug/php-scoper/blob/master/src/NodeVisitor/IgnoreNamespaceScoperNodeVisitor.php#L32

**Comment by theofidry** [comment]
Maybe to expand a bit more. The library is about prefixing the namespace to isolate the code, mostly in the context of a PHAR to avoid any issue when it executes people's code. We however avoid to touch things from the global namespace (internal code or third-party code alike) so we need to count the number of elements the name to know if we should prefix that one or not.

**Comment by nikic** [comment]
I've dropped the deprecation. The original plan to drop this in favor of a string didn't go anywhere, so we can just keep it around for now.

**Comment by theofidry** [comment]
👌
