### ISSUE TITLE
Can us put the plain text code in method ?

### ISSUE THREAD

**Issue by fherryfherry** [nikic/PHP-Parser#398]
Hi, I've read Code Generation doc, but I did not find sure answer to put the plain text code in the method. 
For example I've code template like bellow:
```
<?php namespace Foo\Bar;
use FooUse;
class FooClass {

public function myMethod() {
--> PUT CODE HERE <--
}

}
```
Actually, I just want to insert the code in the method. 
I've form textarea to edit the myMethod code, then POST to insert at the method above. It's why I want to insert the plain text code instead of making a manual with code generation for myMethod content.

Hope you can help for the solution? thanks

**Comment by krageon** [comment]
You could transform your POSTed code using a `Parser` instance, and subsequently put that into the stmts that belong to that `Method`. If you then print your AST, you should see whatever you typed into that box inside the function (assuming it was parseable).

**Comment by nikic** [comment]
As said by @krageon, the way to do this is to parse the code and add it to the AST in the place you want. There's no way to directly insert code as text.

If you really want to avoid the round-trip through the parser, then I think the cleanest way would be to define a custom node and implement pass-through printing for it. This should be the necessary code:

```php
class PlainCode extends \PhpParser\Stmt {
   public $code;
   public function __construct($code) { $this->code = $code; }
   public function getType() { return 'Stmt_PlainCode'; }
   public function getSubNodeNames() { return ['code']; }
}

class MyPrettyPrinter extends PhpParser\PrettyPrinter\Standard {
    public function pStmt_PlainCode(PlainCode $node) {
        return $node->code;
        // OR
        return $this->pNoIndent($node->code);
    }
}
```

There are two variants for the implementation of the printer. If you directly return the code it will be indented (which may corrupt multi-line strings for example). If you use `pNoIndent()`, then the code is inserted exactly as is. (All this assuming PHP-Parser 3.x, not master).
