### ISSUE TITLE
PrettyPrinter localizes floats

### ISSUE THREAD

**Issue by bobthecow** [nikic/PHP-Parser#399]
… which isn't super helpful :)

```php
$parser = (new PhpParser\ParserFactory)->create(PhpParser\ParserFactory::ONLY_PHP7);
$printer = new PhpParser\PrettyPrinter\Standard;

// Ensure locale uses `.` for decimal separator
setlocale(LC_NUMERIC, 'en_US');

$stmts = $parser->parse('<?php $a = [1, 2.3];');
echo $printer->prettyPrint($stmts); // $a = [1, 2.3];

// Switch to a locale with `,` as a decimal separator
setlocale(LC_NUMERIC, 'fr_FR');

echo $printer->prettyPrint($stmts); // $a = [1, 2,2999999999999998];
```

See bobthecow/psysh#398

**Comment by nikic** [comment]
I hope `,` is the only case that can happen...

**Comment by bobthecow** [comment]
:) Thanks!

**Comment by bobthecow** [comment]
Per the Unicode CLDR, Persian and Arabic use different a _glyph_ (`٫` instead of `,` as a decimal separator) but I'm not sure if that's what `setlocale` actually spits out, or if it just uses a comma. And I can't test either of those on my machine.

http://www.unicode.org/cldr/charts/28/verify/numbers/fa.html
http://www.unicode.org/cldr/charts/28/verify/numbers/ar.html
