### ISSUE TITLE
Format-preserving bug for multipes NodeVisitors

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#400]
With format-perserving printer [#344] I came across weird bug.

I have 2 visitor modifying the code:

- [InjectAnnotationToConstructorNodeVisitor](https://github.com/TomasVotruba/Rector/blob/new-rector-named-services/src/NodeVisitor/DependencyInjection/InjectAnnotationToConstructorNodeVisitor.php)
- and [NamedServicesToConstructorNodeVistitor](https://github.com/TomasVotruba/Rector/tree/new-rector-named-services/src/NodeVisitor/DependencyInjection/NamedServicesToConstructor)

This is error output from [Travis Report](https://travis-ci.org/TomasVotruba/Rector/builds/255741707#L547):

- I make property private - doesn't work :-1: 
- I add argument to constructor - works :+1: 
- I add assignment in constuctor method - :-1: 
- `declare (strict_types=1);\n` is added instead of it

```bash
-    private $property;\n
+    public $property;\n
     /**\n
      * @var DateTimeInterface\n
      */\n
-    private $otherProperty;\n
+    public $otherProperty;\n
     public function __construct(stdClass $property, DateTimeInterface $otherProperty)\n
     {\n
-        $this->property = $property;\n
-        $this->otherProperty = $otherProperty;\n
+        declare (strict_types=1);\n
+        declare (strict_types=1);\n
     }\n
 }\n
```

```php
return $this->codeStyledPrinter->printToString($newStmts, $oldStmts, $oldTokens);
```

This would be understandable from some point, but...

### But when I switch first 2 arguments, this NodeVisitor works but the other doesn't.

```php
return $this->codeStyledPrinter->printToString($oldStmts, $newStmts, $oldTokens);
```

In this case, [`afterTraverse()`](https://github.com/TomasVotruba/Rector/blob/5120451ee558d1ae8d9518392075c4d41928825d/src/NodeVisitor/DependencyInjection/NamedServicesToConstructor/AddPropertiesToClassNodeVisitor.php#L42-L56) isn't taken into account.

```bash
 class ClassWithNamedService extends Controller\n
 {\n
-    /**\n
-     * @var stdClass\n
-     */\n
-    private $stdClass;\n
-    public function __construct(stdClass $stdClass)\n
-    {\n
-        $this->stdClass = $stdClass;\n
-    }\n
     public function render()\n
     {\n
         $this->stdClass->render();\n
     }\n
 }\n
```

**Comment by TomasVotruba** [comment]
I used this as hotfix for time being: https://github.com/TomasVotruba/Rector/pull/2/commits/9ab6c8462988fefe7597808dde214ce0eb8fe4cc

**Comment by nikic** [comment]
Where is the CloningVisitor being applied? Unfortunately GH can only search master.

**Comment by TomasVotruba** [comment]
I see.

I use own ApIication for testing, because I don't know how to apply changes on dry-run (without changing actuall content):  https://github.com/TomasVotruba/Rector/blob/9ab6c8462988fefe7597808dde214ce0eb8fe4cc/src/Testing/Application/FileReconstructor.php#L54-L67

Here's the printer: https://github.com/TomasVotruba/Rector/blob/new-rector-named-services/src/Printer/CodeStyledPrinter.php

**Comment by TomasVotruba** [comment]
So it helped me to return new `$node` isntead of null. Resolved :)

**Comment by TomasVotruba** [comment]
Does `CloningVisitor` order matter? 

I tried using it fast and using it last and still there are some issues.

**Comment by nikic** [comment]
@TomasVotruba It should definitely run first. To be on the safe side (especially if enterNode visitors are used), I'd also run it as an independent pass instead of interleaving it with other visitors.

**Comment by TomasVotruba** [comment]
> I'd also run it as an independent pass instead of interleaving it with other visitors.

How to do so? Having 2 NodeTraversers?

At the moment I do it like this:

- NodeTraverser factory: https://github.com/TomasVotruba/Rector/blob/478ce6413824e547bc8d97f0774134f0be82a892/src/NodeTraverser/NodeTraverserFactory.php#L32-L49
- `traverse()` method: https://github.com/TomasVotruba/Rector/blob/478ce6413824e547bc8d97f0774134f0be82a892/src/Testing/Application/FileReconstructor.php#L54-L66

**Comment by TomasVotruba** [comment]
I tried your solution and it works like a charm :champagne: 

```php
$cloningNodeTraverser = new PhpParser\NodeTraverser();
$cloningNodeTraverser->addVisitor(new PhpParser\NodeVisitor\CloningVisitor);

$oldStmts = $this->parser->parse($fileContent);
$oldTokens = $this->lexer->getTokens();
$newStmts  = $cloningNodeTraverser->traverse($oldStmts);
        
$newStmts = $this->nodeTraverser->traverse($newStmts);

$prettyPrinter->printFormatPreserving($newStmts, $oldStmts, $oldTokens);
```

Thank you!
