### ISSUE TITLE
Add constant value

### ISSUE THREAD

**Issue by azurre** [nikic/PHP-Parser#402]
Please make possible to get value of constant

**Comment by nikic** [comment]
The value of a constant is stored inside the `value` of a `Const` node, see https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Const_.php#L14. Or are you looking for something else?

**Comment by azurre** [comment]
Sorry. I mean original value.
Something like this:
```
public function getValue()
    {
        if ($this->value instanceof String_) {
            return $this->value->value;
        } elseif ($this->value instanceof Array_) {
            return $this->value->toArray();
        } elseif ($this->value instanceof LNumber) {
            return $this->value->value;
        } elseif (property_exists($this->value, 'value')) {
            return $this->value->value;
        }
...
}
```

**Comment by nikic** [comment]
This is not entirely simple, because constants can also contain constant expressions. They may also reference other constants. Essentially this requires a full constant expression evaluator. You can find an existing implementation in BetterReflection: https://github.com/Roave/BetterReflection/blob/master/src/NodeCompiler/CompileNodeToValue.php

I do think that integrating something like this in PHP-Parser would be good though.

**Comment by nikic** [comment]
A constant expression evaluator has been added in https://github.com/nikic/PHP-Parser/commit/4b1d9667afdcf8a526e38955dd33def4d75c72d1. A basic usage would be something like this:

```php
$evaluator = new ConstExprEvaluator();
try {
    $value = $evaluator->evaluate($expr);
} catch (ConstExprEvaluationException $e) {
    // Cannot evaluate
}
```

A more advanced usage would also have to provide a fallback evaluator to deal with constant lookup and similar, but this can't be handled generically.

May also be of interest for @Ocramius, though this is 4.0 so not directly usable yet.

**Comment by Ocramius** [comment]
@nikic for now, we have https://github.com/Roave/BetterReflection/blob/d32bda49401cc3ba426a48f40952335aa6797da1/src/NodeCompiler/CompileNodeToValue.php, which recursively resolves constants, given a context. Unsure if this is applicable there too :-\
