### ISSUE TITLE
How to add token with space before it using original Node? 

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#414]
I traverse a code and when I find `methodToBeReplaced()`, I replace it with `newMethod()` by returning node:

```php
public function enterNode($node)
{  
    // if "methodToBeReplaced" method...
    return new MethodCall($node->var, 'newMethod');
}
```

So the code changes from

```php
$class->addMethod()
    ->methodToBeReplaced();
```

to

```php
$class->addMethod()->newMethod();
```

**But I'd like to keep it the original way:**

```php
$class->addMethod()
    ->newMethod();
```

Is there something I could use form original node like line position and pass it to new one?

Thank you

**Comment by nikic** [comment]
Can you replace just the name of the method call? `$call->name = new Identifier('newMethod')` should do it.

**Comment by TomasVotruba** [comment]
That was one idea. But I need to replace `$args` as well and in the future maybe more.

Can try it for now though as good enough solution. Is there any other way I could use?

**Comment by nikic** [comment]
You need to create an `Identifier` node for the name, it's not a plain string (anymore).

Another way that should also work is to copy the `originalNode` attribute from the node you're replacing.

**Comment by TomasVotruba** [comment]
So this helped: https://github.com/TomasVotruba/Rector/pull/28/commits/4e95278f0ab31917b59665fad0e4aa677090c4a1?diff=unified#diff-7f70f2c8f0d3e0388b0d4b3774c8a969R78

Do you think that's ok solution?

**Comment by nikic** [comment]
Yeah, looks right to me.

**Comment by TomasVotruba** [comment]
Allright, thanks :+1:
