### ISSUE TITLE
Add an attribute to the namespace to distinguish `namespace; stmt;` from `namespace {stmt;}`

### ISSUE THREAD

**Issue by TysonAndre** [nikic/PHP-Parser#417]
(e.g. `getAttribute('namespaceHasBracket') : bool`

This will help people writing code pretty printers, visualizers, transformers, etc

Mentioned in https://github.com/TysonAndre/php-parser-to-php-ast/issues/10

**Comment by nikic** [comment]
Attribute added in https://github.com/nikic/PHP-Parser/commit/5a9fbca54a5edba0be673b85f0bc824caddb6567. I'm using `kind` following a convention used by a number of other nodes.
