### ISSUE TITLE
File offsets for comments (docblocks)

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#419]
Perhaps this has been asked before (I did a quick skim through the issues, but couldn't find anything), but is it possible to fetch the start offset of docblocks for nodes? My use case is that sometimes it would be interesting to track the location of types inside docblocks, e.g. after `@var` statements for various reasons, such as underlining it when it mismatches the actual type. Currently, however, there seems to be no way to access the positions as the docblocks aren't actual nodes.

**Comment by nikic** [comment]
Unless I'm misunderstanding something, isn't this what `Comment::getFilePos()` provides? https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Comment.php#L47

**Comment by Gert-dev** [comment]
Ugh, you are right. I see now I even used it before. Don't know where I got the idea that this wasn't possible. Apologies!
