### ISSUE TITLE
PrettyPrinterAbstract ignores removed comment for `Class_`

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#420]
When I try to remove annotations via:

```php
/** @var $class Class_ */
$class->setAttribute('comment', null);
// or
$doc = new Doc($docBlock->getContent());
$class->setDocComment($doc);
```

it doesn't work. **It works for properties though.**

It looks like it's relaled to `PrettyPrinterAbstract`:

https://github.com/nikic/PHP-Parser/blob/403a7c5315beffd269cd4a31ce9307a60d7c8ad6/lib/PhpParser/PrettyPrinterAbstract.php#L680

Not sure how/why.

Let me know if you need more details.

**Comment by nikic** [comment]
The format-preserving printer currently does not detect changes to comments. This is one of the open issues. Properties probably work because it falls back to the normal pretty printer for some other reason.

**Comment by TomasVotruba** [comment]
Thanks for fast reply, I got confused with this.

Do you have any idea how to make this work?

**Comment by nikic** [comment]
As a temporary workaround, you can force a fallback on the *parent* of the node you're changing (e.g. by doing a `$parent->removeAttribute('originalNode')`.

**Comment by TomasVotruba** [comment]
```php 
/** @var Node $parentNode */
$parentNode = $node->getAttribute('parentNode');
$parentNode->removeAttribute('originalNode');
```

`removeAttribute` method doesn't exist, so I tried:

```php
$parentNode->setAttribute('originalNode', null);
```

with no effect

**Comment by nikic** [comment]
Does it work if you try it on the node itself instead of the parent?

**Comment by TomasVotruba** [comment]
I've tried with no success

```php
$node->setAttribute('parentNode', null);
```

**Comment by nikic** [comment]
Did you use `$node->setAttribute('parentNode', null)` or `$node->setAttribute('originalNode', null)`?

**Comment by TomasVotruba** [comment]
Sorry, I used only `parentNode` before.
Now I tried both, yet still remembers it: https://github.com/RectorPHP/Rector/pull/55/commits/d0786f30b4bb2318ae9374174dbacda3cfd7e3b0

**Comment by nikic** [comment]
@TomasVotruba Your last Travis build has

```
+/**\n
+ */\n
```

as the diff. Isn't this the expected output with your current code? After all you're not removing the comment entirely, you're setting it to an empty doc comment.

**Comment by TomasVotruba** [comment]
You're right. I forgot to check for this empty doc block.
Thank you, it works as I need.

This is the final solution:
https://github.com/RectorPHP/Rector/pull/55/files#diff-50bfb8728bc07dc135b0b34ad748425fR91

**Comment by nikic** [comment]
I've added a check in the pretty printer in (https://github.com/nikic/PHP-Parser/commit/f6cc85a7969795d983a758a7a20ee846406bb99a), so the workaround should no longer be necessary. This a temporary fix before a full solution can be implemented.

**Comment by TomasVotruba** [comment]
It works, so I removed the workaround: https://github.com/RectorPHP/Rector/commit/0a621fecf9e43582a0559ddb83caa6c96ad06087

Thank you :clap
