### ISSUE TITLE
File offsets for function/method bodies

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#421]
Second attempt at requesting something that, hopefully, isn't present yet :-).

Currently it is possible to fetch the first statement inside the function body as well as the parameters of the function. These can be used to have some guidance as to where the function's body starts. Unfortunately, these are not always indicative as there may be a large number of characters (i.e. comments) between the function's parameters or return type and the actual start of the body. The same applies for the first statement inside it, which also isn't always present.

The use case I want to use this for is things such as call tips (signature help, if you like), where you want to know what function the cursor is in. Take the following code:

```php
array_walk([1], function ($item) {
    // Some more code here
});
```

In this situation, you'd want to show information about `array_walk` everywhere between the opening paranthesis and the opening brace of the closure, as well as after the closing paranthesis. In the anonymous function itself, information about `array_walk` is mostly a burden.

For this reason, I was hoping for a way to fetch the start and end position of a function's body, being the location of its opening and closing paranthesis.

**Comment by nikic** [comment]
I don't think this will be natively supported (unless as part of something like #16), but it should not be hard to implement this manually:

```php
function getBodyStartPos(FunctionLike $node, string $code) : int {
    $pos = $node->getStartFilePos();
    if ($params = $node->getParams()) {
        $pos = $params[count($params) - 1]->getEndFilePos();
    }
    return strpos($code, '{', $pos);
}
```

The end position of the parameters is used to account for the unlikely case that `{` occurs in the parameter list, which is legal (`function test($param = "foo"{0})`).

**Comment by Gert-dev** [comment]
That was an idea I had too. However as mentioned, there can be a theoretically infinite number of characters between the end of the parameter list (or even the return type) and the function body:

```php
function foo(string $start): Foo // I have a { here in this comment, which the strpos will match
{

}
```

... one would then need to verify that the curly brace is not inside a comment, whilst the comment may not even be a part of any node and it is unfortunate, since now the application needs to be aware of how the code needs to be parsed and treated.

The proposal in #16 to replace the arrays seems like one I could live with for this, granted that the `startFilePos` and `endFilePos` of that block starts just before (or just after, either is fine) the opening and closing paranthesis and not the actual first statement, which may or may not be present :-).

**Comment by nikic** [comment]
Ah right, forgot about the comments. The way to avoid that would be to use token offsets instead and check for `'{'` in the tokens following the position. Unfortunately this does make the code more complicated, as one has to both track the file position and the token position...

```php
function getBodyStartPos(FunctionLike $node, array $tokens) : int {
    $pos = $node->getStartFilePos();
    $tokenPos = $node->getStartTokenPos();
    if ($params = $node->getParams()) {
        $lastParam = $params[count($params) - 1];
        $pos = $lastParam->getEndFilePos();
        $tokenPos = $lastParam->getEndTokenPos();
    }

    while (true) {
        $token = $tokens[$tokenPos];
        if ($token === '{') break;

        $pos += strlen(\is_string($token) ? $token : $token[1]);
        $tokenPos++;
    }

    return $pos;
}
```

I don't have any better solution to offer though.

**Comment by Gert-dev** [comment]
Thanks for the tip. I'll close this since you've basically given me a decent solution and the other ticket regarding the block statement also represents a solution to this problem. Thanks!
