### ISSUE TITLE
Parser to Builder?

### ISSUE THREAD

**Issue by vmitchell85** [nikic/PHP-Parser#424]
First, Thanks for the great resource you've created!

I'm looking to parse a PHP file, add some new statements, and write it back to disk. Does this library provide a way to achieve this? I was unable to find a way to accomplish this looking through the documentation. The only method I could come up with would be to loop through the AST and build a new file with the factory and inserting items where I need to. I was hoping there was an easier way I've missed or isn't documented.

Thanks for taking the time to read and respond!

**Comment by nikic** [comment]
The relevant documentation should be:

 * https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown: For converting AST to code
 * https://github.com/nikic/PHP-Parser/blob/master/doc/4_Code_generation.markdown: Some helpers for creating new AST nodes (you can also manually create them)
 * https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#node-traversation: If you're modifying an existing AST, you will likely handle the insertion/changes using a node visitor.

**Comment by vmitchell85** [comment]
Yeah @nikic thanks... I was trying to run Builder commands on Parser classes... figured it out...
