### ISSUE TITLE
Adding new nodes probably breaks spacings

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#426]
Hi! 

I'm performing transformating from `Pseudo_Namespace`  to `Namespace` (basically inversion of [your tutorial](https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#example-converting-namespaced-code-to-pseudo-namespaces)).

And I need to add `Namespace_` node in `afterTraverse()` method.

All works fine, node is added on right position. But issue is, all **spaces are wiped**.

In examples:

### Before

```php
<?php declare(strict_types=1);

class PHPUnit_TestCase
{
}
```

### After

```php
<?php

declare(strict_types=1);
namespace PHPUnit; // this line was added!
class TestCase
{
}
```

- **[Here is how I'm adding `Namespace_` token](https://github.com/RectorPHP/Rector/pull/88/files#diff-7459368ad1fa2b748f7b8ce5311e3defR157)**

- [Here is input file](https://github.com/RectorPHP/Rector/blob/56bfd53788e76c26e91cc7e006af008c052e5c86/tests/Rector/Dynamic/PseudoNamespaceToNamespaceRector/wrong/wrong3.php.inc
) 

- [Here is output file](https://github.com/RectorPHP/Rector/blob/56bfd53788e76c26e91cc7e006af008c052e5c86/tests/Rector/Dynamic/PseudoNamespaceToNamespaceRector/correct/correct3.php.inc):

---

- **[Here is expected output file](https://github.com/RectorPHP/Rector/blob/56bfd53788e76c26e91cc7e006af008c052e5c86/tests/Rector/Dynamic/PseudoNamespaceToNamespaceRector/correct/correct3-expected.php.inc)**

- [Here is NodeVisitor performing the transformation](https://github.com/RectorPHP/Rector/blob/56bfd53788e76c26e91cc7e006af008c052e5c86/src/Rector/Dynamic/PseudoNamespaceToNamespaceRector.php)

**Comment by nikic** [comment]
Support for this has been implemented only recently, can you try updating the commit hash in https://github.com/RectorPHP/Rector/blob/master/composer.json#L13? ed8a744c does not yet have it.

**Comment by TomasVotruba** [comment]
Yep, it works, thank you.

I have problems to understand this node nulling.

```php
$node->setAttribute('origNode', null);
```

Sometimes it's needed to make things work. It's too random for me know. Is there any explaning that could help me?

**Comment by nikic** [comment]
@TomasVotruba `$node->setAttribute('origNode', null)` is needed if you explicitly don't want to preserve formatting for a node. Normally it shouldn't be necessary unless you need to work around a bug. In what circumstances do you use it?

**Comment by TomasVotruba** [comment]
There are 6 places at the moment: https://github.com/RectorPHP/Rector/search?utf8=%E2%9C%93&q=-%3EsetAttribute%28Attribute%3A%3AORIGINAL_NODE%2C+null%29&type=

I get this error over and over again, if not used at those places: https://travis-ci.org/RectorPHP/Rector/builds/288741165#L622

![image](https://user-images.githubusercontent.com/924196/31633491-dde9294e-b2c0-11e7-8a1f-abe16426c68b.png)

**Comment by nikic** [comment]
@TomasVotruba The problem is that the added statements use keys like `before_2`, while list nodes are expected to be indexed numerically. In `StatementGlue::insertBefore`, replacing the implementation with something like `array_splice($classNode->stmts, $key, 0, [$node])` should work.

**Comment by TomasVotruba** [comment]
@nikic String keys was old hack to make this work. `array_splice` works like a charm, thank you.
I could remove 3 cases of nulling `origNode`: https://github.com/RectorPHP/Rector/pull/94/commits/cf20829bafd13e5e5488791bcc58a9cd79530d22


Only 2 cases related to `Namespace_` node remains:

- https://github.com/RectorPHP/Rector/blob/fba26692b87800e132aa94417dec433936bd792a/src/Rector/Dynamic/NamespaceReplacerRector.php#L72
-
 https://github.com/RectorPHP/Rector/blob/0b5126c4b9496011c6e5942189eb1acb000733a4/src/Rector/Dynamic/PseudoNamespaceToNamespaceRector.php#L93

**Comment by nikic** [comment]
@TomasVotruba Should be fixed by https://github.com/nikic/PHP-Parser/commit/f5de7f9894527186c187084b5e41cdff87b191e0. Please check if updating php-parser resolves this problem.

**Comment by TomasVotruba** [comment]
@nikic It works :clap:  Thanks man
https://github.com/RectorPHP/Rector/pull/94/commits/c268b370626bbc486360241ce1a6e04476f6b529

I wonder, will be comments for these nodes be available in printing?
