### ISSUE TITLE
Formatting is not preserved for function body if signature is changed

### ISSUE THREAD

**Issue by borNfreee** [nikic/PHP-Parser#428]
Hi,

I tried to use new `v4.0.0-alpha` release with `printFormatPreserving()` functionality and seems like there is a bug when I modify function visibility - empty lines are removed inside the function body:

```diff
--- Original
+++ New
@@ @@
      */
-    public function changeTargetDate(\DateTimeInterface $newTargetDate)
+    protected function changeTargetDate(\DateTimeInterface $newTargetDate)
     {
         \Assert\that($newTargetDate)->greaterOrEqualThan(new \DateTimeImmutable());
-
         $this->targetDate = $newTargetDate;
     }
```

Other mutators work fine and preserve original formatting. Issue reproduced just on the `ClassMethod` level mutator.

**Comment by nikic** [comment]
Thanks for the report, this should be fixed with https://github.com/nikic/PHP-Parser/commit/776275361a24214507809d8502ec67473f38af7d.

**Comment by borNfreee** [comment]
Thank you!
