### ISSUE TITLE
Add parent attribute or method.

### ISSUE THREAD

**Issue by dan-da** [nikic/PHP-Parser#429]
Sometimes when traversing a tree (manually or with traverser) it is useful/necessary to know parent node, grandparent node, etc.   For example maybe I am processing a method definition statement and I need to know what class I am a part of.

In my case, i am processing PHP and spitting out a javascript translation.  So for example, when PHP says self::foobar the js must say classname.foobar.

So it would be very useful to have a method such as "getParent()" on each node to facilitate lookups.  Otherwise, the application must somehow store this state/history separately.

I thought perhaps this could be achieved/emulated by pre-traversing the tree and adding an attribute "parentnode" to each node, but the NodeVisitor interface doesn't provide any info about the node's parent.

If there is already a built-in way to do this, please let me know.   So far, I don't see it.

For now the (expensive) hack I'm using is to walk all sub-nodes of a class_ node and add a "classnode" property to them, but the parent() property would be a much more generic and useful mechanism I think.

**Comment by nikic** [comment]
There is no built-in mechanism for this, but it's easy to add with a visitor: https://github.com/nikic/PHP-Parser/blob/master/doc/5_FAQ.markdown#how-can-the-parent-of-a-node-be-obtained
