### ISSUE TITLE
Cloning nodes of anonymous class removes spaces

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#432]
This is last issue I have to make my tests pass.

When `CloningVisitor` traverses anonymous class in this format, it somehow remove its spaces:

```php
function someMethod()
{
    $someAnonymousClass = new class
        extends NodeVisitorAbstract
    {
        private $propertyFollowedByBlankLine;
        private $property;
    };
}
```

- Test case: https://github.com/RectorPHP/Rector/blob/f3d5dc6b0912d96196aed3c36000b5f212d29f55/packages/NodeTraverserQueue/tests/NodeTraverserQueueTest.php#L45-L51

- Parsed file: https://github.com/RectorPHP/Rector/blob/master/packages/NodeTraverserQueue/tests/NodeTraverserQueueSource/Before.php.inc

- Travis fail:
https://travis-ci.org/RectorPHP/Rector/builds/294315844#L574

No other `NodeTraverser` (like NameResolver, TypeResolver etc.) influences this.

Let me know if you need some more.

**Comment by nikic** [comment]
This should be fixed by https://github.com/nikic/PHP-Parser/commit/5900d78cc91f7b4089e83f7f673c22ce71c57d3f.

**Comment by TomasVotruba** [comment]
Yep, works like a charm. Thanks a lot

**Comment by Soullivaneuh** [comment]
@nikic Do you have any ETA for a stable patch release? :-)
