### ISSUE TITLE
Call to undefined method PhpParser\Builder\Namespace_::setDocComment()

### ISSUE THREAD

**Issue by khalyomede** [nikic/PHP-Parser#437]
To produce the error :
1. Attempting to create a node using the BuilderFatctory
2. Copy/paste this code and run it :

```php
use PhpParser\BuilderFactory;
use PhpParser\Node;

$factory = new BuilderFactory;

$node = $factory->namespace('App')
  ->setDocComment('/*
                    * Auto generated file
                    */');
```

This should produce an error, whether you run it in console or web :

```
Call to undefined method PhpParser\Builder\Namespace_::setDocComment()
```

Do you think we could add the possibility to add comment right before a namespace ? The idea is to put this comment just à the top of the generated php file.

Thank you in advance.

**Comment by nikic** [comment]
Added `setDocComment()` method in https://github.com/nikic/PHP-Parser/commit/0ba710affa365eeb217188d733e3e55251963b17 and released a new version https://github.com/nikic/PHP-Parser/releases/tag/v3.1.2.
