### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#439]
The following syntax-affecting RFCs have been implemented in PHP 7.3:

 * [x] https://wiki.php.net/rfc/trailing-comma-function-calls (https://github.com/nikic/PHP-Parser/commit/91a462ce76ee11082b57a225910e90e7ca8fa81f)
 * [x] https://wiki.php.net/rfc/list_reference_assignment (https://github.com/nikic/PHP-Parser/commit/7f8ff1b9a404a25e201b705b9323e4fd68405397)
 * [x] https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

**Comment by carusogabriel** [comment]
@nikic May we require minimum PHP 7.1 in version 4.0?

**Comment by nikic** [comment]
@carusogabriel I'd prefer to keep 7.0 support for now.

**Comment by KugiHaito** [comment]
Is it possible to implement overhead of methods?

**Comment by nikic** [comment]
Emulating the heredoc/nowdoc changes on old versions is going to be quite tough. I'm considering to just add a pure-php token_get_all shim to be used if the file uses flexible heredoc/nowdoc running on <7.3.

**Comment by nikic** [comment]
Flexible heredoc/nowdoc is now supported -- the emulation on PHP < 7.3 is not perfect, but hopefully "good enough". Full emulation would require a complete reimplementation of token_get_all(), which feels like overkill just for this purpose.
