### ISSUE TITLE
endFilePos is lower than startFilePos for ClassConstFetch

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#440]
In #359 I reported an issue with the `endFilePos` of an error node as name running past the expression itself, which was inconsistent with respect to when there is no error.

The change there worked out fine for me and I've had no problems with it. However, I just noticed a small problem, which is probably the result of the resolution in that ticket:

```php
<?php

Test::();
```

This spawns an error node for the name which has an `endFilePos` that lies before the `startFilePos`, which is obviously impossible:

```
====> File /home/me/Downloads/Test.php:
Syntax error, unexpected '(' on line 3
==> Node dump:
array(
    0: Stmt_Expression[3:1 - 3:6](
        expr: Expr_ClassConstFetch[3:1 - 3:6](
            class: Name[3:1 - 3:4](
                parts: array(
                    0: Test
                )
            )
            name: Expr_Error[3:7 - 3:6](
            )
        )
    )
)
```

So it is not the `ClassConstFetch` itself that is affected, its positions seem to be correct. It's just that the name error node somehow extended beyond the end of the expression itself.

**Comment by nikic** [comment]
This is an unavoidable artifact of using closed (inclusive) ranges. The only way to represent an empty range (as the error node is in this case) is to make start greater than end. If start=end that already means that the range contains one character.

**Comment by nikic** [comment]
For reference, the only nodes that can have start>end are Stmt\Nop and Expr\Error, as they are the only nodes that can be empty (there's a test for this: https://github.com/nikic/PHP-Parser/blob/master/test/PhpParser/CodeParsingTest.php#L111).

**Comment by Gert-dev** [comment]
Thanks for your response. That indeed makes sense. Undoubtedly using inclusive ranges was an explicit decision you had good reasons for in the past. It may make sense, if it isn't already, to document this somewhere that this is an intended side effect.

Now that I know this, I'll look into ways to working with this in my implementation. Thanks!

**Comment by nikic** [comment]
To be honest, I don't think the inclusive ranges make a lot of sense. Originally I went with them because the startLine+endLine attributes that already existed at that time *appeared* to be inclusive (though really the concept doesn't apply in the same way there). I'm considering some larger changes to location handling for PHP-Parser 4.0 (in particular switching away from attributes to first-class Location objects) and if I go with it I'll probably switch to the more customary half-closed `[start, end)` intervals as well.

**Comment by Gert-dev** [comment]
I guess half-closed intervals is one of those things that I have become accustomed to, a bit like zero-indexed arrays. Apart from that, I never had any hard preference for them, but now that I've seen the implications for empty ranges, that is no longer the case 😄.

I can't speak for other users, but I would be open to modifying my code to use both the `Location` objects and the half-closed intervals, if you decided to change it.
