### ISSUE TITLE
Broken property indentation after upgrade to 4.0.0-alpha2

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#443]
I've updated dependency from https://github.com/nikic/PHP-Parser/commit/5900d78cc91f7b4089e83f7f673c22ce71c57d3f to 4.0.0-alpha2

and this changed:

```diff
 '<?php declare (strict_types=1);\n
 \n
 class ClassWithInjects\n
 {\n
     /**\n
-     * @var stdClass\n
-     */\n
-    private $property;\n
+ * @var stdClass\n
+ */\n
+private $property;\n
```

See failing build: https://travis-ci.org/rectorphp/rector/jobs/301176072
and related PR: https://github.com/rectorphp/rector/pull/159

Do you have any idea what should check?

**Comment by nikic** [comment]
Thanks for the report, this should be fixed by https://github.com/nikic/PHP-Parser/commit/336a49b428c11c3fd3b73e1018e5e1f8239ee197.

**Comment by TomasVotruba** [comment]
It works, thank you!
