### ISSUE TITLE
Spaces changes on adding new expression to method

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#446]
I add new method statements like this:

https://github.com/rectorphp/rector/blob/83ef68671577c34580a1ee44d2fec70a317d018d/src/Rector/Contrib/PHPUnit/ExceptionAnnotationRector.php#L74

But that causes space removal:

```diff
-    public function testThrowExceptionOnMultiplyWhenInconsistentMatrixSupplied(): void
+    public function testThrowExceptionOnMultiplyWhenInconsistentMatrixSupplied() : void
     {
+        $this->expectException('Phpml\\Exception\\InvalidArgumentException');
         $matrix1 = new Matrix([[1, 2, 3], [4, 5, 6]]);
         $matrix2 = new Matrix([[3, 2, 1], [6, 5, 4]]);
-
         $matrix1->multiply($matrix2);
     }
```

See in diff on Github: https://github.com/TomasVotruba/php-ml/pull/2/commits/f73f3f77e5d80fa25aa8c871cc3211440b3d81d6#diff-b8b8343d1c703aba261caf22ae14dd93R94

Is there a better way to do this?

**Comment by nikic** [comment]
The issue was the additional as the first list element. Hopefully https://github.com/nikic/PHP-Parser/commit/dc3ace55c3beaf026ebcd150659926d3c0a5a60e will resolve this.

**Comment by TomasVotruba** [comment]
This commit probably influenced adding of other elements:

```php
 '<?php declare (strict_types=1);\n
 \n
 class SomePresenter\n
+public function __construct(someType $someType)\n
 {\n
+    $this->someType = $someType;\n
+}\n
+{\n
     /**\n
      * @var someType\n
      */\n
     private $someType;\n
-    public function __construct(someType $someType)\n
-    {\n
-        $this->someType = $someType;\n
-    }\n
```


See [4 more cases on Travis](https://travis-ci.org/rectorphp/rector/jobs/310320144#L620).

It is probably related to this `StatementGlue` method: https://github.com/rectorphp/rector/blob/c3918f3a60c8f093e3272c10fe9b7b3d8e7e0107/src/Builder/StatementGlue.php#L21

**Comment by nikic** [comment]
@TomasVotruba Duh, I forgot to handle insertion of more than one element... Should be fixed with https://github.com/nikic/PHP-Parser/commit/4fcdac40d1a6a6f74ba315d7065053bbcd67d026.

**Comment by TomasVotruba** [comment]
All works now, thanks!
