### ISSUE TITLE
String with class name is outputed with double slashes

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#447]
```php
$stringArgument =  ...;
```

Dump:

```php
PhpParser\Node\Scalar\String_ #73eb
   value => "Phpml\Exception\InvalidArgumentException" (40)
   attributes protected => array ()
```

This is printed like this:

```php
$this->expectException('Phpml\\Exception\\InvalidArgumentException');
```

https://github.com/TomasVotruba/php-ml/pull/2/files#diff-37afeebee82c904c1cc8b84417c086cbR27

I need:

```php
$this->expectException('Phpml\Exception\InvalidArgumentException');
```

Is that possible?

**Comment by nikic** [comment]
Yes, you can set `$string->setAttribute('kind', String_::KIND_SINGLE_QUOTED)`.

**Comment by nikic** [comment]
I've added an explicit `pSingleQuotedString` method to the pretty printer in https://github.com/nikic/PHP-Parser/commit/e5453f0d460e71a493a35f0d476e5530c893793e. You can now achieve this behavior by extending the pretty printer with:

```php
protected function pSingleQuotedString(string $string) {
    return '\'' . preg_replace("/'|\\\\(?=[\\\\']|$)/", '\\\\$0', $string) . '\'';
}
```

I'm not sure whether or not this would make for a good default behavior.

**Comment by TomasVotruba** [comment]
Thanks for this method, I'm trying it.

What about just?

```php
protected function pSingleQuotedString(string $string): string
{
    return '\'' . addcslashes($string, '\'') . '\'';
}
```

**Comment by nikic** [comment]
@TomasVotruba `\` has to be escaped if it is followed by `\`, `'` or the end of the string.

**Comment by TomasVotruba** [comment]
@nikic I see, thanks.
In such case, I'd try making it default in alpha realeases and resolve ad hoc if found buggy.

I think my code example should be resolved properly by default.


One way or another, my issue was resolved. Thank you
