### ISSUE TITLE
wrong argument count for makeNop()

### ISSUE THREAD

**Issue by guangrei** [nikic/PHP-Parser#448]
hi, i tried to add new grammar by this step :
1. add  `%token T_TULIS`  in tokens.y
2. append  ` | T_TULIS`  in line 30 php7.y
3. append   new row  `  | T_TULIS expr_list semi                                 { $$ = Stmt\Tulis_[$2]; }` 
   (emulate T_ECHO) at line 242 php7.py
4. run  `php rebuildParsers.php` 

result :
```
Building temporary Php5 grammar file.
Building Php5 parser.
Output: ""
Building token definition.
Building temporary Php7 grammar file.
Wrong argument count for makeNop().
```

how to solved it, thanks ...

**Comment by nikic** [comment]
Are the rebuildParsers.php and the php7.y file you're basing this on both taken from the same branch? This macro is different between 3.x and master.

**Comment by guangrei** [comment]
yes... solved, thanks you very much 😇
