### ISSUE TITLE
3.x Identifies 'object' as a Built In Type Hint When it Isn't

### ISSUE THREAD

**Issue by loren-osborn** [nikic/PHP-Parser#449]
For the record, this issue relates to PR https://github.com/goaop/parser-reflection/pull/82.

When parsing function signatures, `object` is recognized as a builtin PHP type hint while PHP interprets it as a class name and applies the current namespace to it. This affects the 3.x branch and **may** have already been fixed in the current 4.0.0 alpha 2 release, but https://github.com/goaop/parser-reflection isn't compatible with the new version yet. I hope this fix can be back-ported to the 3.x tree.

**Comment by nikic** [comment]
`object` is a builtin typehint as of PHP 7.2.

**Comment by loren-osborn** [comment]
Here is a `NodeVisitor` that fixes the issue.  It defaults to the current PHP version, but is easily settable. It does not currently have any knowledge of PHP 7.2, but should be easy to add:

https://github.com/loren-osborn/parser-reflection/blob/cf48888e4d08270e9db087e4e28bfb100b6c7de4/src/NodeVisitor/BuiltinAliasFixer.php

Beyond PHP 5 vs 7, is there anyway to tell `PhpParser` what version of PHP to parse code as?

**Comment by loren-osborn** [comment]
@nikic, please let me know if a there is a way to tell the parser what **SPECIFIC** PHP version it should parse like. Should a feature equivalent to what this `NodeVisitor` provides be welcome?

**Comment by nikic** [comment]
I generally like the idea of specifying a more precise PHP version (with the understanding that it only affects thing that would parse *differently*, but still accept newer syntax). This is something that potentially impacts both lexer and parser -- e.g. 7.3 will change heredoc lexing.

**Comment by nikic** [comment]
The next major version will support this, see https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md#changes-to-the-parser-factory.
