### ISSUE TITLE
Format preserving transformation bug.

### ISSUE THREAD

**Issue by SBhojani** [nikic/PHP-Parser#453]
I have been trying to use the 'format preserving transformations' support to fix a bunch of issues in a large old codebase and have found a bug where the generated code is not valid. Example code to reproduce the bug is [attached](https://github.com/nikic/PHP-Parser/files/1567226/issue_code.txt). The code outputs:
```
Input:
--------------------------------------------------------------------------------
<?php
require_once($_SERVER['DOCUMENT_ROOT']."/".'magic.php');
?>
<html>
--------------------------------------------------------------------------------
Output:
--------------------------------------------------------------------------------
<?php

if (!file_exists($_SERVER['DOCUMENT_ROOT'] . "/" . 'magic.php')) {
    $_SERVER['DOCUMENT_ROOT'] = __DIR__;
}
require_once($_SERVER['DOCUMENT_ROOT']."/".'magic.php');
<html>
--------------------------------------------------------------------------------
```
The input is the code that goes in and the output is what comes out. My code adds the `if` before the `require_once` and does that correctly. However the **bug** is that the **`?>`** after the `require_once` and before the `<html>` has been **removed** rendering the output unparseable for PHP.

**Comment by nikic** [comment]
Looks like using the current master rather than the alpha2 release fixes this specific case, because it no longer triggers the fallback code. The fallback case is still broken though.

**Comment by nikic** [comment]
The fallback case has been fixed in https://github.com/nikic/PHP-Parser/commit/a86151f24f803886909aa89fde19497033718d5d, and I've also released another alpha version: https://github.com/nikic/PHP-Parser/releases/tag/v4.0.0alpha3
