### ISSUE TITLE
Does the code generator automatically use self as type hint?

### ISSUE THREAD

**Issue by SamMousa** [nikic/PHP-Parser#454]
I'm seeing some changed behavior between php 7.0 and 7.1 on travis that I cannot reproduce locally.

https://github.com/janephp/openapi/pull/72

Since both code bases, `openapi` and `php-parser` are unfamiliar to me I thought I'd just ask a quick question to get me pointed in the right direction.

Does the code generator in `nikic/php-parser` ever replace an object type hint with `self`?
If yes, when was this functionality introduced?

**Comment by nikic** [comment]
As far as I know the code generator does not automatically replace type hints.

**Comment by SamMousa** [comment]
That's what I thought after inspection, thanks for confirming!
