### ISSUE TITLE
PrettyPrinter incorrectly prints multiple unary minus (or plus) as increment / decrement.

### ISSUE THREAD

**Issue by bobthecow** [nikic/PHP-Parser#459]
For example, `--$a` vs `-(-$a)`.

See bobthecow/psysh#455 for the original report.

They're both parsing correctly:

![screen shot 2018-01-03 at 12 33 47 pm](https://user-images.githubusercontent.com/53660/34539500-92a83972-f085-11e7-8180-740a823f4bb7.png)
![screen shot 2018-01-03 at 12 33 59 pm](https://user-images.githubusercontent.com/53660/34539501-96025ee0-f085-11e7-825b-00b4b49c84e6.png)

… but we run into trouble when we try to print the double unary minus or plus:

![screen shot 2018-01-03 at 12 59 50 pm](https://user-images.githubusercontent.com/53660/34539618-0ee63fca-f086-11e7-81b8-48205f378a46.png)

Here's the test case run above:

```php
<?php

namespace Psy\Test;

/**
 * @group phpparser
 */
class PrinterBugTest extends \PHPUnit\Framework\TestCase
{
    private function getParser()
    {
        return (new \PhpParser\ParserFactory)->create(\PhpParser\ParserFactory::ONLY_PHP7);
    }

    private function getPrinter()
    {
        return new \PhpParser\PrettyPrinter\Standard();
    }

    public function testPreDecrement()
    {
        $stmts = $this->getParser()->parse('<?php --$a;');
        $this->assertEquals('--$a;', $this->getPrinter()->prettyPrint($stmts));
    }

    public function testDoubleUnaryMinus()
    {
        $stmts = $this->getParser()->parse('<?php -(-$a);');
        $this->assertEquals('-(-$a);', $this->getPrinter()->prettyPrint($stmts));
    }

    public function testPreIncrement()
    {
        $stmts = $this->getParser()->parse('<?php ++$a;');
        $this->assertEquals('++$a;', $this->getPrinter()->prettyPrint($stmts));
    }

    public function testDoubleUnaryPlus()
    {
        $stmts = $this->getParser()->parse('<?php +(+$a);');
        $this->assertEquals('+(+$a);', $this->getPrinter()->prettyPrint($stmts));
    }
}
```

**Comment by carusogabriel** [comment]
@nikic Should I try to fix it, should be submitted to `3.x` branch?

**Comment by nikic** [comment]
@carusogabriel Yes, this should go to the 3.x branch.

**Comment by nikic** [comment]
Another case is `+(++$x)` and `-(--$x)` , fixed in https://github.com/nikic/PHP-Parser/commit/d01fafcb40a5de95d3a8272947b38cb39d47c997. Wondering if there's any others...

I've also tagged a new release with these fixes: https://github.com/nikic/PHP-Parser/releases/tag/v3.1.4

**Comment by bobthecow** [comment]
Thank you!
