### ISSUE TITLE
[Proposal] Getters to Nodes

### ISSUE THREAD

**Issue by carusogabriel** [nikic/PHP-Parser#465]
The same way we protect our Node's `$attributes` with `getAttribute` and `getAttributes`, should we do it with:
- `$args`, protecting them with `getArg` and `getArgs`?
- `$stmts`, protecting them with `getStmts` and `getStmt`?
- `$parts`, protecting them with `getPart` and `getParts`?
- etc...

**Comment by nikic** [comment]
Unless a getter/setter is needed for specialized logic, I don't see a benefit in doing this, and a lot of disadvantages (including being less ergonomic, slower and being a BC break if their use is required.)

**Comment by carusogabriel** [comment]
No, was just about make them protected, and make code like:
```php
$node->args[0] -> $node->getFirstArg() or $node->getArg(0);
```
:smile:
