### ISSUE TITLE
Comment duplicated inside switch statement, in Parser

### ISSUE THREAD

**Issue by jhodgdon-drp** [nikic/PHP-Parser#469]
I have some PHP code that looks like this, inside a file:
````php
function tmp() {
  // Comment before switch.
  switch ($foo) {
    // One-line comment before case.
    case 'bar':
      return 1;

    // Make sure comments like this only appear once.
    // Even if they are multi-line.
    case 'baz':
    case 'boo':
      return 2;
  }
}
````

I parse the code in this file by doing the following (after reading the file into $source):
````php
  $parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
  $statements = $parser->parse($docblock['source']);
````

I will attach the output of pretty_print($statement) when applied to the statement containing the above function.... but basically, the problem is that the two-line comment that starts with "// Make sure comments like this only appear once" appears twice in the parse tree. It is attached to the first case 'bar' statement as a Nop statement, and it is attached to the case 'baz' statement as a comment.

Then when I go to pretty print these statements, the comment is appearing twice in my output. (See also https://www.drupal.org/project/api/issues/2935714 -- which reported this bug on our api.drupal.org site.)

[statements.txt](https://github.com/nikic/PHP-Parser/files/1679246/statements.txt)

**Comment by nikic** [comment]
I've disabled the collection of trailing comments for case blocks, not sure why I didn't do this earlier.

**Comment by jhodgdon-drp** [comment]
Thanks for the fast work!!
