### ISSUE TITLE
Consider a different class for destructured array?

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#471]
Would it be feasible to create a separate class for array destructuring? Like `AssignmentArray_` or `ListArray_`.

Using a single class to represent two totally different scenarios (even though the syntax is very similar) is a bit of a challenge for static analysis.

**Comment by TomasVotruba** [comment]
Do you have a use case?

**Comment by muglug** [comment]
Oh, just the inconsistency that `Array_` on the LHS of an assignment may have items that are `null` (like `List_`), but an `Array_` on the RHS of an assignment is guaranteed to never have null items.

**Comment by TomasVotruba** [comment]
Could you share PHP code? It's easier to spot and test

**Comment by nikic** [comment]
I think the suggestion makes sense in general, but I'm going to punt on this for 4.0. I don't want to change types at this point.

**Comment by muglug** [comment]
Makes sense – I'm about 12 months late with this

**Comment by TomasVotruba** [comment]
Is this still relevant?

**Comment by ondrejmirtes** [comment]
Yes

**Comment by TomasVotruba** [comment]
How should the nodes look like for?

```php
[$a, $b,,, $c] = [1, 2, 3, 4, 5];
```

**Comment by nikic** [comment]
What do you think about using `Expr\List_` for both `list($x, $y) = $z` and `[$x, $y] = $z`, together with an attribute that determines the actual style used (like `kind` on `Expr\Array_`)? That seems convenient in that you generally want to treat `list() =` and `[] =` the same, and it avoids an additional node type.

**Comment by ondrejmirtes** [comment]
That would be really nice!
