### ISSUE TITLE
Stable Version 4 Release for Symfony Maker

### ISSUE THREAD

**Issue by weaverryan** [nikic/PHP-Parser#474]
Hi guys!

First, I don't intend to be pestering :) - I've watched the progress on version 4 of this library with great excitement! We're already using it - specifically the new "preserve formatting print mode" - quite extensively in the Symfony world for our code generation bundle: symfony/maker-bundle#104.

It's working *brilliantly*... so brilliantly that the PR is now stuck, waiting for the version 4 stable release.

Do you guys have a specific amount of time in mind between the beta & stable? Does having a library using the new feature help validate? Can I help do anything else (bring coffee, etc).

Cheers!

**Comment by nikic** [comment]
I think we're pretty close to a stable 4.0 release. I don't have any more code changes planned, but want to touch up the documentation a bit more.

**Comment by weaverryan** [comment]
Thanks @nikic! I'm looking forward to it. I noticed the docs reorg lately - it feels a bit "flatter" to me now (in a good way) - easy to see everything from the docs homepage :)

**Comment by nikic** [comment]
Aaaand here we go: https://github.com/nikic/PHP-Parser/releases/tag/v4.0.0

**Comment by weaverryan** [comment]
Wooohoooo! I owe you for having this great new feature, right when we needed it <3
