### ISSUE TITLE
$param->type doesn't have namespacedName

### ISSUE THREAD

**Issue by mnpenner** [nikic/PHP-Parser#475]
I've extracted the parameters for a method via `\PhpParser\Node\Stmt\ClassMethod::getParams`, but `$param->type` doesn't have the `->namespacedName` even though I added `\PhpParser\NodeVisitor\NameResolver`.

It works fine for class names, but doesn't seem to work on parameter types.

e.g.

```php
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class AgencyDocsController {

    static function docsDT($folder_id, MYSQL_Database $pcsDb, User $user, SymfonyRequest $request) {
        ...
    }
```

I'm trying to figure out how to get `Symfony\Component\HttpFoundation\Request` for `$request` instead of `SymfonyRequest`.

**Comment by nikic** [comment]
`namespacedName` is only used on declarations (`class Foo {}` etc). Unless you passed options to the name resolver, it should have changed the type into `\Symfony\Component\HttpFoundation\Request` (a `Name\FullyQualified`). You don't need to access any attributes for that, the node has been replaced entirely.

**Comment by mnpenner** [comment]
@nikic Nope, didn't pass any options:

```php
$traverser->addVisitor(new NameResolver);
```

It definitely doesn't look like it resolved the type for me.

```php
if((string)$param->type == 'SymfonyRequest') {
    var_dump($param->type);
    echo $dumper->dump($param->type);
    exit;
}
```

Outputs:

```
object(PhpParser\Node\Name)#19222 (2) {
  ["parts"]=>
  array(1) {
    [0]=>
    string(14) "SymfonyRequest"
  }
  ["attributes":protected]=>
  array(4) {
    ["startLine"]=>
    int(10)
    ["startFilePos"]=>
    int(350)
    ["endLine"]=>
    int(10)
    ["endFilePos"]=>
    int(363)
  }
}
Name(
    parts: array(
        0: SymfonyRequest
    )
)
```

I did, however, change the lexer options because I want the char offsets:

```php
$lexer = new PhpParser\Lexer([
    'usedAttributes' => [
        'comments', 'startLine', 'endLine', 'startFilePos', 'endFilePos',
    ]
]);
```

Could that have done it?

**Comment by nikic** [comment]
The lexer options shouldn't affect affect this. Would you mind showing the full code you are using? I'd assume there's some issue with the way the name resolver is applied.

**Comment by mnpenner** [comment]
@nikic The script is a major hackjob, but [here it is](https://gist.github.com/mnpenner/0b8ea0cfa0ba5eea6e4f3cae8d5406dd).

The relevant parts (I think) are:

```php
$dumper = new NodeDumper;
$lexer = new PhpParser\Lexer([
    'usedAttributes' => [
        'comments', 'startLine', 'endLine', 'startFilePos', 'endFilePos',
    ]
]);

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP5, $lexer);
$traverser = new NodeTraverser();

$traverser->addVisitor(new NameResolver);
$traverser->addVisitor(new ClassExtractor); // <-- my class

...

$ast = $parser->parse($code);
$traverser->traverse($ast);
```

**Comment by nikic** [comment]
@mnpenner Ah, I see the issue. Both visitors are running in parallel, but the class visitor goes deep inside the tree (inspecting methods and params etc.) before the name resolver gets to them. The solution is to run the name resolver and class extractor in two independent passes:

```php
$nameResolver = new NodeTraverser;
$nameResolver->addVisitor(new NameResolver);
$classExtractor = new NodeTraverser;
$classExtractor->addVisitor(new ClassExtractor);
// ...
$ast = $nameResolver->traverse($ast);
$ast = $classExtractor->traverse($ast);
```

This should make sure that all names are resolved when the class extractor gets to them.

**Comment by mnpenner** [comment]
@nikic Yup, that was it. Thank you so much! Sorry for taking your time, that was my mistake :smile:
