### ISSUE TITLE
Move the class modifiers consts to the ClassLike class

### ISSUE THREAD

**Issue by tomzx** [nikic/PHP-Parser#476]
Since the modifiers apply to all of the `ClassLike` classes, it seems it would make more sense if those `const` where in this class instead.

This will likely require a major bump.

Thoughts?

**Comment by nikic** [comment]
I think if we move those constants, it might be best to create a separate `Modifiers` class for it. After all, they are not specific to classes, but are also used in methods, properties and constants.

**Comment by davidmpaz** [comment]
+1 for:
> it might be best to create a separate Modifiers class for it

Not directly using PHP-Parser in PHP, but taking it as *reference* for some other language related work. I agree It would be better if treated those as separate. 

The same idea apply to *Visibility*. Currently *Modifiers* as well as *Visibility* are treated the same, as **flags**, if I have understood well the code in `Class_` and `ClassMethod`.

**Comment by nikic** [comment]
@davidmpaz The reason why I wouldn't separate visibility and other modifiers is that they are not ordered. I.e. both `public static` and `static public` are valid. It doesn't really matter in the current design where the modifiers are flags, but it would be a problem if we would also try to preserve the order in which the modifiers were declared in the future.
