### ISSUE TITLE
Semicolons aren't preserved in 4.0

### ISSUE THREAD

**Issue by BackEndTea** [nikic/PHP-Parser#480]
The following function is used to mutate a throw statement, to remove the throw keyword.
```php
    public function mutate(Node $node)
    {
        return $node->expr;
    }
```
In 3.0 this caused the code to look like this:
```diff
-throw new \Exception();
+new \Exception();
```
In 4.0 it however looks like this.
```diff
-throw new \Exception();
+new \Exception()
```

As you can see the semicolon is missing.

**Comment by nikic** [comment]
PHP-Parser 4.0 makes a distinction between an expression (`new Foo`) and an expression statement (`new Foo;`). To preserve the semicolon, the mutate method should look as follows:

```
    public function mutate(Node $node)
    {
        return new Node\Stmt\Expression($node->expr);
    }
```

I probably should add some sanity checks for this, as it will probably be a common problem.

**Comment by BackEndTea** [comment]
Thanks for the help, personally i solved it like this in a base class

```php
    protected function wrapInExpression(Node $node)
    {
        if ($this->shouldWrap === null) {
            $this->shouldWrap = class_exists(Node\Stmt\Expression::class);
        }

        if ($this->shouldWrap) {
            return new Node\Stmt\Expression($node);
        }
        return $node;

    }
```

**Comment by nikic** [comment]
I've added some sanity checks in the traverser to help catch this kind of issue: https://github.com/nikic/PHP-Parser/commit/6aba7624ed268fc6d4caf633dd94c2a77fe03f55
