### ISSUE TITLE
ctype_alnum always returns false when passed an int

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#484]
Not sure if this is on a critical path, but it's bad code: https://github.com/nikic/PHP-Parser/blob/610617fe9339a48d7b80148548fcbbb5dd100ebd/lib/PhpParser/PrettyPrinterAbstract.php#L1069

Found via static analysis stuff

**Comment by nikic** [comment]
ctype_alnum accepts either a character string or an ASCII code. This is the usage with an ASCII code. I don't really understand why this would be wrong?

**Comment by nikic** [comment]
Ah, I guess this is because people expect `ctype_alnum($i)` to work as `ctype_alnum((string) $i)` rather than `ctype_alnum(chr($i))`? In that case we could change it to

```
$c = chr($i);
$this->labelCharMap[$c] = $i >= 0x7f || ctype_alnum($c);
```

so the `chr()` call is explicit. Presumably that would appease the static analyzer?

**Comment by muglug** [comment]
> Presumably that would appease the static analyzer?

Sorry, I'm an idiot for just relying on the documentation ;). I'll update the static analyser's idea of what `ctype_alnum` can expect.
