### ISSUE TITLE
Force formatting

### ISSUE THREAD

**Issue by nterray** [nikic/PHP-Parser#485]
Hello,

I would like to output this:
```php
$foo->always()
    ->getTrackerById()
    ->with('param1', 'param2')
    ->andReturns('result');
```
However all is coming on the same line:
```php
$foo->always()->getTrackerById()->with('param1', 'param2')->andReturns('result');
```

I tried by incrementing the startLine attribute during the MethodCall instantiation but it doesn't work:
```php
$start_line = $node->getAttribute('startLine');
$end_line   = $node->getAttribute('endLine');

$node = new Node\Expr\MethodCall(
    new Node\Expr\MethodCall($node, 'always'),
    $method_name,
    [],
    ['startLine' => ++$start_line, 'endLine' => ++$end_line]
);
```

Is there a way to force formatting of the output?

**Comment by nikic** [comment]
There's no built-in way to do this, but you can extend the pretty printer to implement this manually. E.g. do a `$node->setAttribute('fluentStyle', true)` attribute and then extend the pretty printer with

```php
use PhpParser\Node\Expr;
use PhpParser\PrettyPrinter\Standard;
class CustomPrettyPrinter extends Standard {
    protected function pExpr_MethodCall(Expr\MethodCall $node) {
        if ($node->getAttribute('fluentStyle', false)) {
            return $this->pDereferenceLhs($node->var)
                 . $this->nl . '    ->' . $this->pObjectProperty($node->name)
                 . '(' . $this->pMaybeMultiline($node->args) . ')';
        } else {
            return parent::pExpr_MethodCall($node);
        }
    }
}
```

**Comment by TomasVotruba** [comment]
This looks like Coding Standard's job. You might make use of this fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/Whitespace/MethodChainingIndentationFixer.php

**Comment by nterray** [comment]
Thanks for the suggestion, I will try it.

@TomasVotruba I thought about it. Unfortunately, the legacy code that I try to rewrite thanks to PHP-Parser is full of odd (& old) coding styles (if any) and in my refactoring I prefer to style only the updated lines and not the whole file. I'm afraid that php-cs-fixer will change more lines than needed.

**Comment by TomasVotruba** [comment]
@nterray I see, but PHP CS Fixer doesn't care about code quality. It matches only the case you describe

Have you tried it? It has very rarely false positives from my daily experience.

**Comment by nterray** [comment]
@nikic Unfortunately pMaybeMultiline has private access therefore I cannot call it from CustomPrettyPrinter.

Nevertheless by copying private methods pMaybeMultiline and hasNodeWithComments inside the CustomPrettyPrinter, it works like a charm. Closing the issue then.

Thank you.

**Comment by nikic** [comment]
We should make the pMaybeMultiline method protected so this becomes easier in the future.
