### ISSUE TITLE
Q: How the format preserving works in basics?

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#487]
This is rather technical question on how to approach it.
I ask because I work with 3rd party doc block parser and need to build same feature around it.

### Input

The parser returns Nodes (`ParamNode` for `@param Type $name`, `VarNode` etc.),
and lexer returns tokens (`/**`, ` `, `@`, `param` ...).

### Change

Let's say I change `Type` to `TypeFoo` via `$paramNode->type` (like here).

How to connect them together so I could print back the original format?

If that helps, I'm aware there is indent in printer and each node has original node on it.

Thank you for any guidance.

**Comment by nikic** [comment]
Each node has the original node, which has start and end offsets in the token_get_all stream. Then what it does it print something like

    Tokens[node.startPos .. subnode1.startPos]
    Print(subnode1)
    Tokens[subnode1.endPos .. subnode2.startPos]
    Print(subnode2)
    Tokens[subnode2.endPos .. node.endPos]

where Print() does the same thing recursively and the offsets are always taken from the original nodes.

The basic approach is very simple, the devil is in the detail...
