### ISSUE TITLE
3 ways to get an Identifier name

### ISSUE THREAD

**Issue by carusogabriel** [nikic/PHP-Parser#488]
Hi Nikita.

I was playing around the [`Identifier`](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Identifier.php) class, and I notice that are 3 ways to get its name:
```php
$foo->name; //property
$foo->toString(); //method
(string) $foo; //cast
```

Shouldn't we make the property private to reduce the number of ways?

**Comment by nikic** [comment]
We can't make the property private because it's a subnode (things like node dumping would break). We could mark it as `@internal` in phpdoc though.

For the record, the preferred way is to use `toString()`. The string cast is handy if you need to support PHP-Parser 3 and 4 at the same time.

**Comment by carusogabriel** [comment]
> We can't make the property private because it's a subnode (things like node dumping would break)

Yeah, just test it 

> We could mark it as @internal in phpdoc though.

Maybe, but my idea was to avoid false-positives with PHPStan, like:
```
Cannot call method toString() on PhpParser\Node\Expr|string
```

, but
> For the record, the preferred way is to use `toString()`

seems to solve some of them :)

Thanks for the explanation
