### ISSUE TITLE
Question : Modifying generated Code

### ISSUE THREAD

**Issue by harikt** [nikic/PHP-Parser#49]
Hi, 

I was looking at code generation doc https://github.com/nikic/PHP-Parser/blob/master/doc/4_Code_generation.markdown . 

And may be there is a way to add some more methods or properties to the already generated code and pretty print it ?

**Comment by gpgkd906** [comment]
I have read this issue, and i think addStmt can make things easier, like this:
```php
    public function addStmt($stmt)
    {
     	$sort = [
            'Stmt_TraitUse'    => 0,
            'Stmt_ClassConst'  => 1,
            'Stmt_Property'    => 2,
            'Stmt_ClassMethod' => 3,
        ];
        if(!isset($sort[$stmt->getType()])) {
            throw new Error('Cannot add stmt not belong ' . __CLASS__);
        }
        $this->stmts[] = $stmt;
        usort($this->stmts, function($a, $b) use ($sort){
            Return $sort[$a->getType()] > $sort[$b->getType()];
        });
    }
```
so i can use Stmt¥Class_ just like Builder¥Class_
```php
$class->addStmt(...)
```
but, I am not sure if is there something wrong...
