### ISSUE TITLE
"Failed to open stream: No such file or directory" at install

### ISSUE THREAD

**Issue by golddragon007** [nikic/PHP-Parser#491]
Running composer install with Acquia Dev Desktop I get this:

[project-dir]\web>php "C:\Program Files (x86)\DevDesktop\tools\composer.phar" install
No composer.json in current directory, do you want to use the one at [project-dir]? [Y,n]? y
Gathering patches for root package.
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 3 installs, 14 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating nikic/php-parser (v3.1.2 => v3.1.3): Loading from cache

  [ErrorException]
  file_put_contents([project-dir]\vendor\bin/php-parse): failed to open stream: No such file or directory

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

However the file is there. I think the "/" sign is the problem.

**Comment by tomzx** [comment]
Can you please provide the full error stack trace by calling `composer.phar` with `-vvv`? Furthermore, this doesn't look like an issue that is going to be related to PHP-Parser.

**Comment by golddragon007** [comment]
Yes, here it is:

[project-dir]\web>php "C:\Program Files (x86)\DevDesktop\tools\composer.phar" -vvv install
No composer.json in current directory, do you want to use the one at [project-dir]? [Y,n]? y
Reading ./composer.json
Loading config file C:/Users/Marton/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Checked CA file C:\Program Files (x86)\DevDesktop\common\cert\cacert.pem: valid
Executing command ([project-dir]): git branch --no-color --no-abbrev -v
Reading C:/Users/Marton/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/Marton/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/Marton/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\Marton\AppData\Roaming\Composer/auth.json
Reading C:\Users\Marton\AppData\Roaming\Composer/auth.json
Reading [project-dir]/vendor/composer/installed.json
Reading C:/Users/Marton/AppData/Roaming/Composer/vendor/composer/installed.json
Loading plugin cweagans\Composer\Patches
Loading plugin DrupalComposer\DrupalScaffold\Plugin
Loading plugin Composer\Installers\Plugin
Loading plugin Hirak\Prestissimo\Plugin
Running 1.6.2 (2018-01-05 15:28:41) with PHP 7.0.25 on Windows NT / 10.0
Reading ./composer.lock
> pre-install-cmd: DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.008 seconds
Analyzed 342 packages to resolve dependencies
Analyzed 1134 rules to resolve dependencies
Nothing to install or update
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Generating autoload files


  [ErrorException]
  file_put_contents([project-dir]\vendor\bin/php-parse): failed to open stream: No such file or directory


Exception trace:
 () at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/BinaryInstaller.php:167
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 file_put_contents() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/BinaryInstaller.php:167
 Composer\Installer\BinaryInstaller->installUnixyProxyBinaries() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/BinaryInstaller.php:146
 Composer\Installer\BinaryInstaller->installFullBinaries() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/BinaryInstaller.php:86
 Composer\Installer\BinaryInstaller->installBinaries() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/LibraryInstaller.php:159
 Composer\Installer\LibraryInstaller->ensureBinariesPresence() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer/InstallationManager.php:147
 Composer\Installer\InstallationManager->ensureBinariesPresence() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Installer.php:308
 Composer\Installer->run() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/vendor/symfony/console/Application.php:842
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/Program Files (x86)/DevDesktop/tools/composer.phar/bin/composer:58
 require() at C:\Program Files (x86)\DevDesktop\tools\composer.phar:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by nikic** [comment]
The only thing I can recommend here is to delete the vendor directory, as well as the composer cache directory and try again. The forward slash should not be a problem, neither PHP nor Windows care about that.

In any case this is not an issue that can be resolved from the side of this library, as these calls are performed by composer itself. You could try reporting the issue there, but I think it's more likely that this is a cache corruption or configuration issue (do you maybe explicitly specify the `"bin-dir"` option?)
