### ISSUE TITLE
Bad code results in "Unexpected T_STRING"

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#492]
I'm experimenting with using PHP Parser currently throws an exception with

```php
<?php
class A {
  protecte $bar;
}
```

when passed an error handler. It'd be great if it didn't (though I understand that it may be beyond the scope of the project).

**Comment by nikic** [comment]
What do you think about https://github.com/nikic/PHP-Parser/commit/7208b1c7ac915d37cac263045a5dc66f5cfa4f73? It will skip the property, but still parse the rest of the class. Is that good enough?

**Comment by muglug** [comment]
>  Is that good enough?

It's great!
