### ISSUE TITLE
Error recovery for foreach without "as" part

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#496]
A situation that often occurs during autocompletion in language servers is the following:

```php
<?php

foreach ($file->I_am_still_typing_here) {

}
```

Or variants such as:

```php
<?php

foreach ($file
foreach ($file)
```

Would it be possible to add (somewhat sensible) error recovery for these so that some measure of static analysis can be performed? I understand that some things may be hard to recover from, as PHP's tokenization is being used in the background.

**Comment by nikic** [comment]
Recovery from missing `as` implemented in https://github.com/nikic/PHP-Parser/commit/fa99c3fbfb5bece11198ae0bc62f4ef2313dff18. The `valueVar` will be an `Expr\Error` in this case, as `valueVar` is a required property.

Is this good enough for your purposes?

**Comment by Gert-dev** [comment]
My main goal was to get a somewhat sensible AST for this erroneous code [autocompletion could continue functioning for incomplete statements](https://gitlab.com/php-integrator/core/issues/176), which appears to work with this change, so more than good enough, in fact, thanks!
