### ISSUE TITLE
Reclassify node types

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#500]
Currently there are a number of nodes that extend Expr/Stmt but really aren't expressions or statements. Historically the reason is that they are a direct part of an expression or statement.

The following nodes currently extend `Expr` but aren't expressions:

 * [x] `Scalar\EncapsedStringPart` (https://github.com/nikic/PHP-Parser/commit/f4ec6a1e53994b4ecfae574f06e31087d06057ea)
 * [x] `Expr\ArrayItem` (https://github.com/nikic/PHP-Parser/commit/8be56afd2d4e0dcafa164ebf406a8e3f6ff3e053)
 * [x] `Expr\ClosureUse` (https://github.com/nikic/PHP-Parser/commit/b0469d127e2c1bd3645fbc757ef5e10a5f920c29)

The following nodes currently extend `Stmt` but aren't statements:

 * [x] `Stmt\DeclareDeclare` (https://github.com/nikic/PHP-Parser/commit/03ccfa3dd4388024e9dc12a86e0d09642fc44ca0)
 * [x] `Stmt\PropertyProperty` (https://github.com/nikic/PHP-Parser/commit/e1345f0c094dfb0d47abee7f44fb13ffca19cade)
 * [x] `Stmt\StaticVar` (https://github.com/nikic/PHP-Parser/commit/035c1c7cd201698829b9be237de47ecd958a45b7)
 * [x] `Stmt\UseUse` (https://github.com/nikic/PHP-Parser/commit/4917c71a918a2cad4988e7f2c9eca2fb07e3ef83)

The following are a bit less clear-cut. They are not statements per se but could be considered close enough:

 * `Stmt\TraitUseAdaptation\*`
 * `Stmt\Case`
 * `Stmt\Catch`
 * `Stmt\Finally`
 * `Stmt\ElseIf`
 * `Stmt\Else`

We might want to move some or all of these out of Expr/Stmt in a future version.

**Comment by nikic** [comment]
Also, while we're at it, `Scalar\Encapsed` is not a scalar either, it should be `Expr`. `Scalar\MagicConst` is borderline.

**Comment by nikic** [comment]
And it would probably be good to rename some node types to be more obvious to people not familiar with ext/tokenizer lingo. E.g. `Encapsed` should be `InterpolatedString`, `DNumber` should be `Float` and `LNumber` should be `Int`.

We can keep BC aliases for everything, of course.

**Comment by TomasVotruba** [comment]
Looking more and more on nodes, it would be great to correct categories so they have some added value and people can quickly understand the namespace pattern and rely on it.

All these changes can be easily migrated with https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#classreplacerrector
So BC is not really a problem.

**Comment by nikic** [comment]
Planned renames are done. Though I also wonder whether it might make sense to drop the `Scalar` category and merge it into `Expr`. Not sure the distinction provides any real value.
