### ISSUE TITLE
Clarify Const_

### ISSUE THREAD

**Issue by theofidry** [nikic/PHP-Parser#506]
I have some questions regarding `Const_` whilst working on [PHP-Scoper](https://github.com/humbug/php-scoper):

1. Why `Node\Stmt\Const_` has an array of `Node\Const_`?
1. When can it be empty?
1. When can there be more than one?
1. `Node\Const_` seems to not have the `parent` attribute, is this intentional?

Thanks very much

**Comment by nikic** [comment]
1. `const FOO = 1, BAR = 2;` is allowed in PHP.
2. It can't be empty.
3. See 1.
4. There are no `parent` attributes unless you are adding them yourself. See https://github.com/nikic/PHP-Parser/blob/master/doc/component/FAQ.markdown#how-can-the-parent-of-a-node-be-obtained.

**Comment by theofidry** [comment]
Thanks! Will dig into this :)
