### ISSUE TITLE
Linking variables and functions to definitions

### ISSUE THREAD

**Issue by BlakeMScurr** [nikic/PHP-Parser#508]
Heya!

I would like to find all call sites of a function from its definition and vice versa, and (if such a thing exists in PHP - I'm new) I'd like to find the declaration of a variable from a place where it's used. Is thispossible without writing tons of my own code to do name resolution manually? I understand that [getSubNodeNames](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node.php#L19) just refers to subnodes in the AST and won't get call sites.

I had a brief look at the data in [tokenToSymbols and symbolsToName](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/ParserAbstract.php#L55) expecting some kind of symbols table, but it was quite opaque, and I couldn't tell.

Cheers :smile:

**Comment by nikic** [comment]
This functionality is outside the scope of php-parser. Both problems are non-trivial and involve tradeoffs. For the call graph, typical issues are (multiple) dynamic definitions of a function, as well as virtual methods. For variables, there may be multiple [reaching definitions](https://en.wikipedia.org/wiki/Reaching_definition). https://github.com/ircmaxell/php-cfg tries to solve that problem by using [SSA form](https://en.wikipedia.org/wiki/Static_single_assignment_form). However, that project is somewhat dated and not very well tested. For PHP in particular there's also the question of how accurate you want to be (e.g. wrt references and variable variables) and whether you want to perform inter-file analysis (following statically resolvable includes).

My best suggestion is to look at static analyzers such as https://github.com/vimeo/psalm and https://github.com/phpstan/phpstan. It's quite likely that they have code to perform at least some of the things you are interested in.

**Comment by BlakeMScurr** [comment]
Great, thanks for the recommendations and detailed explanation.
