### ISSUE TITLE
Comment stripped at end of class

### ISSUE THREAD

**Issue by manur0** [nikic/PHP-Parser#509]
Hi,
I am using version 4.0.2
With this example:
```
<?php

function myFunct() {
    static $a;
    // my comment
}
class MyClass {
    protected $a;
    // my comment
}
```
Inside AST the second Stmt_Nop item is missing inside Stmt_Class while the first one is present inside Stmt_Function.
Perhaps a  makeNop missing in the class_statement_list grammar rule?

Thanks for this great software!

**Comment by nikic** [comment]
It might happen that this change needs to be reverted due to the BC break. I suspect some libraries will throw an exception if they encounter a Nop node inside a class, as it could not happen before.
