### ISSUE TITLE
Parsing separate Expr node

### ISSUE THREAD

**Issue by ProgMiner** [nikic/PHP-Parser#520]
Hello,

I am developing a PHP code generator with builtin language.

Can PHP-Parser parse separate PHP expressions like `"Foo"` and other expressions that can be a default value of class property?

**Comment by nikic** [comment]
There is no separate expression parser, but you can parse `"<?php EXPR_HERE;` and take `$stmts[0]->expr` as the result.

**Comment by ProgMiner** [comment]
Ok, thanks.
I did it this way already, but opened this issue to find out that there is no better way :)
