### ISSUE TITLE
Binary operators without gaps (spaces)

### ISSUE THREAD

**Issue by ProgMiner** [nikic/PHP-Parser#521]
Can `BinaryOp` store information about the gaps now?
And will this ability be added in future?

**Comment by prail** [comment]
What exactly do you mean by gap? Some example code and what you would expect the tree to look like would be great.

**Comment by TomasVotruba** [comment]
Gaps/spaces/format preserving is supported since PHP-Parser 4.

```diff
$value = 1 + 5;
$value = 1    +    5;
```

See [docs](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown#formatting-preserving-pretty-printing) for more.

**Comment by nikic** [comment]
As mentioned in the preceding comment, the formatting-preserving pretty printer preserves exact whitespace.
