### ISSUE TITLE
NameResolver TraitUse error

### ISSUE THREAD

**Issue by ProgMiner** [nikic/PHP-Parser#523]
I have tried to use `NameResolver` and noticed strange error.

My generated classes have `TraitUse` node with resolved (started with `\`) trait name. But after `NameResolver` use they names been replaced to `namespace` + `trait name`.

Maybe it is linked with wrong `TraitUse` constructing, I don't know.

How I constructs `TraitUse`:
```php
new Node\Stmt\TraitUse([
    Node\Name('\\PHPDataGen\\DataClassTrait')
]);
```

Other class names (in type hints) been resolved correctly.

**Comment by nikic** [comment]
Fully qualified names use a different class, the correct construction code would be:

```php
new Node\Stmt\TraitUse([
    Node\Name\FullyQualified('PHPDataGen\\DataClassTrait')
]);
```

Creating a `Node\Name` with a leading backslash should probably throw an exception to avoid this kind of issue.

**Comment by ProgMiner** [comment]
Yes, maybe.
I think also a special document about naming (about `Name`, `Identifier`, etc) is needed.
Thanks for answer!

**Comment by ProgMiner** [comment]
By the way, my PR #516 with builders for `TraitUse` and `TraitUseAdaptation` probably can resolve trait construction troubles.

**Comment by ProgMiner** [comment]
And another one question: what do you think about needing feature of `NameResolver` for removing `Use_` nodes?
