### ISSUE TITLE
Why StaticVar is a Stmt?

### ISSUE THREAD

**Issue by ProgMiner** [nikic/PHP-Parser#524]
Maybe this is not correct question, but why `StaticVar` extends `Stmt`?

This node, I'm thinking, is not statement like an other statements.

**Comment by nikic** [comment]
Yes, that's right. Historically this is the case because `Stmt\Static_` is a statement and `Stmt\StaticVar` is used within it. The plan is to fix this in the next major version, see #500.

**Comment by ProgMiner** [comment]
Ok, maybe I can help you by sending PR?
