### ISSUE TITLE
"Throw on passing too few function arguments" analyze

### ISSUE THREAD

**Issue by aizuyan** [nikic/PHP-Parser#526]
I want to migrate PHP from 5.4 to 7.2, and analyze code.

but from 7.0 to 7.1, had a  [backward incompatible changes](http://php.net/manual/en/migration71.incompatible.php)

how can i analyze **Throw on passing too few function arguments** incompatible changes, I have no idea, can you give me some advice, thanks very match

```php
<?php
class W
{
    public function test($a, $b)
    {

    }
}

$a = new W();
$a->test();

function test($param){}
test();
```
The above example will output something similar to:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function W::test(), 0 passed
```

**Comment by TomasVotruba** [comment]
It looks like you autoload the files by `include/require` in `composer.json`  or somewhere else.

Could you provide full failing code?

**Comment by TomasVotruba** [comment]
It looks like you autoload the files by `include/require` in `composer.json`  or somewhere else.

Could you provide full code you analyze this code with?
