### ISSUE TITLE
unicode characters?

### ISSUE THREAD

**Issue by voku** [nikic/PHP-Parser#531]
Hi, in this issue https://github.com/spatie/7to5/issues/40 I tried to figure out what goes wrong and I found that the "String_" class breaks the unicode chars, but why and how can I disable this behavior? Thanks!

lib/PhpParser/Node/Scalar/String_.php:
```php
...
return chr(hexdec($str));
...
```

-->

```
  private static $BOM = [
      "\xef\xbb\xbf"     => 3, // UTF-8 BOM
      'ï»¿'              => 6, // UTF-8 BOM as "WINDOWS-1252" (one char has [maybe] more then one byte ...)
      "\x00\x00\xfe\xff" => 4, // UTF-32 (BE) BOM
      '  þÿ'             => 6, // UTF-32 (BE) BOM as "WINDOWS-1252"
      "\xff\xfe\x00\x00" => 4, // UTF-32 (LE) BOM
      'ÿþ  '             => 6, // UTF-32 (LE) BOM as "WINDOWS-1252"
      "\xfe\xff"         => 2, // UTF-16 (BE) BOM
      'þÿ'               => 4, // UTF-16 (BE) BOM as "WINDOWS-1252"
      "\xff\xfe"         => 2, // UTF-16 (LE) BOM
      'ÿþ'               => 4, // UTF-16 (LE) BOM as "WINDOWS-1252"
  ];
```

... becomes ...

```
    private static $BOM = [
        "﻿" => 3,
        // UTF-8 BOM
        'ï»¿' => 6,
        // UTF-8 BOM as "WINDOWS-1252" (one char has [maybe] more then one byte ...)
        "\0\0��" => 4,
        // UTF-32 (BE) BOM
        '  þÿ' => 6,
        // UTF-32 (BE) BOM as "WINDOWS-1252"
        "��\0\0" => 4,
        // UTF-32 (LE) BOM
        'ÿþ  ' => 6,
        // UTF-32 (LE) BOM as "WINDOWS-1252"
        "��" => 2,
        // UTF-16 (BE) BOM
        'þÿ' => 4,
        // UTF-16 (BE) BOM as "WINDOWS-1252"
        "��" => 2,
        // UTF-16 (LE) BOM
        'ÿþ' => 4,
    ];
```

**Comment by nikic** [comment]
An alternative to the full formatting-preserving printer is https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#attribute-handling and extending the pretty printer to use the originalValue attribute. Especially if you know that none of your transformations modify string contents, this would be a quick fix.

**Comment by voku** [comment]
Big thanks for the help and for your work, it works pretty good (https://github.com/voku/7to5/commit/7a62d127552e34c294aa04b59816727a25f430a4) :) but now I have a different problem... 

... after converting a class from PHP7 -> PHP5 there was a different behavior in "if"-conditions, so I tried to fix it, with this "hack":

-> https://github.com/nikic/PHP-Parser/pull/532
