### ISSUE TITLE
Do not visit children and the current node for subsequent visitors

### ISSUE THREAD

**Issue by borNfreee** [nikic/PHP-Parser#534]
This is an attempt to reopen https://github.com/nikic/PHP-Parser/issues/164 but with a real world case rather than "just for performance purposes".

We are writing a Mutation Testing framework, where each Node can be mutated to one or more other nodes, or removed completely. Small example for reference:

```diff
- public function execute()
+ protected function execute()
```

Then, when developer uses `@codeCoverageIgnore` on the method level, we should not mutate anything and just skip it from the mutation process:

```php
class Executor
{
    /**
     * @codeCoverageIgnore
     */
    public function execute()
    {
        // ...
    }
}
```

To achieve this, we can write a simple `NodeVisitor`:

```php
final class CodeCoverageMethodIgnoreVisitor extends NodeVisitorAbstract
{
    public function enterNode(Node $node)
    {
        if (!$node instanceof Node\Stmt\ClassMethod) {
            return null;
        }

        $method = new \ReflectionMethod(...);

        $docComment = $method->getDocComment();

        if ($docComment === false) {
            return null;
        }

        if (strpos($docComment, '@codeCoverageIgnore') !== false) {
           return NodeTraverser::DONT_TRAVERSE_CHILDREN;
        }

        return null;
    }
}
```

This works great, except that the node being visited is still mutated. That is expected, because `Traverser` does not visit *children*, but not the node itself.

And since we have such sequense of visitors:

```php
$traverser->addVisitor(new CodeCoverageMethodIgnoreVisitor());
$traverser->addVisitor(new MutationCollector());
```

`MutationCollector` visits the same `ClassMethod` node and collects mutation.

So, the question is: is it possible to add one more constant that will work exaclty like `DONT_TRAVERSE_CHILDREN`, but in addition won't mutate *current* node (and yes, this will require additinal logic for `leaveNode()` visitors).

Thank you.

**Comment by nikic** [comment]
I'm fine with adding the extra flag, though I'd appreciate a PR for this.
