### ISSUE TITLE
Allow prioritized node visitors

### ISSUE THREAD

**Issue by BackEndTea** [nikic/PHP-Parser#535]
Sometimes its not possible to add all the node visitors in the 'correct' order, as you may only want to add some under certain conditions. 

Therefore it would be nice to add a visitors with a priority, so they will be ran in a specific order.

See also: https://github.com/infection/infection/pull/491

**Comment by nikic** [comment]
For reference, there was a PR for this: https://github.com/nikic/PHP-Parser/pull/537 However, I don't plan to support this functionality, so closing.
