### ISSUE TITLE
Error recovery for missing return type with colon

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#544]
Continuing adventures in just-in-time parsing - this fails to parse:

```
<?php
class X {
    public function foo() : 
    {
        return $a;
    }
}
```

I can probably work around this with a hacky regex for temporary updates FWIW

**Comment by muglug** [comment]
Hey @TomasVotruba - thanks for the heads-up. I'm aware of the other parser, and [have decided against using it](https://github.com/vimeo/psalm/issues/520#issuecomment-430760067) - it still has a few bugs around handling of valid PHP syntax, and I'd rather deal with these minor parsing-of-invalid-code gripes vs parsing-of-valid-code gripes.

@nikic has also shown a great willingness to indulge those of us who are starting to use PHP Parser for making live updates to code - [some](https://github.com/nikic/PHP-Parser/releases/tag/v4.0.3) [recent](https://github.com/nikic/PHP-Parser/releases/tag/v4.0.2) releases have explicit callouts to improved error recovery in certain situations to allow the rest of the AST to be parsed.

**Comment by muglug** [comment]
Example where Php Parser from a missing semicolon: https://getpsalm.org/r/bffe1b1f43, Psalm is still able to infer the return type is wrong.

**Comment by muglug** [comment]
Thanks!

**Comment by nikic** [comment]
I've implemented this with the returnType set to null on error. Is that fine? `Expr\Error` doesn't really fit here from a typesystem perspective.

**Comment by TomasVotruba** [comment]
@muglug I see, I haven't noticed that.

Could you share some parts in psalm where this is used?

**Comment by muglug** [comment]
> Could you share some links to psalm where this is used?

Short answer: not yet

Longer answer: The latest releases for Psalm allow you to [run a language server](https://getpsalm.org/docs/language_server/) to show diagnostics on open and save.

A lot of similar language servers support onChange events too, and I'm working on adding that support to Psalm in [this branch](https://github.com/vimeo/psalm/tree/server-temp-changes).

Part of that effort involves incremental scanning - that is, [scanning only the part of the AST](https://github.com/vimeo/psalm/blob/b46db051fb47601ceb13cc719577f481f3f770e0/src/Psalm/Visitor/OffsetMapCheckerVisitor.php#L120-L126) that the user has changed, and readjusting file offsets in the resultant AST to match the expected one. If that partial parsing fails, a [hacky fix](https://github.com/vimeo/psalm/blob/b46db051fb47601ceb13cc719577f481f3f770e0/src/Psalm/Visitor/OffsetMapCheckerVisitor.php#L131-L137) is applied and parsing re-attempted, and if that fails the whole AST is re-scanned. Whole-file parsing can be expensive for large files, especially as that same failure will occur, resulting in a `null` AST for the entire file.

Compounding that, while in Language Server mode I also perform AST diffing to ensure that no method gets re-analysed as long as none of its dependents have changed (analysis is much more costly than parsing). Without the above fix that AST diffing would mark every node as having changed, forcing them all to be re-analysed. That's not a problem in a small file, but can be annoying when editing a 5-thousand line file as it means that the illusion of checking-as-you-type is lost.
