### ISSUE TITLE
Error recovery from $a->if($b) {}

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#545]
This would be great, but I understand why it might be out-of-scope.

Given this code

```php
$a->
if($b){}
```

PHP Parser currently panics at those braces.

This parses fine (`$a->if` can be a valid method).
```php
$a->
if($b);
```

and this parses as `$a->$b = 5`, which isn't terrible either:

```php
$a->
$b = 5
```

**Comment by nikic** [comment]
Hrm, this one looks really tricky. As you already noted, the `$a->if($b)` part is already valid code by itself, and by the point we reach the `{` it's going to be hard to change that.

I'm wondering why this isn't getting interpreted as `$a->if($b); {}` though.

**Comment by nikic** [comment]
Ah, I think this happens because of the PHP "feature" to support arrays with both `[]` and `{}`. So actually `$a->if($b){` is still valid syntax, because it could be terminated by something like `$a->if($b){0};`, so the error is only detected at the `}`.

**Comment by muglug** [comment]
> because of the PHP "feature" to support arrays with both `[]` and `{}`

🤦‍♂️

The only other option I can think of is having a version of the parser designed just for possible autocompletion of PHP7 code that dropped support for `{}` access on expressions.

Psalm's LSP mode already uses a separate cache from its regular command-line-invoked analysis, so the soundness of its results (e.g. in CI) wouldn't be affected.

If I opened a PR that created a `PhpParser\ParserFactory::PHP7_AUTOCOMPLETE` parser, might you be willing to accept that? It would apply a couple of patches to `php7.y` and build a separate `Php7Autocomplete.php` parser.

If not, I can close this as there's not much of a way forward.

**Comment by muglug** [comment]
I'm still interested in PRing a change, if it might be accepted? Not sure how https://wiki.php.net/rfc/deprecate_curly_braces_array_access will go, but if it passes it would presumably be a requirement.

**Comment by nikic** [comment]
@muglug What do you think about this variant? https://github.com/nikic/PHP-Parser/commit/9d44edf85dc5882e45fed37a6c541bf20e7c8495

It will not give us the output we really want, but it will treat that as an `$obj->if($expr){}`, which at least preserves the object access for autocomplete, even though the `if` statement will be completely lost.

Is that a useful change?

**Comment by muglug** [comment]
I don’t think so, given that if statements below sometimes inform the type of the object above (e.g. in loops). And it would mean the type checker possible displaying (false positive) errors to the user during autocompletion, which would make for a confusing experience.

**Comment by nikic** [comment]
So the preference here would be to rather fail parsing entirely than provide an AST without the if statement?

Regarding the idea of a separate parser that doesn't support the `{}` array syntax, I don't think this will really help in the end. While `{}` makes the problem worse, even without it we'll already have consumed the whole `$a->if($b)` part, in which case we'd basically end up parsing this as a `$a->if($b); { ... }`, i.e. a code block rather than an if.

**Comment by muglug** [comment]
Yeah, I wondered about that. I’ll have a look this evening to see if/how `tolerant-php-parser` handles it

**Comment by muglug** [comment]
Looking at `tolerant-php-parser`'s output, I there's no way to get what I want with either tool, given it's essentially a guessing game. I'll probably just stick to the current hacky solution (replacing `->` with `~;` and re-parsing the function).

Feel free to close, and thanks for your help!

**Comment by nikic** [comment]
I've reverted https://github.com/nikic/PHP-Parser/commit/94d93f27a5779181e4e89e8d51fccacfcaad49b1 now and am going to close this issue -- don't think there's anything really great we can do here, and inserting a semicolon at the cursor seems like a reasonable workaround.
