### ISSUE TITLE
About goto replace with the real code ?

### ISSUE THREAD

**Issue by ethenoscar2011** [nikic/PHP-Parser#556]
Hello , I have some trouble to replace the goto with the real code , is there any way to deal with it ?
such like the code blow!
```php
<?php 

goto label1;
label3: 
if (name == 'me') {
    goto label2;
}
goto label4;
label 1: 
echo 'here';
goto label3;
label2:
echo "data";
label4:
?>
```

**Comment by TomasVotruba** [comment]
Hi, what exactly are you tring to achieve? Before/After code (diff) would be the best.

```diff
-A
+B
```

Could you provide simpler code that demonstrates your intention?

**Comment by nikic** [comment]
I think the best way to do this is to construct an explicit control flow graph and then match typical structures like if/else, for loops etc inside it. Of course, for simple cases like your example it would be enough to just find the corresponding label for a goto, and replace the goto with the code after the label.

In either case, not really in-scope for this project...

**Comment by hongweipeng** [comment]
@ethenoscar2011  Hi, I also encountered this problem, have you solved it?

**Comment by ethenoscar2011** [comment]
> @ethenoscar2011 Hi, I also encountered this problem, have you solved it?

I am sorry , I could not solve it

**Comment by zhaoyanliang2** [comment]
Anybody who encountered this problem, contact me please.
