### ISSUE TITLE
NameResolver adds namespace to built-in PHP functions

### ISSUE THREAD

**Issue by jeroenherczeg** [nikic/PHP-Parser#569]
After I use the NameResolver visitor, built-in PHP functions, like count(), will also have a namespacedName with the current file namespace.

```PhpParser\Node\Expr\FuncCall Object
(
  [name] => PhpParser\Node\Name Object
    (
      [parts] => Array
        (
          [0] => count
        )
      [attributes:protected] => Array
        (
          [startLine] => 45
          [endLine] => 45
          [namespacedName] => PhpParser\Node\Name\FullyQualified Object
            (
              [parts] => Array
                (
                  [0] => App
                  [1] => Http
                  [2] => Controllers
                  [3] => Api
                  [4] => count
                )
              [attributes:protected] => Array
                (
                  [startLine] => 45
                  [endLine] => 45
                )
            )
        )
    )
```

Is this expected behavior? I would expect the namespacedName only contain ['count'], or am I missing something?

**Comment by nikic** [comment]
`count()` inside a namespace can refer either to the global builtin function `count()`, or a `count()` function in the current namespace. Without further information (e.g. from scanning the whole project and collecting all functions), it's not possible to know which is the case.

It's a reasonable default assumption that this refers to the global `count()` though -- if you want to make this assumption, just ignore the `namespacedName` attribute. It's there in case you want to handle namespaced functions as well.

**Comment by jeroenherczeg** [comment]
Thank you @nikic, also for your opensource work!

**Comment by jeroenherczeg** [comment]
For reference to the docs
https://github.com/nikic/PHP-Parser/blob/master/doc/component/Name_resolution.markdown#the-nameresolver-visitor

> Unqualified function and constant names inside a namespace cannot be statically resolved. Inside a namespace Foo, a call to strlen() may either refer to the namespaced \Foo\strlen(), or the global \strlen(). Because PHP-Parser does not have the necessary context to decide this, such names are left unresolved. Additionally a namespacedName attribute is added to the name node.
