### ISSUE TITLE
parse "<?php" results in error

### ISSUE THREAD

**Issue by Netmosfera** [nikic/PHP-Parser#578]
```php
(new ParserFactory())->create(ParserFactory::ONLY_PHP7)->parse("<?php");
```

> PhpParser\Error : Syntax error, unexpected EOF on line 1

**Comment by nikic** [comment]
PHP requires `<?php` to be followed by whitespace, so a standalone `<?php` is indeed a syntax error. See also https://3v4l.org/kuLmD.

**Comment by Netmosfera** [comment]
In all these years, I never noticed that :D weird. Thanks.
