### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by almi9** [nikic/PHP-Parser#579]
Dear

after I test the code I found that risk 

Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')
(CWE ID 78)

rebuildParsers.php

and that is the place 

    echo "Building $name parser.\n";
    $output = trim(shell_exec("$kmyacc $additionalArgs -l -m $skeletonFile -p $name $tmpGrammarFile 2>&1"));
    echo "Output: \"$output\"\n";

can you please example for me is that code is a risky code? 

thank you

**Comment by nikic** [comment]
The code is indeed risky, but used only by developers to generate files. It is not part of the library itself and will never be called by users of the library.
