### ISSUE TITLE
Add "Use_" node without "Namespace_" parent node

### ISSUE THREAD

**Issue by vvval** [nikic/PHP-Parser#583]
Right now, if parsed file contains `Node\Stmt\Namespace_` node, I can add new `Node\Stmt\Use_` node into its `stmts` array (before 1st `Node\Stmt\Class_` usage). But what if the file doesn't have a namespace? Where should I add the `Node\Stmt\Use_` node?

**Comment by TomasVotruba** [comment]
What happens if you add them before first class?

**Comment by vvval** [comment]
> What happens if you add them before first class?

@TomasVotruba 
I tried to insert the `new Node\Stmt\Use_(...)` into the nodes which I got from the parser:
```php
$nodes = $parser->parse($source);
//$classNodePosition = 2;
$useNodeBuilder = new \PhpParser\Builder\Use_('Example', \PhpParser\Node\Stmt\Use_::TYPE_NORMAL);
$before = array_slice($nodes, 0, $classNodePosition);
$after = array_slice($nodes, $classNodePosition);
$nodes = array_merge($before, [$useNodeBuilder->getNode()], $after);
```
But in this case, the printer failed asserting:
```
assert(): assert($itemStartPos >= 0 && $itemEndPos >= 0) failed
vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php:787
vendor\nikic\php-parser\lib\PhpParser\PrettyPrinterAbstract.php:515```

**Comment by rossity** [comment]
Any update on this? I'm having the same issue. You are unable to add Use statements to a builder factory unless you add a Namespace first.

**Comment by nikic** [comment]
To add a use node outside a namespace you need to add it to the top-level $stmts array.

Not sure where the assertion failure above comes from, but I suspect that maybe you tried to modify the original AST rather than the cloned one?

**Comment by nikic** [comment]
Adding a use statement outside a namespace (but in the top level statements) should work fine. There's not enough information here to determine where the assertion failure comes from.
