### ISSUE TITLE
Consider & argument support

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#584]
I came to a legacy project and tried to parse this:

```diff
-myFunc(&$arg);
+myFunc($arg);
 function myFunc($arg) { }
```

But it seems it's not supported, though it's valid PHP 5.3 code (just deprecated).

> Deprecated: Call-time pass-by-reference has been deprecated in /in/oLWoF on line > 4
> 2

- https://3v4l.org/oLWoF

I want to add upgrade rule to Rector that removes this token. Could I add it to PHP 5 parser?

**Comment by nikic** [comment]
This should work already: https://github.com/nikic/PHP-Parser/blob/master/grammar/php7.y#L495 It's present in both the PHP 5 and PHP 7 parsers.

**Comment by TomasVotruba** [comment]
I have PHP 7.3 installed localy and it throws fatal error. Do you think that's related?

**Comment by nikic** [comment]
@TomasVotruba The error likely comes from something other than PhpParser.

**Comment by TomasVotruba** [comment]
It works untill I include the file (for static analysis). But I think there is no better way to do it.

**Comment by TomasVotruba** [comment]
It's based on PHPStan convention.
To autoload function names and to allow reflection of 3rd party code from `/vendor`.
