### ISSUE TITLE
PHP-Parser can parse mathematical expressions

### ISSUE THREAD

**Issue by zh7314** [nikic/PHP-Parser#585]
i want to parse mathematical expressions ,string like "((99 + 1)-1)",i tried use PHP-Parser,but it is not work,
it's just show me  like this array(
    0: Stmt_InlineHTML(
        value: ((99 + 1)-1)
    )
) ，
is any tools or ways to parse mathematical expressions string ？

**Comment by nikic** [comment]
You need to wrap the expression with `<?php` before and `;` after to make it valid PHP. Then PHP-Parser should be able to parser it.

**Comment by zh7314** [comment]
thanks every helpful
