### ISSUE TITLE
This vs nikic/php-ast

### ISSUE THREAD

**Issue by garygreen** [nikic/PHP-Parser#586]
What's the difference between this and the package [nikic/php-ast](https://github.com/nikic/php-ast) ?

I can't help but think isn't this package just re-inventing the wheel? Surely it's best just to get the AST from PHP directly, rather than implementing ANOTHER ast parser IN PHP which isn't ever going to be as reliable as just using the ast PHP provides?

Not directly related - but I guess it's the same story with other AST parsers out there - a Javascript parser written in Javascript, presumably because Javascript has no official way to give the AST it generates. So people have to constantly write their own inferior solutions which are more unreliable and much slower than their native counterparts.

**Comment by TomasVotruba** [comment]
Long answer: https://github.com/nikic/php-ast/blob/master/README.md#differences-to-php-parser

Short answer: https://www.tomasvotruba.cz/blog/2017/11/06/how-to-change-php-code-with-abstract-syntax-tree/

**Comment by TomasVotruba** [comment]
The main added value of this package I change PHP with PHP. So any PHP programmer can transform PHP in any way.

That's how Rector can work: https://github.com/rectorphp/rector

With just c extension, it would be useless to 99 % of PHP devs.

**Comment by nikic** [comment]
Closing this as @TomasVotruba's links should explain everything...
