### ISSUE TITLE
how to get parsed code Priority of execution

### ISSUE THREAD

**Issue by zh7314** [nikic/PHP-Parser#588]
`$string =  '-1.5+((99 + 1)*2-(10+8))';`
i parsed code，add visitor to traverse the node
```
            $traverser = new NodeTraverser;
            $Visitor = new Visitor();
            $traverser->addVisitor($Visitor);
            
            $modifiedStmts = $traverser->traverse($ast);
```

visitor leaveNode function
```
     public function leaveNode(Node $node) {
        if ($node instanceof Node\Expr\BinaryOp || $node instanceof Node\Expr\UnaryMinus || $node instanceof Node\Expr\UnaryPlus) {
            $this->operator->push($node->getType());
        }

        if ($node instanceof Node\Scalar) {
            $this->data->push((string) $node->value);
        }
    }
```

 i use SplStack to get data and operator ，it look like this
```
SplStack Object
(
    [flags:SplDoublyLinkedList:private] => 6
    [dllist:SplDoublyLinkedList:private] => Array
        (
            [0] => Expr_UnaryMinus
            [1] => Expr_BinaryOp_Plus
            [2] => Expr_BinaryOp_Mul
            [3] => Expr_BinaryOp_Plus
            [4] => Expr_BinaryOp_Minus
            [5] => Expr_BinaryOp_Plus
        )

)
SplStack Object
(
    [flags:SplDoublyLinkedList:private] => 6
    [dllist:SplDoublyLinkedList:private] => Array
        (
            [0] => 1.5
            [1] => 99
            [2] => 1
            [3] => 2
            [4] => 10
            [5] => 8
        )

)
```
but i can't find the way or tool to get priority  of execution
i want to parse like
step one  to do what
step two to do what
step three to do what

**Comment by nikic** [comment]
I don't really understand what the question here is, but either way this is out of scope for the project. As a rule of thumb, sub-nodes are executed in the order they are declared, but actual order of execution in PHP can be quite complex when it comes to details.

Also worth noting that https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/ConstExprEvaluator.php can evaluate constant expression ASTs, if that's all that's needed.
