### ISSUE TITLE
PhpParser\Node\Expr\Variable::toString()

### ISSUE THREAD

**Issue by ahmed-abid** [nikic/PHP-Parser#597]
got this issue :
[Error] Call to undefined method PhpParser\Node\Expr\Variable::toString()

while running some tests using AspectMock caused by this line:

https://github.com/goaop/framework/blob/72521d026692131f4052c1d7b3dad15c846cdd0f/src/Instrument/Transformer/MagicConstantTransformer.php#L94

**Comment by ahmed-abid** [comment]
resolved here: https://github.com/nikic/PHP-Parser/pull/596/files

**Comment by nikic** [comment]
Closing per comment on PR / the linked goaop fix.
