### ISSUE TITLE
Tolerant parser with option to recover from unexpected token error

### ISSUE THREAD

**Issue by deweller** [nikic/PHP-Parser#60]
Is it possible for a parser to recover from an unexpected token and return the nodes that it was able to parse?

Consider the following PHP code:

```
<?php
class MyClass {
    public function myMethod() {
        $this->something
    }
}
```

(Notice the missing semicolon)

When I parse this code, I get the following error:

`Unexpected token '}' on line 5`

And this is the expected behavior.

But what I would like is to parse the statements that the parser knows about.  In other words, I'd like to be able to traverse the Stmt_Class and Stmt_ClassMethod nodes even in spite of the error.

Is this even possible?

I tried working my way through the parse method of PHPParser_Parser to figure it out.  But I do not understand the complexities of how the parser works.  Even if someone could point me in the right direction as to how to solve this problem myself, I would appreciate it.

My reason for the request is this: I'm writing a PHP autocompletion plugin for Sublime Text and I am using PHP-Parser to try to extract the context of the class while the user is typing.

**Comment by nikic** [comment]
Closing this in favor of #170 which links to a more up-to-date implementation.
