### ISSUE TITLE
Request: produce clean bin/php-parse output on stdout

### ISSUE THREAD

**Issue by cyrus-and** [nikic/PHP-Parser#605]
That is, anything that is not the *actual output* should go to stderr. This would allow for example to do:

```console
$ vendor/bin/php-parse -j test.php >test.json
```

Now instead `test.json` begins with:

```
====> File test.php:
==> JSON dump:
```

This is a trivial change but I'm not sure if you're interested. Also trivial would be to write a custom script, but since there's `bin/php-parse` already, it would be nice to just use it.

**Comment by nikic** [comment]
Sound good to me :)
