### ISSUE TITLE
PrettyPrint/PrettyPrintFile for echo expression.

### ISSUE THREAD

**Issue by peng-hui** [nikic/PHP-Parser#608]
```
<?php
$var = "one";
echo "$var  two three";
```

Parse the code above to AST using PHP-Parser, and then use PrettyPrint/PrettyPrintFile for turning back to PHP will raise a fatal error about the strict_type is set to 1. There might be some problem with prettyprinter.

Error Info is as following:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\PrettyPrinterAbstract::p() must implement interface PhpParser\Node, array given, called in /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php on line 388 and defined in /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php:516
Stack trace:
#0 /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php(388): PhpParser\PrettyPrinterAbstract->p(Array)
#1 /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php(403): PhpParser\PrettyPrinterAbstract->pImplode(Array, ', ')
#2 /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinter/Standard.php(834): PhpParser\PrettyPrinterAbstract->pCommaSeparated(Array)
#3 /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php(519): PhpParser\PrettyPrinter\Standard->pStmt_Echo(Object(PhpParser\Node\Stmt\Echo_))
#4 /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpPar in /home/penghui/cuhk/cpu_dos/PHP-Parser-master/lib/PhpParser/PrettyPrinterAbstract.php on line 516
penghui@laptop:~/cuhk/cpu_dos$ cd PHP-Parser-master/lib/PhpParser/

**Comment by nikic** [comment]
I can't reproduce this issue:

```
~/PHP-Parser$ cat input.php 
<?php
$var = "one";
echo "$var  two three";
~/PHP-Parser$ php bin/php-parse -p input.php 
====> File input.php:
==> Pretty print:
<?php

$var = "one";
echo "{$var}  two three";
```
