### ISSUE TITLE
How can I delete the next node in this node?

### ISSUE THREAD

**Issue by wapai** [nikic/PHP-Parser#611]
in current node，I generate new node include next node，so i want delete next node，what should I do，thanks so much

**Comment by wapai** [comment]
@TomasVotruba

**Comment by nikic** [comment]
There's no convenient way to do this, but basically you'll have to go to the parent node and delete it from there. Either by directly operating on the parent node, or having parent references as described in https://github.com/nikic/PHP-Parser/blob/master/doc/component/FAQ.markdown#how-can-the-parent-of-a-node-be-obtained. So go to parent, then find the node you want to delete in its children and delete it.
