### ISSUE TITLE
Failing to parse nikic iter

### ISSUE THREAD

**Issue by theofidry** [nikic/PHP-Parser#612]
You can find the original [here](https://travis-ci.org/humbug/php-scoper/jobs/538602589#L1586).

To reproduce:

- clone https://github.com/humbug/php-scoper
- run `make e2e_025`

I think the issue comes from:

```
<?php

namespace iter\fn;

```

As `fn` has been picked as the short closure name. The token parsed here is `T_FN` instead of previous `T_STRING` so the parser bails out at the unexpected token

**Comment by nikic** [comment]
Assuming you're not running on 7.4, as a workaround you can stop using the Emulative lexer.

**Comment by theofidry** [comment]
>Assuming you're not running on 7.4

That was on PHP 7.2.18 I think.

May I ask what the emulative lexer is for?

**Comment by nikic** [comment]
@theofidry Emulates lexer behavior of future PHP versions. In this case that means that we recognize `fn` as a keyword.

**Comment by theofidry** [comment]
But isn't it the case here? That `fn` _is_ interpreted as a keyword which is not allowed in a namespace name?

**Comment by nikic** [comment]
@theofidry Yes, in PHP 7.4 this is no longer valid code. I'll release a new version of iter that changes the namespace soon, maybe later today.

**Comment by theofidry** [comment]
Alright, will be closing this issue then as it's to be fixed in the `nikic/iter` package itself then :)

**Comment by nikic** [comment]
I've released version 2.0 of nikic/iter with the namespace rename.

**Comment by theofidry** [comment]
Thanks! Will update ASAP :)
