### ISSUE TITLE
Feature request: add builders for namespace, use, and traits.

### ISSUE THREAD

**Issue by hinikato** [nikic/PHP-Parser#62]
I have similar to #61 feature request: It would be nice to add builders for namespace and use statements as well to add a capability to generate a whole PHP file: https://github.com/myak/framework/blob/master/lib/Myak/Code/CodeGenerator.php (see ns() and uses() methods). Probably builder for traits would be also useful.

**Comment by sh-dude** [comment]
Is it a possible to generate the following code using BuilderFactory and PrettyPrinter?
```php
<?php
namespace {
    use Foo\BarTrait;
    use PHPUnit_Framework_TestCase as TestCase;

    class Test
    {
    }

    class MyTest extends TestCase
    {
    }
}
```
If I try to use namespace with empty name I get LogicException:
```
$builderFactory = new BuilderFactory();
$builderFactory->namespace(null)  // Exception here!
    // ->addStmt($stmt);  
```
If no please consider ability to add support of this case.

**Comment by nikic** [comment]
@sh-dude Done: https://github.com/nikic/PHP-Parser/commit/f9fc2fc9ee3b3672aba185d609483484e8cae34b

**Comment by nikic** [comment]
"Use" builder added as well in https://github.com/nikic/PHP-Parser/commit/0c34706799d298864a8e0cd4b1cb3eff710540bc, so closing this FR.
