### ISSUE TITLE
Constant documentation block parsing

### ISSUE THREAD

**Issue by mglaman** [nikic/PHP-Parser#624]
I'm not sure if this belongs in this library, or libraries which extend this (such as phpstan/phpdoc-parser.) We're currently needing to check for deprecated constant usages, and would like to extract docblock comments from constants.

For example:

```
/**
 * Defines the format that dates should be stored in.
 *
 * @deprecated in Drupal 8.5.x and will be removed before Drupal 9.0.x. Use
 * \Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface::DATE_STORAGE_FORMAT
 * instead.
 *
 * @see https://www.drupal.org/node/2912980
 */
const DATETIME_DATE_STORAGE_FORMAT = 'Y-m-d';
```

It seems ConstFetch only have the start and endline. Not sure where to begin looking on building this feature

**Comment by nikic** [comment]
As this is a constant declaration, the doc comment will be on a node of type `PhpParser\Node\Stmt\Const_`. It should be available via the `getDocComment()` method.

**Comment by mglaman** [comment]
🤔 okay, I had a ConstFetch class. I am targeting the wrong class, thanks @nikic I will review and follow up.

**Comment by TomasVotruba** [comment]
@mglaman Same is for properties btw:

- 1 `Property` has many `PropertyProperty`
- 1 `PhpParser\Node\Stmt\Const_` has many `PhpParser\Node\Const_`

**Comment by TomasVotruba** [comment]
Btw, looking at your issue description, you can replace these constants with [Rector rule](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#renameclassconstantrector).

**Comment by mglaman** [comment]
@TomasVotruba :) someone has made a Rector integration for Drupal for our D8 -> D9 deprecation push. I've been using PHPStan to reveal deprecations in our code. The big task is to build deprecation reports and then let contributors use Rector in all of the Drupal contributed code space.

I think I have my problem/thinking backwards. I am able to get PHPStan to check `Node\Expr\ConstFetch`, but I need its brokers to find the parsed definition in its broker. This works perfectly fine with functions, classes, etc. But I probably need to add code to its broker to get the `Node\Stmt\Const_` so I can retrieve the document block.

I appreciate the help on this issue :)

**Comment by mglaman** [comment]
![Screen Shot 2019-08-02 at 3 27 40 PM](https://user-images.githubusercontent.com/3698644/62396958-15cd0880-b53a-11e9-87eb-00f73643a415.png)

😄 I found it out. Now the problem is that PHP makes it impossible to know where a constant is defined so you can parse the file.

**Comment by TomasVotruba** [comment]
I've done this before, it can be done.

You'd have to include all the files, e.g. with composer "files" section, then it's possible.
