### ISSUE TITLE
When parse a php file result a fatal error.

### ISSUE THREAD

**Issue by arjenzhou** [nikic/PHP-Parser#625]
When I am using PHP-parser 3.1.1, a fatal occurred as 
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 37753026 bytes) in /usr/local/PHP-Parser-3.1.1/lib/PhpParser/Serializer/XML.php on line 40
```
What should I do to avoid this?

**Comment by isfett** [comment]
that's a php general error. use php -d memory_limit=-1 or change the memory_limit in your php.ini to a higher amount to fix this

**Comment by arjenzhou** [comment]
Thanks @isfett
