### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by hypeJunction** [nikic/PHP-Parser#626]
I have just received 4.2.3 with a composer update and now my production instance is running out of memory. 

```
PHP Fatal error:  Allowed memory size of 67108864 byte                                                                          s exhausted (tried to allocate 69632 bytes) in /var/www/html/fostercare/docroot/                                                                          vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 28
```

**Comment by hypeJunction** [comment]
```
PHP Fatal error:  Allowed memory size of 67108864 byte                                                                          s exhausted (tried to allocate 20480 bytes) in /var/www/html/fostercare/docroot/                                                                          vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php on line 2108, referer: htt                                                                          ps://faithbridge.arckdev.com/tasks/all
```

**Comment by hypeJunction** [comment]
Downgraded, same issue. Seems like a server issue, will report back and devops are awake.

**Comment by isfett** [comment]
php -d memory_limit=-1 path/to/your/script. that's not a library problem

**Comment by hypeJunction** [comment]
Well, that won't solve the memory leak problem. I don't want the server to go bonkers without memory limits. I will report back when we find out what's leaking memory. It dies on php-parser files, but we need to see the traces. Probably the problem is on our end.

**Comment by nikic** [comment]
This is likely not a problem with the library (well, apart that it could generally use less memory, the meta-issue for that is #349). Two possibilities here are that you're parsing a very large file (some projects contain generated files that a huge) or are keeping too many ASTs in memory. In either case, I don't think I can do anything here.
