### ISSUE TITLE
Literal number separators not parsed on 4.2.3?

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#628]
Hi,
I have this file:

```
<?php

var_dump(1_000);
```

Which works on PHP 7.4: https://3v4l.org/FIlSp

But PHP-Parser 4.2.3 isn't able to parse it, the parser throws an error:

```
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_STRING, expecting ')' on line 3
```

/cc @TomasVotruba

**Comment by TomasVotruba** [comment]
Got same issue in @rectorphp https://github.com/rectorphp/rector/pull/1847
Not sure why

**Comment by nikic** [comment]
```
~/PHP-Parser$ cat t001.php 
<?php

var_dump(1_000);
~/PHP-Parser$ bin/php-parse t001.php 
====> File t001.php:
==> Node dump:
array(
    0: Stmt_Expression(
        expr: Expr_FuncCall(
            name: Name(
                parts: array(
                    0: var_dump
                )
            )
            args: array(
                0: Arg(
                    value: Scalar_LNumber(
                        value: 1000
                    )
                    byRef: false
                    unpack: false
                )
            )
        )
    )
)
```

Same output on 7.2, 7.3 and 7.4.

**Comment by ondrejmirtes** [comment]
Something weird is going on. Can it be used by a different Lexer? I've been using `PhpParser\Lexeer` instead of Emulative. (I don't know what's the difference between them, I can switch.)

**Comment by nikic** [comment]
Emulative is used to emulate tokens from future PHP versions, so yes, if you want to support numeric separators while running on an older PHP version, you need to use it.

**Comment by ondrejmirtes** [comment]
Ah, I didn't realize that's the case. Thank you!
