### ISSUE TITLE
Add reference to New_ node to be PHP 5.x compatible

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#631]
I wanted to create following Rector rule:

```diff
-$value = &new DateTime();
+$value = new DateTime();
```

But php-parser misses "&" in `New_` node. It was [deprecated in PHP 5.3+](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.reference) but still valid part of syntax

See https://3v4l.org/0oksT.

Shall I add it to the node + emulative grammar?

**Comment by nikic** [comment]
The `= & new` syntax is supported in the Php5 parser, but not the Php7 one. We could support it in the Php7 parser as well, together with a manual error emission.

**Comment by TomasVotruba** [comment]
So basically the same way as emulative lexer e.g. [for array spread](https://github.com/nikic/PHP-Parser/pull/609/files)?

> together with a manual error emission.

What exactly does that mean?

**Comment by TomasVotruba** [comment]
Closing for lack of need in real world

**Comment by nikic** [comment]
> So basically the same way as emulative lexer e.g. [for array spread](https://github.com/nikic/PHP-Parser/pull/609/files)?
> 
> > together with a manual error emission.
> 
> What exactly does that mean?

A bit late, but what I meant is copying this line https://github.com/nikic/PHP-Parser/blob/603203177e8483205f1f8b8cf31a41ec20a6c880/grammar/php5.y#L567 to the PHP 7 parser together with an emitError() call like https://github.com/nikic/PHP-Parser/blob/603203177e8483205f1f8b8cf31a41ec20a6c880/grammar/php7.y#L71

**Comment by TomasVotruba** [comment]
No troubles! 
I actually saw that only in theory in PHP doc, not worth so much energy if no-one really needs it.
