### ISSUE TITLE
[PHP 8.0] Add Union types

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#636]
Grammar file: https://github.com/php/php-src/pull/4838/files#diff-7eff82c2c5b45db512a9dc49fb990bb8

I guess that should be part of emulative lexer for PHP 7, right?

Should there be PHP 8 parser version (as is PHP 5 and PHP 7)?

**Comment by nikic** [comment]
This is already implemented in https://github.com/nikic/PHP-Parser/tree/union-types ;)

**Comment by TomasVotruba** [comment]
:+1:  Quick one :)

**Comment by nikic** [comment]
Union type support merged and released.
