### ISSUE TITLE
How to resolve the parent interface of the current class interface

### ISSUE THREAD

**Issue by opjklu** [nikic/PHP-Parser#637]
How to resolve the parent interface of the current class interface

**Comment by oscarnevarezleal** [comment]
+1 I also have that doubt.

**Comment by nikic** [comment]
The AST always only represents a single file. Assuming the parent interface is defined in another class, the usual approach is two have a two phase analysis approach: First, you make one pass over all files and build up an index that contains relevant global information. For example (I don't know what exactly you need for your use-case), you may want to store all classes/interfaces and their method signatures, but discard their method bodies. Then in the second pass you do your actual analysis, and can use your built index to look up non-local information, e.g. go from an interface name to the actual interface definition.

**Comment by oscarnevarezleal** [comment]
Thank you, @nikic, make sense.
