### ISSUE TITLE
NumericLiteralSeparatorEmulator issue

### ISSUE THREAD

**Issue by zhaoyanliang2** [nikic/PHP-Parser#639]
https://github.com/nikic/PHP-Parser/blob/f862853987130d73777ca038ec49d4ed5f0d5df4/lib/PhpParser/Lexer/TokenEmulator/NumericLiteralSeparatorEmulator.php#L24

> preg_match() returns 1 if the pattern matches given subject, 0 if it does not, or FALSE if an error occurred.

Should it be like this?
```php
return preg_match('~[0-9a-f]_[0-9a-f]~i', $code) !== 0; 
```

----

In addition, this regular expression can match ***too many*** irrelevant codes, such as `call_user_func_array` `E_ALL` `method_exists` `file_exists` `base64_encode` `base64_decode`. This seems to make performance slightly affected.

**Comment by nikic** [comment]
Nice catch! It should probably just use `(bool)`.

We could make the regular expression more restrictive, do you see any performance issues in practice?
