### ISSUE TITLE
pStmt_For function return two semicolon

### ISSUE THREAD

**Issue by tyonly** [nikic/PHP-Parser#640]
input: $i=0
   `         $var = new Variable("b");
            $new_expr = [];
            if($expr->expr instanceof Node\Scalar\LNumber)
            {
                $new_expr= new LNumber("11");
                $new_expr->setAttribute('kind', 10);
            }
            $init = new Expression(new Node\Expr\Assign($var,$new_expr)); 
        $arr = ['init'=>[$init], 'cond'=>[example code], 'loop'=>[example code], 'stmts'=>example code];
        return new For_($arr);
`

`   protected function pStmt_For(Stmt\For_ $node) { 
        var_dump($this->pCommaSeparated($node->init));exit();
       .......
    }`

output:
`$i=0;`

the output include one semicolon;

**Comment by nikic** [comment]
The `new Expression(...)` is unnecessary and causes the additional semicolon. You can simply drop it.

**Comment by tyonly** [comment]
> 
> 
> The `new Expression(...)` is unnecessary and causes the additional semicolon. You can simply drop it.

OK I'll try

**Comment by tyonly** [comment]
`        $arr = ['init'=>[$init], 'cond'=>[$condition], 'loop'=>[$end], 'stmts'=>$node_if];
        return new For_($arr);`
I'll try use this code,and  return two semicolon too.Then I modify Standard.php with these codes:

```
    protected function pStmt_For(Stmt\For_ $node) { 
        $first = $this->pCommaSeparated($node->init);
        if(!(strpos($first, ';') === FALSE))
        {
            $first = rtrim($first,';');
        }
//        var_dump($first);exit();
        return 'for ('
             . $first . ';' . (!empty($node->cond) ? ' ' : '')
             . $this->pCommaSeparated($node->cond) . ';' . (!empty($node->loop) ? ' ' : '')
             . $this->pCommaSeparated($node->loop)
             . ') {' . $this->pStmts($node->stmts) . $this->nl . '}';
    }
```
