### ISSUE TITLE
Possible wrong token positions?

### ISSUE THREAD

**Issue by isfett** [nikic/PHP-Parser#650]
I assume that the token positions are wrong. But maybe I don't get how it's calculated and I'm just totally wrong.

Here some tokens are dropped: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer.php#L47 

Code-Example:
```
<?php

class Foo
{
    private $number = 4;
}
```

The PhpParser\Node\Stmt\Class_ Object has the current startTokenPos 2 and endTokenPos 17. But it should have startTokenPos 7 and endTokenPos 45.
The PhpParser\Node\Stmt\Property Object has the current startTokenPos 8 and endTokenPos 14. This seems also to be wrong or I didn't get the point how it's calculated. With Whitespaces it should be 23 (from the beginning) or 5 (inside the class) with a length of 20?

I use the PREPER_PHP7 parser actually if this matters.

**Comment by nikic** [comment]
Token positions refer to positions inside `token_get_all()` output. Maybe you are looking for `startFilePos` and `endFilePos`?

**Comment by isfett** [comment]
thanks a lot, I checked it and you are right, **I was looking for this** and didn't get it that startTokenPos refer to position inside token_get_all. Maybe that's something that could be described better here: https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown
