### ISSUE TITLE
PhpParser\NodeAbstract::getDocComment returns null for DocComment separated by comment

### ISSUE THREAD

**Issue by ostrolucky** [nikic/PHP-Parser#652]
We are using PHPCS rule to force marking classes final unless class is specifically ignored. Way how to do this with phpcs is with `// phpcs:ignore` comment. It MUST NOT be as part of PHPDocblock and it MUST be directly above line of code violating the rule, otherwise suppression does not work.

It looks like following
```php
/**
 * @method B b();
 */
// phpcs:ignore
interface A {}
```

Unfortunately, php-parser returns `null` for such code. This of course causes issues down the ecosystem in tools like phpstan.

Interestingly, PHP native `ReflectionClass` returns correct value by calling its`getDocComment`

**Comment by nikic** [comment]
Don't think there's any specific reason for the current requirement that the doc comment must be the last comment before the node, so we can relax this. Especially if PHP Reflection doesn't require it to be directly preceding.
