### ISSUE TITLE
Fails to parse `list(($a))`

### ISSUE THREAD

**Issue by rainbow-alex** [nikic/PHP-Parser#653]
It's not very useful, but this is valid php code:

```php
<?php
list(($a)) = [3];
```

`php -l` accepts it, and it executes.

PHP parser doesn't accept it: `Syntax error, unexpected ')' on line 2`

The same happens for `isset(($a))`.

I'm curious how this is possible, isn't php-parser based on the same parser generation as the zend internal one?

**Comment by nikic** [comment]
Nice catch! The grammar is limited to variables here, while it should accept expressions.

The fact that PHP doesn't throw a compile error for those is a borderline bug though.

> I'm curious how this is possible, isn't php-parser based on the same parser generation as the zend internal one?

They use the same parser generation in that both use a generated LALR(1) parser, but the used grammar is not shared.

**Comment by rainbow-alex** [comment]
> Nice catch!

Thanks, I've been doing fuzz testing for rainbow-alex/phi and this came up. I know there are some more edge case issues, e.g. with `fn` on <7.4. Likely I'll stumble upon a few more. When I feel my coverage is somewhat complete, I'll report those too.

> They use the same parser generation in that both use a generated LALR(1) parser, but the used grammar is not shared.

Ah damn, I've been assuming php-parser would match zend exactly...

**Comment by nikic** [comment]
Should be fixed by https://github.com/nikic/PHP-Parser/commit/9dda080a9dcecd6c9870c2034f97ec690bd4e053 and https://github.com/nikic/PHP-Parser/commit/568236a3051c990c4e54cba710195b9eeefc52e3.

> Thanks, I've been doing fuzz testing for rainbow-alex/phi and this came up. I know there are some more edge case issues, e.g. with fn on <7.4. Likely I'll stumble upon a few more. When I feel my coverage is somewhat complete, I'll report those too.

Do you happen to use https://github.com/nikic/PHP-Fuzzer for that?

**Comment by rainbow-alex** [comment]
No, I've got some code to [generate source fragments](https://github.com/rainbow-alex/phi/blob/master/tests/Parser/data/EXPR.txt) which I run through `php -l` (currently only 7.2 - 7.4). I save those results to be used as `expected` value in assertions when running the same sources through phi. It's specifically about getting parity with the zend internal parser, not finding paths that have programmer errors.

PHP-Fuzzer looks good to test a parser by itself though, I'll definitely look into it.
