### ISSUE TITLE
NameResolver namespaces reserved return types eg: void

### ISSUE THREAD

**Issue by dhensby** [nikic/PHP-Parser#656]
I've tested this on v3 but I think it's also an issue on v4.

When using the `NamespaceResolver` and examining the `returnType` of a `ClassMethod` the type is namespaced in instances when it shouldn't be.

This affects `void` but I also assume it affects other scalars / reserved words as well.

**Comment by nikic** [comment]
Best guess is that you're using the PHP 5 parser rather than the PHP 7 parser.

**Comment by dhensby** [comment]
yep - thanks for the quick reply!

**Comment by dhensby** [comment]
Just to touch on this - if the functions have return types declared, shouldn't the parser be using PHP7?
