### ISSUE TITLE
Call to undefined method PhpParser\Lexer::render()

### ISSUE THREAD

**Issue by snake-py** [nikic/PHP-Parser#657]
Hello,
I am getting undefined method when I am trying to call render:

```
        $lexer = new Lexer(json_decode($delta, true));
        echo $lexer->render();
        return;
```

**Comment by nikic** [comment]
There is no render() method on Lexer, so yes, it is not surprising that you get an undefined method error...

**Comment by snake-py** [comment]
@nikic Thank you for your fast response. 
I just did what was shown in the docu? Did I do it wrong? 
![image](https://user-images.githubusercontent.com/59285387/79265708-d3184a00-7e96-11ea-8459-9a1e7682eb36.png)

**Comment by snake-py** [comment]
Oh damn, I opened in the wrong repo. I am very sorry.
