### ISSUE TITLE
"Unpack" AST into PHP?

### ISSUE THREAD

**Issue by ajthinking** [nikic/PHP-Parser#660]
Given some `$ast` containing "primitive" values for instance
```
PhpParser\Node\Expr\Array_^ {#23868
  +items: array:1 [
    0 => PhpParser\Node\Expr\ArrayItem^ {#23874
      +key: null
      +value: PhpParser\Node\Scalar\String_^ {#23876
        +value: "name"
        #attributes: array:3 [
          "startLine" => 18
          "endLine" => 18
          "kind" => 1
        ]
      }
      +byRef: false
      +unpack: false
      #attributes: array:2 [
        "startLine" => 18
        "endLine" => 18
      ]
    }

```
Is it possible to use php-parser to do something like
```
$value = unpack($ast);
$value == ['name']; // true
```
That is, to turn it BACK into PHP? I noticed the `PhpParser\BuilderHelpers::normalizeValue` method which does the *opposite* ($var to AST) but did not find/understand if my use case is also possible.
Thanks!

**Comment by nikic** [comment]
You're probably looking for https://github.com/nikic/PHP-Parser/blob/master/doc/component/Constant_expression_evaluation.markdown?

**Comment by ajthinking** [comment]
Spot on! Thanks nikic
