### ISSUE TITLE
use parser for limited functionality php

### ISSUE THREAD

**Issue by prashant-saxena** [nikic/PHP-Parser#663]
Hi,

Previously I have written a simple php templating class that was processing the php file using php's **token_get_all** function to check and limit the set of expressions that are allowed. How ever **token_get_all** doesn't give you much detail info compare to this parser.
The idea is to use parser to check and limit the functionality that is allowed in a php file. For example
only for, foreach, if/else and method call using __this__ is allowed and if anything else is available then throw a warning and then you can strictly check the syntax of allowed expressions.

I'm pretty sure this can be achieved by parser and malicious code injection can be prevented completely, I just need a direction how do I implement above logic.

Cheers
Prashant

**Comment by ondrejmirtes** [comment]
You should look into custom PHPStan rules for that. PHPStan is built on top of nikic/php-parser but it also does type inference, PHPDoc parsing and much more.

See:

* https://phpstan.org/user-guide/getting-started
* https://github.com/phpstan/phpstan-src/tree/master/src/Rules
* https://github.com/ergebnis/phpstan-rules

**Comment by nikic** [comment]
If it's just a matter of allowing / forbidding certain statement / expression kinds, you can use a node visitor (https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown) to explicitly list everything that is allowed:

```php
use PhpParser\{Node, NodeTraverser, NodeVisitorAbstract};

$traverser = new NodeTraverser;
$traverser->addVisitor(new class extends NodeVisitorAbstract {
    public function leaveNode(Node $node) {
        if ($node instanceof Node\Stmt\If_ ||
            $node instanceof Node\Stmt\While_ ||
            ...
        ) {
            return; // Allowed
        }
        throw new Exception("Not allowed!");
    }
});
$stmts = ...;
$traverser->traverse($stmts);
```

If you need more complex, type-based criteria, then basing on an existing type inference engine as suggested above would be the way to go.
