### ISSUE TITLE
Empty JSON Dump

### ISSUE THREAD

**Issue by erwanlr** [nikic/PHP-Parser#664]
When trying to parse this file: https://github.com/WordPress/WordPress/blob/master/wp-includes/ID3/module.audio-video.riff.php, the JSON dump is empty, even though there is an AST returned when dumping normally.

```
% php vendor/bin/php-parse -j module.audio-video.riff.php
====> File module.audio-video.riff.php:
==> JSON dump:

```

```
% php vendor/bin/php-parse module.audio-video.riff.php
====> File module.audio-video.riff.php:
==> Node dump:
array(
    0: Stmt_Expression(
        expr: Expr_StaticCall(
            class: Name(
                parts: array(
                    0: getid3_lib
                )
[SNIPPED]
```

Other files affected by this from the ID3 library:
- ID3/module.audio.flac.php
- ID3/module.tag.id3v2.php
- ID3/module.audio-video.quicktime.php

**Comment by nikic** [comment]
Most likely the file contains non UTF-8 strings, which cannot be JSON encoded.

**Comment by erwanlr** [comment]
Yep, seems like it was that.

Thanks!
