### ISSUE TITLE
How to reconstitute the parsed content of a \PhpParser\Node\Expr\ClassConstFetch

### ISSUE THREAD

**Issue by rquadling** [nikic/PHP-Parser#673]
I've got a PHPStan rule that validates some constraints of an Enumeration class.

The code all works. Coverage is fine. But I'm getting a little stuck with the static analysis.

Using PHP 7.4 : PHPStan 0.12.30 (which is using a PHAR'd nikic/php-parser at v4.5.0).

I'm trying to correct the static analysis for this piece of code:

```php
        switch (\get_class($rawValue)) {
            case ClassConstFetch::class:
                // A 'SomeClass::class' is not the same as 'SomeClass::constant'.
                $constant = \sprintf(
                    '%s::%s',
                    $rawValue->class, // tried with ->__toString(), (string), and ->toString()
                    $rawValue->name
                );
                switch ($rawValue->name) {
                    case 'class':
                        $value = $constant;
                        break;
                    default:
                        $value = \constant($constant);
                }
                break;
```

But PHPStan (level 8 checking) correctly complains about the other possible type that could be there :
```
  162    Call to an undefined method PhpParser\Node\Expr|PhpParser\Node\Name::toString().              
  163    Call to an undefined method PhpParser\Node\Expr\Error|PhpParser\Node\Identifier::toString().  
```

So, from `$rawValue` is there a way to get the constant that has been parsed in a cleaner way than me composing myself using string concatenation?

**Comment by nikic** [comment]
The problem is that `ClassConstFetch::$class` can be either a class name, or an expression, such as `$variableClassName::FOOBAR`. You'll want to do something along the lines of:

```php
if (!$rawValue->class instanceof Name) {
    throw new ConstExprEvaluationException("Cannot evaluate class constant with variable class name");
}
// $rawValue->class known to be Name here, can use (string), ->toString() etc.
```

**Comment by rquadling** [comment]
Aha! So subdividing the logic for class and expression would help here for the rendering,

My use case is that I'm validating the definition of class constants, so no potential for them to be an expression (at least in the current PHP versions).

But this will certainly help me move on.

Thank you.
