### ISSUE TITLE
[Question] Is it possible to detect if ClassMethod Node is actually a method from a trait? 

### ISSUE THREAD

**Issue by LoopKarma** [nikic/PHP-Parser#677]
Any ideas how I can detect is some ClassMethod Node is a method defined in a trait only?

**Comment by nikic** [comment]
You either need to remember whether you are currently inside a trait in your NodeVisitor, or you need to add parent references, as described in https://github.com/nikic/PHP-Parser/blob/master/doc/component/FAQ.markdown#how-can-the-parent-of-a-node-be-obtained. In this case you can just check whether your parent node is a trait or not.

**Comment by LoopKarma** [comment]
@nikic thank you for the fast answer, I will check approach with parent node

**Comment by LoopKarma** [comment]
Hey I'd like to check one thing. I've checked AST produced from php class with trait usage and there is nothing that can bound method call with used trait. Does this mean that it's better to created AST from trait as well and then somehow compare ClassMethod nodes?
