### ISSUE TITLE
[PHP 8.0] Support for static as return type

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#679]
RFC: https://wiki.php.net/rfc/static_return_type

The parser cannot currently parse this: https://phpstan.org/r/c33ac255-8b28-4c81-a664-e1bf17e5fb91

/cc @TomasVotruba Could you look into it? Looks like you have many great contributions recently .)

**Comment by nikic** [comment]
Static return type support added in https://github.com/nikic/PHP-Parser/commit/7f398769a09a87f60516cb47ba6bf075dde88661.

**Comment by ondrejmirtes** [comment]
Thank you very much!
