### ISSUE TITLE
[Question] Viktor score: percentage of if and foreach

### ISSUE THREAD

**Issue by szepeviktor** [nikic/PHP-Parser#680]
Hello! I quiet frequently meet poorly written PHP code.
How is it possible to count statements and function calls only (e.g. exclude value assignments) inside functions and methods and calculate the percentage of `if` and `foreach`.
Thank you.

**Comment by szepeviktor** [comment]
You may have guessed that _poorly written code_ means almost only if+foreach inside functions.

**Comment by mfn** [comment]
"Viktor Score"

😄

**Comment by nikic** [comment]
General approach here would be to use a node visitor (https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown) and then check the nodes you're interested in, such as `PhpParser\Node\Stmt\If_` or `PhpParser\Node\Stmt\Foreach_`.
