### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to PhpParser\NodeTraverser::traverseNode() must implement interface PhpParser\Node, string given

### ISSUE THREAD

**Issue by williamdes** [nikic/PHP-Parser#687]
Using [Doctum](https://github.com/code-lts/doctum#readme) I have this issue, I tried to switch to PHP 7.4 just in case but it does not solve the issue.
Doctum 5.0.1 uses `"nikic/php-parser": "~4.5",`
https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/709689913#L350

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\NodeTraverser::traverseNode() must implement interface PhpParser\Node, string given, called in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 223 and defined in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:109
Stack trace:
#0 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode('object(PhpParse...')
#1 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#3 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\ in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 109
```

```
Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\NodeTraverser::traverseNode() must implement interface PhpParser\Node, string given, called in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 223 and defined in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:109
Stack trace:
#0 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode('object(PhpParse...')
#1 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#3 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\ in /home/travis/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 109
```

**Comment by williamdes** [comment]
Same using my phar: https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/709799949#L311

**Comment by williamdes** [comment]
Same at https://github.com/laravel/laravel.com-next/pull/124

**Comment by nikic** [comment]
Please provide a minimal reproduction.

**Comment by williamdes** [comment]
@nikic I would like some help because for now I struggle reproducing this issue on any of my workstations and versions of PHP, with docker or not

Could you please help me ?

The php version does not seem to  have something to do with this issue, TravisCI has the error. Using docker on the same Ubuntu version I could not reproduce it.

**Comment by nikic** [comment]
@williamdes Based on the trace, the best guess I have is that you have an `enterNode()` handler that returns a string somewhere.

**Comment by nikic** [comment]
Maybe https://github.com/nikic/PHP-Parser/blob/acaf3fecad7f2ee0d82bb51ea680e396aae07b97/lib/PhpParser/NodeTraverser.php#L275 could be extended with more sanity checks, to catch this closer to the source (if it's indeed the issue).

**Comment by nikic** [comment]
No, that's not it, returning a string from enterNode() would already throw. I don't really see how this can happen, as we check that `$node instanceof Node` and the replacement also only happens if `$return instanceof Node`, so by rights this method can only be called with `$node` being a `Node`.

Maybe this is a PHP bug?

**Comment by nikic** [comment]
Do you have some instructions on how to run Doctum on an affected codebase (even if it does not reproduce for you)?

**Comment by williamdes** [comment]
> Do you have some instructions on how to run Doctum on an affected codebase (even if it does not reproduce for you)?

Yes, basically you can do is:
- Clone an affected repo (`git@github.com:phpmyadmin/phpmyadmin.git`) branch: `QA_5_0`
- Follow the script:
```yml
      install: curl -O https://doctum.long-term.support/releases/latest/doctum.phar
      script:
        - chmod +x ./doctum.phar
        - php ./doctum.phar --version
        - php ./doctum.phar --no-interaction update ./test/doctum-config.php
```
- Use the config from my PR (https://github.com/phpmyadmin/phpmyadmin/pull/16273/files#diff-354f30a63fb0907d4ad57269548329e3R176)

My PR should show you how to setup Doctum (https://github.com/phpmyadmin/phpmyadmin/pull/16273)

I hope you will be able to reproduce this issue, anyway thanks a lot for the above comments. Let me know if you expect me to do something :)

**Comment by nikic** [comment]
I've managed to track this down to this genius piece of code: https://github.com/phpDocumentor/ReflectionDocBlock/blob/1ac416df3f66c542f2d3688925105b539f064b64/src/DocBlock/Tags/InvalidTag.php#L78

NodeTraverser iterates over the array by-reference, the reference gets captured by the exception trace and that code ends up converting the node into a string :(

This needs to be fixed in phpDocumentor/ReflectionDocBlock, and I will also fix https://bugs.php.net/bug.php?id=79108 for PHP 8.0, to ensure this kind of interference is impossible in the future.

**Comment by nikic** [comment]
I've fixed the issue on the PHP side for PHP 8, and reported https://github.com/phpDocumentor/ReflectionDocBlock/issues/249 for ReflectionDocBlock. Closing here as the rest is outside the scope of PhpParser.

**Comment by williamdes** [comment]
Thank you so much!!
