### ISSUE TITLE
No longer to parse PHP 7.4 syntax in php parser

### ISSUE THREAD

**Issue by GrahamCampbell** [nikic/PHP-Parser#690]
The following file is valid PHP 7 syntax, however php parser rejects it:

```
<?php

class Match {}
```

**Comment by GrahamCampbell** [comment]
Do we need to separate PHP 7 from 8 in the same way as 5 from 7?

**Comment by GrahamCampbell** [comment]
Similarly, `T_NAME_*` is a bit of a pain. It would be nice to be able to set the target language version to 7.4 or 8.0, and have the correct parsing behaviour.

**Comment by ondrejmirtes** [comment]
Yeah, I wanted to suggest Emulative lexer to be configurable with a PHP version but unfortunately spilled water on my Macbook during preparing a PR for that and killed it on Wednesday 😂

**Comment by ondrejmirtes** [comment]
I first discovered this problem here: https://github.com/nikic/PHP-Parser/pull/672#issuecomment-659343331

**Comment by GrahamCampbell** [comment]
Yeh, the match PR was the breaking point for me too. I know that technically each minor PHP 7 release had breaking syntax changes too, but PHP 8.0 seems to have changed a particularly large amount. Indeed, the PHP 7 integration tests (https://travis-ci.org/github/nikic/PHP-Parser/jobs/711719487) in this repo are actually failing, which is a pretty good indicator that we need to separate PHP 7 and 8.

**Comment by GrahamCampbell** [comment]
So, if this is even wanted, the question is how we backtrack without messing up libraries. Do we say that it was a bug that PHP7 mode was parsing as PHP8, and break it, or do we maybe change the default parsing mode to PHP8, but if someone explicitly asks for PHP7, they get PHP7 still.

**Comment by muglug** [comment]
I think there should be a distinct PHP Parser mode for PHP 8, and the current PHP 7 parser mode must not parse match expressions or union types or really any other PHP 8 syntax.

**Comment by nikic** [comment]
> Yeah, I wanted to suggest Emulative lexer to be configurable with a PHP version but unfortunately spilled water on my Macbook during preparing a PR for that and killed it on Wednesday.

Happy to accept this -- though it's important here to not just disable forward emulation by version, but have reverse emulation if you're running on a newer PHP version and want to parse an older one. Reverse emulation should generally be a lot simpler than forward emulation though.

> Similarly, T_NAME_* is a bit of a pain. It would be nice to be able to set the target language version to 7.4 or 8.0, and have the correct parsing behaviour.

I will not support non-T_NAME token representation. Supporting two canonical token dialects is more work for me and anyone else who needs the token representation. It's a one time effort for you to update to the new representation (as I already take care of emulation for you), but a long-term maintenance burden if you need to support both.

>  Indeed, the PHP 7 integration tests (https://travis-ci.org/github/nikic/PHP-Parser/jobs/711719487) in this repo are actually failing

These are not PHP 7 integration tests. These are PHP 8 integration tests running on an old PHP version to test emulation. PHP 8 support is not finished yet, thus the failures.

> I think there should be a distinct PHP Parser mode for PHP 8, and the current PHP 7 parser mode must not parse match expressions or union types or really any other PHP 8 syntax.

A PHP 8 parser will have to be introduced at some point. However, I expect the only difference will be the treatment of concatenation precedence. This library has always been very liberal with accepting code from newer PHP versions. It's an explicit non-goal to reject this at the parser level, though of course you can check for the presence of new features in the AST, if you like.

**Comment by GrahamCampbell** [comment]
> These are not PHP 7 integration tests. These are PHP 8 integration tests running on an old PHP version to test emulation. PHP 8 support is not finished yet, thus the failures.

The PHP 7 integration tests also fail. That's what I meant to say.

**Comment by nikic** [comment]
It should now be possible to control the emulation level by passing `['phpVersion' => '7.4']` to the emulative lexer. For now, the only things that can be emulated in both directions are the `match` and `fn` keywords.

**Comment by GrahamCampbell** [comment]
Thanks for working on this. There seems to be an new issue still with the "old tests":

```
Notice: Undefined array key 383 in /home/travis/build/nikic/PHP-Parser/lib/PhpParser/Lexer.php on line 323
./data/php-src/Zend/tests/ctor_promotion_attributes.phpt:
    Unknown error occurred: TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in /home/travis/build/nikic/PHP-Parser/lib/PhpParser/Lexer.php:363

Stack trace:
#0 /home/travis/build/nikic/PHP-Parser/lib/PhpParser/ParserAbstract.php(208): PhpParser\Lexer->getNextToken('@@', Array, Array)
#1 /home/travis/build/nikic/PHP-Parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#2 /home/travis/build/nikic/PHP-Parser/test_old/run.php(181): PhpParser\ParserAbstract->parse('<?php\n\nclass Te...')
#3 {main}
```

https://travis-ci.org/github/nikic/PHP-Parser/jobs/714099888

**Comment by nikic** [comment]
@GrahamCampbell Those failures are currently expected, because PHP-Parser doesn't implement `?->` support yet.

**Comment by GrahamCampbell** [comment]
Ah, I see. :)

**Comment by GrahamCampbell** [comment]
There's also an issue processing PHP 7.4's "old tests" using PHP_7_4 lexer:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/2829600/89121535-a45ec780-d4b7-11ea-9215-b3a0879523df.png">

**Comment by GrahamCampbell** [comment]
Ah yes, one can see the test was updated on master to make it PHP 8.0 syntax compatible: https://www.diffchecker.com/Ji9tSDqD.

**Comment by GrahamCampbell** [comment]
Is there an issue with emulating PHP 8.0 on 7.4? I ran the old tests again, with php 8.0.0-beta3 tests on PHP 7.4:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/2829600/89121686-d3296d80-d4b8-11ea-9218-f405979378e2.png">

**Comment by ondrejmirtes** [comment]
Thank you @nikic, I really appreciate it!

**Comment by GrahamCampbell** [comment]
Fixed in 4.8.0.

**Comment by sebastianbergmann** [comment]
> It should now be possible to control the emulation level by passing `['phpVersion' => '7.4']` to the emulative lexer. For now, the only things that can be emulated in both directions are the `match` and `fn` keywords.

Does this mean that I must pass `['phpVersion' => '7.4']` when PHPUnit / php-code-coverage is run on PHP 7 and must not pass it when PHPUnit / php-code-coverage is run on PHP 8?

**Comment by nikic** [comment]
@sebastianbergmann If you would like things to be parsed according to the PHP version you're running on, you can directly use `PhpParser\Lexer`. Using `PhpParser\Lexer\Emulative` only makes sense if you do want to support parsing code from newer PHP versions than the one you're current running on. Though passing `['phpVersion' => PHP_VERSION]` explicitly would give you about the same behavior in a roundabout manner.

If you do want to support parsing code from newer (or for that matter, older) PHP versions (which doesn't seem relevant for code coverage though), then you should either just leave the setting at the default value (and not be too loud if a file fails to parse) or determine the target version in some smart way, e.g. based on composer.json or some PHP version setting in a static analyzer.

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann If you would like things to be parsed according to the PHP version you're running on, you can directly use `PhpParser\Lexer`.

Thank you, Nikita. I must have copy/pasted code that uses `PhpParser\Lexer\Emulative` when I started to use PHP-Parser in php-code-coverage. Sorry for the noise.

**Comment by muglug** [comment]
Thanks for this!
