### ISSUE TITLE
PHPStan complaining about traverse and parse

### ISSUE THREAD

**Issue by icanhazstring** [nikic/PHP-Parser#694]
Recently I discovered that phpstan is complaining about the following code:

```
$parser = // instance of Parser
$traverser = // instance of Traverser

$traverser->traverse($parser->parse($code));
```

I receive the following error:
```
Parameter #1 $nodes of method PhpParser\NodeTraverser::traverse()      
         expects array<PhpParser\Node>, array<PhpParser\Node\Stmt>|null given. 
```

Which holds true, because `Parser::parse` does return `Node\Stmt[]` where as `NodeTraverserInterface::traverse` only accepts `Node[]`

https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Parser.php#L14
https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeTraverserInterface.php#L24

I would file a PR to fix this, but don't know which one needs fixing.

**Comment by nikic** [comment]
phpstan is probably complaining about the `|null`. Maybe you need to add a n `assert($stmts !== null)` or something.

**Comment by icanhazstring** [comment]
You are right, me was stupid 🤦 :D
