### ISSUE TITLE
Virtual property \PhpParser\Node\Stmt\ClassLike::@$namespacedName

### ISSUE THREAD

**Issue by xepozz** [nikic/PHP-Parser#695]
I think it's a wrong way to use virtual property and that's why:
1. It's requires to use check `property_exists` before use property value.
2. Static analyzers wrong interpreter annotation with like this message: 
    ```
    ERROR: DocblockTypeContradiction - src/StaticAnalysis/CodeUnitFindingVisitor.php:228:112 - Cannot resolve types for $parentNode->namespacedName with docblock-defined type PhpParser\Node\Name and !isset assertion (see https://psalm.dev/155)
    ```

Therefore I have two ways to solve this bug:
1. Add property to `\PhpParser\Node\Stmt\ClassLike` and initialize as `null` by default.
2. Extend property value with `null` (`@property Node\Name $namespacedName` => `@property Node\Name|null $namespacedName`).

**Comment by ondrejmirtes** [comment]
PHPStan AFAIK doesn't have problem understanding this dynamic property with this extension installed: https://github.com/phpstan/phpstan-php-parser

**Comment by nikic** [comment]
This is a declared property nowadays.
