### ISSUE TITLE
NodeConnectingVisitor bug

### ISSUE THREAD

**Issue by pilot114** [nikic/PHP-Parser#697]
I try to get the previous and next nodes, but only works with the previous ones.
Full example:

```
<?php

include './vendor/autoload.php';

use PhpParser\{Node,
    NodeTraverser,
    NodeVisitor\NodeConnectingVisitor,
    NodeVisitorAbstract,
    ParserFactory
};

$traverser = new NodeTraverser;
$traverser->addVisitor(new NodeConnectingVisitor());
$traverser->addVisitor(new class extends NodeVisitorAbstract {

    public function leaveNode(Node $node)
    {
        if ($prev = $node->getAttribute('previous')) {
            echo sprintf("Find prev: %s\n", get_class($prev));
        }
        if ($next = $node->getAttribute('next')) {
            echo sprintf("Find next: %s\n", get_class($next));
        }
    }
});

$code = '<?php
echo 1;
echo 2;
';

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
$stmts = $parser->parse($code);
$traverser->traverse($stmts);
```

Expected output:

> Find next: PhpParser\Node\Stmt\Echo_
> Find prev: PhpParser\Node\Stmt\Echo_

Current output:
> Find prev: PhpParser\Node\Stmt\Echo_

Tested on php 7.0-7.4

**Comment by nikic** [comment]
I don't think NodeConnectingVisitor works when running multiple visitors in parallel -- it will not set the attributes early enough. You probably need to first run a traverser with only NodeConnectingVisitor, and then another independent one with your own visitor.

**Comment by pilot114** [comment]
Indeed, sequential run solves the problem. Thank!
