### ISSUE TITLE
Emulative lexer should cause parse error with this code

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#704]
Why isn't this parse error with the current Emulative lexer set to PHP 8?

```php
<?php declare(strict_types = 1);

class HelloWorld
{
	private\Date $date;
}
```

It's a parse error for PHP: https://3v4l.org/kX27d

**Comment by ondrejmirtes** [comment]
I can also invert this issue: This code should be parsed as valid (it's by PHP: https://3v4l.org/eBfKf) but in PHP-Parser it fails:

```php
<?php declare(strict_types = 1);

class HelloWorld
{
	function doFoo(): private\Date
	{
	    
	}
}
```

Fails with:

```
====> File test.php:
Syntax error, unexpected T_PRIVATE on line 5
```

**Comment by nikic** [comment]
This should be fixed now. The issue was specific to member modifiers, which I missed because they are part of a different reserved keywords list (semi_reserved rather than reserved_non_modifiers).

**Comment by ondrejmirtes** [comment]
Perfect, thank you!
