### ISSUE TITLE
Error on namespace with backslashes

### ISSUE THREAD

**Issue by ElRochito** [nikic/PHP-Parser#708]
Hi,

I've got this error when I try to parse : 
`Syntax error, unexpected T_NAME_FULLY_QUALIFIED on line 3`

Obviously, I use PHP 7.4.

When my namespace like `namespace MyNamespace;` it's work but when it `namespace My\Namespace;` it doesn't

Thanks for your help

**Comment by nikic** [comment]
Can you share how your namespace declaration looks like exactly (preserving any whitespace there may be)?

**Comment by ElRochito** [comment]
`<?php

namespace Domain\Form\Policies;

use Domain\Form\Models\Formula;
use Domain\User\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class FormulaPolicy
{
    use HandlesAuthorization;

    public function update(User $user, Formula $formula): bool
    {
        return $user->id === $formula->user_id;
    }

    public function delete(User $user, Formula $formula): bool
    {
        return $user->id === $formula->user_id;
    }
}
`

**Comment by nikic** [comment]
Does this issue still exist? I believe this was an incompatibility with swagger-php that has been resolved in the meantime.

**Comment by ElRochito** [comment]
Yes it is! Issue can be closed 😉
