### ISSUE TITLE
Function/method specified parameter type gives error

### ISSUE THREAD

**Issue by Jeckerson** [nikic/PHP-Parser#709]
Tried to modify example from README, by adding `string` type for `$foo` variable:

```
 $code = <<<CODE
<?php

use PhpParser\Error;
use PhpParser\NodeDumper;
use PhpParser\ParserFactory;

$code = <<<CODE
<?php

function test(string $foo)
{
    var_dump($foo);
}
CODE;

$parser = (new ParserFactory())->create(ParserFactory::ONLY_PHP7);
try {
    $ast = $parser->parse($code);
} catch (Error $error) {
    echo "Parse error: {$error->getMessage()}\n";
    return;
}

$dumper = new NodeDumper();
echo $dumper->dump($ast) . "\n";
```

And gives error:

> Parse error: Syntax error, unexpected T_STRING_CAST, expecting '(' on line 5

* Package version: `v4.9.1`
* PHP version: `7.4.10` and `8.0.0beta3`

**Comment by nikic** [comment]
You are using `<<<CODE` instead of `<<<'CODE'`. This makes it an interpolated string and will replace `$foo`. As it is undefined, you will get a notice and it will become an empty string. So you're left with `(string )`, thus the error.

**Comment by Jeckerson** [comment]
Didn't noticed nowdoc syntax. Thank you!
