### ISSUE TITLE
Built-in constants are prefixed when using the NameResolver

### ISSUE THREAD

**Issue by m-vo** [nikic/PHP-Parser#711]
When using the `NameResolver` entities are prefixed with a slash. Why is this also the case for built-in constants like `true` or `false`?

Minimal reproducer:
```php
$content = '<?php $foo = true;';

$parser = (new ParserFactory())->create(ParserFactory::PREFER_PHP7);
$traverser = new NodeTraverser();
$traverser->addVisitor(new NameResolver());

$ast = $traverser->traverse($parser->parse($content));

echo (new PrettyPrinter\Standard())->prettyPrint($ast); //$foo = \true;
```
I'd expected the output to be `$foo = true;` instead.

**Comment by nikic** [comment]
Why should they not be resolved?

Not sure what you're doing, but you may want to pass `['replaceNodes' => false]` to NameResolver, in which case it won't modify the nodes and only adds an attribute with the resolved name. That provides the information without modifying the code.

**Comment by m-vo** [comment]
>Why should they not be resolved?

Maybe my question rather is why the pretty printer outputs `true` as `\true` then. When is this ever helpful? 🙂

**Comment by m-vo** [comment]
Ok, my bad. I didn't think of `true` just being a regular constant that you can possibly redefine.
