### ISSUE TITLE
Different parsing for properties missing semicolons

### ISSUE THREAD

**Issue by muglug** [nikic/PHP-Parser#712]
Not sure if this is avoidable or not, but malformed property parsing has changed with the merging of https://github.com/nikic/PHP-Parser/pull/661

Given a property declaration without a trailing semicolon:

```php
class A {
    /** @var ?string */
    private $foo

    public function __construct(string $s) {
        $this->foo = $s;
    }
}
```

The emulative parser generates an AST that corresponds to

```php
class A {
    /** @var ?string */
    public function __construct(string $s) {
        $this->foo = $s;
    }
}
```

Where previously it generated code that corresponds to

```php
class A {
    public function __construct(string $s) {
        $this->foo = $s;
    }
}
```

You can probably close this (I'm not particularly bothered by it), but just a heads-up.

cc @TomasVotruba

**Comment by nikic** [comment]
I've pushed a change that will retain the full property in this case. Does that work for you?

**Comment by muglug** [comment]
Even better!
