### ISSUE TITLE
Is it possible to detect nested ternaries without parentheses?

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#722]
Basically I want PHPStan to detect situations from this RFC: https://wiki.php.net/rfc/ternary_associativity

Can we differentiate in the AST the first line from the two other lines?

```php
1 ? 2 : 3 ? 4 : 5;   // deprecated
(1 ? 2 : 3) ? 4 : 5; // ok
1 ? 2 : (3 ? 4 : 5); // ok
```

Ideally the Emulative lexer for PHP 8 should have this as a parse error?

**Comment by nikic** [comment]
It should be possible to detect this by checking if the nested ternary is wrapped in `(`/`)` using getFilePos + code or getTokenPos + tokens.

**Comment by ondrejmirtes** [comment]
Alright, I managed to do it :) https://github.com/phpstan/phpstan-src/commit/a231694531d016972ae2814b735a2d38e6fd9f7c

The main thing allowing me to inspect the surrounding tokens is the NodeTokensVisitor.
