### ISSUE TITLE
Access from C# .NET?

### ISSUE THREAD

**Issue by ajhalls** [nikic/PHP-Parser#724]
Is it possible to utilize this to parse PHP from within a C# application? Trying to think through how to do a basic test. I built it into a C# DLL using PeachPie which was super easy, but then with the basic example:

```

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
try {
    $ast = $parser->parse($code);
} catch (Error $error) {
    echo "Parse error: {$error->getMessage()}\n";
    return;
}

$dumper = new NodeDumper;
echo $dumper->dump($ast) . "\n";
```
I am not sure how to translate that into C#. When using Intellisense I can get the following to show up without error messages:
```
Context ctx = Context.CreateConsole(null);
PhpParser.ParserFactory parser = new ParserFactory(ctx);
parser.create(1, null, null);
NodeDumper dumper = new NodeDumper(ctx, null);
```
Obviously there are too many `null` references, but it doesn't let me do anything like `ParserFactory::PREFER_PHP7` and can't find the `parse()` function at all. The `Context ctx` stuff that is there is required by PeachPie. I haven't ever worked with either of these two applications, so learning as I go.

**Comment by nikic** [comment]
Sorry, I don't think there's any meaningful way to use this library from C#.

However, peachpie itself should have some form of parser implementation for PHP, so maybe that's something you could use? From a cursory look, it's located here: https://github.com/peachpiecompiler/peachpie/tree/master/src/Peachpie.CodeAnalysis/Syntax
