### ISSUE TITLE
add phpstan/psalm class-string types (phpdocs)

### ISSUE THREAD

**Issue by staabm** [nikic/PHP-Parser#726]
would you accept a PR which adds a [`class-string` return type](https://phpstan.org/writing-php-code/phpdoc-types#class-string), where appropriate?

this would ease building new tools on top of php-parser, as we could typecheck things on top of it.

recent use-case https://github.com/composer-unused/composer-unused/pull/111

**Comment by nikic** [comment]
At least as used in the PR referenced above, certainly not. Use of `class-string` is inappropriate in this context, as you are confusing classes in the code using PHP-Parser, and classes in the code parsed by PHP-Parser.
