### ISSUE TITLE
PHP Warning: Undefined array key 383 in lib/PhpParser/Lexer.php on line 323 with PHP 8

### ISSUE THREAD

**Issue by sebastianbergmann** [nikic/PHP-Parser#728]
See https://github.com/sebastianbergmann/phpunit/runs/1331313918?check_suite_focus=true#step:12:133 for example:

```
PHP Warning: Undefined array key 383 in /home/runner/work/phpunit/phpunit/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 323
Generating code coverage report in Clover XML format ... PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned
```

**Comment by nikic** [comment]
Token 383 is T_ATTRIBUTE...

**Comment by sebastianbergmann** [comment]
Makes sense, sort of, as this started happening after adding the first code that uses attributes. Is this because I use `ParserFactory::PREFER_PHP7` in php-code-coverage?

**Comment by nikic** [comment]
I think this happens because you PHP-Parser version constraint it too low, and you're installing with prefer-lowest.

**Comment by sebastianbergmann** [comment]
You're right. Sorry for the noise!
