### ISSUE TITLE
Unexpected character ASCII 127

### ISSUE THREAD

**Issue by m4p1e** [nikic/PHP-Parser#730]
php variable name support ` ^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$ `, but when i use \x7f in variable , show me that exception,but why?

**Comment by nikic** [comment]
\x7f is not included in \x80-\xff...

**Comment by m4p1e** [comment]
> \x7f is not included in \x80-\xff...

sorry ,i means thats valid in php5

**Comment by nikic** [comment]
You're right that the rules were different in PHP 5. However, actually supporting this would be quite hard (requires emulating old lexer behavior), and I don't think it is worth it for this edge-case.
