### ISSUE TITLE
Support for PHP 8 code/features

### ISSUE THREAD

**Issue by asgrim** [nikic/PHP-Parser#733]
Hey Nikita! Hope all is well. Just wondering if PHP-Parser might consider support for analysing PHP 8.0 code and features in the future.

I guess it might already be on the roadmap, but I couldn't find a ticket; so sorry if this was already asked!

Many thanks! :pray:

**Comment by Ocramius** [comment]
Seems already part of the changelog: https://github.com/nikic/PHP-Parser/blob/1d1bc8a36459d67acef508b952dad097960b110e/CHANGELOG.md#version-470-2020-07-25

**Comment by asgrim** [comment]
Ah yes, I only did a cursory check of the readme. I'll send a PR to update it then :)
