### ISSUE TITLE
Using the Lexer class in a shutdown function makes the last fatal error lost

### ISSUE THREAD

**Issue by ste93cry** [nikic/PHP-Parser#735]
While trying to debug some failing tests of the `getsentry/sentry-php` package I found out that PHPUnit since a while [calls](https://github.com/sebastianbergmann/php-code-coverage/commit/9568cbcc4753379e6496fee0d57a951b1e55916c#diff-d16e0344560947d040ce5c081d24deec6daa7ce2a91d7fc4f073f6fb9982a430) the parser with non-emulative lexing and that that code is executed inside a `register_shutdown_function` callback. Unluckily, the [Lexer::startLexing()](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer.php#L88) method calls `error_clear_last()` which clears the last catched fatal error and thus the next callback does not know anything about it anymore. I cannot find any call to `error_get_last()` in the source code and so I cannot think about what is the purpose of clearing the error, so I was wondering if it would be possible to remove that function call

**Comment by nikic** [comment]
This is a leftover from an earlier implementation that did use error_get_last(). It should be fine to drop the call now.

**Comment by ste93cry** [comment]
Do you plan to release a patch version soon? This issue is blocking one project I'm contributing to because the tests are broken

**Comment by nikic** [comment]
@ste93cry Done!
