### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by nikic** [nikic/PHP-Parser#737]
See https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works for context, Travis is no longer a feasible CI provider for open-source projects, so the CI setup needs to be moved over to GH actions.

**Comment by mglaman** [comment]
I'll try and give this a go. Github Actions automatically kicks on once a workflow is committed, so I'll experiment against my fork.
