### ISSUE TITLE
Update .gitattributes

### ISSUE THREAD

**Issue by williamdes** [nikic/PHP-Parser#744]
Hi,

My [phar building script](https://github.com/code-lts/doctum/blob/4ba546ab5924dc635bd7252dc5bc1e168543274f/scripts/phar-generator-script.php#L145) did catch that you added a unwanted directory: https://github.com/code-lts/doctum/commit/31f643ef262fd961e7c7bdcfa79f1c417d123419#diff-eb0630b9ce0f53a98adb24768fb1f770bf4457865616961abc1c8658ba536735R4327 `vendor/nikic/php-parser/.github`

**Comment by nikic** [comment]
This was fixed by e3471d94d3be48f8baa8f828dd9914f7b938ac12.
