### ISSUE TITLE
Yield generates error 

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [nikic/PHP-Parser#746]
Hi all, I am trying to parse a file that contains this statement for example:

```
$class = Products::class;
yield new $class();
```

If I parse this code with this function of that file in this way:

`$this->parser->parse($file->getContents());`

I get this error:

```
Call to undefined method PhpParser\Node\Expr\Variable::toString()#0 /Users/alessandrominoccheri/Work/Ale/project/arkitect/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Arkitect\Analyzer\FileVisitor->enterNode(Object(PhpParser\Node\Expr\New_))
#1 /Users/alessandrominoccheri/Work/Ale/project/vendor/arkitect/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Yield_))
....
```

If I remove the line with `yield` parsing it's ok.
I have tried it in many files with the same result.

I am using the 4.10.2 version

Thanks

**Comment by nikic** [comment]
Based on the exception, your own visitor is assuming that `new` only works on constant class names, while in your example it will accept a variable. This does not appear to be related to yield.

**Comment by AlessandroMinoccheri** [comment]
Ok, I understand, my example was a try to understand the problem that happened to parse this Symfony file, the Kernel that contains the `yield` 

https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php

For that reason, I have tried to replicate the behavior.

**Comment by AlessandroMinoccheri** [comment]
I can understand that it's not related with PHP-Parser library so I can close this issue!
