### ISSUE TITLE
Question about PhpToken

### ISSUE THREAD

**Issue by fezfez** [nikic/PHP-Parser#754]
Hello, 

I wonder if there is any plan to use PhpToken::tokenize instead of token_get_all when it's possible.

Anyway thanks for your awesome work!

**Comment by nikic** [comment]
Yeah, this is definitely planned for the next major version ... whenever that may be.

**Comment by nikic** [comment]
Next major version uses `PhpParser\Token`, which is structurally compatible with `PhpToken` (and extends from it on PHP >= 8.0).
