### ISSUE TITLE
[Regression] Error on split namespaces accross lines

### ISSUE THREAD

**Issue by xi-ao** [nikic/PHP-Parser#760]
____
:point_up: This issue has been updated after its creation. It's not a limitation but a regression.
____

Hi,

First of all, thanks for your work on this amazing lib, it helps a lot.

I came accross what I think is an unhandled syntax, where the `use <namespace>;` is split over several lines.
I didn't even know this was a valid syntax, but it's used by Magento 2 and indeed does not trigger any error from PHP:

```php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\CatalogSearch\Model\Adapter\Mysql\Aggregation\DataProvider;

use Magento\CatalogSearch\Model\Adapter\Mysql\Aggregation\DataProvider\SelectBuilderForAttribute\
ApplyStockConditionToSelect; // <= HERE
use Magento\Customer\Model\Session;
// ...
```

> Source: https://github.com/magento/magento2/blob/2.3/app/code/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider/SelectBuilderForAttribute.php

What I get in this case is `Syntax error, unexpected T_STRING, expecting '{' on line xx`

I'll try to take a look at the code myself but I'm not sure I'll be able to fix it.

_Edit: I realize you can always break a namespace anywhere in the code, only before or after a backslash. The more you know._

**Comment by xi-ao** [comment]
:point_up: **Update:** That seems to be a regression somewhere between 4.2 and 4.10.

Parsing the same files with PHP-Parser 4.2 works flawlessly.

**Comment by nikic** [comment]
Namespaced names containing whitespace are no longer supported since PHP 8.0. Due to implementation complexity, this library does not support them for earlier versions either. (Support for that was dropped when PHP 8.0 support was added.)

I've added some explicit documentation of that fact in https://github.com/nikic/PHP-Parser/commit/37ac4ea9c20ffd121ea63b7a4532ad730305f11c.

**Comment by xi-ao** [comment]
OK, that seems fair. Too bad it still breaks with not-yet-PHP8-compatible apps like Magento at this time.
Thanks
