### ISSUE TITLE
PHP-Parser does not properly handle UTF-8 multibyte characters such as U+00C0

### ISSUE THREAD

**Issue by marekdedic** [nikic/PHP-Parser#763]
Hi,
I've encountered an issue where php-parser corrupts hex escaped characters in PHP code. I've made a repro in a [gist](https://gist.github.com/marekdedic/9ef501e2dcc898b9fd0272e25d2e0116) - run `run.php` and diff source and output to see the issue. Somehow deleting anything from this file changes the output of those unicode characters, so it may be file-size related?

Let me know if you need any additional info.

PHP version: `7.4.15`
php-parser version: `v4.10.4`

**Comment by marekdedic** [comment]
Ok, for some reason, when I shorten the file (e. g. remove the first comment), `meld` sees the last 4 lines differently (and also complains about broken encoding), but `vimdiff` sees them as being the same

**Comment by marekdedic** [comment]
Ok, I've made some leeway into this. The file linked in the gist is part of symfony/polyfill-mbstring, so truly some nasty unicode stuff :D

It seems like php-parser "discards" (some?) hex escape sequences and replaces them by the actual characters. While this is fine for most characters, in this particular file, it "de-escapes" characters `\U+0080` (also known as `\xC0`). I am not a unicode expert, but from what I've read putting this character into the file really messes up everything - my editors are not able to read or diff it properly, `mb_ereg_replace` fails etc.

The PR I've linked is overzealous and just hex-escapes everything. This is because my editors (vim, meld) were showing me wildly different files - because they were confused by the `U+0080` I think.

I'll try in a new PR, just hex-escaping `U+0080`, which should do the trick.

**Comment by marekdedic** [comment]
Ok, the plot thickens.

I've fixed `U+0080`, but it's still broken. So that's probably not the issue...

However, after reading some more of the unicode spec and looking at hexedit, I've noticed a different thing:

In the file, there is character `U+00C0`, escaped as `\xC0`. PHP-Parser reads correctly, but prints it as the **byte** `C0`, not as the bytes `C3 80` - the correct UTF-8 way to convert it to from code point to bytes. This is surely incorrect, as the byte `C0` is *forbidden* in UTF-8.

**Comment by nikic** [comment]
You seem to be under the impression that PHP files are required to be UTF-8 encoded. However, this is not the case. PHP files can use any ASCII-compatible encoding. Strings in particular are raw binary data and can use any encoding (or no encoding). A string containing the raw byte `C0` is legal as far as PHP is concerned. I assume that you are seeing issues with some tooling other than PHP itself, which is not capable of handling non-UTF-8 data? Or does PHP actually interpret the contents differently (in which case there would definitely be a bug)?

Just to have it mentioned, it's possible to [preserve formatting](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown#formatting-preserving-pretty-printing) in the pretty printer, which will also retain the original formatting of strings as long as you don't modify the content.

**Comment by marekdedic** [comment]
Oh, OK, my mistake. I knew PHP files didn't have to be UTF-8, but I assumed if I put UTF-8 in, UTF-8 would come out again (since that's what practically everyone uses these days, it didn't occur to me it could be that that's not the case).

So, what is the encoding of the output? Is it no encoding? Yes, I encountered problems trying to open the output in pretty much everything (even `file` and `vim` didn't know what to make of it...). But my original problem was trying to manipulate the output with mb_ereg_replace, which fails on incorrect encoding.

Thanks

**Comment by marekdedic** [comment]
Hi,
after playing with it some more, I can't seem to get the output to be valid UTF-8 in any way - I've tried `mb_convert_encoding` with several source encoding, `iconv`, `utf8_encode`... :/ Any help please? I'd like to `mb_ereg_replace` on the output... Thanks

**Comment by theofidry** [comment]
@nikic is there a way without preserving formatting? I doubt the later can be used within PHP-Scoper (cf. https://github.com/humbug/php-scoper/issues/464)

**Comment by nikic** [comment]
I pushed a possible fix in https://github.com/nikic/PHP-Parser/commit/33d7c8d3d8178b3d2442c85c155b2715d6ed2592. Could you give it a try?

**Comment by miljan-aleksic** [comment]
Hi @nikic, I end up here after weeks misslead about the root of this issue and finally got a clue from the library using the php-parser. I don't know the extens of the issue, but I can confirm your fix has solved our situation where`$values[$key] = ["\x9d" . ...` ended up being `$values[$key] = ["�" . ...`.

**Comment by Skullbock** [comment]
@nikic I can confirm @miljan-aleksic statement, the fix solves our issue, great work!

**Comment by marekdedic** [comment]
Hi, I can also confirm that the fix does the trick: all the tools work fine, `file` recognizes the output, `mb_ereg_replace` doesn't crash. Tested both directly and through PHPScoper.

Thanks a lot for being patient with me on this one, took a long time to figure out what's what!

**Comment by nikic** [comment]
Thanks for the confirmation! I've released a new version with this change (https://github.com/nikic/PHP-Parser/releases/tag/v4.10.5).
