### ISSUE TITLE
Syntax error, unexpected EOF

### ISSUE THREAD

**Issue by zim32** [nikic/PHP-Parser#766]
Trying to parse simple code

```
<?php

function(string $a, int $b) {
    return (int)$a + $b;
}
```

Leads to **Syntax error, unexpected EOF on line 5**

If I add ?> in the end everything is fine.

**Comment by sjerdo** [comment]
This is the same behavior as PHP. The code is missing a semicolon. Adding a PHP end tag matches single line PHP code behavior (e.g. `<?php STATEMENT ?>`, which is valid PHP code)

- Without PHP end tag: https://3v4l.org/M7sI6
- With PHP end tag: https://3v4l.org/6mbD2

What are your intentions for using this code? The given code has no effect: it does nothing and equals an empty file.

Closures should be assigned to a variable, named or executed directly to have any effects.

```
function A(string $a, int $b) {
    return (int)$a + $b;
}
$a = function A(string $a, int $b) {
    return (int)$a + $b;
};
function(string $a, int $b) {
    return (int)$a + $b;
}('1', 2);
```

**Comment by zim32** [comment]
Hm. I think I did something wrong. It's syntax error in php. I thought it was valid syntax
