### ISSUE TITLE
Syntax error in ParserAbstract.php:317

### ISSUE THREAD

**Issue by CreativeChuang** [nikic/PHP-Parser#768]
I tried to parse some php files but a lot of them have thrown the same issue, as described in the title.

**PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected '<' on line 73 in /mnt**
**vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:317**

**Comment by nikic** [comment]
How does line 73 of the file you're trying to parse look like (maybe with a bit of context)?

**Comment by CreativeChuang** [comment]
![Screenshot 2021-04-06 150356](https://user-images.githubusercontent.com/43147844/113764777-6ae6f780-96e9-11eb-98bf-6d7c4de91f8f.png)

**Comment by CreativeChuang** [comment]
I guess it means the line 73 in file ParserAbstract.php but there is nothing there also

**Comment by CreativeChuang** [comment]
![image](https://user-images.githubusercontent.com/43147844/113765180-ecd72080-96e9-11eb-9fa9-ce362e624041.png)

**Comment by CreativeChuang** [comment]
![Screenshot 2021-04-06 151548](https://user-images.githubusercontent.com/43147844/113766029-fc0a9e00-96ea-11eb-8a69-94b417cfe645.png)

**Comment by TomasVotruba** [comment]
Do you still have this issue? It can be probably closed.
If so, could you share a reproducible repository on Github?

**Comment by nikic** [comment]
This isn't actionable without a reproducer, so I'm closing this issue.
