### ISSUE TITLE
[PrettyPrinter] Using PHP_EOL for newline

### ISSUE THREAD

**Issue by AlexeyOnsite** [nikic/PHP-Parser#773]
Currently hard coded "\n" is used for line breaks in pretty printer. It would be nice if pretty printer would use PHP_EOL, for cross plattform compatibillity.

**Comment by nikic** [comment]
Implemented support for CRLF newlines in https://github.com/nikic/PHP-Parser/commit/d43edfbb319616dc305ce806b3653778fc13e76e. You can construct the pretty printer with `["newline" => PHP_EOL]`.
