### ISSUE TITLE
Undefined constant PhpParser\Parser\Tokens::T_ENUM

### ISSUE THREAD

**Issue by jasonmccreary** [nikic/PHP-Parser#776]
Upon a recent `composer update` within my project, I began receiving the following error:

> Fatal error: Uncaught Error: Undefined constant PhpParser\Parser\Tokens::T_ENUM in vendor/nikic/php-parser/lib/PhpParser/Lexer.php:517

Downgrading to version 4.10.4 resolved the issue. Looks like "support for enums" was added in 4.10.5. But seems there is an issue.

**Comment by nikic** [comment]
This kinda looks like the Lexer.php from version 4.10.5 is working together with the Tokens.php of version 4.10.4.

**Comment by jasonmccreary** [comment]
Downstream in the stack, it does look like Rector is the caller. Maybe they overwrote the `Tokens` class. In which case I it looks like [they are now locking the version](https://github.com/rectorphp/rector/commit/442b5b3d51e9a3cb00bbff5c9795ed5e6097ac72). But will admit it seems changes like this probably shouldn't be in a "patch" release.

**Comment by nikic** [comment]
> But will admit it seems changes like this probably shouldn't be in a "patch" release.

Yeah, this should've been a minor version bump. Sorry about that!

**Comment by dvapelnik** [comment]
So, is v4.10.5 broken version and cannot be installed with other pacakges like `rector/rector` and `symplify/phpstan-rules`?
