### ISSUE TITLE
Remove "mt_rand" from PrettyPrinterAbstract

### ISSUE THREAD

**Issue by mvorisek** [nikic/PHP-Parser#778]
see https://github.com/nikic/PHP-Parser/blob/v4.10.5/lib/PhpParser/PrettyPrinterAbstract.php#L148

Why is there a random function?

If we need an unique value here, use private static variable as a counter, but I would still prefer to use stateless solution.

This issue was found during comparison of trace files when debugging https://bugs.php.net/bug.php?id=81041

**Comment by nikic** [comment]
The randomness is there to prevent clashes with any fixed string.

**Comment by mvorisek** [comment]
Can it be removed completely or should it be replaced with static counter?

**Comment by nikic** [comment]
This is won't fix, but after https://github.com/nikic/PHP-Parser/commit/646b490735ac02d7f42081ff8b8674651456ce17 it's possible to avoid by specifying a target PHP version >= 7.3.
