### ISSUE TITLE
Builder for $this?

### ISSUE THREAD

**Issue by burzum** [nikic/PHP-Parser#779]
How do I generate `return $this->someProperty`?

I couldn't figure out how to generate `$this`, not for a property, nor a method.

https://github.com/nikic/PHP-Parser/blob/master/doc/component/AST_builders.markdown I could not figure out how to do it by looking at this page nor by looking at the code.

**Comment by nikic** [comment]
`$factor->var('this')`. Or just `new Expr\Variable('this')`.

**Comment by burzum** [comment]
Thank you! I didn't thought this would be considered as variabel for some reason. :)
