### ISSUE TITLE
Wrong operator priority for expressions containing both +/- and .

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#783]
This changed in PHP 8: https://3v4l.org/FZPg9

For expressions like `'Calculated in '.microtime(true) - LARAVEL_START`, PHP 7.4 reports:

> Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /in/FZPg9 on line 7

But in PHP-Parser it's still the wrong priority:

```
    3: Stmt_Expression(
        expr: Expr_BinaryOp_Minus(
            left: Expr_BinaryOp_Concat(
                left: Scalar_String(
                    value: Calculated in
                )
                right: Expr_FuncCall(
                    name: Name(
                        parts: array(
                            0: microtime
                        )
                    )
                    args: array(
                        0: Arg(
                            name: null
                            value: Expr_ConstFetch(
                                name: Name(
                                    parts: array(
                                        0: true
                                    )
                                )
                            )
                            byRef: false
                            unpack: false
                        )
                    )
                )
            )
            right: Expr_ConstFetch(
                name: Name(
                    parts: array(
                        0: LARAVEL_START
                    )
                )
            )
        )
    )
```

Originally reported: https://github.com/phpstan/phpstan/issues/5168

Of course it would be nice if this behaviour was switchable in the Emulative lexer based on the `phpVersion` option but I'd understand if it was not.

Thank you.

**Comment by nikic** [comment]
Yeah, this is a known issue. I've been holding off on it because it requires introducing a PHP 8 parser variant :(

**Comment by ondrejmirtes** [comment]
Yeah, no worries, they should be using parentheses anyway :)

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/PHP-Parser/commit/0ea134a5077a73c6d85f497a92efcafabd185360. The behavior depends on the version passed to `ParserFactory::createForVersion()`

**Comment by ondrejmirtes** [comment]
Awesome, thank you!
