### ISSUE TITLE
Ability to retrieve parameters from FuncCall and similar types

### ISSUE THREAD

**Issue by TimothyJCowen** [nikic/PHP-Parser#793]
I am trying to create an analyzer that looks at a FuncCall (or MethodCall, or New_...) and checks if any of the parameters of the function have been defined with a [PHP Attribute](https://php.watch/articles/php-attributes#:~:text=A%20PHP%20attribute%20is%20a,declared%20with%20%23%5BAttribute%5D%20attribute.&text=By%20default%2C%20a%20declared%20attribute,%2C%20parameters%2C%20and%20class%20properties.). Depending on the attribute attached to the parameter, the analyzer would ensure that the value being passed to that parameter has certain conditions.
Currently, there seems to be no way of getting the parameter nodes from the function call itself. I have tried using the reflection library provided by PHPStan, however it does not seem to include any ability for resolving attributes.

**Comment by nikic** [comment]
The parser itself doesn't know anything about the method being called -- it will generally be part of a different file, and determining it requires type inference, or may not even be statically possible in some cases. This is definitely out of scope for this project, so basing it on something like PHPStan/Psalm that already needs to resolve calls to declarations is definitely the right idea. However, I'm not familiar with the APIs they expose at all, so I'd recommend asking there...
