### ISSUE TITLE
Question - execute AST

### ISSUE THREAD

**Issue by jorisatabix** [nikic/PHP-Parser#795]
I have a file of which I create an AST. Then I modify the AST. Is it then possible to execute a function within the AST without creating a new file?

**Comment by nikic** [comment]
No -- or at least, there is no AST evaluator part of this project. The only thing that's provided is https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/ConstExprEvaluator.php, which can be used to evaluate constant expressions.

It should be possible to implement something like this, but personally I'd recommend to convert the AST to PHP code and execute that -- either through a new file, or by using eval().
