### ISSUE TITLE
readonly reserved keyword conflicts in php 7.4

### ISSUE THREAD

**Issue by Levivb** [nikic/PHP-Parser#799]
Hey,

Dropping in here real quick.

The latest release (4.12.0) of this package introduces a seemingly incompatible construction for pre php 8.1 projects (https://github.com/nikic/PHP-Parser/compare/v4.11.0...v4.12.0) under certain circumstances.

Whenever running a require-checker (https://packagist.org/packages/maglnet/composer-require-checker) on our code, it uses this package to tokenise relevant files.

When parsing this class: https://github.com/schmittjoh/serializer/blob/master/src/Annotation/ReadOnly.php
the parser crashes with the message: `Syntax error, unexpected T_READONLY, expecting T_STRING`

Since I'm not sure whether this should be fixed here, in `jms/serializer` (or perhaps even in `maglnet/composer-require-checker`?) I'll open an issue in `jms/serializer` as well :)

Seems to me pre php 8.1 projects should not have to be compatible with php 8.1 reserved keywords just yet. (running php 7.4 btw)

Would be great if you could shed some light on this!

**Comment by nikic** [comment]
You can either not use the `Emulative` lexer, or pass in your target PHP version (https://github.com/nikic/PHP-Parser/blob/5a430154993baff5c828aec8350939ce5018f911/lib/PhpParser/Lexer/Emulative.php#L43). The composer require checker should likely not be using the emulative lexer.

**Comment by nikic** [comment]
Apparently it already doesn't since https://github.com/maglnet/ComposerRequireChecker/commit/9f0d65f4bbed8e945e5d3e606f873a61f56e13d3. Maybe you're using an old version?

**Comment by Levivb** [comment]
oh, you'r absolutely right 🤦 

bumping `maglnet/composer-require-checker` from version `2.1` to `3.3` fixes the error.

Sorry for letting you check this 😬 . Today was a bit of a hectic day causing me to skip the usual thorough exploration step (hence the `Dropping in here real quick` in the initial post)

Thanks anyway!

**Comment by bshaffer** [comment]
I've tried passing the `ParserFactory::ONLY_PHP7` flag in, but the error for `T_READONLY` is still thrown. I believe this is because the flag is being added to [`grammar/php7.y`](https://github.com/nikic/PHP-Parser/commit/55c42692320d7295081d9441f33f974f53215a40#diff-14ec37995c001c0c9808ab73668d64db5d1acc1ab0f60a360dcb9c611ecd57ea). Is there a way to not parse 8.1, short of rolling this library back to `4.11`?

**Comment by nikic** [comment]
@bshaffer https://github.com/nikic/PHP-Parser/issues/799#issuecomment-885599753
