### ISSUE TITLE
Unexpected `T_READONLY` if the class property in the constructor has a different modifier

### ISSUE THREAD

**Issue by i582** [nikic/PHP-Parser#800]
Minimal example (From: https://wiki.php.net/rfc/readonly_properties_v2):
```php

class User {
    public function __construct(
        public readonly string $name
    ) {}
}
```

## Actual Behavior

```
Syntax error, unexpected T_READONLY, expecting T_VARIABLE on line 3
```

## Expected Behavior

No error.

## After words

The point seems to be that the `optional_visibility_modifier` grammar rule that is used for 
visibility modifiers for properties in a constructor cannot handle more than one modifier 
at a time. Unlike `method_modifiers`, which is used in other places, for example, when 
defining a property in a class, where no error occurs.

P.S. I looked in the PHP source and there really is a different grammar for this case.

```yacc
optional_property_modifiers:
		%empty					{ $$ = 0; }
	|	optional_property_modifiers property_modifier
			{ $$ = zend_add_member_modifier($1, $2); if (!$$) { YYERROR; } }

property_modifier:
		T_PUBLIC				{ $$ = ZEND_ACC_PUBLIC; }
	|	T_PROTECTED				{ $$ = ZEND_ACC_PROTECTED; }
	|	T_PRIVATE				{ $$ = ZEND_ACC_PRIVATE; }
	|	T_READONLY				{ $$ = ZEND_ACC_READONLY; }

```

**Comment by nikic** [comment]
Thanks for the report, should be fixed by https://github.com/nikic/PHP-Parser/commit/9aebf377fcdf205b2156cb78c0bd6e7b2003f106!
