### ISSUE TITLE
Error when using static return type hint on php8.0

### ISSUE THREAD

**Issue by fernando-rivas-smtp** [nikic/PHP-Parser#809]
```
trait Resolvable
{

    public static function resolve(): static
    {
        return resolve(static::class);
    }

}
```
It doesn't seems to be working properly .. it throws the following error:

`SyntaxError: Parse Error : syntax error, unexpected 'static' (T_STATIC), expecting '{' on line 104`

**Comment by nikic** [comment]
Which version of PHP-Parser are you using? And do you use the `Php7` version of the parser (I don't think the `Php5` version supports static return types)?

**Comment by fernando-rivas-smtp** [comment]
is php 8.0 they introduce the static return type in that version.
