### ISSUE TITLE
sonarqube tag this as an issue

### ISSUE THREAD

**Issue by braguzz** [nikic/PHP-Parser#810]
https://github.com/nikic/PHP-Parser/blob/50953a2691a922aa1769461637869a0a2faa3f53/lib/PhpParser/Parser/Php5.php#L1340

SonarQube tag this line (and the others) as an issue:
Identical sub-expressions on both sides of operator "-"
Using the same value on either side of a binary operator is almost always a mistake. In the case of logical operators, it is either a copy/paste error and therefore a bug, or it is simply wasted code, and should be simplified. In the case of bitwise operators and most binary mathematical operators, having the same value on both sides of an operator yields predictable results, and should be simplified.

its a real issue or not? thanks

**Comment by nikic** [comment]
The analysis is correct per se, but this is generated code, which is why it uses this odd pattern.
