### ISSUE TITLE
Nullsafe method call with VariadicPlaceholder should be a parse error

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#817]
Right now parsing the following code:

```php
$obj?->method(...);
```

leads to this AST:

```
array(
    0: Stmt_Expression(
        expr: Expr_NullsafeMethodCall(
            var: Expr_Variable(
                name: obj
            )
            name: Identifier(
                name: method
            )
            args: array(
                0: VariadicPlaceholder(
                )
            )
        )
    )
)
```

The first-class callable RFC states:

```
The first-class callable syntax cannot be combined with the nullsafe operator.
```

This really surprised me, mainly because NullsafeMethodCall does not extend `CallLike` and its `$args` property is documented to only contain `Arg[]`.

**Comment by nikic** [comment]
I've changed NullsafeMethodCall to extend from CallLike in https://github.com/nikic/PHP-Parser/commit/4122ff3a91fe81ad094b7e0cdbf9231cb82e8262 -- if nothing else, this would be necessary for error recovery mode.
