### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#820]
Hello @nikic, as the news of your departure from the PHP development hit yesterday and everyone expressed their gratitude of how you improved the language in the past year, I also want to join them and tell you how much I appreciate all of your work! I love the improvements you made to the language, and I also want to appreciate your work on PHP-Parser. Today's ecosystem of static analysis tools wouldn't exist if it weren't for you. So thank you and I hope you enjoy your new role!

I also want to ask how you envision the future of PHP-Parser. Since it's vital for PHPStan I want to make sure that it continues to keep pace with the language.

1) Do you have any maintainers in mind that would be able to take over this package and continue developing it?
2) Do you think it should continue to exist under the `nikic` vendor or should it get its own?

**Comment by othercorey** [comment]
This seems a little drastic. Of all the maintainers out there, I don't think nikic is going to neglect the project or ignore PRs.

**Comment by nikic** [comment]
I guess we'll see how it goes, but I do plan to continue maintaining this project.

**Comment by ondrejmirtes** [comment]
Alright, thank you, good to know!

**Comment by nikic** [comment]
Library is still maintained, so I'll go ahead and close this.
