### ISSUE TITLE
Anonymous class does have a name

### ISSUE THREAD

**Issue by darthf1** [nikic/PHP-Parser#821]
Hi!

I'm on PHP 8.0.13.

For a phpstan rule I'm checking whether a defined class is an anonymous class or not. Reading the parser code, if the class does not have a name it is anonymous.

https://github.com/nikic/PHP-Parser/blob/210577fe3cf7badcc5814d99455df46564f3c077/lib/PhpParser/Node/Stmt/Class_.php#L71-L78

With this class:
```php

<?php

declare(strict_types=1);

class SomeClass
{
    public function something(): void
    {
        new class() implements SomeInterface{
            public function someMethod(): string
            {
                return 'ok';
            }
        };
    }
}
```

The class does receive a name and starts with `AnonymousClass`.

![image](https://user-images.githubusercontent.com/17253332/144862189-20d305f0-6c80-4e9f-be84-e36996e7348f.png)

Is there something going on I don't understand? Or should an additional check be made to verify if the class is actually anonymous besides `name === null`?

**Comment by nikic** [comment]
Maybe @ondrejmirtes can help. This library does not set the name for anonymous classes, but phpstan probably does.

**Comment by ondrejmirtes** [comment]
Hi, you're writing a PHPStan rule - you should open a PHPStan issue/discussion, not ask about it in the PHP-Parser repo 😊

**Comment by darthf1** [comment]
Ok, let's do that then.
