### ISSUE TITLE
Parsing performance improvement and easier grammar?

### ISSUE THREAD

**Issue by frodeborli** [nikic/PHP-Parser#824]
Is there demand for faster parsing and a grammar that is easier to understand and modify? I feel I can contribute in this area, and I am just checking to see if there is demand for that.

In such a case, it would involve writing a new grammar and replacing yacc as the parser generator. I've done some very early benchmarks, so it is too early to conclude about performance - but it will definitely be a simpler grammar to work with.

I think a simpler grammar could trigger cool new innovation in the PHP language design because it will become much easier to modify the grammar.

**Comment by othercorey** [comment]
> I think a simpler grammar could trigger cool new innovation in the PHP language design because it will become much easier to modify the grammar.

This is not the php language specification. It is a php parser written in php for reflection.

**Comment by frodeborli** [comment]
> This is not the php language specification. It is a php parser written in php for reflection.

Yes, it is quite obvious that this is not the PHP spec.

The parser is written to be used for reflection? Not allowed to use it for other things? Is that part of the license?
