### ISSUE TITLE
Name::toCodeString() does not include leading \ as documented

### ISSUE THREAD

**Issue by joachim-n** [nikic/PHP-Parser#829]
The docs for this say:

```
     * Returns a string representation of the name as it would occur in code (e.g., including
     * leading backslash for fully qualified names.
```

But the code is just calling toString(), and the docs for that say:

```
     * Returns a string representation of the name itself, without taking the name type into
     * account (e.g., not including a leading backslash for fully qualified names).
```

One method just calls the other, but the two docs are different!

Calling this on a Name that's part of a Use_ statement returns the fully-qualified classname, but without the leading slash.

**Comment by nikic** [comment]
The output differs between `Name`, `Name\FullyQualified` and `Name\Relative`. See for example: https://github.com/nikic/PHP-Parser/blob/a6e34665fd6a2bcefc924cb5fd73788767ae510e/lib/PhpParser/Node/Name/FullyQualified.php#L43

**Comment by joachim-n** [comment]
My AST looked like this:

```
array:1 [
  0 => PhpParser\Node\Stmt\Use_^ {#3190
    +type: 1
    +uses: array:1 [
      0 => PhpParser\Node\Stmt\UseUse^ {#3215
        +type: 0
        +name: PhpParser\Node\Name^ {#3177
          +parts: array:2 [
            0 => "QualifiedNamespace"
            1 => "ShortClassName"
          ]
          #attributes: array:2 [
            "startLine" => 8
            "endLine" => 8
          ]
        }
        +alias: null
        #attributes: array:2 [
          "startLine" => 8
          "endLine" => 8
        ]
      }
    ]
// SNIP
```

so the name in question was a `Name` object.

Is the leading slash omitted for a `use` statement because the actual code for the use statement doesn't have it? That would certainly make sense, but then the documentation in `Name` is incomplete:

```
     * Returns a string representation of the name as it would occur in code (e.g., including
     * leading backslash for fully qualified names.
```

since it's not *always* the case that a fully qualified name has the leading backslash.
