### ISSUE TITLE
Pretty printing does not print the modifiers (static, private, protected etc.) and type on class properties.

### ISSUE THREAD

**Issue by oschildt** [nikic/PHP-Parser#835]
It works fine on methods, but on properties they are omitted.

private IRequestHandler $handler;

prints

$handler;

private string $name = "Dora";

prints

$name = "Dora";

static int $counter = 0;

prints

$counter = 0;

**Comment by dryabov** [comment]
Hmm, the code
```php
<?php

class Test {
	private IRequestHandler $obj;
}
```
is reproduced identically by `prettyPrintFile`. Could you post a minimal example to reproduce the issue?

**Comment by nikic** [comment]
You're probably trying to print a PropertyProperty node rather than a Property node.

**Comment by oschildt** [comment]
> 

Yes. That is. Thank you!
