### ISSUE TITLE
determine position in line

### ISSUE THREAD

**Issue by ckilb** [nikic/PHP-Parser#843]
Hello,

I'm wondering if I did miss it or if it's simply not possible:
Is there a way to get the position of a node in a line?

I know it's possible to get the position in the file via `startFilePos` but what I'd like to have is a `startLinePos`.

**Comment by nikic** [comment]
See https://github.com/nikic/PHP-Parser/blob/5aae65e627f8f3cdf6b109dc6a2bddbd92e0867a/lib/PhpParser/Error.php#L155 for how to do this.

This functionality is not exposed outside the Error class, but you can copy the implementation.

**Comment by ckilb** [comment]
Thank @nikic 
I did something similar. Just wanted to be sure I didn’t miss some already existing functionality.
Might be a lower-priority improvement for the future.
