### ISSUE TITLE
`FunctionLike` must be in `PhpParser\Node\Stmt` namespace

### ISSUE THREAD

**Issue by WinterSilence** [nikic/PHP-Parser#870]
`Function_` in `PhpParser\Node\Stmt` namespace, but `FunctionLike` in `PhpParser\Node`. It's look like strange because `ClassLike` and `Class_` in `PhpParser\Node\Stmt` namespace.

Need create class `PhpParser\Node\Stmt\FunctionLike`, update  classes `Function_`, `ClassMethod`, `Closure` and `ArrowFunction` and add alias `PhpParser\Node\FunctionLike` to keep BC.

Off-top: why `Closure` and `ArrowFunction` in `PhpParser\Node\Expr` namespace instead `PhpParser\Node\Stmt`?

**Comment by nikic** [comment]
This is not in the Stmt namespace because Closure and ArrowFunction are expressions, not statements (they evaluate to a closure object).
