### ISSUE TITLE
5.0.0-alpha1: Discussion about compatibility layer

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#888]
It's impressive that 5.0.0 is almost a drop-in replacement for 4.x. I tried to update it in Roave/BetterReflection and aside from changes in parser constructor and ParserFactory, the test suite stayed green.

But in PHPStan, it's complicated. I don't want to be forced to release PHPStan 2.0 when I update to PHP-Parser 5.0.

There are several factors at play:

* PHPStan is weirdly distributed as a PHAR with zero dependencies, so that it can be installed alongside packages in different versions
* But PHP-Parser inside the PHAR isn't in prefixed namespace as other dependencies are. This is because people write custom rules and extensions on top of PHPStan (https://phpstan.org/developing-extensions/extension-types).

With some hindsight I could have solved this/can solve this in the future, perhaps similarly to how PHPStan ships its own version of BetterReflection under `PHPStan` namespace.

The specific problems that come with bumping PHP-Parser to 5.0 in a minor PHPStan version will cause some custom rules and other projects built on top of PHPStan (like Rector) to break:

* `PhpParser\Node\Closure` is aliased as `PhpParser\Node\Expr\ClosureUse` but it no longer extends Expr. When I look at that, it's perhaps more damaging/confusing than a clean break without any compatibility aliases.
* Same problem with other node types listed in https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md#renamed-nodes with " and no longer extends..." note.

So from one point of view it's impressive that 5.0 almost works as a drop-in replacement for 4.x, but do we really need that? It's a major version and people should be expected to make some changes when upgrading.

What I'd probably prefer more is for the compatibility layer to be optional:

1) Remove files like `DNumber.php` that just do `require __DIR__ . '/Float_.php';`.
2) Move all `class_alias()` calls into a single file that isn't loaded by default.

Then I'd be free to make my own compatibility layer. For all the renamed classes, I'd copy the original classes (with the old name), mark them as `@deprecated` and ship them with PHPStan.

And when the analyzer encouters `PhpParser\Node\ClosureUse`, it calls rules registered for `PhpParser\Node\ClosureUse`, but also rules registered for `PhpParser\Node\Expr\ClosureUse`. And it calls them with a real `PhpParser\Node\Expr\ClosureUse` instance from PHPStan sources and that isn't related to the new `PhpParser\Node\ClosureUse` in the object hierarchy.

Thanks to the PHAR build step, I can do it completely on my side by patching PHP-Parser sources to my needs, but of course, I'd prefer it if I didn't have to do that, and we'd agree on what the solution should be :)

Thank you.

**Comment by ondrejmirtes** [comment]
I also realize that my idea for compatibility isn't going to be perfect, because for example when the user asks for `Array_` and then iterates over items, the value can no longer be used in places where `Expr` is expected (because ArrayItem is no longer an Expr). But I'd like to get as close as possible :)

**Comment by nikic** [comment]
> Then I'd be free to make my own compatibility layer. For all the renamed classes, I'd copy the original classes (with the old name), mark them as `@deprecated` and ship them with PHPStan.
> 
> And when the analyzer encouters `PhpParser\Node\ClosureUse`, it calls rules registered for `PhpParser\Node\ClosureUse`, but also rules registered for `PhpParser\Node\Expr\ClosureUse`. And it calls them with a real `PhpParser\Node\Expr\ClosureUse` instance from PHPStan sources and that isn't related to the new `PhpParser\Node\ClosureUse` in the object hierarchy.

I'm not sure I understand how this is going to work. Maybe this makes this specific case work, but it will instead break others, e.g. if there is an `instanceof` check for `Expr\ClosureUse` (or one of the other classes) somewhere (other than the top-level node type for which it is registered). The class_alias is important to make that work.

I don't really see how this can work fully reliably if you want to retain the extension of Expr, unless maybe your plugin API is versioned and you can rewrite the entire AST to use different nodes before calling into it?

**Comment by ondrejmirtes** [comment]
Yes, it wouldn't be perfect. I could rewrite the whole AST, but at that point that would just be reimplementing PHP-Parser 4.x on top of 5.0... for no reason at all?

It's really nice that PHP 8.2 support is decoupled from 5.0 and is already done on 4.x. That probably means I don't have to hurry upgrading to 5.0 and risking backward incompatibility for PHPStan users with custom extensions.

I will upgrade to 5.0 when I release PHPStan 2.0 some time during the next year. I already have a working branch but I don't want to release 2.0 with new features just yet.

BTW I can also foresee there's gonna be some "dependency hell" situations when PHP-Parser 5.0 is released as there are some popular packages that depend on 4.x. Biggest of them is probably PHPUnit. Given the compatibility layer we could persuade the most popular packages to maybe depend on `^4 || ^5` but of course no one can be forced to do it if they don't want to. (But for PHPStan this isn't a concern beside testing itself during development, because `phpstan/phpstan` is distributed as a PHAR with no dependencies.)

Thank you.

**Comment by nikic** [comment]
> It's really nice that PHP 8.2 support is decoupled from 5.0 and is already done on 4.x. That probably means I don't have to hurry upgrading to 5.0 and risking backward incompatibility for PHPStan users with custom extensions.

Yeah, there's no rush here. I don't plan to add support for PHP 8.3 or newer to the 4.x branch, but that's still a year away now :)

> I will upgrade to 5.0 when I release PHPStan 2.0 some time during the next year. I already have a working branch but I don't want to release 2.0 with new features just yet.

Sounds good!
 
> BTW I can also foresee there's gonna be some "dependency hell" situations when PHP-Parser 5.0 is released as there are some popular packages that depend on 4.x. Biggest of them is probably PHPUnit. Given the compatibility layer we could persuade the most popular packages to maybe depend on `^4 || ^5` but of course no one can be forced to do it if they don't want to. (But for PHPStan this isn't a concern beside testing itself during development, because `phpstan/phpstan` is distributed as a PHAR with no dependencies.)

Right. I hope that at least PHPUnit will be able to support both. This package itself uses PHPUnit for testing, and I believe this currently only works out fine because PHPUnit < 9 did not depend on PHP-Parser :)
