### ISSUE TITLE
PHP 7.4 getStmts interface incompatible - Bug in 4.15, works in 4.14

### ISSUE THREAD

**Issue by sshilko** [nikic/PHP-Parser#893]
```
Fatal error: Declaration of PhpParser\Node\Stmt\ClassMethod::getStmts() must be compatible with PhpParser\Node\FunctionLike::getStmts(): ?array in /app/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/ClassMethod.php on line 105
```

**Comment by nikic** [comment]
`FunctionLike::getStmts()` does not declare a return type on 4.x: https://github.com/nikic/PHP-Parser/blob/2f1fd784fe5560675722a1e5cbbcece5f43bf3a0/lib/PhpParser/Node/FunctionLike.php#L35

It does declare one on master: https://github.com/nikic/PHP-Parser/blob/b0edd4c41111042d43bb45c6c657b2e0db367d9e/lib/PhpParser/Node/FunctionLike.php#L34

It seems like sources from 4.x and master are getting mixed up?

**Comment by sshilko** [comment]
yes that's the issue

**Comment by sshilko** [comment]
👍

**Comment by sshilko** [comment]
True in 4.x branch they look fine, must be local issue

https://github.com/nikic/PHP-Parser/blob/4.x/lib/PhpParser/Node/FunctionLike.php#L35
https://github.com/nikic/PHP-Parser/blob/4.x/lib/PhpParser/Node/Stmt/ClassMethod.php#L86
