### ISSUE TITLE
How to get dependencies from docblock?

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [nikic/PHP-Parser#895]
Hi all,
I would like to know if it's possible to get dependencies from docblock comments?
This is an example:

```
class ApplicationLevelDto
{
    /**
     * @var NotBlank
     */
    public $foo;
}
```

Inside `$node->getDocComment()` I can retrieve the string I know and I can parse in some way, but it could be difficult.
Is it possible to get dependencies inside docblock?

I have tried with `Variable` class without success

**Comment by nikic** [comment]
PHP-Parser itself doesn't provide support for this (or only in the form of NameContext to help with name resolution). You'd want to use an additional phpdoc parser, https://github.com/phpstan/phpdoc-parser is probably a good one.
