### ISSUE TITLE
Parser sometimes mistakes regular comment for phpDoc comment

### ISSUE THREAD

**Issue by Danon** [nikic/PHP-Parser#898]
This source code
```php
<?php
/** @param */ 
function one () {} 
```
is represented as `\PhpParser\Comment\Doc` is `'comments'` attribute.

However, if you remove a space before `@`, like this:
```php
<?php
/**@param*/ 
function one () {} 
```
then the comment is `\PhpParser\Comment`. I have a feeling, that because it starts with `/**` it should be `Doc`.

**Comment by nikic** [comment]
It's a bit weird, but this is indeed how PHP defines doc comments: Some kind of whitespace after the `/**` is required for a doc comment, otherwise it is treated as a normal comment.

**Comment by Danon** [comment]
@nikic Oh, wow.

Okay, so it's not a bug in a parser. Sorry to have taken your time. Great project!
