### ISSUE TITLE
PHP parser 5 compatability with 4.x?

### ISSUE THREAD

**Issue by frodeborli** [nikic/PHP-Parser#902]
I’ve written a PHP interpreter based on this parser - it is part of a project where I want to write a WebAssembly compiler for a (strictly typed) subset of PHP to WASM. A lot of the work is done, but I don’t have support for classes and some of the more advanced modern features of PHP such as generators. I will release the interpreter soon, since it is clearly useful as a separate component (for business logic sandboxing, or even educational purposes).

Anyway, I noticed there being a 5.0 alpha branch. Is the goal to keep the AST structure compatible or mostly compatible with the 4.x version - or should I switch to version 5 as soon as possible? Are there any fundamental changes in philosophy, is what I am asking…

—
For those curious: The interpreter is actually surprisingly fast when JIT is enabled in native PHP. I would guess the performance is comparable to PHP 3 running on a web server 15 years ago.

The purpose of the interpreter, is to enable more advanced compatibility with PHP during compilation of WASM. In short; to evaluate static parts of the program before finally building the WASM byte code - code that runs in the global scope can decide which version of a function gets declared or a value of a global constant for example. All such global code will be evaluated before the WASM is generated. It can probably also help resolve auto loading of classes. It turns out that writing a compiler is a giant, very interesting rabbit hole🤣

**Comment by nikic** [comment]
Version 5 is expected to be largely backwards-compatible with version 4. Differences in the AST structure are mostly renames with compatibility aliases.
