### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [nikic/PHP-Parser#904]
**Description Of Issue:** 

I am unable to buy you a coffee. 

**Steps to reproduce:** 

1. Check readme for button or link, verify not present. 
2. Check github profile for button or link, verify not present. 
3. Check personal website for button or link, verify not present. 

**Notes:** 

User story:

>As a user of software you have donated to the community for free, I would like to be able to buy you a coffee to say thank you.

**Comment by nikic** [comment]
I appreciate the sentiment, but don't plan to open sponsorship at this time...
