### ISSUE TITLE
using `list` in phpdoc

### ISSUE THREAD

**Issue by staabm** [nikic/PHP-Parser#905]
would you accept a PR which turns array-phpdoc types into [lists](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#lists) where appropriate?

**Comment by nikic** [comment]
Are list types supported by both PhpStan and PhpStorm?

**Comment by staabm** [comment]
phpstan and psalm support it.

phpstorm seem to at least not error about it, even if you violate the list constraints:

<img width="265" alt="grafik" src="https://user-images.githubusercontent.com/120441/207428690-dce2d1b5-66e4-493a-9a7a-2280eb7c2ea8.png">

**Comment by nikic** [comment]
For PhpStorm I'm mainly interested in auto-complete not breaking, not so much validation.

I think using `list<>` would be fine for the master branch, which uses phpstan.

**Comment by staabm** [comment]
I did not find any mentions of phpstan at the master branch?

**Comment by nikic** [comment]
> I did not find any mentions of phpstan at the master branch?

Config is in https://github.com/nikic/PHP-Parser/blob/master/phpstan.neon.dist and the dependency in the tools/ directory. IIRC it can't be a dependency of the main project because of version conflicts.
