### ISSUE TITLE
expr printing performance

### ISSUE THREAD

**Issue by staabm** [nikic/PHP-Parser#908]
in phpstan profiles we see in different workloads that pretty printing of expressions take a considerable amount of time of the static analysis run.

see e.g.

<img width="1099" alt="grafik" src="https://user-images.githubusercontent.com/120441/209107731-163192dc-c39c-4329-bd19-5cbd04155b3f.png">

measuered using `bin/phpstan --debug -vvv analyze fonts/cid0kr.ph` ([cid0kr](https://github.com/tecnickcom/TCPDF/blob/2fb1c01bc37487d1f94fe1297f8d8ad1b5c290bb/fonts/cid0kr.php) from TCPDF repo - it happens in other profiles too though)

I just want to leave this issue here, in case you see some performance low hanging fruits in the expression printing parts.

**Comment by nikic** [comment]
It sounds like in this case the "expression" is actually a very large array.
