### ISSUE TITLE
NameResolver::resolveSignature does not resolve Param's default value

### ISSUE THREAD

**Issue by JanTvrdik** [nikic/PHP-Parser#913]
Similar to already fixed https://github.com/nikic/PHP-Parser/issues/188 and https://github.com/nikic/PHP-Parser/issues/360, it would be useful if `Param::$default` was resolved in `resolveSignature` as it may contain e.g. `ClassConstFetch`.

**Comment by nikic** [comment]
This requires arbitrary recursion -- which is the whole point of using a visitor in the first place. If you need this, run name resolution first, without interleaving with other visitors.
