### ISSUE TITLE
different parsing of "elseif" & "else if"

### ISSUE THREAD

**Issue by lc1337** [nikic/PHP-Parser#915]
"elseif" and "else if" should have same meaning, but it's being treated differently

"else if" - incorrect
```
<?php

if(1){
}else if(2){
}else{
}
```
![Screenshot_37](https://user-images.githubusercontent.com/8530123/222936551-eaa62c6a-91cf-4f4b-ae27-636c47c5bca1.jpg)

"elseif" - correct
```
<?php

if(1){
}elseif(2){
}else{
}
```
![Screenshot_38](https://user-images.githubusercontent.com/8530123/222936553-bc916bc0-a313-4d1b-9ef6-b66018fe4579.jpg)

**Comment by nikic** [comment]
`elseif` is a special syntactical feature of `if` statements. `else if` is simply an `else` block that happens to contain an `if`. They are semantically the same, but syntactically quite different.

Now, the parser does sometimes gloss over syntactical differences, and for example will not distinguish between `$$x` and `${$x}`. So I can in principle see an argument in favor of canonicalizing everything to the `elseif` representation.

Maybe @TomasVotruba or @ondrejmirtes have an opinion on that. Personally, I think it's preferable to stay closer to the actual syntactical structure of the program, especially wrt formatting preservation. (To give an example, the `else if` "syntax" allows you to mix normal and alternative form of `if`, while this is not possible with `elseif`. This sounds very painful to untangle.)

**Comment by TomasVotruba** [comment]
I agree with @nikic . 
Having an array suggest there is 1+ items possible, but `else` is always a single item. I haven't had a need to use it differently.

**Comment by lc1337** [comment]
OK, makes sense. 

It's just a pity, because when reconstructing the PHP code back, instead of nice and flat structure of `else if` blocks, I would get a deep nested structure of `else` and `if` blocks.

**Comment by nikic** [comment]
I think we can accommodate this in the pretty printer. We should be able to print it as `else if`. I'll run some tests.

**Comment by nikic** [comment]
Done in https://github.com/nikic/PHP-Parser/commit/aa721520f9dbc64628a87105e6a63931ad9d1833.

**Comment by lc1337** [comment]
Tested and works for me, thanks.

Hopefully it won't cause any troubles for others, since now, when the nested structure is coded explicitly:
```
if(1){
}else{
	  if(2){
	  }else{
	  }
}
```

by parsing + reprinting, it will change it to:
```
if (1) {
} else if (2) {
} else {
}
```
