### ISSUE TITLE
Constructor property promotion support

### ISSUE THREAD

**Issue by WyriHaximus** [nikic/PHP-Parser#917]
Are there plans to add support for constructor property promotion when using this package to generate PHP files? Currently `PhpParser\Builder` is not exposing anyway to do that aside from inheritance and passing a visibility flag to `Node\Param` while overriding the `getNode` method. Are PR's accepted to add support for this?

**Comment by nikic** [comment]
> Are PR's accepted to add support for this?

Yup

**Comment by WyriHaximus** [comment]
> > Are PR's accepted to add support for this?
> 
> Yup

4.x: https://github.com/nikic/PHP-Parser/pull/918
5.x: https://github.com/nikic/PHP-Parser/pull/919 (assumed master is the upcoming 5.x I seen tweets about earlier)

**Comment by WyriHaximus** [comment]
Closing this as this has been implemented through #918 and #919.
