### ISSUE TITLE
Remove redundant parameter

### ISSUE THREAD

**Issue by PavelSPN** [nikic/PHP-Parser#921]
As the "__construct(Expr $value, Expr $key = null, bool $byRef = false, array $attributes = [], bool $unpack = false)" function (in ArrayItem.php) expects 1-5 parameters it would be better to remove redundant parameter in the Php7.php & Php5.php files to prevent possible issues in future.
These issues are found after PHP Stan checks.
Pull request created: https://github.com/nikic/PHP-Parser/pull/920
Patch added.
[remove_redundant_parameter.patch](https://github.com/nikic/PHP-Parser/files/11077551/remove_redundant_parameter.patch)

**Comment by nikic** [comment]
Pull request has been merged, so closing this.
