### ISSUE TITLE
utilize static closures to improve performance

### ISSUE THREAD

**Issue by staabm** [nikic/PHP-Parser#923]
looking at rector profiles one can see node-traversal as a bottleneck.

I wonder whether we can/should use some assumptions to improve performance, e.g. don't traverse into static closures when searching for a `MethodCall` with `var='this'` .

do you think such things are acceptable as a PR?

**Comment by nikic** [comment]
PhpParser only allows finding nodes by class (or generic callback), so it sounds like you're talking about some utility implemented in Rector here?

**Comment by staabm** [comment]
hmm you are right. to make this work we would need e.g. a new class representing method-calls on `$this`.

**Comment by staabm** [comment]
btw: this is the use-case at the rector side:

https://github.com/rectorphp/rector-src/blob/d7a738c67ea10acaec04e1d49febe591aac96ed5/src/PhpParser/NodeFinder/LocalMethodCallFinder.php#L27-L63

**Comment by nikic** [comment]
Closing this as I believe it's out of scope for this library, it needs to be solved on a higher level. E.g. a custom visitor that returns DONT_TRAVERSE_CHILDREN for static closures would work.
