### ISSUE TITLE
Missing support for PHP 8.3 typed class constants

### ISSUE THREAD

**Issue by ju1ius** [nikic/PHP-Parser#925]
I guess the title says it all !

**Comment by nikic** [comment]
Typed constants are supported by PHP-Parser 5 on the master branch.

**Comment by ju1ius** [comment]
> Typed constants are supported by PHP-Parser 5 on the master branch.

Indeed, thanks !

**Comment by nikic** [comment]
Huh, could have sworn I already made a release, but apparently not. Here it is: https://github.com/nikic/PHP-Parser/releases/tag/v5.0.0alpha3

**Comment by kocsismate** [comment]
Thanks for the release! Apparently, it works for php-src with minimal changes.
