### ISSUE TITLE
php generics (for merthods)

### ISSUE THREAD

**Issue by N0zzy** [nikic/PHP-Parser#927]
hi. i use your library and i have some code according to peachpie(c#+php) syntax:

![image](https://github.com/nikic/PHP-Parser/assets/46209742/82d51ffe-36ca-4ef8-9b22-aad41f1c70cb)

![image](https://github.com/nikic/PHP-Parser/assets/46209742/408bc971-b95e-49cb-a421-79e33d20c863)

how do i make the parser ignore the error (generic) or how do i add it myself?

**Comment by nikic** [comment]
Generics are not supported by this library (as they are not supported by upstream PHP).

However, there are some forks that extend this parser with generics support. See for example https://github.com/mrsuh/php-generics, which uses https://github.com/mrsuh/PHP-Parser/tree/generics-support. I'm not familiar with what exactly this one supports.
