### ISSUE TITLE
MIT License for PHP-Styler?

### ISSUE THREAD

**Issue by pmjones** [nikic/PHP-Parser#937]
@nikic Thank you for your work on PHP-Parser.

PHP-Styler is a companion to PHP-Parser to handle pretty-printing in a more configurable/overridable fashion:

  <https://github.com/pmjones/php-styler>

It uses some of the PrettyPrinter code, notably these methods and their related members:

- pPrec()
- pScalar_DNumber()
- pScalar_LNumber()
- pScaler_Encapsed()
- pScalar_EncapsedStringPart()
- pScalar_String()

Would you grant me an MIT license to those portions of your work, so that PHP-Styler itself may use the MIT license cleanly?

Thanks again, and I hope you are doing well!

**Comment by nikic** [comment]
Sure, at least from my side feel free to license these as MIT. However, I haven't checked whether anyone else made any substantial contributions to these.

**Comment by pmjones** [comment]
A brief look over 'blame` on AbstractPrettyPrinter and PrettyPrinter\Standard reveals only @algo13 as an additional contributor to those portions. @algo13 do you have any objections to an MIT license?

**Comment by pmjones** [comment]
@nikic Meanwhile,  I'd appreciate your insights [here](https://github.com/pmjones/php-styler/issues/1) -- though please ignore if too busy.

**Comment by pmjones** [comment]
@nikic On further consideration, given Styler's close dependence on Parser, it's probably easier to use the same license instead of checking up on each release. Thank you for your accommodation in the first place!
