### ISSUE TITLE
Invalid docblock in 4.17.0 for `PHPParser\Node\Stmt\ClassConst`

### ISSUE THREAD

**Issue by weirdan** [nikic/PHP-Parser#939]
4.17.0 introduced `$type` property in `PHPParser\Node\Stmt\ClassConst`. However, docblock types for the constructor parameter and the property itself are not compatible. Constructor accepts `null|string|...`:

https://github.com/nikic/PHP-Parser/blob/844c228bf2b34a25ea8fed58f7929d14cf0c068e/lib/PhpParser/Node/Stmt/ClassConst.php#L25

 then assigns it directly to the property. But the property does not accept neither `null` nor `string`:
https://github.com/nikic/PHP-Parser/blob/844c228bf2b34a25ea8fed58f7929d14cf0c068e/lib/PhpParser/Node/Stmt/ClassConst.php#L15

**Comment by nikic** [comment]
Thanks for catching, looks like a mistake was introduced in the backport from the master branch. I've tagged 4.17.1 with a fix.
