### ISSUE TITLE
`elseif` vs `else if` node structure

### ISSUE THREAD

**Issue by pmjones** [nikic/PHP-Parser#948]
This came up in https://github.com/pmjones/php-styler/issues/4 earlier today. PHP-Styler rebuilds this original code using `else if`:

```php
if ($foo) {
    $foo = 'bar';
} else if ($bar) {
    $foo = 'baz';
}
```

...to this:

```php
if ($foo) {
    $foo = 'bar';
} else {
    if ($bar) {
        $foo = 'baz';
    }
}
```

This is because PHP-Parser sees a second `If_` as part of the `Else_`, rather than an `Elseif_` that is part of the `If_`.

How difficult would it be for PHP-Parser to recognize `else if` as `elseif` in these conditions? (My guess is that it would involve substantial effort.)

**Comment by nikic** [comment]
It's not difficult, but then I'll get complaints that the distinction between elseif and else if gets lost ;)

You should be able to easily print these without the extra nesting, like this: https://github.com/nikic/PHP-Parser/blob/f5adbb5e3fa57d2ff7b9ea179b88bcd2ced153e0/lib/PhpParser/PrettyPrinter/Standard.php#L893-L896

**Comment by pmjones** [comment]
> but then I'll get complaints

Man, I hear you. :-)

> You should be able to easily print these

Excellent, I will try that -- thanks!

**Comment by pmjones** [comment]
Thanks @nikic that did the trick.

**Comment by pmjones** [comment]
Update: it turns out that was not quite enough. When something like this occurs ...

```php
if (true) {
    if (true) {
        // foo
    } else {
        // bar
    }
} else {
    if (true) {
        // baz
    } else {
        // dib
    }
}
```

... the final else (with `//dib`) disappears.

Instead, this mitigation seems to handle it properly (no disappearing `else`):

```php
if (
    count($node->stmts) === 1
    && $node->stmts[0] instanceof Stmt\If_
    && ! $node->stmts[0]->elseifs
    && ! $node->stmts[0]->else
        ) {
            // treat as `elseif`
        }
```

Thanks again for the help, and for this project.

**Comment by staabm** [comment]
Fyi we tried similar things in phpstan, but all suggested solutions until now did not work in all cases. 

See https://github.com/phpstan/phpstan/issues/10113

**Comment by pmjones** [comment]
@staabm Thanks for that -- so, no reliable solution?

**Comment by staabm** [comment]
Until now, I think no reliable solution, right.

**Comment by pmjones** [comment]
All right, I may have to go back to https://github.com/pmjones/php-styler/issues/4 and tell him there's nothing to do, other than manually change `else if` to `elseif` -- unless someone here can think of other solutions.

**Comment by pmjones** [comment]
@staabm @herndlm If you recall, can you say what the failure modes were? That is, under what conditions did the `else if`-to-`elseif` conversion fail to honor the original logic?
