### ISSUE TITLE
Global symbols usage

### ISSUE THREAD

**Issue by theofidry** [nikic/PHP-Parser#957]
Whilst working on [PHP-Scoper](https://github.com/humbug/php-scoper) and reviewing the symbols it is exposing*, I found that PHP-Parser had a few global symbols being used:

- `LIB`
- `PARAMS`
- `ARGS`
- `preprocessGrammar`
- `resolveNodes`
- ...

I am wondering if it is truly necessary for them to be registered as global symbols?

*: PHP-Scoper changes the namespace, and for not breaking globally registered user functions, it aliases the ones it came across with a statement like so:

```php
if (!function_exists('preprocessGrammar')) { function preprocessGrammar() { return \_HumbugBox57f37d5ac4d1\preprocessGrammar(...func_get_args()); } }
```

**Comment by nikic** [comment]
These are part of the parser generation in https://github.com/nikic/PHP-Parser/tree/master/grammar. You should be able to skip the files in that directory entirely, they are only used for development.

**Comment by theofidry** [comment]
if they are only for development maybe it makes more sense to exclude it from the final artifact like it is done for tests? Or do you see issues with this?

**Comment by nikic** [comment]
I think it would be okay to exclude it.
