### ISSUE TITLE
php composer.phar problem 

### ISSUE THREAD

**Issue by Trinity-SYT-SECURITY** [nikic/PHP-Parser#964]
I'm seeing this problem when I put php composer.phar require nikic/php-parser command, how can I solve it?

- Root package 'nikic/php-parser' cannot require itself in its composer.json

**Comment by ondrejmirtes** [comment]
You're probably doing that inside a cloned repository of `https://github.com/nikic/PHP-Parser`. Why?

Can you show the composer.json where this happens?
