### ISSUE TITLE
[Format-preserving printer] How to get rid of trailing commas in function calls/parameter definitions/closure uses

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#968]
This is not related to PHP-Parser 5.0.

I've created this package https://github.com/ondrejmirtes/simple-downgrader to help me develop PHPStan on newer PHP versions while supporting older versions in the compiled PHAR.

I know this use-case is not ideal for AST parser because it needs to work with semantics-unrelated tokens.

I want to be able to downgrade code such as:

```php
<?php

class SomeClass
{
    public function doFoo(
        $a,
        $b,
    ): void
    {
    }
}
```

to:

```php
<?php

class SomeClass
{
    public function doFoo(
        $a,
        $b
    ): void
    {
    }
}
```

The only way that works for me now is inspired by Rector and is basically this:

```php
if (!$this->followedByCommaAnalyzer->isFollowed($this->tokens, $lastParam)) {
	return null;
}

$lastParam->setAttribute(PhpPrinter::FUNC_ARGS_TRAILING_COMMA_ATTRIBUTE, false);
$node->setAttribute('origNode', null);
```

And overwritten method in the printer:

```php
	/**
	 * @param array<mixed> $nodes
	 */
	protected function pCommaSeparated(array $nodes): string
	{
		$result = parent::pCommaSeparated($nodes);
		if (count($nodes) === 0) {
			return $result;
		}
		$last = $nodes[count($nodes) - 1];
		if (!$last instanceof Node) {
			return $result;
		}

		$trailingComma = $last->getAttribute(self::FUNC_ARGS_TRAILING_COMMA_ATTRIBUTE);
		if ($trailingComma === false) {
			$result = rtrim($result, ',');
		}

		return $result;
	}
```

The downside is that this throws all formatting in the function and the whole body is printed with the fallback method.

Is there a better way to achieve this, without this downside? Thank you.

**Comment by nikic** [comment]
I don't think there is any way to do this. An alternative could be to post-process the result and drop any `,` token followed by `)` (ignoring whitespace / comments).

**Comment by ondrejmirtes** [comment]
Alright, thank you!
