### ISSUE TITLE
getPhpVersion() method has different return type in V5

### ISSUE THREAD

**Issue by phpfui** [nikic/PHP-Parser#975]
getPhpVersion() returns PhpVersion in some places and string in others.  This causes issues in PHP 8.3 (have not tested in other versions).  I would be happy to submit a PR if given guidance on the best solution. Off the top of my head, I would convert everything to return PhpVersion and add toString to PhpVersion.

Fatal error: Declaration of PhpParser\Lexer\TokenEmulator\CoaleseEqualTokenEmulator::getPhpVersion(): string must be compatible with PhpParser\Lexer\TokenEmulator\TokenEmulator::getPhpVersion(): PhpParser\PhpVersion in C:\websites\PHPFUIWebsite\PhpParser\Lexer\TokenEmulator\CoaleseEqualTokenEmulator.php on line 9

<pre>
PhpParser\Lexer\TokenEmulator\AttributeEmulator.php 9 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\CoaleseEqualTokenEmulator.php 9 12:    public function getPhpVersion(): string
PhpParser\Lexer\TokenEmulator\EnumTokenEmulator.php 8 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\ExplicitOctalEmulator.php 9 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\FlexibleDocStringEmulator.php 15 12:    public function getPhpVersion(): string
PhpParser\Lexer\TokenEmulator\FnTokenEmulator.php 9 12:    public function getPhpVersion(): string
PhpParser\Lexer\TokenEmulator\MatchTokenEmulator.php 8 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\NullsafeTokenEmulator.php 9 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\NumericLiteralSeparatorEmulator.php 17 12:    public function getPhpVersion(): string
PhpParser\Lexer\TokenEmulator\ReadonlyFunctionTokenEmulator.php 23 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\ReadonlyTokenEmulator.php 8 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\ReverseEmulator.php 18 12:    public function getPhpVersion(): PhpVersion {
PhpParser\Lexer\TokenEmulator\TokenEmulator.php 10 21:    abstract public function getPhpVersion(): PhpVersion;
</pre>

**Comment by xabbuh** [comment]
This looks like you have two versions of this package installed (`CoaleseEqualTokenEmulator` is part of version 4, but not of version 5). Are you using the Symfony PHPUnit bridge? In this case the error could be related to symfony/symfony#53459.

**Comment by phpfui** [comment]
Yes, that was the problem.  Found this error on a site that automatically updates, but did not purge the old source with the version change.  Will close.

Thanks for the super fast response!
