### ISSUE TITLE
Appending new statements

### ISSUE THREAD

**Issue by sergio-fferreira** [nikic/PHP-Parser#979]
Let's assume I have the following code:

```php
func1();
func2();
```

After parsing and finding the first statement, `func1();`, I want to append a sibling statement. For example:

```php
func1();
anotherFunc();
func2();
```

Is this possible? As far as I know, `$node->getAttribute('next')` only stores the next sibling node in an attribute, which is useful if I want to modify the next sibling. However, appending a new statement after the current statement appears not to be possible.

Thank you in advance.

**Comment by nikic** [comment]
There's indeed no straightforward way to do this. You'd have to go to the parent node, find where `next` is located in it, and insert the new node there.
