### ISSUE TITLE
Error "Syntax error, unexpected EOF on line" when parse valid php file

### ISSUE THREAD

**Issue by gromdron** [nikic/PHP-Parser#991]
I use nikic/php-parser to build a class tree of a proprietary product. A code was found inside the product that leads the parser to a fatal error when parsing a file. The product works and php 8.1 does not issue errors - the error is in the parser.

I got "Syntax error, unexpected EOF on line 11" when parse file:

```php
<?php

class SomeClass
{
	protected static function someMethod()
	{
		ob_start();
		?><script>alert('123');</script><?
		return ob_get_clean();
	}
}
```

I use php 8.1 and composer.json:

```
{
    "require": {
        "nikic/php-parser": "^5.0"
    }
}
```

Parsing code:

```php
<?php
require_once './vendor/autoload.php';

use PhpParser\ParserFactory;
use PhpParser\PhpVersion;

try
{
	$fileContent = file_get_contents(__DIR__.'/test_file.php');

	$parser = (new ParserFactory)->createForVersion(PhpVersion::fromString("8.1"));
 
    $parser->parse($fileContent);
}
catch (Throwable $error)
{
    fwrite(STDOUT, $error->getMessage());
}
```

How can i fix that?

**Comment by dryabov** [comment]
Do you have `short_open_tag` enabled before parsing?
