### ISSUE TITLE
Is there a way to find places from where specific class/object methods are called

### ISSUE THREAD

**Issue by bogdan-dubyk** [nikic/PHP-Parser#992]
Let's say I wan to identify all occurrences of `Model->save()`;

```
$model = new Model();
$model->save(); /// need to be identified

$notModel = new NotModel();
$notModel->save(); // need to be ignored

$model->run()->run()->save(); // need to be identified

$model->getNotModel()->save(); // need to be ignored
```

also if save called from inside of `Model` it needs to be identified too

```
class Model {
     public function addItems(array $items)
    {
          $this->items = $items
          $this-save(); // need to be identified

         foreach($items as $item) {
           $item->addModel($this);
           $item->save(); // need to be ignored
        }
    }
}
```

Is this possible to do???

**Comment by staabm** [comment]
To achieve what you want in plain php-parser you need to build a lot of stuff on top of it.

Maybe its an option to you to use PHPStan collectors for your use-case: https://phpstan.org/developing-extensions/collectors

It allows doing such things easily - see e.g. https://github.com/TomasVotruba/unused-public where we do this kind of stuff

**Comment by bogdan-dubyk** [comment]
@staabm, actually I want to build PHPStan rull depending on how the `save` of a specific model is called, so will take a look at collectors, thank you!

**Comment by staabm** [comment]
Hmm in that case it might be doable without a collector. What difficulties do you have with identifying these calls atm? Maybe you can bring up a repo with your current approach and a few tests?

**Comment by bogdan-dubyk** [comment]
sorry, do not have any public repo, basically  I have let's say `Cart` model, and it has public `save` method. And I want restrict other devs to call this method outside of `CartRepository`.

This one allows
```
class CartRepository {
     public function save(Cart $cart) {
          $cart->save();
    }
}
```

And all this not
```
class Service {

     public function run()
    {
         $cart = .... // get cart
         // update cart
        $cart->save();  <===== here I want PHPStan to scream
     }
}

class Cart {
       public function updateAndSave(array $data) {
            // update
            $this-save(); <========= scream too
       }

          public function addItems(array $items)
    {
          $this->items = $items
          $this-save();  <========= scream too

         foreach($items as $item) {
           $item->addModel($this);
           $item->save(); <========= not scream
        }
    }
}
```

I tried to do it with custom PHPStan rules and stuck 
```
final class CartRules implements Rule
{
    public function getNodeType(): string
    {
        return MethodCall::class;
    }

    public function processNode(Node $node, Scope $scope): array
    {
        if ($this->isCartMethod($scope) === false) {
            return [];
        }

        if ($this->isCalledFromCartRepository($scope)) {
            return [];
        }

        return [
            RuleErrorBuilder::message(
                    sprintf(
                        'Calling Cart::%s() method outside of CartRepository class is not allowed.',
                        $node->name->toString()
                    )
                )->line($node->getLine())
                ->file($scope->getFile())
                ->build()
        ];
    }

    private function isCartMethod(Scope $scope): bool
    {
        if (!$scope->isInClass()) {
            return false;
        }

        /** @var ClassReflection $classReflection */
        $classReflection = $scope->getClassReflection();

        return $classReflection->getName() === Cart::class;
    }

    private function isCalledFromCartRepository(Scope $scope): bool
    {
        if (!$scope->isInClass()) {
            return false;
        }

        /** @var ClassReflection $classReflection */
        $classReflection = $scope->getClassReflection();

        return $classReflection->isSubclassOf(CartRepository::class);
    }
}
```

Few things:
 - I do not know if I used the correct node type 
 - I do not know how to properly implement `isCalledFromCartRepository`. Do we need something else except `getClassReflection()` here to get the parent? 
 - with this code `isCartMethod` will identify code like 
 ```

class Cart {
    public function addItems(array $items)
    {

         foreach($items as $item) {
           $item->addModel($this);
           $item->save(); 
        }
    }
}
```
but it needs to be ignored as `save` is not triggered by $this but on a different object.

Sorry I'm doing this for the first time, and found that there are not much documentation, so I'm even confused about which not type exactly I need to use.

**Comment by staabm** [comment]
> Sorry I'm doing this for the first time, and found that there are not much documentation, so I'm even confused about which not type exactly I need to use.

no problem. please put what you have in a repo with appropriate tests (also failling tests), so I can run phpstan and your expectations and see whats missing. it will also help yourself for a better understanding.

I can guide you thru the remaining steps.

**Comment by ondrejmirtes** [comment]
This should be a discussion in PHPStan's repository, not here.
